-- DROP TABLE DQ_ADM.TB_DQM_RULES2 PURGE;
CREATE TABLE DQ_ADM.TB_DQM_RULES2
(
    RULE_ID         VARCHAR2(20) NOT NULL,   -- 규칙ID
    RULE_TYPE       VARCHAR2(50),            -- 규칙유형
    LCLS_NM         VARCHAR2(100),           -- 대분류
    MCLS_NM         VARCHAR2(100),           -- 중분류
    TGT_DB_NM       VARCHAR2(50),            -- 대상DB
    TGT_TAB_NM      VARCHAR2(50),            -- 대상테이블
    TGT_COL_NM      VARCHAR2(50),            -- 대상컬럼
    TGT_TAB_KO_NM   VARCHAR2(200),           -- 대상테이블명
    TGT_COL_KO_NM   VARCHAR2(200),           -- 대상컬럼명
    CMP_DB_NM       VARCHAR2(50),            -- 비교DB
    CMP_TAB_NM      VARCHAR2(50),            -- 비교테이블
    CMP_TAB_KO_NM   VARCHAR2(200),           -- 비교테이블명
    RULE_DFN        VARCHAR2(1000),          -- 규칙정의
    VRFY_DFN        VARCHAR2(1000),          -- 검증방법
    ERR_PROC_DFN    VARCHAR2(1000),          -- 처리사항
    DB_N1_CONN_NM   VARCHAR2(30),            -- DB1연결명
    RULE_N1_SQL     VARCHAR2(4000),          -- 검증1SQL
    DB_N2_CONN_NM   VARCHAR2(30),            -- DB2연결명
    RULE_N2_SQL     VARCHAR2(4000),          -- 검증2SQL
    ERR_SAV_TAB_NM  VARCHAR2(30),            -- 오류저장테이블명
    CYCLE           VARCHAR2(10),            -- 주기
    RMK             VARCHAR2(200),           -- 비고
    USE_YN          VARCHAR2(1),             -- 사용여부
    FST_INSRT_DTM   DATE,                    -- 최초입력일시
    FST_INSRTR_ID   VARCHAR2(20),            -- 최초입력자ID
    LST_MDFY_DTM    DATE,                    -- 최종수정일시
    LST_MDFYR_ID    VARCHAR2(20)             -- 최종수정자ID
)
TABLESPACE NPIMS_DQ_DAT01;

CREATE UNIQUE INDEX DQ_ADM.PK_TB_DQM_RULES2
ON DQ_ADM.TB_DQM_RULES2 (RULE_ID) 
TABLESPACE NPIMS_DQ_DAT01;

ALTER TABLE DQ_ADM.TB_DQM_RULES2
ADD CONSTRAINT PK_TB_DQM_RULES2 PRIMARY KEY (RULE_ID);

COMMENT ON TABLE DQ_ADM.TB_DQM_RULES2 IS '검증규칙';
COMMENT ON COLUMN DQ_ADM.TB_DQM_RULES2.RULE_ID         IS '규칙ID';
COMMENT ON COLUMN DQ_ADM.TB_DQM_RULES2.RULE_TYPE       IS '규칙유형';
COMMENT ON COLUMN DQ_ADM.TB_DQM_RULES2.LCLS_NM         IS '대분류';
COMMENT ON COLUMN DQ_ADM.TB_DQM_RULES2.MCLS_NM         IS '중분류';
COMMENT ON COLUMN DQ_ADM.TB_DQM_RULES2.TGT_DB_NM       IS '대상DB';
COMMENT ON COLUMN DQ_ADM.TB_DQM_RULES2.TGT_TAB_NM      IS '대상테이블';
COMMENT ON COLUMN DQ_ADM.TB_DQM_RULES2.TGT_COL_NM      IS '대상컬럼';
COMMENT ON COLUMN DQ_ADM.TB_DQM_RULES2.TGT_TAB_KO_NM   IS '대상테이블명';
COMMENT ON COLUMN DQ_ADM.TB_DQM_RULES2.TGT_COL_KO_NM   IS '대상컬럼명';

COMMENT ON COLUMN DQ_ADM.TB_DQM_RULES2.CMP_DB_NM       IS '비교DB';
COMMENT ON COLUMN DQ_ADM.TB_DQM_RULES2.CMP_TAB_NM      IS '비교테이블';
COMMENT ON COLUMN DQ_ADM.TB_DQM_RULES2.CMP_TAB_KO_NM   IS '비교테이블명';

COMMENT ON COLUMN DQ_ADM.TB_DQM_RULES2.RULE_DFN        IS '규칙정의';
COMMENT ON COLUMN DQ_ADM.TB_DQM_RULES2.VRFY_DFN        IS '검증방법';
COMMENT ON COLUMN DQ_ADM.TB_DQM_RULES2.ERR_PROC_DFN    IS '처리사항';
COMMENT ON COLUMN DQ_ADM.TB_DQM_RULES2.DB_N1_CONN_NM   IS 'DB1연결명';
COMMENT ON COLUMN DQ_ADM.TB_DQM_RULES2.RULE_N1_SQL     IS '검증1SQL';
COMMENT ON COLUMN DQ_ADM.TB_DQM_RULES2.DB_N2_CONN_NM   IS 'DB2연결명';
COMMENT ON COLUMN DQ_ADM.TB_DQM_RULES2.RULE_N2_SQL     IS '검증2SQL';
COMMENT ON COLUMN DQ_ADM.TB_DQM_RULES2.ERR_SAV_TAB_NM  IS '오류저장테이블명';
COMMENT ON COLUMN DQ_ADM.TB_DQM_RULES2.CYCLE           IS '주기';
COMMENT ON COLUMN DQ_ADM.TB_DQM_RULES2.RMK             IS '비고';
COMMENT ON COLUMN DQ_ADM.TB_DQM_RULES2.USE_YN          IS '사용여부';
COMMENT ON COLUMN DQ_ADM.TB_DQM_RULES2.FST_INSRT_DTM   IS '최초입력일시';
COMMENT ON COLUMN DQ_ADM.TB_DQM_RULES2.FST_INSRTR_ID   IS '최초입력자ID';
COMMENT ON COLUMN DQ_ADM.TB_DQM_RULES2.LST_MDFY_DTM    IS '최종수정일시';
COMMENT ON COLUMN DQ_ADM.TB_DQM_RULES2.LST_MDFYR_ID    IS '최종수정자ID';


-- DROP TABLE DQ_ADM.TB_DQM_ERR_DAT PURGE;
CREATE TABLE DQ_ADM.TB_DQM_ERR_DAT
(
    LOG_ID          VARCHAR2(30) NOT NULL,   -- LOGID(PK)
    SEQ             NUMBER(10)   NOT NULL,   -- 일련번호(PK), (-1:명칭, 0:타입, 1~:데이터))         
    RULE_ID         VARCHAR2(20) NOT NULL,   -- 규칙ID
    LOG_DTM         DATE         NOT NULL,   -- 로그일시
    TG_DB_NM        VARCHAR2(50),            -- 대상DB
    TAB_NM          VARCHAR2(50),            -- 대상테이블
    COL_NM          VARCHAR2(50),            -- 대상컬럼
    VAL01            VARCHAR2(1000),          -- 값01
    VAL02            VARCHAR2(1000),          -- 값02
    VAL03            VARCHAR2(1000),          -- 값03
    VAL04            VARCHAR2(1000),          -- 값04
    VAL05            VARCHAR2(1000),          -- 값05
    VAL06            VARCHAR2(1000),          -- 값06
    VAL07            VARCHAR2(1000),          -- 값07
    VAL08            VARCHAR2(1000),          -- 값08
    VAL09            VARCHAR2(1000),          -- 값09
    VAL10            VARCHAR2(1000),          -- 값10
    VAL11            VARCHAR2(1000),          -- 값11
    VAL12            VARCHAR2(1000),          -- 값12
    VAL13            VARCHAR2(1000),          -- 값13
    VAL14            VARCHAR2(1000),          -- 값14
    VAL15            VARCHAR2(1000),          -- 값15
    VAL16            VARCHAR2(1000),          -- 값16
    VAL17            VARCHAR2(1000),          -- 값17
    VAL18            VARCHAR2(1000),          -- 값18
    VAL19            VARCHAR2(1000),          -- 값19
    VAL20            VARCHAR2(1000),          -- 값20
    VAL21            VARCHAR2(1000),          -- 값21
    VAL22            VARCHAR2(1000),          -- 값22
    VAL23            VARCHAR2(1000),          -- 값23
    VAL24            VARCHAR2(1000),          -- 값24
    VAL25            VARCHAR2(1000),          -- 값25
    VAL26            VARCHAR2(1000),          -- 값26
    VAL27            VARCHAR2(1000),          -- 값27
    VAL28            VARCHAR2(1000),          -- 값28
    VAL29            VARCHAR2(1000),          -- 값29
    VAL30            VARCHAR2(1000)          -- 값30
) 
TABLESPACE NPIMS_DQ_DAT01;

ALTER TABLE DQ_ADM.TB_DQM_ERR_DAT ADD CONSTRAINT PK_DBM_ERR_DAT
   PRIMARY KEY(LOG_ID, SEQ)
   USING INDEX TABLESPACE NPIMS_DQ_DAT01;

COMMENT ON TABLE DQ_ADM.TB_DQM_ERR_DAT    IS '검증오류데이터';
COMMENT ON COLUMN DQ_ADM.TB_DQM_ERR_DAT.LOG_ID     IS 'LOGID';
COMMENT ON COLUMN DQ_ADM.TB_DQM_ERR_DAT.SEQ        IS '일련번호';      
COMMENT ON COLUMN DQ_ADM.TB_DQM_ERR_DAT.RULE_ID    IS '규칙ID';
COMMENT ON COLUMN DQ_ADM.TB_DQM_ERR_DAT.LOG_DTM    IS 'LOG일시';
COMMENT ON COLUMN DQ_ADM.TB_DQM_ERR_DAT.TG_DB_NM   IS '대상DB';
COMMENT ON COLUMN DQ_ADM.TB_DQM_ERR_DAT.TAB_NM     IS '대상테이블';
COMMENT ON COLUMN DQ_ADM.TB_DQM_ERR_DAT.COL_NM     IS '대상컬럼';
COMMENT ON COLUMN DQ_ADM.TB_DQM_ERR_DAT.VAL01      IS '값01';
COMMENT ON COLUMN DQ_ADM.TB_DQM_ERR_DAT.VAL02      IS '값02';
COMMENT ON COLUMN DQ_ADM.TB_DQM_ERR_DAT.VAL03      IS '값03';
COMMENT ON COLUMN DQ_ADM.TB_DQM_ERR_DAT.VAL04      IS '값04';
COMMENT ON COLUMN DQ_ADM.TB_DQM_ERR_DAT.VAL05      IS '값05';
COMMENT ON COLUMN DQ_ADM.TB_DQM_ERR_DAT.VAL06      IS '값06';
COMMENT ON COLUMN DQ_ADM.TB_DQM_ERR_DAT.VAL07      IS '값07';
COMMENT ON COLUMN DQ_ADM.TB_DQM_ERR_DAT.VAL08      IS '값08';
COMMENT ON COLUMN DQ_ADM.TB_DQM_ERR_DAT.VAL09      IS '값09';
COMMENT ON COLUMN DQ_ADM.TB_DQM_ERR_DAT.VAL10      IS '값10';
COMMENT ON COLUMN DQ_ADM.TB_DQM_ERR_DAT.VAL11      IS '값11';
COMMENT ON COLUMN DQ_ADM.TB_DQM_ERR_DAT.VAL12      IS '값12';
COMMENT ON COLUMN DQ_ADM.TB_DQM_ERR_DAT.VAL13      IS '값13';
COMMENT ON COLUMN DQ_ADM.TB_DQM_ERR_DAT.VAL14      IS '값14';
COMMENT ON COLUMN DQ_ADM.TB_DQM_ERR_DAT.VAL15      IS '값15';
COMMENT ON COLUMN DQ_ADM.TB_DQM_ERR_DAT.VAL16      IS '값16';
COMMENT ON COLUMN DQ_ADM.TB_DQM_ERR_DAT.VAL17      IS '값17';
COMMENT ON COLUMN DQ_ADM.TB_DQM_ERR_DAT.VAL18      IS '값18';
COMMENT ON COLUMN DQ_ADM.TB_DQM_ERR_DAT.VAL19      IS '값19';
COMMENT ON COLUMN DQ_ADM.TB_DQM_ERR_DAT.VAL20      IS '값20';
COMMENT ON COLUMN DQ_ADM.TB_DQM_ERR_DAT.VAL21      IS '값21';
COMMENT ON COLUMN DQ_ADM.TB_DQM_ERR_DAT.VAL22      IS '값22';
COMMENT ON COLUMN DQ_ADM.TB_DQM_ERR_DAT.VAL23      IS '값23';
COMMENT ON COLUMN DQ_ADM.TB_DQM_ERR_DAT.VAL24      IS '값24';
COMMENT ON COLUMN DQ_ADM.TB_DQM_ERR_DAT.VAL25      IS '값25';
COMMENT ON COLUMN DQ_ADM.TB_DQM_ERR_DAT.VAL26      IS '값26';
COMMENT ON COLUMN DQ_ADM.TB_DQM_ERR_DAT.VAL27      IS '값27';
COMMENT ON COLUMN DQ_ADM.TB_DQM_ERR_DAT.VAL28      IS '값28';
COMMENT ON COLUMN DQ_ADM.TB_DQM_ERR_DAT.VAL29      IS '값29';
COMMENT ON COLUMN DQ_ADM.TB_DQM_ERR_DAT.VAL30      IS '값30';



-- DROP TABLE DQ_ADM.TB_DQM_RULE_LOGS PURGE;

CREATE TABLE DQ_ADM.TB_DQM_RULE_LOGS (
      LOG_ID                                       VARCHAR2(30)      NOT NULL
    , RULE_ID                                      VARCHAR2(10)      NOT NULL
    , LOG_DTM                                      DATE              NOT NULL
    , VRFY_RSLT                                    VARCHAR2(10)
    , SQL_N1_RSLT                                  VARCHAR2(100)
    , SQL_N2_RSLT                                  VARCHAR2(100)
    , ERR_CD                                       VARCHAR2(100)
    , ERR_MSG                                      VARCHAR2(1000)
    , PROC_STTS                                    VARCHAR2(50)
    , STTS_DTM                                     DATE
    , STRT_DTM                                     DATE
    , END_DTM                                      DATE
    , RMK                                          VARCHAR2(2000)
) TABLESPACE NPIMS_DQ_DAT01;

ALTER TABLE DQ_ADM.TB_DQM_RULE_LOGS
    ADD CONSTRAINT PK_DQM_RULE_LOGS PRIMARY KEY (LOG_ID) 
    USING INDEX TABLESPACE NPIMS_DQ_DAT01;


COMMENT ON TABLE DQ_ADM.TB_DQM_RULE_LOGS                                  IS '검증로그';
COMMENT ON COLUMN DQ_ADM.TB_DQM_RULE_LOGS.LOG_ID                          IS '로그ID';
COMMENT ON COLUMN DQ_ADM.TB_DQM_RULE_LOGS.RULE_ID                         IS '규칙ID';
COMMENT ON COLUMN DQ_ADM.TB_DQM_RULE_LOGS.LOG_DTM                         IS '로그일시';
COMMENT ON COLUMN DQ_ADM.TB_DQM_RULE_LOGS.VRFY_RSLT                       IS '실행결과';
COMMENT ON COLUMN DQ_ADM.TB_DQM_RULE_LOGS.SQL_N2_RSLT                     IS 'SQL1결과';
COMMENT ON COLUMN DQ_ADM.TB_DQM_RULE_LOGS.SQL_N2_RSLT                     IS 'SQL2결과';
COMMENT ON COLUMN DQ_ADM.TB_DQM_RULE_LOGS.ERR_CD                          IS '오류코드';
COMMENT ON COLUMN DQ_ADM.TB_DQM_RULE_LOGS.ERR_MSG                         IS '오류메시지';
COMMENT ON COLUMN DQ_ADM.TB_DQM_RULE_LOGS.PROC_STTS                       IS '진행상태';
COMMENT ON COLUMN DQ_ADM.TB_DQM_RULE_LOGS.STTS_DTM                        IS '상태일시';
COMMENT ON COLUMN DQ_ADM.TB_DQM_RULE_LOGS.STRT_DTM                        IS '시작일시';
COMMENT ON COLUMN DQ_ADM.TB_DQM_RULE_LOGS.END_DTM                         IS '종료일시';
COMMENT ON COLUMN DQ_ADM.TB_DQM_RULE_LOGS.RMK                             IS '비고';
