/* *************************************************************************
 * NAME : dbo.UDP_PRICELIST_NULL_PROC
 * TYPE : PROCEDURE (SQL_STORED_PROCEDURE)
 * TIME : Create: 2004-11-04 10:30:51.56
 *        Modify: 2018-05-03 17:23:34.583
 *        Backup: 20180521_1737
 ************************************************************************* */

CREATE PROC UDP_PRICELIST_NULL_PROC

AS
BEGIN
	SET NOCOUNT ON
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

	DECLARE @TEMP TABLE
	(
		IDX INT IDENTITY(1,1),
		PNO	INT,
		VCODE	INT
	)
	INSERT INTO @TEMP (PNO,VCODE)
	SELECT PL_NO, PL_VCODE --, COUNT(PL_VCODE) 
	FROM PRICELIST (NOLOCK) 
	WHERE PL_MODELNO =-100
		AND PL_NO <100000
	
	DECLARE @I	INT
	DECLARE @J	INT
	DECLARE @VCODE INT
	SELECT @I= MAX(IDX) FROM @TEMP
	WHILE @I<>0
	BEGIN
		SELECT @J=PNO, @VCODE=VCODE
		FROM @TEMP
		WHERE IDX=@I
		
		

		UPDATE PRICELIST
		SET PL_MODELNO=NULL
		WHERE PL_VCODE=@VCODE
			AND PL_MODELNO=-100
			AND PL_NO = @J
		PRINT @J --+ '¿Ï·á'
		SET @I=@I-1
	END


END
