/* *************************************************************************
 * NAME : dbo.UDP_BC_BOARD_REPLY
 * TYPE : PROCEDURE (SQL_STORED_PROCEDURE)
 * TIME : Create: 2004-11-02 03:31:53.997
 *        Modify: 2018-05-03 17:23:35.063
 *        Backup: 20180521_1737
 ************************************************************************* */



/****** 개체: 저장 프로시저 dbo.UP_BC_BOARD_REPLY    스크립트 날짜: 2004-10-23 오전 10:56:22 ******/

/****** 개체: 저장 프로시저 dbo.UP_BC_BOARD_REPLY    스크립트 날짜: 2004-08-05 오전 10:59:05 ******/

/****** 개체: 저장 프로시저 dbo.UP_BC_BOARD_REPLY    스크립트 날짜: 2004-07-07 오후 1:08:03 ******/

/****** 개체: 저장 프로시저 dbo.UP_BC_BOARD_REPLY    스크립트 날짜: 2004-07-07 오전 11:31:45 ******/

/****** 개체: 저장 프로시저 dbo.UP_BC_BOARD_INSERT    스크립트 날짜: 2004-07-07 오전 9:57:44 ******/
CREATE      PROC UDP_BC_BOARD_REPLY
	@GROUP 	INT,
	@BB_NO		INT,
	@USERID	VARCHAR(12),
	@USERNM	VARCHAR(12),
	@RECEIVER	VARCHAR(12),
	@REFERER	VARCHAR(512),
	@TITLE		VARCHAR(255),
	@CONTENT	VARCHAR(8000),
	@PWD		VARCHAR(12),
	@FILE1		VARCHAR(255),
	@FILE2		VARCHAR(255),

	@iRETURN	INT 	OUTPUT
AS
BEGIN
	SET NOCOUNT ON
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

	DECLARE @MX_BB_NO       INT
	DECLARE @REF         INT
	DECLARE @DEPTH       TINYINT
	DECLARE @STEP        TINYINT
	DECLARE @STATUS  VARCHAR(1)

	BEGIN TRAN
		SELECT @MX_BB_NO = ISNULL(MAX(BB_NO), 0) + 1
	  	FROM TBL_BC_BOARD (NOLOCK)
		WHERE BB_GROUP = @GROUP
	
		SELECT @REF = BB_REF,
			@DEPTH = BB_DEPTH,
			@STEP = BB_STEP,
			@STATUS = BB_STATUS
		FROM TBL_BC_BOARD (NOLOCK)
		WHERE BB_GROUP = @GROUP
			AND BB_NO = @BB_NO
		
		UPDATE TBL_BC_BOARD
		SET BB_STEP = BB_STEP+1
		WHERE BB_GROUP = @GROUP
			AND BB_REF = @REF
			AND BB_STEP > @STEP
		

		INSERT INTO TBL_BC_BOARD
		(BB_GROUP, BB_NO, BB_REF, BB_STEP, BB_DEPTH, 
			BB_USERID, BB_USERNAME, BB_RECEIVER, BB_REFERER, BB_TITLE, BB_CONTENT, BB_PWD, BB_STATUS)
		VALUES
		(@GROUP, @MX_BB_NO, @REF, @STEP+1, @DEPTH+1,
			@USERID, @USERNM, @RECEIVER, @REFERER, @TITLE, @CONTENT, @PWD, @STATUS)
		IF @@ERROR<>0 GOTO ERROR_HANDLER

		IF (@FILE1<>'')
		BEGIN
			INSERT INTO TBL_BOARD_ATTACHFILE 
			(BA_GROUP, BA_NO, BA_FILE)
			VALUES
			(@GROUP, @MX_BB_NO,@FILE1)
			IF @@ERROR<>0 GOTO ERROR_HANDLER
		END
		
		IF (@FILE2<>'')
		BEGIN
			INSERT INTO TBL_BOARD_ATTACHFILE 
			(BA_GROUP, BA_NO, BA_FILE)
			VALUES
			(@GROUP, @MX_BB_NO,@FILE2)
			IF @@ERROR<>0 GOTO ERROR_HANDLER
		END
		
	IF @@ERROR<>0
	BEGIN
		ERROR_HANDLER:
		BEGIN
			SET @iRETURN =1
			ROLLBACK TRAN
		END
	END
	ELSE
	BEGIN
		SET @iRETURN = 0
		COMMIT TRAN
	END	




END






