/* *************************************************************************
 * NAME : dbo.UDP_MP_GOODS_CATEGORY_ATTRIBUTE_COPY
 * TYPE : PROCEDURE (SQL_STORED_PROCEDURE)
 * TIME : Create: 2016-04-05 20:25:10.583
 *        Modify: 2018-05-03 17:23:35.217
 *        Backup: 20180521_1737
 ************************************************************************* */


CREATE PROC [DBO].[UDP_MP_GOODS_CATEGORY_ATTRIBUTE_COPY]
	@FIND_CATEGORY VARCHAR(12),
	@REPLACE_CATEGORY VARCHAR(12)
AS
BEGIN
	SET NOCOUNT ON;
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
	
	-- 분류 속성 복사
	DELETE FROM GOODS_CATEGORY_ATTRIBUTE
	WHERE CATEGORY = @REPLACE_CATEGORY
	
	IF LEFT(@FIND_CATEGORY, 4) <> LEFT(@REPLACE_CATEGORY, 4)
	BEGIN
		INSERT INTO GOODS_CATEGORY_ATTRIBUTE(CATEGORY, ATTRIBUTE_ID, DISPLAY_ORDER, TAG_ORDER)
		SELECT @REPLACE_CATEGORY, C.ATTRIBUTE_ID, DISPLAY_ORDER, TAG_ORDER
		FROM GOODS_CATEGORY_ATTRIBUTE A
			INNER JOIN GOODS_ATTRIBUTE B ON A.ATTRIBUTE_ID = B.ATTRIBUTE_ID AND B.CATEGORY = LEFT(@FIND_CATEGORY, 4)
			INNER JOIN GOODS_ATTRIBUTE C ON B.MANAGE_ATTRIBUTE_NM = C.MANAGE_ATTRIBUTE_NM AND C.CATEGORY = LEFT(@REPLACE_CATEGORY, 4)
		WHERE A.CATEGORY = @FIND_CATEGORY
	END
	ELSE
	BEGIN
		INSERT INTO GOODS_CATEGORY_ATTRIBUTE(CATEGORY, ATTRIBUTE_ID, DISPLAY_ORDER, TAG_ORDER)
		SELECT @REPLACE_CATEGORY, ATTRIBUTE_ID, DISPLAY_ORDER, TAG_ORDER
		FROM GOODS_CATEGORY_ATTRIBUTE
		WHERE CATEGORY = @FIND_CATEGORY
	END
END
