/* *************************************************************************
 * NAME : dbo.UDP_ELOC_EDU_PRICELIST_INSERT
 * TYPE : PROCEDURE (SQL_STORED_PROCEDURE)
 * TIME : Create: 2005-01-25 19:15:40.217
 *        Modify: 2015-09-17 16:49:12.22
 *        Backup: 20180521_1737
 ************************************************************************* */

CREATE PROC UDP_ELOC_EDU_PRICELIST_INSERT
	@FLAG			CHAR(1),
	@PL_NO2		bigINT,
	@PL_MODELNO	INT,
	@PL_VCODE		INT,
	@PL_CATEGORY	VARCHAR(8),
	@PL_GOODSNM	NVARCHAR(200),
	@PL_PRICE		MONEY,
	@PL_STATUS		CHAR(1),
	@PL_JOBTYPE		CHAR(1),
	@PL_AUTHFLAG	CHAR(1),
	@PL_MULTIFLAG	CHAR(1),
	
	@PLNO		bigINT	OUTPUT,
	@iRETURN		INT 	OUTPUT
AS
BEGIN
	SET NOCOUNT ON
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
	--BEGIN TRAN
	IF @FLAG = '1'		-- 새로 INSERT 하는 경우 
		BEGIN
			INSERT INTO PRICELIST( PL_MODELNO, PL_VCODE, PL_CATEGORY, PL_GOODSNM, PL_PRICE, PL_STATUS, PL_JOBTYPE, PL_AUTHFLAG, PL_MULTIFLAG) 
			VALUES(@PL_MODELNO,@PL_VCODE,@PL_CATEGORY,@PL_GOODSNM,@PL_PRICE,@PL_STATUS,@PL_JOBTYPE,@PL_AUTHFLAG,@PL_MULTIFLAG)
	
			SET @PLNO=SCOPE_IDENTITY()
		END
	ELSE			-- 내용 업데이트
		BEGIN
			UPDATE PRICELIST SET PL_GOODSNM = @PL_GOODSNM, PL_PRICE = @PL_PRICE, PL_STATUS = @PL_STATUS
			WHERE PL_VCODE = @PL_VCODE AND PL_NO = @PL_NO2

			SET @PLNO=@PL_NO2
		END

	IF @@ERROR<>0
		BEGIN
	--		ROLLBACK TRAN
			SET @iRETURN = 99
		END
	ELSE
		BEGIN
	--		COMMIT TRAN
			SET @iRETURN = 00
				
		END

END
