/* *************************************************************************
 * NAME : dbo.UDP_PRICELIST_DEL
 * TYPE : PROCEDURE (SQL_STORED_PROCEDURE)
 * TIME : Create: 2005-03-28 15:08:55.293
 *        Modify: 2018-05-03 17:23:35.497
 *        Backup: 20180521_1737
 ************************************************************************* */

CREATE PROC UDP_PRICELIST_DEL
	@intTmpVcode	INT

AS
BEGIN
	
	SET NOCOUNT ON
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

	DECLARE @TabCount	INT
	DECLARE @TabLoopCount	INT
	DECLARE @TMP_VCODE	INT
	
	DECLARE @TMPSDUINSP TABLE
		(
			PL_NO	INT
			, PL_MODELNO	INT
			, PL_VCODE	INT
		)
	
	DECLARE @TMPSDUVALID TABLE
		(
			PL_NO	INT
			, PL_MODELNO	INT
			, PL_VCODE	INT
		)
	
	
	DECLARE @TEMPT TABLE
		(
			T_IDX	INT	 IDENTITY(1,1),
			T_VCODE	INT
		)
		INSERT INTO @TEMPT(T_VCODE) VALUES (@intTmpVcode)
		/*
		INSERT INTO @TEMPT(T_VCODE)
		SELECT
			PL_VCODE
		FROM PRICELIST WITH (READUNCOMMITTED)
		WHERE  PL_VCODE = @intTmpVcode
		GROUP BY PL_VCODE
		*/
	
	SET @TabCount	     = @@ROWCOUNT
	SET @TabLoopCount = @TabCount
	
	WHILE @TabLoopCount<>0
	BEGIN
		--PRINT @TabLoopCount
		SELECT @TMP_VCODE = T_VCODE FROM @TEMPT WHERE T_IDX = @TabLoopCount
		--PRINT @TMP_VCODE
	
		
		-- SDU에서 추가한 상품
		INSERT INTO @TMPSDUINSP
		SELECT
			PL_NO
			, PL_MODELNO
			, PL_VCODE
		FROM PRICELIST WITH (READUNCOMMITTED)
		WHERE
			PL_VCODE=  @TMP_VCODE
			AND PL_GOODSNM = ''
	
	
		-- 수집데이터가 있는 상품
		INSERT INTO @TMPSDUVALID
		SELECT
			A.PL_NO
			, A.PL_MODELNO
			, A.PL_VCODE
		FROM PRICELIST AS A WITH (READUNCOMMITTED)
		INNER JOIN @TMPSDUINSP AS B
		ON A.PL_MODELNO = B.PL_MODELNO AND A.PL_VCODE = B.PL_VCODE
		WHERE A.PL_VCODE=  @TMP_VCODE AND A.PL_NO != B.PL_NO
	
	
		-- 삭제되어야 할 상품
		INSERT INTO TMP_BSLEE_PRICELIST
		SELECT * FROM PRICELIST
		WHERE PL_NO IN 
		(
			SELECT
				PL_NO 
			FROM @TMPSDUINSP
				WHERE PL_MODELNO IN (
					SELECT
						PL_MODELNO
					FROM @TMPSDUVALID)
		)
		AND PL_VCODE=  @TMP_VCODE
	
		DELETE FROM PRICELIST WHERE PL_NO IN 
		(
			SELECT
				PL_NO 
			FROM @TMPSDUINSP
				WHERE PL_MODELNO IN (
					SELECT
						PL_MODELNO
					FROM @TMPSDUVALID)
		)
		AND PL_VCODE=  @TMP_VCODE
	
		DELETE @TMPSDUINSP
		DELETE @TMPSDUVALID
	
		SET @TabLoopCount = @TabLoopCount -1
	END
END
