/* *************************************************************************
 * NAME : dbo.UDP_MP_GOODS_ATTRIBUTE_UPLOAD
 * TYPE : PROCEDURE (SQL_STORED_PROCEDURE)
 * TIME : Create: 2016-12-15 16:17:43.937
 *        Modify: 2018-05-03 17:23:34.83
 *        Backup: 20180521_1737
 ************************************************************************* */


CREATE PROC [DBO].[UDP_MP_GOODS_ATTRIBUTE_UPLOAD]
	@CATEGORY CHAR(4)
AS
BEGIN
	SET NOCOUNT ON;

	SET TRANSACTION ISOLATION LEVEL READ COMMITTED;
	--##################################################################
	DECLARE @QRY VARCHAR(8000)
	SET @QRY = 'DELETE OPENQUERY(ORADB, ''SELECT ATTRIBUTE_ID, ATTRIBUTE_ELEMENT_ID, ATTRIBUTE_ELEMENT, DISPLAY_ORDER, DEL_YN, INS_DATE, INS_OPRT, UPD_DATE, UPD_OPRT, IS_DISPLAY, IS_BOLD, SPECNO, ICONNO FROM TBL_GOODS_ATTRIBUTE_ELEMENT WHERE ATTRIBUTE_ID IN (SELECT ATTRIBUTE_ID FROM TBL_GOODS_ATTRIBUTE WHERE CATEGORY = ''''' + @CATEGORY + ''''')'')'
	EXEC (@QRY)
	
	SET @QRY = 'DELETE OPENQUERY(ORADB, ''SELECT ATTRIBUTE_ID, MANAGE_ATTRIBUTE_NM, GALLERY_ATTRIBUTE_NM, IS_MANAGE_DISPLAY, USE_CLASS_CODE, IS_UNIT, UNIT_NM, INS_DATE, INS_OPRT, UPD_DATE, UPD_OPRT, DEL_YN, GROUP_ATTRIBUTE_ID, GROUP_CHAR, IS_GALLERY_DISPLAY, CATEGORY, IS_BOLD, ELEMENT_CHAR FROM TBL_GOODS_ATTRIBUTE WHERE CATEGORY = ''''' + @CATEGORY + ''''''')'
	EXEC (@QRY)
	
	-- 속성ID의 분류코드가 변경될 경우 PK 오류 날 수 있음.
	INSERT OPENQUERY(ORADB, 'SELECT ATTRIBUTE_ID, MANAGE_ATTRIBUTE_NM, GALLERY_ATTRIBUTE_NM, IS_MANAGE_DISPLAY, USE_CLASS_CODE, IS_UNIT, UNIT_NM, INS_DATE, INS_OPRT, UPD_DATE, UPD_OPRT, DEL_YN, GROUP_ATTRIBUTE_ID, GROUP_CHAR, IS_GALLERY_DISPLAY, CATEGORY, IS_BOLD, ELEMENT_CHAR FROM TBL_GOODS_ATTRIBUTE')
	SELECT ATTRIBUTE_ID, MANAGE_ATTRIBUTE_NM, GALLERY_ATTRIBUTE_NM, IS_MANAGE_DISPLAY, USE_CLASS_CODE, IS_UNIT, UNIT_NM, INS_DATE, INS_OPRT, UPD_DATE, UPD_OPRT, DEL_YN, GROUP_ATTRIBUTE_ID, GROUP_CHAR, IS_GALLERY_DISPLAY, CATEGORY, IS_BOLD, ELEMENT_CHAR
	FROM GOODS_ATTRIBUTE
	WHERE CATEGORY = @CATEGORY
	
	INSERT OPENQUERY(ORADB, 'SELECT ATTRIBUTE_ID, ATTRIBUTE_ELEMENT_ID, ATTRIBUTE_ELEMENT, DISPLAY_ORDER, DEL_YN, INS_DATE, INS_OPRT, UPD_DATE, UPD_OPRT, IS_DISPLAY, IS_BOLD, SPECNO, ICONNO FROM TBL_GOODS_ATTRIBUTE_ELEMENT')
	SELECT ATTRIBUTE_ID, ATTRIBUTE_ELEMENT_ID, ATTRIBUTE_ELEMENT, DISPLAY_ORDER, DEL_YN, INS_DATE, INS_OPRT, UPD_DATE, UPD_OPRT, IS_DISPLAY, IS_BOLD, SPECNO, ICONNO
	FROM GOODS_ATTRIBUTE_ELEMENT
	WHERE ATTRIBUTE_ID IN (SELECT ATTRIBUTE_ID FROM GOODS_ATTRIBUTE	WHERE CATEGORY = @CATEGORY)
	--##################################################################
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
	
	EXEC UDP_MP_TERMDIC_ATTRIBUTE @CATEGORY
END
