/* *************************************************************************
 * NAME : dbo.USP_PRICELIST_SEL_13
 * TYPE : PROCEDURE (SQL_STORED_PROCEDURE)
 * TIME : Create: 2007-03-26 17:58:58.467
 *        Modify: 2018-05-03 17:23:35.913
 *        Backup: 20180521_1737
 ************************************************************************* */

CREATE PROC [dbo].[USP_PRICELIST_SEL_13]
	@PL_VCODE INT,
	@PL_MODELNO INT,
	@PL_GOODSCODE VARCHAR(50)
AS
BEGIN
	SET NOCOUNT ON
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
	SELECT PL_NO
	FROM PRICELIST-- WITH (INDEX(NCL_PRICELIST_6))
	WHERE PL_VCODE= @PL_VCODE
		AND PL_MODELNO = @PL_MODELNO
		AND PL_GOODSCODE = @PL_GOODSCODE
		AND PL_GOODSCODE_CS = CHECKSUM(@PL_GOODSCODE)
	ORDER BY PL_DATE DESC
END