/* *************************************************************************
 * NAME : dbo.UDP_NB_PRICELIST_SDU_CHECK_PROC_1
 * TYPE : PROCEDURE (SQL_STORED_PROCEDURE)
 * TIME : Create: 2004-11-26 16:35:26.797
 *        Modify: 2015-05-15 03:31:33.503
 *        Backup: 20180521_1737
 ************************************************************************* */







-- UDP_NB_PRICELIST_SDU_CHECK_PROC_1  :   edit bslee2004.11.26 --
CREATE              PROC UDP_NB_PRICELIST_SDU_CHECK_PROC_1
	@p_vcode int
AS
BEGIN
	SET NOCOUNT ON
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
	
	SELECT
		PL_NO
		, PL_MODELNO
		, PL_VCODE
		, PL_CATEGORY
		, PL_GOODSNM
		, IsNull(PL_PRICE, 0) as PL_PRICE
		, IsNull(PL_URL, '') as PL_URL
		, PL_NOTE
		, PL_SRVFLAG
		, PL_STATUS
		, PL_ETC
		, PL_AUTHFLAG
		, PL_AUTHDATE
		, PL_DATE
		, ISNULL(PL_RIGHTNLEFT, '0') AS PL_RIGHTNLEFT
		, PL_IMGURL
		, PL_COUPON
		, PL_DELFEETYPE
		, IsNull(PL_DELPRICE,0) as PL_DELPRICE 
		, PL_DELIVERYFLAG
		,PL_DELFEEDESC
		,PL_DELAREADESC 
		,PL_ACCOUNT_YN
	FROM PRICELIST WITH(READUNCOMMITTED)
	WHERE
		PL_VCODE= @p_vcode 
		AND PL_MODELNO > 0 
		AND (PL_GOODSNM IS NULL OR LEN(PL_GOODSNM) < 2)
		AND PL_STATUS < '3'
	
	SET NOCOUNT OFF
END






