/* *************************************************************************
 * NAME : dbo.UDP_VA_LIST
 * TYPE : PROCEDURE (SQL_STORED_PROCEDURE)
 * TIME : Create: 2005-07-26 16:32:28.03
 *        Modify: 2018-05-03 17:23:34.093
 *        Backup: 20180521_1737
 ************************************************************************* */

CREATE PROC UDP_VA_LIST
	@SDATE VARCHAR(8),
	@EDATE VARCHAR(8),

	@LISTSIZE	INT,
	@PAGESIZE	INT,
	@PAGE		INT
	
AS
BEGIN
	SET NOCOUNT ON
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

	DECLARE @SEEK INT
	SET @SEEK = @LISTSIZE * @PAGE

	DECLARE @SQL NVARCHAR(3000)
	DECLARE @CNTSQL NVARCHAR(1000)
	DECLARE @DETAILSQL NVARCHAR(1000)
	DECLARE @ORDERSQL NVARCHAR(100)
	
	SET @CNTSQL = N' SELECT COUNT(SL_KEY) '
	SET @DETAILSQL =  N' SELECT TOP  ' + CONVERT( VARCHAR(15), @SEEK)
	SET @DETAILSQL = @DETAILSQL +  N' D.SL_KEY, '
	SET @DETAILSQL = @DETAILSQL +  N' D.SL_SHOP_CODE, '
	SET @DETAILSQL = @DETAILSQL +  N' S.SHOP_NAME, '
	SET @DETAILSQL = @DETAILSQL +  N' D.SL_PRICE, '
	SET @DETAILSQL = @DETAILSQL +  N' D.SL_REGYMD, '
	SET @DETAILSQL = @DETAILSQL +  N' D.SL_REGHMS, '
	SET @DETAILSQL = @DETAILSQL +  N' D.SL_STATUS '

	SET @SQL = N' FROM TBL_SHOPDEPOSIT_LIST D '
	SET @SQL = @SQL +  N' INNER JOIN SHOPLIST S '
	SET @SQL = @SQL +  N' ON D.SL_SHOP_CODE = S.SHOP_VCODE '
	SET @SQL = @SQL +  N' WHERE D.SL_REGYMD >= ''' + @SDATE + ''' '
	SET @SQL = @SQL +  N' AND D.SL_REGYMD <= ''' + @EDATE + ''' '

	SET @ORDERSQL = N' ORDER BY D.SL_REGYMD DESC, D.SL_REGHMS DESC '
	
	DECLARE @LASTSQL	NVARCHAR(4000)
	--1. 전체 갯수확인
	SET @LASTSQL = @CNTSQL + @SQL
	EXEC SP_EXECUTESQL @LASTSQL

	--2. 리스트 확인
	SET @LASTSQL = @DETAILSQL + @SQL + @ORDERSQL
	EXEC SP_EXECUTESQL @LASTSQL

	/*
	SELECT 
		D.SL_KEY,
		D.SL_SHOP_CODE,
		S.SHOP_NAME,
		D.SL_PRICE,
		D.SL_REGYMD,
		D.SL_REGHMS,
		D.SL_STATUS

	FROM TBL_SHOPDEPOSIT_LIST D
	LEFT JOIN SHOPLIST S
	ON D.SL_SHOP_CODE = S.SHOP_VCODE
	WHERE D.SL_REGYMD >= @SDATE
		AND D.SL_REGYMD <= @EDATE
	*/
END
