/* *************************************************************************
 * NAME : dbo.UDP_MP_TBL_DUPCHECK_MODEL_STATS
 * TYPE : PROCEDURE (SQL_STORED_PROCEDURE)
 * TIME : Create: 2016-05-03 17:49:11.297
 *        Modify: 2018-05-03 17:23:36.043
 *        Backup: 20180521_1737
 ************************************************************************* */


CREATE PROC [DBO].[UDP_MP_TBL_DUPCHECK_MODEL_STATS]
	@CA_CODE VARCHAR(12),
	@MM_ID VARCHAR(15)
AS
BEGIN
	SET NOCOUNT ON;
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
	
	DECLARE @AUTO INT
	DECLARE @MANUAL INT
	
	-- 수동처리 CONVERT(VARCHAR(10), GETDATE(), 112) -> CONVERT(VARCHAR(10), DATEADD(DAY, -1, GETDATE()), 112)

	SELECT @AUTO = COUNT(DISTINCT JG_MODELNO)
	--FROM (
	--	SELECT DISTINCT JG_MODELNO
		FROM LOGDB.DBO.JOB_GOODS
		WHERE JG_MODELNO IN (
			SELECT MODELNO
			FROM TBL_DUPCHECK_MODEL
			WHERE CA_CODE = @CA_CODE AND JTYPE IN ('1', '3')
		) AND JG_ID = @MM_ID AND JG_FLAG = 'D'
	--	UNION ALL
	--	SELECT DISTINCT JG_MODELNO
	--	FROM OLTPLOG_196.OLTPLOG.DBO.JOB_GOODS
	--	WHERE JG_MODELNO IN (
	--		SELECT MODELNO
	--		FROM TBL_DUPCHECK_MODEL
	--		WHERE CA_CODE = @CA_CODE AND JTYPE IN ('1', '3')
	--	) AND JG_ID = @MM_ID AND JG_FLAG = 'D'
	--) A

	SELECT @MANUAL = COUNT(MODELNO) - COUNT(DISTINCT INDEXER)
	FROM TBL_DUPCHECK_MODEL
	WHERE CA_CODE = @CA_CODE AND JTYPE = '2' AND JOB_FLAG = '0'

	UPDATE TBL_DUPCHECK_MODEL_LOG
	SET AUTO_MODEL_CNT = @AUTO, MANUAL_MODEL_CNT = @MANUAL
	WHERE START_DATE = CONVERT(VARCHAR(10), GETDATE(), 112) AND CA_CODE = @CA_CODE
END
