/* *************************************************************************
 * NAME : dbo.UDF_RTN_SUPPLY_MODELNM
 * TYPE : FUNCTION (SQL_SCALAR_FUNCTION)
 * TIME : Create: 2015-10-12 18:47:20.233
 *        Modify: 2018-05-03 17:23:34.287
 *        Backup: 20180521_1737
 ************************************************************************* */

CREATE FUNCTION UDF_RTN_SUPPLY_MODELNM (@SZMODELNO INT)
RETURNS VARCHAR(5000)
AS
BEGIN
	DECLARE @RETURN VARCHAR(5000)
	DECLARE @SZMODELNM VARCHAR(200)
	
	DECLARE FETCH_CURSOR CURSOR FOR
	SELECT DISTINCT ORIGINMODELNM
	FROM (
		SELECT B.G_MODELNM AS ORIGINMODELNM
		FROM GOODS_PRTSUPPLY
			INNER JOIN GOODS A ON A.G_MODELNO = GPRT_MODELNO
			INNER JOIN GOODS B ON B.G_MODELNO = GPRT_POINTMODELNO
		WHERE A.G_CATEGORY LIKE '040207%' AND GPRT_MODELNO = @SZMODELNO
		UNION ALL
		SELECT A.G_MODELNM AS ORIGINMODELNM
		FROM GOODS_PRTSUPPLY
			INNER JOIN GOODS A ON A.G_MODELNO = GPRT_MODELNO
			INNER JOIN GOODS B ON B.G_MODELNO = GPRT_POINTMODELNO
		WHERE B.G_CATEGORY LIKE '0402%' AND GPRT_POINTMODELNO = @SZMODELNO) A
	
	OPEN FETCH_CURSOR
	
	SELECT @RETURN = ''
	FETCH NEXT FROM FETCH_CURSOR INTO @SZMODELNM
	WHILE (@@FETCH_STATUS = 0)
	BEGIN
		SELECT @RETURN = @RETURN + CASE WHEN @RETURN <> '' THEN ' ' ELSE '' END + REPLACE(@SZMODELNM, '@', ' ')
		FETCH NEXT FROM FETCH_CURSOR INTO @SZMODELNM
	END
	
	CLOSE FETCH_CURSOR
	
	DEALLOCATE FETCH_CURSOR
	
	RETURN @RETURN
END
