/* *************************************************************************
 * NAME : dbo.UDP_OPTION_PRICE_INSERT
 * TYPE : PROCEDURE (SQL_STORED_PROCEDURE)
 * TIME : Create: 2014-11-10 14:51:52.773
 *        Modify: 2018-05-03 17:23:35.583
 *        Backup: 20180521_1737
 ************************************************************************* */


CREATE    PROC [dbo].[UDP_OPTION_PRICE_INSERT]
AS
BEGIN
	SET NOCOUNT ON;
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
	
	WITH
		TEMP_JOB_PRICELIST(JP_PLISTNO, JP_VCODE, JP_GOODSNM, JP_PRICE, JP_CATEGORY, JP_MODELNO) AS
		(
			SELECT JP_PLISTNO, JP_VCODE, JP_GOODSNM, JP_PRICE, JP_CATEGORY, JP_MODELNO
			FROM OLTPLOG_196.OLTPLOG.DBO.JOB_PRICELIST WITH (READUNCOMMITTED)
			WHERE JP_DATE > DATEADD(DAY, -1, CAST(CAST(GETDATE() AS VARCHAR(10)) AS SMALLDATETIME)) AND JP_FLAG = '0' AND JP_MODELNO > 0 AND
				  JP_ID NOT LIKE 'ENURI%' AND JP_ID NOT LIKE 'BRAND%' AND JP_ID NOT LIKE 'MP%' AND JP_ID NOT LIKE 'NURIBOT%' AND JP_ID NOT LIKE 'SHOP%' AND JP_ID NOT LIKE 'SDU%'
		),
		TEMP_PRICELIST(PL_MODELNO, MIN_PRICE, OPTION_PRICE, PL_URL, PL_GOODSCODE) AS
		(
			SELECT PL_MODELNO, MIN(PL_PRICE), MIN(CASE WHEN OPTION_FLAG2 = '1' THEN PL_PRICE END), MAX(PL_URL), MAX(PL_GOODSCODE)
			FROM PRICELIST WITH (READUNCOMMITTED)
			WHERE PL_STATUS IN ('0','1') AND PL_MODELNO IN (
				SELECT DISTINCT PL_MODELNO
				FROM PRICELIST WITH (READUNCOMMITTED)
				WHERE PL_MODELNO > 0 AND PL_STATUS IN ('0','1') AND OPTION_FLAG2 = '1' AND PL_MODELNO IN (SELECT DISTINCT JP_MODELNO FROM TEMP_JOB_PRICELIST WITH (READUNCOMMITTED))
			)
			GROUP BY PL_MODELNO
		)
	INSERT INTO TBL_STRANGE_LIST (SL_PLNO, SL_VCODE, SL_GOODSNM, SL_PRICE, SL_URL, SL_GOODSCODE, SL_CATEGORY, SL_MODELNO, SL_SRVFLAG)
	SELECT JP_PLISTNO, JP_VCODE, JP_GOODSNM, JP_PRICE, PL_URL, PL_GOODSCODE, JP_CATEGORY, JP_MODELNO, 'O'
	FROM TEMP_JOB_PRICELIST WITH (READUNCOMMITTED)
		INNER JOIN TEMP_PRICELIST WITH (READUNCOMMITTED) ON JP_MODELNO = PL_MODELNO
	WHERE JP_PRICE < OPTION_PRICE AND MIN_PRICE * 1.05 >= OPTION_PRICE
	OPTION (MAXDOP 1)
END

