/* *************************************************************************
 * NAME : dbo.UDF_GET_PL_NO_MODELNO
 * TYPE : FUNCTION (SQL_SCALAR_FUNCTION)
 * TIME : Create: 2006-03-27 17:32:01.56
 *        Modify: 2015-05-15 03:31:33.923
 *        Backup: 20180521_1737
 ************************************************************************* */

CREATE FUNCTION UDF_GET_PL_NO_MODELNO( @MODELNO INT)
	RETURNS INT
AS
BEGIN
	DECLARE @RET INT		
	SET @RET=0
	IF @MODELNO>0 
	BEGIN
		SELECT TOP 1 @RET = PL_NO
			--CASE WHEN (PL_INSTANCE_PRICE IS NULL OR PL_INSTANCE_PRICE=0) THEN PRICE ELSE PL_INSTANCE_PRICE END			
		FROM PRICELIST WITH (READUNCOMMITTED)
		WHERE PL_MODELNO=@MODELNO
			AND PL_SRVFLAG='0'
			AND PL_STATUS<'3'
			AND PL_JOBCODE='1'
		ORDER BY CASE WHEN (PL_INSTANCE_PRICE IS NULL OR PL_INSTANCE_PRICE=0) THEN PL_PRICE ELSE PL_INSTANCE_PRICE END ASC, PL_JOBTYPE DESC	

	END
	ELSE
	BEGIN
		SET @RET=0
	END 

	RETURN @RET
END
