/* *************************************************************************
 * NAME : dbo.UDP_MAKERBRAND_STATUS_SYNC
 * TYPE : PROCEDURE (SQL_STORED_PROCEDURE)
 * TIME : Create: 2017-04-07 16:06:19.283
 *        Modify: 2018-05-03 17:23:34.743
 *        Backup: 20180521_1737
 ************************************************************************* */


CREATE PROC [DBO].[UDP_MAKERBRAND_STATUS_SYNC]
AS
BEGIN
	SET NOCOUNT ON;
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
	
	-- 삭제된 제조사의 브랜드 삭제
	UPDATE TBL_ENURI_BRAND
	SET DEL_YN = 'Y', UPD_DATE = GETDATE(), UPD_OPRT = 'Lab_batch'
	WHERE DEL_YN = 'N' AND MAKER_ID IN (SELECT MAKER_ID FROM TBL_ENURI_MAKER WHERE DEL_YN = 'Y')
	
	-- 삭제된 제조사 EBAY-ENURI 매칭 삭제
	UPDATE TBL_EBAY_MATCHING_MAKER
	SET DEL_YN = 'Y', UPD_DATE = GETDATE(), UPD_OPRT = 'Lab_batch'
	WHERE DEL_YN = 'N' AND (EBAY_MAKER_ID IN (SELECT MAKER_ID FROM TBL_EBAY_MAKER WHERE DEL_YN = 'Y') OR ENURI_MAKER_ID IN (SELECT MAKER_ID FROM TBL_ENURI_MAKER WHERE DEL_YN = 'Y'))
	
	-- 삭제된 브랜드 EBAY-ENURI 매칭 삭제
	UPDATE TBL_EBAY_MATCHING_BRAND
	SET DEL_YN = 'Y', UPD_DATE = GETDATE(), UPD_OPRT = 'Lab_batch'
	WHERE DEL_YN = 'N' AND (EBAY_BRAND_ID IN (SELECT BRAND_ID FROM TBL_EBAY_BRAND WHERE DEL_YN = 'Y') OR ENURI_BRAND_ID IN (SELECT BRAND_ID FROM TBL_ENURI_BRAND WHERE DEL_YN = 'Y'))
END
