/* *************************************************************************
 * NAME : dbo.UDP_MP_GOODS_ATTRIBUTE_CONVERSION
 * TYPE : PROCEDURE (SQL_STORED_PROCEDURE)
 * TIME : Create: 2017-05-12 17:17:49.307
 *        Modify: 2018-05-03 17:23:34.677
 *        Backup: 20180521_1737
 ************************************************************************* */


CREATE PROC [DBO].[UDP_MP_GOODS_ATTRIBUTE_CONVERSION]
	@MODELNO INT,
	@MM_ID VARCHAR(20)
AS
BEGIN
	SET NOCOUNT ON;
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
	
	DECLARE @CATEGORY VARCHAR(12)
	SELECT @CATEGORY = LTRIM(RTRIM(ISNULL(G_CATEGORY, '')))
	FROM GOODS
	WHERE G_MODELNO = @MODELNO
	
	CREATE TABLE #TARGET(
		MODELNO INT,
		ATTRIBUTE_ID INT,
		ATTRIBUTE_ELEMENT_ID SMALLINT
	)
	CREATE TABLE #CONVERSION_FORMULA(
		FORMULA VARCHAR(4000),
		REF_ATTRIBUTE_ELEMENT_ID SMALLINT
	)
	
	DECLARE @CRITERIA_SEQ INT
	DECLARE @ATTRIBUTE_ID INT
	DECLARE @ATTRIBUTE_ELEMENT_ID SMALLINT
	DECLARE @REF_ATTRIBUTE_ID INT
	DECLARE CONVERSION_CURSOR CURSOR FOR
	SELECT CRITERIA_SEQ, ATTRIBUTE_ID, ATTRIBUTE_ELEMENT_ID, REF_ATTRIBUTE_ID
	FROM GOODS_ATTRIBUTE_CONVERSION_CRITERIA
	WHERE CA_CODE = LEFT(@CATEGORY, 4) AND DEL_YN = 'N'
	ORDER BY CRITERIA_SEQ
	
	OPEN CONVERSION_CURSOR
	
	FETCH NEXT FROM CONVERSION_CURSOR INTO @CRITERIA_SEQ, @ATTRIBUTE_ID, @ATTRIBUTE_ELEMENT_ID, @REF_ATTRIBUTE_ID
	WHILE @@FETCH_STATUS = 0
	BEGIN
		TRUNCATE TABLE #TARGET
		TRUNCATE TABLE #CONVERSION_FORMULA
		INSERT INTO #CONVERSION_FORMULA(FORMULA, REF_ATTRIBUTE_ELEMENT_ID)
		SELECT REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(UPPER(CRITERIA_RANGE), 'C', '(' + UPPER(CONVERSION_FORMULA) + ')'), 'A', CAST(CAST(REPLACE(UPPER(LTRIM(RTRIM(ISNULL(C.ATTRIBUTE_VALUE, '')))), UPPER(LTRIM(RTRIM(ATTRIBUTE_UNIT))), '') AS FLOAT) AS VARCHAR(500))), 'B', CAST(CAST(REPLACE(UPPER(LTRIM(RTRIM(ISNULL(B.ATTRIBUTE_VALUE, '')))), UPPER(LTRIM(RTRIM(CRITERIA_UNIT))), '') AS FLOAT) AS VARCHAR(500))), '&&', 'AND'), '||', 'OR'), REF_ATTRIBUTE_ELEMENT_ID
		FROM GOODS_ATTRIBUTE_CONVERSION A
			INNER JOIN GOODS_CATALOG_ATTRIBUTE B ON B.DEL_YN = 'N' AND B.G_MODELNO = @MODELNO AND B.ATTRIBUTE_ID = @ATTRIBUTE_ID AND B.ATTRIBUTE_ELEMENT_ID = @ATTRIBUTE_ELEMENT_ID
			INNER JOIN GOODS_CATALOG_ATTRIBUTE C ON C.DEL_YN = 'N' AND C.G_MODELNO = @MODELNO AND C.ATTRIBUTE_ID = A.ATTRIBUTE_ID AND C.ATTRIBUTE_ELEMENT_ID = A.ATTRIBUTE_ELEMENT_ID
		WHERE CRITERIA_SEQ = @CRITERIA_SEQ AND A.DEL_YN = 'N'
		  AND REF_ATTRIBUTE_ID = @REF_ATTRIBUTE_ID
		  AND LTRIM(RTRIM(CRITERIA_UNIT)) <> ''
		  AND ISNUMERIC(REPLACE(UPPER(LTRIM(RTRIM(ISNULL(B.ATTRIBUTE_VALUE, '')))), UPPER(LTRIM(RTRIM(CRITERIA_UNIT))), '')) = 1
		  AND ISNUMERIC(REPLACE(UPPER(LTRIM(RTRIM(ISNULL(C.ATTRIBUTE_VALUE, '')))), UPPER(LTRIM(RTRIM(ATTRIBUTE_UNIT))), '')) = 1
		
		DECLARE @FORMULA VARCHAR(4000)
		DECLARE @REF_ATTRIBUTE_ELEMENT_ID SMALLINT
		DECLARE FETCH_CURSOR CURSOR FOR
		SELECT FORMULA, REF_ATTRIBUTE_ELEMENT_ID
		FROM #CONVERSION_FORMULA
		
		OPEN FETCH_CURSOR
		
		FETCH NEXT FROM FETCH_CURSOR INTO @FORMULA, @REF_ATTRIBUTE_ELEMENT_ID
		WHILE @@FETCH_STATUS = 0
		BEGIN
			DECLARE @QRY VARCHAR(8000)
			SET @QRY = '
				IF ' + @FORMULA + '
					INSERT INTO #TARGET(MODELNO, ATTRIBUTE_ID, ATTRIBUTE_ELEMENT_ID) SELECT ' + CAST(@MODELNO AS VARCHAR(20)) + ', ' + CAST(@REF_ATTRIBUTE_ID AS VARCHAR(20)) + ', ' + CAST(@REF_ATTRIBUTE_ELEMENT_ID AS VARCHAR(20))
			EXEC (@QRY)
			
			FETCH NEXT FROM FETCH_CURSOR INTO @FORMULA, @REF_ATTRIBUTE_ELEMENT_ID
		END
		
		CLOSE FETCH_CURSOR
		DEALLOCATE FETCH_CURSOR
		
		SET @QRY = '
			INSERT INTO GOODS_CATALOG_ATTRIBUTE(G_MODELNO, ATTRIBUTE_ID, ATTRIBUTE_ELEMENT_ID, INS_DATE, INS_OPRT, DEL_YN, UPD_DATE, UPD_OPRT)
			SELECT DISTINCT MODELNO, A.ATTRIBUTE_ID, A.ATTRIBUTE_ELEMENT_ID, GETDATE(), ''' + @MM_ID + ''', ''N'', GETDATE(), ''temp_batch''
			FROM #TARGET A
				LEFT JOIN GOODS_CATALOG_ATTRIBUTE B ON G_MODELNO = MODELNO AND B.ATTRIBUTE_ID = A.ATTRIBUTE_ID AND B.ATTRIBUTE_ELEMENT_ID = A.ATTRIBUTE_ELEMENT_ID
			WHERE G_MODELNO IS NULL
			
			UPDATE GOODS_CATALOG_ATTRIBUTE
			SET DEL_YN = ''N''
				, INS_DATE = (CASE WHEN DEL_YN = ''Y'' THEN GETDATE() ELSE INS_DATE END)
				, UPD_DATE = (CASE WHEN DEL_YN = ''Y'' THEN GETDATE() ELSE UPD_DATE END)
				, UPD_OPRT = ''temp_batch''
			FROM GOODS_CATALOG_ATTRIBUTE A
				INNER JOIN #TARGET B ON MODELNO = G_MODELNO AND B.ATTRIBUTE_ID = A.ATTRIBUTE_ID AND B.ATTRIBUTE_ELEMENT_ID = A.ATTRIBUTE_ELEMENT_ID
			
			UPDATE GOODS_CATALOG_ATTRIBUTE
			SET DEL_YN = (CASE WHEN UPD_OPRT = ''temp_batch'' THEN DEL_YN ELSE ''Y'' END)
				, UPD_DATE = (CASE WHEN UPD_OPRT = ''temp_batch'' THEN UPD_DATE ELSE GETDATE() END)
				, UPD_OPRT = ''' + @MM_ID + '''
			WHERE DEL_YN = ''N'' AND G_MODELNO = ' + CAST(@MODELNO AS VARCHAR(20)) + ' AND ATTRIBUTE_ID = ' + CAST(@REF_ATTRIBUTE_ID AS VARCHAR(20))
		EXEC (@QRY)
		
		FETCH NEXT FROM CONVERSION_CURSOR INTO @CRITERIA_SEQ, @ATTRIBUTE_ID, @ATTRIBUTE_ELEMENT_ID, @REF_ATTRIBUTE_ID
	END
	
	CLOSE CONVERSION_CURSOR
	DEALLOCATE CONVERSION_CURSOR
	
	/*
	TRUNCATE TABLE GOODS_ATTRIBUTE_CONVERSION_CRITERIA
	INSERT INTO GOODS_ATTRIBUTE_CONVERSION_CRITERIA(CA_CODE, ATTRIBUTE_ID, ATTRIBUTE_ELEMENT_ID, REF_ATTRIBUTE_ID, UPD_OPRT)
	VALUES('1508', 210415, 1, 212488, 'Lab_batch')

	TRUNCATE TABLE GOODS_ATTRIBUTE_CONVERSION
	INSERT INTO GOODS_ATTRIBUTE_CONVERSION(CRITERIA_SEQ, CRITERIA_UNIT, ATTRIBUTE_ID, ATTRIBUTE_ELEMENT_ID, ATTRIBUTE_UNIT, CONVERSION_FORMULA, CRITERIA_RANGE, REF_ATTRIBUTE_ID, REF_ATTRIBUTE_ELEMENT_ID, UPD_OPRT)
	VALUES(1, 'g', 202115, 1, 'kcal', 'A * 100 / B', 'C < 40', 212488, 4, 'Lab_batch')
	INSERT INTO GOODS_ATTRIBUTE_CONVERSION(CRITERIA_SEQ, CRITERIA_UNIT, ATTRIBUTE_ID, ATTRIBUTE_ELEMENT_ID, ATTRIBUTE_UNIT, CONVERSION_FORMULA, CRITERIA_RANGE, REF_ATTRIBUTE_ID, REF_ATTRIBUTE_ELEMENT_ID, UPD_OPRT)
	VALUES(1, 'ml', 202115, 1, 'kcal', 'A * 100 / B', 'C < 4', 212488, 1, 'Lab_batch')
	INSERT INTO GOODS_ATTRIBUTE_CONVERSION(CRITERIA_SEQ, CRITERIA_UNIT, ATTRIBUTE_ID, ATTRIBUTE_ELEMENT_ID, ATTRIBUTE_UNIT, CONVERSION_FORMULA, CRITERIA_RANGE, REF_ATTRIBUTE_ID, REF_ATTRIBUTE_ELEMENT_ID, UPD_OPRT)
	VALUES(1, 'ml', 202115, 1, 'kcal', 'A * 100 / B', '4 <= C && C < 40', 212488, 4, 'Lab_batch')
	
	INSERT INTO GOODS_ATTRIBUTE_CONVERSION(CRITERIA_SEQ, CRITERIA_UNIT, ATTRIBUTE_ID, ATTRIBUTE_ELEMENT_ID, ATTRIBUTE_UNIT, CONVERSION_FORMULA, CRITERIA_RANGE, REF_ATTRIBUTE_ID, REF_ATTRIBUTE_ELEMENT_ID, UPD_OPRT)
	VALUES(1, 'g', 166219, 1, 'g', 'A * 100 / B', 'C < 0.5', 212488, 7, 'Lab_batch')
	INSERT INTO GOODS_ATTRIBUTE_CONVERSION(CRITERIA_SEQ, CRITERIA_UNIT, ATTRIBUTE_ID, ATTRIBUTE_ELEMENT_ID, ATTRIBUTE_UNIT, CONVERSION_FORMULA, CRITERIA_RANGE, REF_ATTRIBUTE_ID, REF_ATTRIBUTE_ELEMENT_ID, UPD_OPRT)
	VALUES(1, 'g', 166219, 1, 'g', 'A * 100 / B', '0.5 <= C && C < 5', 212488, 8, 'Lab_batch')
	INSERT INTO GOODS_ATTRIBUTE_CONVERSION(CRITERIA_SEQ, CRITERIA_UNIT, ATTRIBUTE_ID, ATTRIBUTE_ELEMENT_ID, ATTRIBUTE_UNIT, CONVERSION_FORMULA, CRITERIA_RANGE, REF_ATTRIBUTE_ID, REF_ATTRIBUTE_ELEMENT_ID, UPD_OPRT)
	VALUES(1, 'ml', 166219, 1, 'g', 'A * 100 / B', 'C < 0.5', 212488, 7, 'Lab_batch')
	INSERT INTO GOODS_ATTRIBUTE_CONVERSION(CRITERIA_SEQ, CRITERIA_UNIT, ATTRIBUTE_ID, ATTRIBUTE_ELEMENT_ID, ATTRIBUTE_UNIT, CONVERSION_FORMULA, CRITERIA_RANGE, REF_ATTRIBUTE_ID, REF_ATTRIBUTE_ELEMENT_ID, UPD_OPRT)
	VALUES(1, 'ml', 166219, 1, 'g', 'A * 100 / B', '0.5 <= C && C < 2.5', 212488, 8, 'Lab_batch')
	
	INSERT INTO GOODS_ATTRIBUTE_CONVERSION(CRITERIA_SEQ, CRITERIA_UNIT, ATTRIBUTE_ID, ATTRIBUTE_ELEMENT_ID, ATTRIBUTE_UNIT, CONVERSION_FORMULA, CRITERIA_RANGE, REF_ATTRIBUTE_ID, REF_ATTRIBUTE_ELEMENT_ID, UPD_OPRT)
	VALUES(1, 'g', 166223, 1, 'g', 'A * 100 / B', 'C < 0.5', 212488, 5, 'Lab_batch')
	INSERT INTO GOODS_ATTRIBUTE_CONVERSION(CRITERIA_SEQ, CRITERIA_UNIT, ATTRIBUTE_ID, ATTRIBUTE_ELEMENT_ID, ATTRIBUTE_UNIT, CONVERSION_FORMULA, CRITERIA_RANGE, REF_ATTRIBUTE_ID, REF_ATTRIBUTE_ELEMENT_ID, UPD_OPRT)
	VALUES(1, 'g', 166223, 1, 'g', 'A * 100 / B', '0.5 <= C && C < 3', 212488, 6, 'Lab_batch')
	INSERT INTO GOODS_ATTRIBUTE_CONVERSION(CRITERIA_SEQ, CRITERIA_UNIT, ATTRIBUTE_ID, ATTRIBUTE_ELEMENT_ID, ATTRIBUTE_UNIT, CONVERSION_FORMULA, CRITERIA_RANGE, REF_ATTRIBUTE_ID, REF_ATTRIBUTE_ELEMENT_ID, UPD_OPRT)
	VALUES(1, 'ml', 166223, 1, 'g', 'A * 100 / B', 'C < 0.5', 212488, 5, 'Lab_batch')
	INSERT INTO GOODS_ATTRIBUTE_CONVERSION(CRITERIA_SEQ, CRITERIA_UNIT, ATTRIBUTE_ID, ATTRIBUTE_ELEMENT_ID, ATTRIBUTE_UNIT, CONVERSION_FORMULA, CRITERIA_RANGE, REF_ATTRIBUTE_ID, REF_ATTRIBUTE_ELEMENT_ID, UPD_OPRT)
	VALUES(1, 'ml', 166223, 1, 'g', 'A * 100 / B', '0.5 <= C && C < 1.5', 212488, 6, 'Lab_batch')
	
	INSERT INTO GOODS_ATTRIBUTE_CONVERSION(CRITERIA_SEQ, CRITERIA_UNIT, ATTRIBUTE_ID, ATTRIBUTE_ELEMENT_ID, ATTRIBUTE_UNIT, CONVERSION_FORMULA, CRITERIA_RANGE, REF_ATTRIBUTE_ID, REF_ATTRIBUTE_ELEMENT_ID, UPD_OPRT)
	VALUES(1, 'g', 166218, 1, 'mg', 'A * 100 / B', 'C < 5', 212488, 9, 'Lab_batch')
	INSERT INTO GOODS_ATTRIBUTE_CONVERSION(CRITERIA_SEQ, CRITERIA_UNIT, ATTRIBUTE_ID, ATTRIBUTE_ELEMENT_ID, ATTRIBUTE_UNIT, CONVERSION_FORMULA, CRITERIA_RANGE, REF_ATTRIBUTE_ID, REF_ATTRIBUTE_ELEMENT_ID, UPD_OPRT)
	VALUES(1, 'g', 166218, 1, 'mg', 'A * 100 / B', '5 <= C && C < 120', 212488, 10, 'Lab_batch')
	*/
END
