/* *************************************************************************
 * NAME : dbo.UDP_JCA_AP_REPORT_INS_ORD_PMPINSIDE
 * TYPE : PROCEDURE (SQL_STORED_PROCEDURE)
 * TIME : Create: 2008-03-18 13:12:17.287
 *        Modify: 2018-05-03 17:23:35.66
 *        Backup: 20180521_1737
 ************************************************************************* */

CREATE PROC [dbo].[UDP_JCA_AP_REPORT_INS_ORD_PMPINSIDE]
	@SHOPCODE	INT,
	@YEAR		INT,
	@MONTH		INT,
	@DAY		INT,
	@MONEY		MONEY
AS
	SET NOCOUNT ON
	SET TRANSACTION ISOLATION LEVEL  READ UNCOMMITTED
	-- ----------------------------------------------------------------------------------
	-- 작성자 : WOOKKI25 / 2008.03.18
	-- 설  명 : AP 업체 일별 주문액 데이터 입력
	-- 실  행 : UDP_JCA_AP_REPORT_INS_ORD_PMPINSIDE 536, 2008, 12, 6, 6000
	-- ----------------------------------------------------------------------------------
	
	-- ----------------------------------------------------------------------------------
	-- 수정내역
	-- ----------------------------------------------------------------------------------
	/*
	수정일:			수정자:			수정내용:
	----------		-----------		-----------------------------------------------------		
	*/
	IF NOT EXISTS(SELECT TOP 1 * FROM TBL_AP_SHOP_PMPINSIDE WHERE AS_SHOP=@SHOPCODE AND AS_DATE_YEAR=@YEAR AND AS_DATE_MONTH=@MONTH)
	BEGIN
		INSERT INTO TBL_AP_SHOP_PMPINSIDE (AS_SHOP, AS_DATE_YEAR, AS_DATE_MONTH)
		VALUES (@SHOPCODE, @YEAR, @MONTH)		
	END
	
	DECLARE @SUM1	MONEY,@SUM2	MONEY,@SUM3	MONEY,@SUM4	MONEY,@SUM5	MONEY,@SUM6	MONEY,@SUM7	MONEY,@SUM8	MONEY,@SUM9	MONEY
	DECLARE @SUM10	MONEY,@SUM11	MONEY,@SUM12	MONEY,@SUM13	MONEY,@SUM14	MONEY,@SUM15	MONEY,@SUM16	MONEY,@SUM17	MONEY,@SUM18	MONEY
	DECLARE @SUM19	MONEY,@SUM20	MONEY,@SUM21	MONEY,@SUM22	MONEY,@SUM23	MONEY,@SUM24	MONEY,@SUM25	MONEY,@SUM26	MONEY,@SUM27	MONEY
	DECLARE @SUM28	MONEY,@SUM29	MONEY,@SUM30	MONEY,@SUM31	MONEY
	
	-- 일별 데이터 업데이트
	UPDATE	TBL_AP_SHOP_PMPINSIDE
	SET		@SUM1 = 	AS_DAY1  =  CASE WHEN @DAY = 1 THEN @MONEY ELSE AS_DAY1  END,
			@SUM2 =		AS_DAY2  =  CASE WHEN @DAY = 2 THEN @MONEY ELSE AS_DAY2 END,
			@SUM3 =		AS_DAY3  =  CASE WHEN @DAY = 3 THEN @MONEY ELSE AS_DAY3 END,
			@SUM4 =		AS_DAY4  =  CASE WHEN @DAY = 4 THEN @MONEY ELSE AS_DAY4 END,
			@SUM5 =		AS_DAY5  =  CASE WHEN @DAY = 5 THEN @MONEY ELSE AS_DAY5 END,
			@SUM6 =		AS_DAY6  =  CASE WHEN @DAY = 6 THEN @MONEY ELSE AS_DAY6 END,
			@SUM7 =		AS_DAY7  =  CASE WHEN @DAY = 7 THEN @MONEY ELSE AS_DAY7 END,
			@SUM8 =		AS_DAY8  =  CASE WHEN @DAY = 8 THEN @MONEY ELSE AS_DAY8 END,
			@SUM9 =		AS_DAY9  =  CASE WHEN @DAY = 9 THEN @MONEY ELSE AS_DAY9 END,
			@SUM10 =	AS_DAY10 =  CASE WHEN @DAY = 10 THEN @MONEY ELSE AS_DAY10 END,
			@SUM11 =	AS_DAY11 =  CASE WHEN @DAY = 11 THEN @MONEY ELSE AS_DAY11 END,
			@SUM12 =	AS_DAY12 =  CASE WHEN @DAY = 12 THEN @MONEY ELSE AS_DAY12 END,
			@SUM13 =	AS_DAY13 =  CASE WHEN @DAY = 13 THEN @MONEY ELSE AS_DAY13 END,
			@SUM14 =	AS_DAY14 =  CASE WHEN @DAY = 14 THEN @MONEY ELSE AS_DAY14 END,
			@SUM15 =	AS_DAY15 =  CASE WHEN @DAY = 15 THEN @MONEY ELSE AS_DAY15 END,
			@SUM16 =	AS_DAY16 =  CASE WHEN @DAY = 16 THEN @MONEY ELSE AS_DAY16 END,
			@SUM17 =	AS_DAY17 =  CASE WHEN @DAY = 17 THEN @MONEY ELSE AS_DAY17 END,
			@SUM18 =	AS_DAY18 =  CASE WHEN @DAY = 18 THEN @MONEY ELSE AS_DAY18 END,
			@SUM19 =	AS_DAY19 =  CASE WHEN @DAY = 19 THEN @MONEY ELSE AS_DAY19 END,
			@SUM20 =	AS_DAY20 =  CASE WHEN @DAY = 20 THEN @MONEY ELSE AS_DAY20 END,
			@SUM21 =	AS_DAY21 =  CASE WHEN @DAY = 21 THEN @MONEY ELSE AS_DAY21 END,
			@SUM22 =	AS_DAY22 =  CASE WHEN @DAY = 22 THEN @MONEY ELSE AS_DAY22 END,
			@SUM23 =	AS_DAY23 =  CASE WHEN @DAY = 23 THEN @MONEY ELSE AS_DAY23 END,
			@SUM24 =	AS_DAY24 =  CASE WHEN @DAY = 24 THEN @MONEY ELSE AS_DAY24 END,
			@SUM25 =	AS_DAY25 =  CASE WHEN @DAY = 25 THEN @MONEY ELSE AS_DAY25 END,
			@SUM26 =	AS_DAY26 =  CASE WHEN @DAY = 26 THEN @MONEY ELSE AS_DAY26 END,
			@SUM27 =	AS_DAY27 =  CASE WHEN @DAY = 27 THEN @MONEY ELSE AS_DAY27 END,
			@SUM28 =	AS_DAY28 =  CASE WHEN @DAY = 28 THEN @MONEY ELSE AS_DAY28 END,
			@SUM29 =	AS_DAY29 =  CASE WHEN @DAY = 29 THEN @MONEY ELSE AS_DAY29 END,
			@SUM30 =	AS_DAY30 =  CASE WHEN @DAY = 30 THEN @MONEY ELSE AS_DAY30 END,
			@SUM31 =	AS_DAY31 =  CASE WHEN @DAY = 31 THEN @MONEY ELSE AS_DAY31 END
	WHERE	AS_SHOP = @SHOPCODE AND
			AS_DATE_YEAR = @YEAR AND
			AS_DATE_MONTH = @MONTH
			
	-- 일별 데이터 합계
	UPDATE	TBL_AP_SHOP_PMPINSIDE	
	SET		AS_DAY_SUM = ISNULL(@SUM1,0)+ISNULL(@SUM2,0)+ISNULL(@SUM3,0)+ISNULL(@SUM4,0)+ISNULL(@SUM5,0)+ISNULL(@SUM6,0)+ISNULL(@SUM7,0)+ISNULL(@SUM8,0)+ISNULL(@SUM9,0)+ISNULL(@SUM10,0)+ISNULL(@SUM11,0)+ISNULL(@SUM12,0)+ISNULL(@SUM13,0)+ISNULL(@SUM14,0)+ISNULL(@SUM15,0)+ISNULL(@SUM16,0)+ISNULL(@SUM17,0)+ISNULL(@SUM18,0)+ISNULL(@SUM19,0)+ISNULL(@SUM20,0)+ISNULL(@SUM21,0)+ISNULL(@SUM22,0)+ISNULL(@SUM23,0)+ISNULL(@SUM24,0)+ISNULL(@SUM25,0)+ISNULL(@SUM26,0)+ISNULL(@SUM27,0)+ISNULL(@SUM28,0)+ISNULL(@SUM29,0)+ISNULL(@SUM30,0)+ISNULL(@SUM31,0) 
	WHERE	AS_SHOP = @SHOPCODE AND
			AS_DATE_YEAR = @YEAR AND
			AS_DATE_MONTH = @MONTH
