/* *************************************************************************
 * NAME : dbo.UDP_MP_GOODS_ATTRIBUTE_COMPONENT
 * TYPE : PROCEDURE (SQL_STORED_PROCEDURE)
 * TIME : Create: 2016-04-05 20:19:19.53
 *        Modify: 2018-05-03 17:23:34.673
 *        Backup: 20180521_1737
 ************************************************************************* */


CREATE PROC [DBO].[UDP_MP_GOODS_ATTRIBUTE_COMPONENT]
	@MODELNO INT,
	@CATEGORY VARCHAR(12),
	@MM_ID VARCHAR(20)
AS
BEGIN
	SET @MM_ID = REPLACE(@MM_ID, '''', '''''')

	DECLARE @SZQRY VARCHAR(4000)
	SET @SZQRY = '
		SET NOCOUNT ON;
		SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
		
		DECLARE @ATTRIBUTE_CNT INT
		DECLARE @ATTRIBUTE INT

		SELECT *
		INTO #TEMP
		FROM OPENQUERY(ORADB, ''
			SELECT ' + CAST(@MODELNO AS VARCHAR(20)) + ' MODELNO, ATTRIBUTE_ID, ATTRIBUTE_ELEMENT_ID, SUM(NVL(CNT, 0)) CNT
			FROM TBL_COMPONENT_TITLE A
				LEFT JOIN (
					SELECT B.CPT_ID, COUNT(*) CNT
					FROM TBL_COMPONENT_MODELNO_ORIGINAL A
						INNER JOIN TBL_COMPONENT_MAPPING B ON A.CP_ID = B.CP_ID
					WHERE MODELNO = ' + CAST(@MODELNO AS VARCHAR(20)) + ' AND A.DEL_YN = ''''N'''' AND B.DEL_YN = ''''N''''
					GROUP BY B.CPT_ID
				) B ON A.CPT_ID = B.CPT_ID
			WHERE CA_CODE = ''''' + LEFT(@CATEGORY, 4) + ''''' AND ATTRIBUTE_ID IS NOT NULL AND ATTRIBUTE_ELEMENT_ID IS NOT NULL AND DEL_YN = ''''N''''
			GROUP BY ATTRIBUTE_ID, ATTRIBUTE_ELEMENT_ID'')
		
		SELECT @ATTRIBUTE_CNT = COUNT(DISTINCT ATTRIBUTE_ID)
		FROM #TEMP

		IF @ATTRIBUTE_CNT = 1
		BEGIN
			SET @ATTRIBUTE = (SELECT TOP 1 ATTRIBUTE_ID FROM #TEMP)
			
			INSERT INTO GOODS_CATALOG_ATTRIBUTE(G_MODELNO, ATTRIBUTE_ID, ATTRIBUTE_ELEMENT_ID, ATTRIBUTE_VALUE, INS_DATE, INS_OPRT, DEL_YN, UPD_DATE, UPD_OPRT)
			SELECT MODELNO, A.ATTRIBUTE_ID, A.ATTRIBUTE_ELEMENT_ID, A.CNT, GETDATE(), ''' + @MM_ID + ''', ''N'', GETDATE(), ''temp_batch''
			FROM #TEMP A
				LEFT JOIN GOODS_CATALOG_ATTRIBUTE B ON MODELNO = G_MODELNO AND A.ATTRIBUTE_ID = B.ATTRIBUTE_ID AND A.ATTRIBUTE_ELEMENT_ID = B.ATTRIBUTE_ELEMENT_ID
			WHERE G_MODELNO IS NULL

			UPDATE GOODS_CATALOG_ATTRIBUTE
			SET DEL_YN = ''N''
			  , ATTRIBUTE_VALUE = CNT
			  , INS_DATE = (CASE WHEN DEL_YN = ''Y'' THEN GETDATE() ELSE INS_DATE END)
			  , UPD_DATE = (CASE WHEN DEL_YN = ''Y'' OR ATTRIBUTE_VALUE <> CNT THEN GETDATE() ELSE UPD_DATE END)
			  , UPD_OPRT = ''temp_batch''
			FROM GOODS_CATALOG_ATTRIBUTE A
				INNER JOIN #TEMP B ON MODELNO = G_MODELNO AND A.ATTRIBUTE_ID = B.ATTRIBUTE_ID AND A.ATTRIBUTE_ELEMENT_ID = B.ATTRIBUTE_ELEMENT_ID

			UPDATE GOODS_CATALOG_ATTRIBUTE
			SET DEL_YN = (CASE WHEN UPD_OPRT = ''temp_batch'' THEN DEL_YN ELSE ''Y'' END)
			  , UPD_DATE = (CASE WHEN UPD_OPRT = ''temp_batch'' THEN UPD_DATE ELSE GETDATE() END)
			  , UPD_OPRT = ''' + @MM_ID + '''
			WHERE DEL_YN = ''N'' AND G_MODELNO IN (SELECT MODELNO FROM #TEMP) AND ATTRIBUTE_ID = @ATTRIBUTE
		END'

	EXEC (@SZQRY)
END
