/* *************************************************************************
 * NAME : dbo.UDP_NURIBOT_BOOK_MODELNO
 * TYPE : PROCEDURE (SQL_STORED_PROCEDURE)
 * TIME : Create: 2015-08-12 19:05:09.917
 *        Modify: 2017-07-12 12:58:56.37
 *        Backup: 20180521_1737
 ************************************************************************* */



CREATE PROCEDURE [dbo].[UDP_NURIBOT_BOOK_MODELNO]

AS
BEGIN
	SET NOCOUNT ON
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
		
		DECLARE @ChkCount int 
		DECLARE @MultiInt int
		DECLARE @MultiCnt int
		
		SET @ChkCount = 0
		SET @MultiInt = 0

		TRUNCATE TABLE NB02.DBO.PRICE_BOOK

		INSERT INTO NB02.DBO.PRICE_BOOK(PL_NO, PL_VCODE, PL_MODELNO, PL_GOODSNM, PL_PRICE, PL_SRVFLAG, PL_AVGPRICE)
		SELECT PL_NO, PL_VCODE, G_MODELNO, PL_GOODSNM, PL_PRICE, PL_SRVFLAG, 0
		FROM ELOC2001.DBO.PRICELIST WITH(READUNCOMMITTED)
		LEFT OUTER JOIN ELOC2001.DBO.GOODS_BOOK WITH(READUNCOMMITTED)
		ON REPLACE(REPLACE(REVERSE(LEFT(REVERSE(PL_GOODSNM), CHARINDEX('[',REVERSE(PL_GOODSNM)))),'[',''),']','') = ISBN
		WHERE PL_CATEGORY LIKE '93%' AND PL_MODELNO = 0 AND PL_GOODSNM LIKE '%]' AND PL_VCODE IN (47, 374, 6665) AND G_MODELNO IS NOT NULL
		
		UPDATE PRICELIST SET PL_MODELNO = NP.PL_MODELNO, PL_STATUS = '1'
		FROM PRICELIST P 
		INNER JOIN (SELECT PL_NO, PL_MODELNO 
					FROM NB02.DBO.PRICE_BOOK WITH(READUNCOMMITTED)) NP
		ON P.PL_NO = NP.PL_NO
		WHERE PL_VCODE IN (47, 374, 6665) AND P.PL_MODELNO = 0 AND PL_STATUS = '0'


				
		TRUNCATE TABLE NB02.DBO.PRICE_BOOK
		
		INSERT INTO NB02.DBO.PRICE_BOOK(PL_NO, PL_VCODE, PL_MODELNO, PL_GOODSNM, PL_PRICE, PL_SRVFLAG, PL_AVGPRICE)
		SELECT PL_NO, PL_VCODE, PL_MODELNO
		, REPLACE(REPLACE((CASE 
			WHEN PL_VCODE = 55 THEN REPLACE(REPLACE(PL_GOODSNM, ' ' ,''), '('+PL_GOODSFACTORY+')','')  
			WHEN PL_VCODE IN (974,6588) AND (CHARINDEX('(',PL_GOODSNM) > CHARINDEX(')',PL_GOODSNM) OR CHARINDEX('(',PL_GOODSNM) = 0) THEN REPLACE(PL_GOODSNM, LEFT(PL_GOODSNM, CHARINDEX(')', PL_GOODSNM)),'')
			WHEN PL_VCODE = 6361 THEN REPLACE(REPLACE(REPLACE(PL_GOODSNM, LEFT(PL_GOODSNM, CHARINDEX('_',PL_GOODSNM)),''), LEFT(REPLACE(PL_GOODSNM, LEFT(PL_GOODSNM, CHARINDEX('_',PL_GOODSNM)),''), CHARINDEX('-',REPLACE(PL_GOODSNM, LEFT(PL_GOODSNM, CHARINDEX('_',PL_GOODSNM)),''))),''), REVERSE(LEFT(REVERSE(REPLACE(REPLACE(PL_GOODSNM, LEFT(PL_GOODSNM, CHARINDEX('_',PL_GOODSNM)),''), LEFT(REPLACE(PL_GOODSNM, LEFT(PL_GOODSNM, CHARINDEX('_',PL_GOODSNM)),''), CHARINDEX('-',REPLACE(PL_GOODSNM, LEFT(PL_GOODSNM, CHARINDEX('_',PL_GOODSNM)),''))),'')), CHARINDEX('(',REVERSE(REPLACE(REPLACE(PL_GOODSNM, LEFT(PL_GOODSNM, CHARINDEX('_',PL_GOODSNM)),''), LEFT(REPLACE(PL_GOODSNM, LEFT(PL_GOODSNM, CHARINDEX('_',PL_GOODSNM)),''), CHARINDEX('-',REPLACE(PL_GOODSNM, LEFT(PL_GOODSNM, CHARINDEX('_',PL_GOODSNM)),''))),''))))),'')
			WHEN PL_VCODE = 6508 AND CHARINDEX('_',PL_GOODSNM) > 0 THEN LEFT(PL_GOODSNM, CHARINDEX('_',PL_GOODSNM)-1)
			ELSE REPLACE(REPLACE(PL_GOODSNM, ' ' ,''),REPLACE(PL_GOODSFACTORY, ' ' ,''),'') 
		END),' ',''),'	','') AS PL_GOODSNM
		, PL_PRICE, PL_SRVFLAG, 0
		FROM ELOC2001.DBO.PRICELIST WITH(READUNCOMMITTED)
		WHERE PL_CATEGORY LIKE '93%' OR (PL_VCODE = 5910 AND PL_CATEGORY LIKE '1011%')
		
		--괄호제거[]
		WHILE @MultiInt < 10
			BEGIN
				UPDATE PRICE_BOOK SET PL_GOODSNM = REPLACE(PL_GOODSNM, SUBSTRING(PL_GOODSNM, CHARINDEX('[', PL_GOODSNM),CHARINDEX(']',RIGHT(PL_GOODSNM, LEN(PL_GOODSNM) - CHARINDEX('[', PL_GOODSNM)+1))), '')
				--SELECT PL_NO, PL_GOODSNM,  REPLACE(PL_GOODSNM, SUBSTRING(PL_GOODSNM, CHARINDEX('[', PL_GOODSNM),CHARINDEX(']',RIGHT(PL_GOODSNM, LEN(PL_GOODSNM) - CHARINDEX('[', PL_GOODSNM)+1))), '')
				--SELECT COUNT(*)
				FROM NB02.DBO.PRICE_BOOK WITH(READUNCOMMITTED)
				WHERE PL_GOODSNM LIKE '%]%' AND CHARINDEX('[',PL_GOODSNM) > 0

				SET @MultiInt = @MultiInt + 1
			END

		--삭제 키워드(무료배송, 총알배송 ,OK캐쉬백/롯데포인트 적립, 좋은서점, 반디앤루니스, 텐바이텐, 인터파크1, 인터파크2)
		UPDATE NB02.DBO.PRICE_BOOK SET PL_GOODSNM = REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(PL_GOODSNM, '무료배송' ,''), '총알배송' ,''), 'OK캐쉬백/롯데포인트적립' ,''), '좋은서점' ,''), '반디앤루니스' ,''), '텐바이텐' ,''), '인터파크1' ,''), '인터파크2' ,'')
		
		DELETE NB02.DBO.PRICE_BOOK WHERE PL_GOODSNM = ''
		
		
		DECLARE @O TABLE
		(
			IDX INT IDENTITY(1,1) PRIMARY KEY,
			PLNO BIGINT,
			VCODE INT,
			MODELNO INT,
			CATE varchar(8),
			PRICE money
		)

		INSERT INTO @O(PLNO, MODELNO, VCODE, CATE, PRICE)
		SELECT A.PL_NO, B.PL_MODELNO, MAX(A.PL_VCODE), MAX(G_CATEGORY), MAX(A.PL_PRICE)
		FROM 
		(SELECT PL_NO, PL_VCODE, PL_GOODSNM, PL_PRICE
		FROM NB02.DBO.PRICE_BOOK WITH(READUNCOMMITTED)
		WHERE PL_MODELNO < 1 AND PL_SRVFLAG <> 'B') A
		LEFT JOIN 
		(SELECT PL_MODELNO, PL_GOODSNM, PL_PRICE
		FROM NB02.DBO.PRICE_BOOK WITH(READUNCOMMITTED)
		WHERE PL_MODELNO > 0 ) B
		ON A.PL_GOODSNM = B.PL_GOODSNM 
		INNER JOIN GOODS WITH(READUNCOMMITTED)
		ON B.PL_MODELNO = G_MODELNO
		WHERE B.PL_MODELNO > 0 AND (A.PL_PRICE = B.PL_PRICE OR (A.PL_PRICE >= G_MINPRICE3*0.95 AND A.PL_PRICE <= G_MINPRICE3*1.05))
		GROUP BY A.PL_NO, B.PL_MODELNO 
		OPTION (MAXDOP 1)
		
		Set @MultiCnt = @@rowcount	
				
		DECLARE @VCODE int
		DECLARE @MODELNO int
		DECLARE @NO BIGINT
		DECLARE @CATE varchar(8)
		DECLARE @PRICE money

		WHILE @MultiCnt <> 0
			Begin
				select @NO = PLNO, @VCODE = VCODE, @MODELNO = MODELNO, @CATE = CATE, @PRICE= PRICE  from @O where IDX = @MultiCnt
				
				UPDATE PRICELIST SET PL_MODELNO = @MODELNO, PL_CATEGORY = @CATE, PL_STATUS = (CASE PL_STATUS WHEN '0' THEN '1' ELSE PL_STATUS END)
				WHERE PL_NO = @NO AND PL_MODELNO < 1

				INSERT INTO LOGDB.DBO.JOB_PRICELIST (JP_PLISTNO, JP_MODELNO, JP_VCODE, JP_ID, JP_FLAG, JP_GOODSNM, JP_PRICE, JP_CATEGORY)
				VALUES (@NO, @MODELNO, @VCODE, 'NURIBOT_BOOK', '0', '', @PRICE, @CATE)
				
				SET @MultiCnt = @MultiCnt-1
				SET @ChkCount = @ChkCount+1
			End		
		--return @ChkCount
END





