/* *************************************************************************
 * NAME : dbo.USP_PRICELIST_UP_10
 * TYPE : PROCEDURE (SQL_STORED_PROCEDURE)
 * TIME : Create: 2007-03-26 18:03:38.42
 *        Modify: 2018-05-03 17:23:35.98
 *        Backup: 20180521_1737
 ************************************************************************* */

CREATE PROC [dbo].[USP_PRICELIST_UP_10]
	@PL_VCODE INT,
	@PL_GOODSCODE VARCHAR(50)
AS
BEGIN
	SET NOCOUNT ON
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
	UPDATE PRICELIST
	SET PL_STATUS = '3',
		PL_DATE = GETDATE()
	WHERE PL_VCODE = @PL_VCODE
		AND PL_GOODSCODE = @PL_GOODSCODE
		AND PL_GOODSCODE_CS = CHECKSUM(@PL_GOODSCODE)
END
