/* *************************************************************************
 * NAME : dbo.UDP_GOODS_EXTERNAL_CATEGORY
 * TYPE : PROCEDURE (SQL_STORED_PROCEDURE)
 * TIME : Create: 2017-02-17 10:46:58.343
 *        Modify: 2018-05-03 17:23:34.073
 *        Backup: 20180521_1737
 ************************************************************************* */


CREATE PROC [DBO].[UDP_GOODS_EXTERNAL_CATEGORY]
AS
BEGIN
	SET NOCOUNT ON;
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
	
	SELECT CL_LCODE CA_CODE, CL_NAME C_NAME, CL_SEQNO C_SEQNO
	INTO #TARGET_LCATEGORY
	FROM C_LCATE
	WHERE CL_LCODE IN ('02', '03', '04', '05', '06', '07', '08', '09', '10', '12', '14', '15', '16', '18', '21', '22', '24', '93', '95')
      AND CL_SEQNO > 0 AND LTRIM(RTRIM(ISNULL(CL_NAME, ''))) <> ''
      AND CHARINDEX('temp', CL_NAME) = 0 AND CHARINDEX('blank', CL_NAME) = 0 AND CHARINDEX('≮包府侩', CL_NAME) = 0
	
	SELECT CM_LCODE + CM_MCODE CA_CODE, CM_NAME C_NAME, CM_SEQNO C_SEQNO
	INTO #TARGET_MCATEGORY
	FROM C_MCATE
	WHERE CM_LCODE IN (SELECT DISTINCT CA_CODE FROM #TARGET_LCATEGORY)
      AND CM_SEQNO > 0 AND LTRIM(RTRIM(ISNULL(CM_NAME, ''))) <> ''
      AND CHARINDEX('temp', CM_NAME) = 0 AND CHARINDEX('blank', CM_NAME) = 0 AND CHARINDEX('≮包府侩', CM_NAME) = 0
	
	SELECT CS_LCODE + CS_MCODE + CS_SCODE CA_CODE, CS_NAME C_NAME, CS_SEQNO C_SEQNO
	INTO #TARGET_SCATEGORY
	FROM C_SCATE
	WHERE CS_LCODE + CS_MCODE IN (SELECT DISTINCT CA_CODE FROM #TARGET_MCATEGORY)
      AND CS_SEQNO > 0 AND LTRIM(RTRIM(ISNULL(CS_NAME, ''))) <> ''
      AND CHARINDEX('temp', CS_NAME) = 0 AND CHARINDEX('blank', CS_NAME) = 0 AND CHARINDEX('≮包府侩', CS_NAME) = 0
	
	SELECT CD_LCODE + CD_MCODE + CD_SCODE + CD_DCODE CA_CODE, CD_NAME C_NAME, CD_SEQNO C_SEQNO
	INTO #TARGET_DCATEGORY
	FROM C_DCATE
	WHERE CD_LCODE + CD_MCODE + CD_SCODE IN (SELECT DISTINCT CA_CODE FROM #TARGET_SCATEGORY)
      AND CD_SEQNO > 0 AND LTRIM(RTRIM(ISNULL(CD_NAME, ''))) <> ''
      AND CHARINDEX('temp', CD_NAME) = 0 AND CHARINDEX('blank', CD_NAME) = 0 AND CHARINDEX('≮包府侩', CD_NAME) = 0
	
	SELECT CA_CODE, C_NAME, C_SEQNO
	FROM (
		SELECT CA_CODE, C_NAME, C_SEQNO FROM #TARGET_LCATEGORY UNION ALL
		SELECT CA_CODE, C_NAME, C_SEQNO FROM #TARGET_MCATEGORY UNION ALL
		SELECT CA_CODE, C_NAME, C_SEQNO FROM #TARGET_SCATEGORY UNION ALL
		SELECT CA_CODE, C_NAME, C_SEQNO FROM #TARGET_DCATEGORY
	) A
	ORDER BY CA_CODE
END
