/* *************************************************************************
 * NAME : dbo.UDF_RTN_MODELNM
 * TYPE : FUNCTION (SQL_SCALAR_FUNCTION)
 * TIME : Create: 2016-01-06 12:55:01.357
 *        Modify: 2018-05-03 17:23:35.557
 *        Backup: 20180521_1737
 ************************************************************************* */


CREATE FUNCTION [dbo].[UDF_RTN_MODELNM] (@MODELNM VARCHAR(500))
RETURNS VARCHAR(8000)
AS
BEGIN
	DECLARE @RETURN VARCHAR(8000)
	DECLARE @STR VARCHAR(100)
	DECLARE @I INT
	DECLARE @J INT

	SET @MODELNM = LTRIM(RTRIM(CASE WHEN CHARINDEX('@', @MODELNM) > 0 THEN SUBSTRING(@MODELNM, 1, CHARINDEX('@', @MODELNM) - 1) ELSE @MODELNM END))
	SET @RETURN  = @MODELNM
	SET @MODELNM = ''
	SET @I = 1
	WHILE LEN(@RETURN) >= @I
	BEGIN
		SET @MODELNM = @MODELNM + 
		               CASE WHEN CHARINDEX(SUBSTRING(@RETURN, @I, 1), '¤¡¤¢¤¤¤§¤¨¤©¤±¤²¤³¤µ¤¶¤·¤¸¤¹¤º¤»¤¼¤½¤¾') > 0 OR 
					             UNICODE(SUBSTRING(@RETURN, @I, 1)) >= UNICODE('°¡') AND UNICODE(SUBSTRING(@RETURN, @I, 1)) <= UNICODE('ÆR')
							THEN ''
							ELSE SUBSTRING(@RETURN, @I, 1) END

		SET @I = @I + 1
	END
	SET @MODELNM = LTRIM(RTRIM(@MODELNM))
	SET @RETURN  = ''

	SET @MODELNM = REPLACE(@MODELNM, '[]', '')
	SET @MODELNM = REPLACE(@MODELNM, '_', ' ')
	SET @MODELNM = REPLACE(@MODELNM, '<', ' ')
	SET @MODELNM = REPLACE(@MODELNM, '>', ' ')
	SET @MODELNM = REPLACE(@MODELNM, '[', ' ')
	SET @MODELNM = REPLACE(@MODELNM, ']', ' ')
	SET @MODELNM = REPLACE(@MODELNM, '/', ' ')
	SET @MODELNM = REPLACE(@MODELNM, '(', ' ')
	SET @MODELNM = REPLACE(@MODELNM, ')', ' ')
	SET @MODELNM = REPLACE(@MODELNM, '-', ' ')
	SET @MODELNM = REPLACE(@MODELNM, ',', ' ')

	WHILE LEN(@MODELNM) > 0
	BEGIN
		SET @STR	  = LTRIM(RTRIM((CASE WHEN CHARINDEX(' ', @MODELNM) > 0 THEN SUBSTRING(@MODELNM, 1, CHARINDEX(' ', @MODELNM) - 1) ELSE @MODELNM END)))
		SET @MODELNM  = LTRIM(RTRIM((CASE WHEN CHARINDEX(' ', @MODELNM) > 0 THEN SUBSTRING(@MODELNM, CHARINDEX(' ', @MODELNM) + 1, 8000) ELSE '' END)))

		IF @STR <> '' And LEN(@STR) > 1
		BEGIN
			SET @I = 1
			WHILE LEN(@STR) >= @I
			BEGIN
				SET @J = 1
				WHILE LEN(@STR) >= @I + @J - 1
				BEGIN
					SET @RETURN = @RETURN + SUBSTRING(@STR, @I, @J) + ' '

					SET @J = @J + 1
				END

				SET @I = @I + 1
			END
		END
	END

	RETURN LTRIM(RTRIM(@RETURN))
END