/* *************************************************************************
 * NAME : dbo.UDP_MP_BRAND_NM_CHANGE
 * TYPE : PROCEDURE (SQL_STORED_PROCEDURE)
 * TIME : Create: 2016-04-05 20:21:45.27
 *        Modify: 2018-05-03 17:23:34.853
 *        Backup: 20180521_1737
 ************************************************************************* */


CREATE PROC [DBO].[UDP_MP_BRAND_NM_CHANGE]
	@BRAND_ID INT,
	@BRAND_NM VARCHAR(200),
	@MM_ID VARCHAR(20)
AS
BEGIN
	SET NOCOUNT ON;
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
	
	UPDATE TBL_ENURI_BRAND
	SET BRAND_NM		= @BRAND_NM,
		UPD_DATE		= GETDATE(),
		UPD_OPRT		= @MM_ID
	WHERE BRAND_ID		= @BRAND_ID

	UPDATE GOODS
	SET G_FLAG		= '1',
		G_BRAND		= (SELECT BRAND_NM FROM TBL_ENURI_BRAND WHERE BRAND_ID = @BRAND_ID)
	WHERE BRAND_ID	= @BRAND_ID

	INSERT INTO LOGDB.DBO.JOB_GOODS(JG_MODELNO, JG_ID, JG_FLAG, JG_DATE, JG_CATEGORY)
	SELECT G_MODELNO, @MM_ID, '3', GETDATE(), G_CATEGORY
	FROM GOODS
	WHERE BRAND_ID	= @BRAND_ID
END
