/* *************************************************************************
 * NAME : dbo.UDP_JCA_AP_REPORT_SALES_SEL_WEEKLY
 * TYPE : PROCEDURE (SQL_STORED_PROCEDURE)
 * TIME : Create: 2010-03-10 15:04:01.733
 *        Modify: 2018-05-03 17:23:34.197
 *        Backup: 20180521_1737
 ************************************************************************* */

CREATE PROC UDP_JCA_AP_REPORT_SALES_SEL_WEEKLY
	@YYYY	VARCHAR(4)
,	@SHOP_GROUP CHAR(1) = NULL
,	@device char(1) = null
AS
	SET NOCOUNT ON
	SET TRANSACTION ISOLATION LEVEL  READ UNCOMMITTED
	-- ----------------------------------------------------------------------------------
	-- 累己磊 : WOOKKI25 / 2010.03.10
	-- 汲  疙 : AP 诀眉 林喊 概免咀
	-- ----------------------------------------------------------------------------------
	-- 荐沥郴开
	-- ----------------------------------------------------------------------------------
	/*
	荐沥老:			荐沥磊:			荐沥郴侩:
	----------		-----------		-----------------------------------------------------		
	*/
	DECLARE @SDATE SMALLDATETIME, @EDATE SMALLDATETIME
	SET @SDATE = CAST(@YYYY+'-01-01' AS SMALLDATETIME)
	SET @EDATE = CAST(@YYYY+'-12-31' AS SMALLDATETIME)



	SELECT SHOP_NAME
		,[1林] ,[2林] ,[3林] ,[4林] ,[5林] ,[6林] ,[7林] ,[8林] ,[9林] ,[10林]
		,[11林],[12林],[13林],[14林],[15林],[16林],[17林],[18林],[19林],[20林]
		,[21林],[22林],[23林],[24林],[25林],[26林],[27林],[28林],[29林],[30林]
		,[31林],[32林],[33林],[34林],[35林],[36林],[37林],[38林],[39林],[40林]
		,[41林],[42林],[43林],[44林],[45林],[46林],[47林],[48林],[49林],[50林]
		,[51林],[52林],[53林],SALES_SUM
	FROM
	(
		SELECT	SHOP_VCODE
		,		[1林] = SUM(CASE WHEN DATEPART(WW, SALES_DATE) = 1 THEN SALES_SUM END) 
		,		[2林] = SUM(CASE WHEN DATEPART(WW, SALES_DATE) = 2 THEN SALES_SUM END)
		,		[3林] = SUM(CASE WHEN DATEPART(WW, SALES_DATE) = 3 THEN SALES_SUM END)
		,		[4林] = SUM(CASE WHEN DATEPART(WW, SALES_DATE) = 4 THEN SALES_SUM END)
		,		[5林] = SUM(CASE WHEN DATEPART(WW, SALES_DATE) = 5 THEN SALES_SUM END)
		,		[6林] = SUM(CASE WHEN DATEPART(WW, SALES_DATE) = 6 THEN SALES_SUM END)
		,		[7林] = SUM(CASE WHEN DATEPART(WW, SALES_DATE) = 7 THEN SALES_SUM END)
		,		[8林] = SUM(CASE WHEN DATEPART(WW, SALES_DATE) = 8 THEN SALES_SUM END)
		,		[9林] = SUM(CASE WHEN DATEPART(WW, SALES_DATE) = 9 THEN SALES_SUM END)
		,		[10林] = SUM(CASE WHEN DATEPART(WW, SALES_DATE) = 10 THEN SALES_SUM END)
		,		[11林] = SUM(CASE WHEN DATEPART(WW, SALES_DATE) = 11 THEN SALES_SUM END)
		,		[12林] = SUM(CASE WHEN DATEPART(WW, SALES_DATE) = 12 THEN SALES_SUM END)
		,		[13林] = SUM(CASE WHEN DATEPART(WW, SALES_DATE) = 13 THEN SALES_SUM END)
		,		[14林] = SUM(CASE WHEN DATEPART(WW, SALES_DATE) = 14 THEN SALES_SUM END)
		,		[15林] = SUM(CASE WHEN DATEPART(WW, SALES_DATE) = 15 THEN SALES_SUM END)
		,		[16林] = SUM(CASE WHEN DATEPART(WW, SALES_DATE) = 16 THEN SALES_SUM END)
		,		[17林] = SUM(CASE WHEN DATEPART(WW, SALES_DATE) = 17 THEN SALES_SUM END)
		,		[18林] = SUM(CASE WHEN DATEPART(WW, SALES_DATE) = 18 THEN SALES_SUM END)
		,		[19林] = SUM(CASE WHEN DATEPART(WW, SALES_DATE) = 19 THEN SALES_SUM END)
		,		[20林] = SUM(CASE WHEN DATEPART(WW, SALES_DATE) = 20 THEN SALES_SUM END)
		,		[21林] = SUM(CASE WHEN DATEPART(WW, SALES_DATE) = 21 THEN SALES_SUM END)
		,		[22林] = SUM(CASE WHEN DATEPART(WW, SALES_DATE) = 22 THEN SALES_SUM END)
		,		[23林] = SUM(CASE WHEN DATEPART(WW, SALES_DATE) = 23 THEN SALES_SUM END)
		,		[24林] = SUM(CASE WHEN DATEPART(WW, SALES_DATE) = 24 THEN SALES_SUM END)
		,		[25林] = SUM(CASE WHEN DATEPART(WW, SALES_DATE) = 25 THEN SALES_SUM END)
		,		[26林] = SUM(CASE WHEN DATEPART(WW, SALES_DATE) = 26 THEN SALES_SUM END)
		,		[27林] = SUM(CASE WHEN DATEPART(WW, SALES_DATE) = 27 THEN SALES_SUM END)
		,		[28林] = SUM(CASE WHEN DATEPART(WW, SALES_DATE) = 28 THEN SALES_SUM END)
		,		[29林] = SUM(CASE WHEN DATEPART(WW, SALES_DATE) = 29 THEN SALES_SUM END)
		,		[30林] = SUM(CASE WHEN DATEPART(WW, SALES_DATE) = 30 THEN SALES_SUM END)
		,		[31林] = SUM(CASE WHEN DATEPART(WW, SALES_DATE) = 31 THEN SALES_SUM END)
		,		[32林] = SUM(CASE WHEN DATEPART(WW, SALES_DATE) = 32 THEN SALES_SUM END)
		,		[33林] = SUM(CASE WHEN DATEPART(WW, SALES_DATE) = 33 THEN SALES_SUM END)
		,		[34林] = SUM(CASE WHEN DATEPART(WW, SALES_DATE) = 34 THEN SALES_SUM END)
		,		[35林] = SUM(CASE WHEN DATEPART(WW, SALES_DATE) = 35 THEN SALES_SUM END)
		,		[36林] = SUM(CASE WHEN DATEPART(WW, SALES_DATE) = 36 THEN SALES_SUM END)
		,		[37林] = SUM(CASE WHEN DATEPART(WW, SALES_DATE) = 37 THEN SALES_SUM END)
		,		[38林] = SUM(CASE WHEN DATEPART(WW, SALES_DATE) = 38 THEN SALES_SUM END)
		,		[39林] = SUM(CASE WHEN DATEPART(WW, SALES_DATE) = 39 THEN SALES_SUM END)
		,		[40林] = SUM(CASE WHEN DATEPART(WW, SALES_DATE) = 40 THEN SALES_SUM END)
		,		[41林] = SUM(CASE WHEN DATEPART(WW, SALES_DATE) = 41 THEN SALES_SUM END)
		,		[42林] = SUM(CASE WHEN DATEPART(WW, SALES_DATE) = 42 THEN SALES_SUM END)
		,		[43林] = SUM(CASE WHEN DATEPART(WW, SALES_DATE) = 43 THEN SALES_SUM END)
		,		[44林] = SUM(CASE WHEN DATEPART(WW, SALES_DATE) = 44 THEN SALES_SUM END)
		,		[45林] = SUM(CASE WHEN DATEPART(WW, SALES_DATE) = 45 THEN SALES_SUM END)
		,		[46林] = SUM(CASE WHEN DATEPART(WW, SALES_DATE) = 46 THEN SALES_SUM END)
		,		[47林] = SUM(CASE WHEN DATEPART(WW, SALES_DATE) = 47 THEN SALES_SUM END)
		,		[48林] = SUM(CASE WHEN DATEPART(WW, SALES_DATE) = 48 THEN SALES_SUM END)
		,		[49林] = SUM(CASE WHEN DATEPART(WW, SALES_DATE) = 49 THEN SALES_SUM END)
		,		[50林] = SUM(CASE WHEN DATEPART(WW, SALES_DATE) = 50 THEN SALES_SUM END)
		,		[51林] = SUM(CASE WHEN DATEPART(WW, SALES_DATE) = 51 THEN SALES_SUM END)
		,		[52林] = SUM(CASE WHEN DATEPART(WW, SALES_DATE) = 52 THEN SALES_SUM END)
		,		[53林] = SUM(CASE WHEN DATEPART(WW, SALES_DATE) = 53 THEN SALES_SUM END)
		,		[SALES_SUM] = SUM(SALES_SUM)
		FROM TBL_AP_SHOP_SALES
		WHERE SALES_DATE BETWEEN @SDATE AND case when cast(@yyyy as int)=year(getdate()) then cast(convert(varchar(10), getdate() - datepart(dw, getdate()), 120) as datetime) else @EDATE end 
		AND	SHOP_GROUP = @SHOP_GROUP
		and device = isnull(@device, device)
		GROUP BY SHOP_VCODE
	) A INNER JOIN SHOPLIST B ON A.SHOP_VCODE = B.SHOP_VCODE
	ORDER BY CASE WHEN @SHOP_GROUP = 'B' THEN CAST(100000000 - SALES_SUM AS INT) ELSE ROW_NUMBER() OVER(ORDER BY B.SHOP_NAME asc) END

