/* *************************************************************************
 * NAME : dbo.UDF_RTN_DUPCHECK_MODELNOS
 * TYPE : FUNCTION (SQL_SCALAR_FUNCTION)
 * TIME : Create: 2016-05-04 10:41:40.74
 *        Modify: 2018-05-03 17:23:34.633
 *        Backup: 20180521_1737
 ************************************************************************* */


CREATE FUNCTION [DBO].[UDF_RTN_DUPCHECK_MODELNOS] (@CA_CODE VARCHAR(12), @JTYPE AS CHAR(1), @INDEXER AS VARCHAR(800), @MODELNO INT)
RETURNS VARCHAR(1000)
AS
BEGIN
	DECLARE @RETURN VARCHAR(1000)
	DECLARE @TEMP_MODELNO INT

	DECLARE FETCH_CURSOR CURSOR FOR
	SELECT MODELNO
	FROM TBL_DUPCHECK_MODEL
		INNER JOIN GOODS ON MODELNO = G_MODELNO
	WHERE CA_CODE = @CA_CODE AND JTYPE = @JTYPE AND JOB_FLAG = '0' AND INDEXER = @INDEXER AND G_MODELNM <> '¸ðµ¨»èÁ¦' AND MODELNO <> @MODELNO
	ORDER BY MODELNO

	SET @RETURN = ''

	OPEN FETCH_CURSOR

	FETCH NEXT FROM FETCH_CURSOR INTO @TEMP_MODELNO
	WHILE (@@FETCH_STATUS = 0)
	BEGIN
		SET @RETURN = @RETURN + CASE WHEN @RETURN <> '' THEN ',' ELSE '' END + CAST(@TEMP_MODELNO AS VARCHAR(20))

		FETCH NEXT FROM FETCH_CURSOR INTO @TEMP_MODELNO
	END
	
	CLOSE FETCH_CURSOR
	
	DEALLOCATE FETCH_CURSOR

	RETURN @RETURN
END
