/* *************************************************************************
 * NAME : dbo.UDP_MP_GOODS_CATALOG_ATTRIBUTE_SPEC_MAKE
 * TYPE : PROCEDURE (SQL_STORED_PROCEDURE)
 * TIME : Create: 2016-10-24 15:24:15.7
 *        Modify: 2018-05-03 17:23:35.897
 *        Backup: 20180521_1737
 ************************************************************************* */


CREATE PROC [DBO].[UDP_MP_GOODS_CATALOG_ATTRIBUTE_SPEC_MAKE]
	@MODELNO INT,
	@CATEGORY VARCHAR(100),
	@MOBILEFLAG VARCHAR(1),
	@PRINTFLAG VARCHAR(1),
	@SZLPTAG1 VARCHAR(8000) OUTPUT,
	@SZLPTAG2 VARCHAR(8000) OUTPUT,
	@SZVIPTAG VARCHAR(8000) OUTPUT
AS
BEGIN
	SET NOCOUNT ON;
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
	
	DECLARE @QRY NVARCHAR(1000)
    DECLARE @TEMP_SPEC AS VARCHAR(8000)
    DECLARE @TEMP_SPECTITLE AS VARCHAR(8000)
    DECLARE @TEMP_ATTRIBUTE_ID AS INT
    DECLARE @GROUP_MAIN_SPEC AS VARCHAR(8000)
    DECLARE @GROUP_SPEC AS VARCHAR(8000)
	DECLARE @REMOVE_SPECTITLE AS VARCHAR(8000)
	DECLARE @REMOVE_GROUP_MAIN_SPEC AS VARCHAR(8000)
    DECLARE @REMOVE_GROUP_SPEC AS VARCHAR(8000)
    DECLARE @GROUP_ID AS INT
    DECLARE @GROUP_CHAR AS VARCHAR(10)
	DECLARE @ELEMENT_CHAR AS VARCHAR(10)
    DECLARE @SPEC_DESCRIPTION AS VARCHAR(8000)
    DECLARE @I AS INT
    DECLARE @SPEC AS VARCHAR(8000)
	
	DECLARE @ATTRIBUTE_ID INT
	DECLARE @GALLERY_ATTRIBUTE_NM VARCHAR(40)
	DECLARE @USE_CLASS_CODE CHAR(1)
	DECLARE @GROUP_ATTRIBUTE_ID INT
	DECLARE @CHAR VARCHAR(3)
	DECLARE @ELE_CHAR VARCHAR(3)
	DECLARE @IS_GALLERY_DISPLAY BIT
	DECLARE @ATTRIBUTE_ELEMENT_ID SMALLINT
	DECLARE @ATTRIBUTE_ELEMENT VARCHAR(100)
	DECLARE @ATTRIBUTE_VALUE VARCHAR(500)
	DECLARE @IS_DISPLAY BIT
	DECLARE @ATTRIBUTE_BOLD BIT
	DECLARE @ELEMENT_BOLD BIT
	DECLARE @SPECNO INT
	
	CREATE TABLE #TARGET_ATTRIBUTE(
		SEQNO INT IDENTITY(1, 1),
		ATTRIBUTE_ID INT,
		GALLERY_ATTRIBUTE_NM VARCHAR(40),
		USE_CLASS_CODE CHAR(1),
		GROUP_ATTRIBUTE_ID INT,
		GROUP_CHAR VARCHAR(3),
		ELEMENT_CHAR VARCHAR(3),
		IS_GALLERY_DISPLAY BIT,
		ATTRIBUTE_ELEMENT_ID SMALLINT,
		ATTRIBUTE_ELEMENT VARCHAR(100),
		ATTRIBUTE_VALUE VARCHAR(500),
		IS_DISPLAY BIT,
		ATTRIBUTE_BOLD BIT,
		ELEMENT_BOLD BIT,
		SPECNO INT
	)
	
    SET @SPEC = ''
    IF CHARINDEX('_', @CATEGORY) = 0
	BEGIN
		SELECT @CATEGORY = G_CATEGORY, @SPEC_DESCRIPTION = ISNULL(G_SPEC_DESCRIPTION, '')
		FROM GOODS
		WHERE G_MODELNO = @MODELNO;
		
		IF @MOBILEFLAG = 'Y'
		BEGIN
			DECLARE @TOP_CNT INT
			SET @TOP_CNT = 10
			SET @QRY = N'SELECT @I = CASE WHEN ISNULL(ATT_CNT, 10) = 0 THEN 10 ELSE ISNULL(ATT_CNT, 10) END FROM OPENQUERY(ORADB, ''SELECT CA_CODE, SPEC_CNT, ATT_CNT, KEYWORD_CNT FROM TBL_CATE_DISPLAY WHERE CA_CODE = ''''' + CAST(LEFT(@CATEGORY, 4) AS NVARCHAR(12)) + ''''''')'
			
			EXECUTE SP_EXECUTESQL @QRY, N'@I INT OUTPUT', @I = @TOP_CNT OUTPUT
			
			DECLARE @BATCH_FLAG INT
			SELECT @BATCH_FLAG = COUNT(*)
			FROM GOODS_AUTO_APPLY_CATE WITH (READUNCOMMITTED)
			WHERE CATEGORY = LEFT(@CATEGORY, 4) AND FLAG = '0'
			
			IF @BATCH_FLAG > 0
			BEGIN
				SELECT @MODELNO MODELNO
					 , DENSE_RANK() OVER(ORDER BY D.TAG_ORDER
												, CASE WHEN ISNULL(GROUP_ATTRIBUTE_ID, 0) = B.ATTRIBUTE_ID THEN '0' ELSE '1' END
												, GALLERY_ATTRIBUTE_NM
												, C.DISPLAY_ORDER
												, CASE WHEN USE_CLASS_CODE <> '2' THEN ATTRIBUTE_ELEMENT ELSE ATTRIBUTE_VALUE END) SORTNO
					 , LTRIM(RTRIM(ISNULL(CASE WHEN CHARINDEX('_', MANAGE_ATTRIBUTE_NM) > 0 THEN SUBSTRING(MANAGE_ATTRIBUTE_NM, 1, CHARINDEX('_', MANAGE_ATTRIBUTE_NM) - 1) ELSE '' END, ''))) GROUPNM
					 , LTRIM(RTRIM(ISNULL(GALLERY_ATTRIBUTE_NM, ''))) TITLE
					 , LTRIM(RTRIM(ISNULL(CASE WHEN USE_CLASS_CODE <> '2' THEN ATTRIBUTE_ELEMENT ELSE ATTRIBUTE_VALUE END, ''))) CONTENT
					 , B.ATTRIBUTE_ID
					 , GALLERY_ATTRIBUTE_NM
					 , USE_CLASS_CODE
					 , GROUP_ATTRIBUTE_ID
					 , GROUP_CHAR
					 , ELEMENT_CHAR
					 , IS_GALLERY_DISPLAY
					 , C.ATTRIBUTE_ELEMENT_ID
					 , ATTRIBUTE_ELEMENT
					 , ATTRIBUTE_VALUE
					 , IS_DISPLAY
					 , B.IS_BOLD ATTRIBUTE_BOLD
					 , C.IS_BOLD ELEMENT_BOLD
					 , C.SPECNO
				INTO #SPEC_DETAIL_TEMP
				FROM GOODS_CATALOG_ATTRIBUTE A
					INNER JOIN GOODS_ATTRIBUTE B ON A.ATTRIBUTE_ID = B.ATTRIBUTE_ID
					INNER JOIN GOODS_ATTRIBUTE_ELEMENT C ON A.ATTRIBUTE_ID = C.ATTRIBUTE_ID AND A.ATTRIBUTE_ELEMENT_ID = C.ATTRIBUTE_ELEMENT_ID
					INNER JOIN GOODS_CATEGORY_ATTRIBUTE D ON A.ATTRIBUTE_ID = D.ATTRIBUTE_ID AND D.CATEGORY IN (SELECT TOP 1 CATEGORY FROM GOODS_CATEGORY_ATTRIBUTE WHERE CATEGORY = LEFT(@CATEGORY, 4) OR CATEGORY = LEFT(@CATEGORY, 6) OR CATEGORY = LEFT(@CATEGORY, 8) ORDER BY LEN(CATEGORY) DESC)
				WHERE A.DEL_YN = 'N'
				  AND B.DEL_YN = 'N'
				  AND C.DEL_YN = 'N'
				  AND G_MODELNO = @MODELNO
				  AND USE_CLASS_CODE < '4'
				  AND LTRIM(RTRIM(ISNULL(CASE WHEN USE_CLASS_CODE <> '2' THEN ATTRIBUTE_ELEMENT ELSE ATTRIBUTE_VALUE END, ''))) <> ''
				  AND D.TAG_ORDER > 0
				
				SELECT GROUPNM
					 , TITLE
					 , COUNT(*) CNT
					 , MIN(SORTNO) TITLE_ORDER
				INTO #SPEC_DETAIL_GROUP
				FROM #SPEC_DETAIL_TEMP
				GROUP BY GROUPNM, TITLE
				
				SELECT MODELNO
					 , SORTNO
					 , CASE WHEN GROUPNO = 1 AND (SELECT COUNT(*) FROM #SPEC_DETAIL_TEMP) > 5 THEN GROUPNM ELSE '' END GROUPNM
					 , CASE WHEN TITLENO = 1 THEN TITLE ELSE '' END TITLE
					 , CNT
					 , CONTENT
					 , ATTRIBUTE_ID
					 , ATTRIBUTE_ELEMENT_ID
					 , SPECNO
					 , DENSE_RANK() OVER(ORDER BY (SORTNO - TITLENO + 1)) DISPLAY_ROWNUM
				INTO #SPEC_DETAIL
				FROM (
					SELECT MODELNO
						 , DENSE_RANK() OVER(ORDER BY TITLE_ORDER, SORTNO) SORTNO
						 , A.GROUPNM
						 , A.TITLE
						 , CNT
						 , CONTENT
						 , ATTRIBUTE_ID
						 , ATTRIBUTE_ELEMENT_ID
						 , SPECNO
						 , DENSE_RANK() OVER(PARTITION BY A.GROUPNM ORDER BY SORTNO) GROUPNO
						 , DENSE_RANK() OVER(PARTITION BY A.GROUPNM, A.TITLE ORDER BY SORTNO) TITLENO
					FROM #SPEC_DETAIL_TEMP A
						INNER JOIN #SPEC_DETAIL_GROUP B ON A.GROUPNM = B.GROUPNM AND A.TITLE = B.TITLE
				) A
				
				INSERT INTO #TARGET_ATTRIBUTE(ATTRIBUTE_ID, GALLERY_ATTRIBUTE_NM, USE_CLASS_CODE, GROUP_ATTRIBUTE_ID, GROUP_CHAR, ELEMENT_CHAR, IS_GALLERY_DISPLAY, ATTRIBUTE_ELEMENT_ID, ATTRIBUTE_ELEMENT, ATTRIBUTE_VALUE, IS_DISPLAY, ATTRIBUTE_BOLD, ELEMENT_BOLD, SPECNO)
				SELECT A.ATTRIBUTE_ID, GALLERY_ATTRIBUTE_NM, USE_CLASS_CODE, GROUP_ATTRIBUTE_ID, GROUP_CHAR, ELEMENT_CHAR, IS_GALLERY_DISPLAY, A.ATTRIBUTE_ELEMENT_ID, ATTRIBUTE_ELEMENT, ATTRIBUTE_VALUE, IS_DISPLAY, ATTRIBUTE_BOLD, ELEMENT_BOLD, A.SPECNO
				FROM #SPEC_DETAIL A
					INNER JOIN #SPEC_DETAIL_TEMP B ON A.ATTRIBUTE_ID = B.ATTRIBUTE_ID AND A.ATTRIBUTE_ELEMENT_ID = B.ATTRIBUTE_ELEMENT_ID
				GROUP BY A.MODELNO, A.SORTNO, A.GROUPNM, A.TITLE, A.CONTENT, A.ATTRIBUTE_ID, GALLERY_ATTRIBUTE_NM, USE_CLASS_CODE, GROUP_ATTRIBUTE_ID, GROUP_CHAR, ELEMENT_CHAR, IS_GALLERY_DISPLAY, A.ATTRIBUTE_ELEMENT_ID, ATTRIBUTE_ELEMENT, ATTRIBUTE_VALUE, IS_DISPLAY, ATTRIBUTE_BOLD, ELEMENT_BOLD, A.SPECNO
				ORDER BY A.SORTNO
			END
		END
		ELSE IF @MODELNO > 0
		BEGIN
			INSERT INTO #TARGET_ATTRIBUTE(ATTRIBUTE_ID, GALLERY_ATTRIBUTE_NM, USE_CLASS_CODE, GROUP_ATTRIBUTE_ID, GROUP_CHAR, ELEMENT_CHAR, IS_GALLERY_DISPLAY, ATTRIBUTE_ELEMENT_ID, ATTRIBUTE_ELEMENT, ATTRIBUTE_VALUE, IS_DISPLAY, ATTRIBUTE_BOLD, ELEMENT_BOLD)
			SELECT B.ATTRIBUTE_ID
				 , GALLERY_ATTRIBUTE_NM
				 , USE_CLASS_CODE
				 , GROUP_ATTRIBUTE_ID
				 , GROUP_CHAR
				 , ELEMENT_CHAR
				 , IS_GALLERY_DISPLAY
				 , C.ATTRIBUTE_ELEMENT_ID
				 , ATTRIBUTE_ELEMENT
				 , ATTRIBUTE_VALUE
				 , IS_DISPLAY
				 , B.IS_BOLD ATTRIBUTE_BOLD
				 , C.IS_BOLD ELEMENT_BOLD
			FROM GOODS_CATALOG_ATTRIBUTE A
				INNER JOIN GOODS_ATTRIBUTE B ON A.ATTRIBUTE_ID = B.ATTRIBUTE_ID
				INNER JOIN GOODS_ATTRIBUTE_ELEMENT C ON A.ATTRIBUTE_ID = C.ATTRIBUTE_ID AND A.ATTRIBUTE_ELEMENT_ID = C.ATTRIBUTE_ELEMENT_ID
				INNER JOIN GOODS_CATEGORY_ATTRIBUTE D ON A.ATTRIBUTE_ID = D.ATTRIBUTE_ID AND D.CATEGORY IN (SELECT TOP 1 CATEGORY FROM GOODS_CATEGORY_ATTRIBUTE WHERE CATEGORY = LEFT(@CATEGORY, 4) OR CATEGORY = LEFT(@CATEGORY, 6) OR CATEGORY = LEFT(@CATEGORY, 8) ORDER BY LEN(CATEGORY) DESC)
			WHERE A.DEL_YN = 'N'
			  AND B.DEL_YN = 'N'
			  AND C.DEL_YN = 'N'
			  AND G_MODELNO = @MODELNO
			  AND USE_CLASS_CODE < '4'
			  AND LTRIM(RTRIM(ISNULL(CASE WHEN USE_CLASS_CODE <> '2' THEN ATTRIBUTE_ELEMENT ELSE ATTRIBUTE_VALUE END, ''))) <> ''
			  AND (IS_GALLERY_DISPLAY = 1 OR IS_DISPLAY = 1)
			ORDER BY D.DISPLAY_ORDER
				   , CASE WHEN ISNULL(GROUP_ATTRIBUTE_ID, 0) = B.ATTRIBUTE_ID THEN '0' ELSE '1' END
				   , GALLERY_ATTRIBUTE_NM
				   , C.DISPLAY_ORDER
				   , CASE WHEN USE_CLASS_CODE <> '2' THEN ATTRIBUTE_ELEMENT ELSE ATTRIBUTE_VALUE END
		END
		ELSE
		BEGIN
			INSERT INTO #TARGET_ATTRIBUTE(ATTRIBUTE_ID, GALLERY_ATTRIBUTE_NM, USE_CLASS_CODE, GROUP_ATTRIBUTE_ID, GROUP_CHAR, ELEMENT_CHAR, IS_GALLERY_DISPLAY, ATTRIBUTE_ELEMENT_ID, ATTRIBUTE_ELEMENT, ATTRIBUTE_VALUE, IS_DISPLAY, ATTRIBUTE_BOLD, ELEMENT_BOLD)
			SELECT A.ATTRIBUTE_ID
				 , MANAGE_ATTRIBUTE_NM
				 , USE_CLASS_CODE
				 , GROUP_ATTRIBUTE_ID
				 , GROUP_CHAR
				 , ELEMENT_CHAR
				 , 1
				 , 0
				 , ''
				 , ''
				 , '0'
				 , 0
				 , 0
			FROM GOODS_ATTRIBUTE A
				INNER JOIN GOODS_CATEGORY_ATTRIBUTE B ON A.ATTRIBUTE_ID = B.ATTRIBUTE_ID AND B.CATEGORY IN (SELECT TOP 1 CATEGORY FROM GOODS_CATEGORY_ATTRIBUTE WHERE CATEGORY = LEFT(@CATEGORY, 4) OR CATEGORY = LEFT(@CATEGORY, 6) OR CATEGORY = LEFT(@CATEGORY, 8) ORDER BY LEN(CATEGORY) DESC)
			WHERE DEL_YN = 'N'
			  AND USE_CLASS_CODE < '4'
			ORDER BY DISPLAY_ORDER
				   , CASE WHEN ISNULL(GROUP_ATTRIBUTE_ID, 0) = B.ATTRIBUTE_ID THEN '0' ELSE '1' END
				   , GALLERY_ATTRIBUTE_NM
		END
	END
    ELSE
	BEGIN
		IF CHARINDEX('_', REVERSE(@CATEGORY)) > 0
		BEGIN
			SET @ATTRIBUTE_ELEMENT_ID =  REVERSE(SUBSTRING(REVERSE(@CATEGORY), 1, CHARINDEX('_', REVERSE(@CATEGORY)) - 1))
			SET @CATEGORY = REVERSE(SUBSTRING(REVERSE(@CATEGORY), CHARINDEX('_', REVERSE(@CATEGORY)) + 1, 100))
		END
		IF CHARINDEX('_', REVERSE(@CATEGORY)) > 0
		BEGIN
			SET @ATTRIBUTE_ID =  REVERSE(SUBSTRING(REVERSE(@CATEGORY), 1, CHARINDEX('_', REVERSE(@CATEGORY)) - 1))
			SET @CATEGORY = REVERSE(SUBSTRING(REVERSE(@CATEGORY), CHARINDEX('_', REVERSE(@CATEGORY)) + 1, 100))
		END
		IF ISNUMERIC(@CATEGORY) = 0 OR ISNUMERIC(@ATTRIBUTE_ID) = 0 OR ISNUMERIC(@ATTRIBUTE_ELEMENT_ID) = 0
		BEGIN
			SET @ATTRIBUTE_ELEMENT_ID = 0
			SET @ATTRIBUTE_ID = 0
			SET @CATEGORY = ''
		END
		
		INSERT INTO #TARGET_ATTRIBUTE(ATTRIBUTE_ID, GALLERY_ATTRIBUTE_NM, USE_CLASS_CODE, GROUP_ATTRIBUTE_ID, GROUP_CHAR, ELEMENT_CHAR, IS_GALLERY_DISPLAY, ATTRIBUTE_ELEMENT_ID, ATTRIBUTE_ELEMENT, ATTRIBUTE_VALUE, IS_DISPLAY, ATTRIBUTE_BOLD, ELEMENT_BOLD)
		SELECT A.ATTRIBUTE_ID
			 , GALLERY_ATTRIBUTE_NM
			 , USE_CLASS_CODE
			 , GROUP_ATTRIBUTE_ID
			 , GROUP_CHAR
			 , ELEMENT_CHAR
			 , IS_GALLERY_DISPLAY
			 , B.ATTRIBUTE_ELEMENT_ID
			 , ATTRIBUTE_ELEMENT
			 , '' ATTRIBUTE_VALUE
			 , IS_DISPLAY
			 , A.IS_BOLD ATTRIBUTE_BOLD
			 , B.IS_BOLD ELEMENT_BOLD
		FROM GOODS_ATTRIBUTE A
			INNER JOIN GOODS_ATTRIBUTE_ELEMENT B ON A.ATTRIBUTE_ID = B.ATTRIBUTE_ID
			INNER JOIN GOODS_CATEGORY_ATTRIBUTE C ON A.ATTRIBUTE_ID = C.ATTRIBUTE_ID AND C.CATEGORY IN (SELECT TOP 1 CATEGORY FROM GOODS_CATEGORY_ATTRIBUTE WHERE LEFT(CATEGORY, 4) = LEFT(@CATEGORY, 4) AND ATTRIBUTE_ID = @ATTRIBUTE_ID ORDER BY LEN(CATEGORY) DESC)
			INNER JOIN GOODS_REFER_ATTRIBUTE D ON B.ATTRIBUTE_ID = D.REF_ATTRIBUTE_ID AND B.ATTRIBUTE_ELEMENT_ID = D.REF_ATTRIBUTE_ELEMENT_ID AND D.CATEGORY = @CATEGORY AND D.ATTRIBUTE_ID = @ATTRIBUTE_ID AND D.ATTRIBUTE_ELEMENT_ID = @ATTRIBUTE_ELEMENT_ID
		WHERE A.DEL_YN = 'N'
		  AND B.DEL_YN = 'N'
		  AND USE_CLASS_CODE < '4'
		  AND LTRIM(RTRIM(ISNULL(ATTRIBUTE_ELEMENT, ''))) <> ''
		ORDER BY C.DISPLAY_ORDER
			   , CASE WHEN ISNULL(GROUP_ATTRIBUTE_ID, 0) = A.ATTRIBUTE_ID THEN '0' ELSE '1' END
			   , GALLERY_ATTRIBUTE_NM
			   , B.DISPLAY_ORDER
			   , ATTRIBUTE_ELEMENT
	END
	
	SELECT ATTRIBUTE_ID BRACKET_ATTRIBUTE_ID
	INTO #BRACKET_GROUP
	FROM GOODS_ATTRIBUTE
	WHERE CATEGORY = LEFT(@CATEGORY, 4) AND DEL_YN = 'N'
		AND CHARINDEX('_´ë°ýÈ£', MANAGE_ATTRIBUTE_NM) > 0
	
	DECLARE FETCH_CURSOR CURSOR FOR
	SELECT ATTRIBUTE_ID, ISNULL(GALLERY_ATTRIBUTE_NM, '') GALLERY_ATTRIBUTE_NM, USE_CLASS_CODE, ISNULL(GROUP_ATTRIBUTE_ID, 0) GROUP_ATTRIBUTE_ID, ISNULL(GROUP_CHAR, '') GROUP_CHAR, ISNULL(ELEMENT_CHAR, '') ELEMENT_CHAR, IS_GALLERY_DISPLAY, ATTRIBUTE_ELEMENT_ID, ISNULL(ATTRIBUTE_ELEMENT, '') ATTRIBUTE_ELEMENT, ISNULL(ATTRIBUTE_VALUE, '') ATTRIBUTE_VALUE, IS_DISPLAY, ATTRIBUTE_BOLD, ELEMENT_BOLD, SPECNO
	FROM #TARGET_ATTRIBUTE
	ORDER BY SEQNO
	
	OPEN FETCH_CURSOR
	
	SET @TEMP_SPEC = ''
    SET @TEMP_SPECTITLE = ''
    SET @TEMP_ATTRIBUTE_ID = 0
    SET @GROUP_MAIN_SPEC = ''
    SET @GROUP_SPEC = ''
    SET @GROUP_ID = 0
	SET @REMOVE_SPECTITLE = ''
	SET @REMOVE_GROUP_MAIN_SPEC = ''
    SET @REMOVE_GROUP_SPEC = ''
	FETCH NEXT FROM FETCH_CURSOR INTO @ATTRIBUTE_ID, @GALLERY_ATTRIBUTE_NM, @USE_CLASS_CODE, @GROUP_ATTRIBUTE_ID, @CHAR, @ELE_CHAR, @IS_GALLERY_DISPLAY, @ATTRIBUTE_ELEMENT_ID, @ATTRIBUTE_ELEMENT, @ATTRIBUTE_VALUE, @IS_DISPLAY, @ATTRIBUTE_BOLD, @ELEMENT_BOLD, @SPECNO
	WHILE @@FETCH_STATUS = 0
	BEGIN
		IF @GROUP_ID > 0
		BEGIN
            IF @TEMP_ATTRIBUTE_ID = @GROUP_ID AND @TEMP_ATTRIBUTE_ID <> @ATTRIBUTE_ID
			BEGIN
                SET @GROUP_MAIN_SPEC = @TEMP_SPECTITLE + 
									   CASE WHEN @TEMP_SPECTITLE = '' OR @TEMP_SPEC = '' THEN '' ELSE ':' END + 
									   @TEMP_SPEC
                
				SET @REMOVE_GROUP_MAIN_SPEC = @REMOVE_SPECTITLE + 
											  CASE WHEN @REMOVE_SPECTITLE = '' OR @TEMP_SPEC = '' THEN '' ELSE ':' END + 
									          @TEMP_SPEC 
				
                SET @TEMP_SPECTITLE = ''
                SET @TEMP_SPEC = ''
				SET @REMOVE_SPECTITLE = ''
			END
            ELSE IF @TEMP_ATTRIBUTE_ID <> @ATTRIBUTE_ID
			BEGIN
				SET @GROUP_SPEC = @GROUP_SPEC + 
								  CASE WHEN @GROUP_SPEC = '' OR (@TEMP_SPECTITLE = '' AND @TEMP_SPEC = '') THEN '' ELSE CASE WHEN @GROUP_CHAR <> '' AND LEN(@GROUP_CHAR) % 2 <> 0 THEN @GROUP_CHAR ELSE ',' END END + 
								  @TEMP_SPECTITLE + 
								  CASE WHEN @TEMP_SPECTITLE = '' OR @TEMP_SPEC = '' THEN '' ELSE ':' END + 
								  @TEMP_SPEC
				
				SET @REMOVE_GROUP_SPEC = @REMOVE_GROUP_SPEC + 
										 CASE WHEN @REMOVE_GROUP_SPEC = '' OR (@REMOVE_SPECTITLE = '' AND @TEMP_SPEC = '') THEN '' ELSE CASE WHEN @GROUP_CHAR <> '' AND LEN(@GROUP_CHAR) % 2 <> 0 THEN @GROUP_CHAR ELSE ',' END END + 
										 @REMOVE_SPECTITLE + 
										 CASE WHEN @REMOVE_SPECTITLE = '' OR @TEMP_SPEC = '' THEN '' ELSE ':' END + 
										 @TEMP_SPEC
				
                SET @TEMP_SPECTITLE = ''
                SET @TEMP_SPEC = ''
				SET @REMOVE_SPECTITLE = ''
			END
            
            IF @GROUP_ID <> @GROUP_ATTRIBUTE_ID
			BEGIN
				SET @SPEC = @SPEC + 
				            CASE WHEN @SPEC = '' OR (@GROUP_MAIN_SPEC = '' AND @GROUP_SPEC = '') THEN '' ELSE CASE WHEN @MOBILEFLAG = 'Y' AND (SELECT COUNT(*) FROM #BRACKET_GROUP WHERE BRACKET_ATTRIBUTE_ID = @TEMP_ATTRIBUTE_ID) > 0 THEN '/[´ë°ýÈ£]' ELSE '/' END END + 
							@GROUP_MAIN_SPEC + 
							CASE WHEN @GROUP_MAIN_SPEC = '' OR @GROUP_SPEC = '' THEN '' ELSE CASE WHEN @GROUP_CHAR <> '' AND LEN(@GROUP_CHAR) % 2 = 0 THEN LEFT(@GROUP_CHAR, LEN(@GROUP_CHAR) / 2) ELSE CASE WHEN @GROUP_CHAR <> '' THEN @GROUP_CHAR ELSE ',' END END END + 
							@GROUP_SPEC + 
							CASE WHEN @GROUP_MAIN_SPEC = '' OR @GROUP_SPEC = '' THEN '' ELSE CASE WHEN @GROUP_CHAR <> '' AND LEN(@GROUP_CHAR) % 2 = 0 THEN RIGHT(@GROUP_CHAR, LEN(@GROUP_CHAR) / 2) ELSE '' END END
				
                SET @GROUP_MAIN_SPEC = ''
                SET @GROUP_SPEC = ''
				SET @REMOVE_GROUP_MAIN_SPEC = ''
                SET @REMOVE_GROUP_SPEC = ''
            END
		END
        ELSE
		BEGIN
            IF @TEMP_ATTRIBUTE_ID <> @ATTRIBUTE_ID
			BEGIN
				SET @SPEC = @SPEC + 
							CASE WHEN @SPEC = '' OR (@TEMP_SPECTITLE = '' AND @TEMP_SPEC = '') THEN '' ELSE CASE WHEN @MOBILEFLAG = 'Y' AND (SELECT COUNT(*) FROM #BRACKET_GROUP WHERE BRACKET_ATTRIBUTE_ID = @TEMP_ATTRIBUTE_ID) > 0 THEN '/[´ë°ýÈ£]' ELSE '/' END END + 
							@TEMP_SPECTITLE + 
							CASE WHEN @TEMP_SPECTITLE = '' OR @TEMP_SPEC = '' THEN '' ELSE ':' END + 
							@TEMP_SPEC
				
                SET @TEMP_SPECTITLE = ''
                SET @TEMP_SPEC = ''
				SET @REMOVE_SPECTITLE = ''
            END
        END
        
        IF @TEMP_ATTRIBUTE_ID <> @ATTRIBUTE_ID
		BEGIN
            IF NOT(@GROUP_ATTRIBUTE_ID <> 0 AND @GROUP_ID = @GROUP_ATTRIBUTE_ID)
				SET @GROUP_CHAR = LTRIM(RTRIM(@CHAR))
        END
        SET @TEMP_ATTRIBUTE_ID = @ATTRIBUTE_ID
        SET @GROUP_ID = @GROUP_ATTRIBUTE_ID
        SET @ELEMENT_CHAR = LTRIM(RTRIM(@ELE_CHAR))
		
        IF @IS_GALLERY_DISPLAY = 1 AND @TEMP_SPECTITLE = ''
		BEGIN
            IF @GALLERY_ATTRIBUTE_NM <> ''
			BEGIN
				SET @I = 0
				IF @MOBILEFLAG = 'Y'
				BEGIN
					SET @QRY = N'SELECT @CNT = CNT FROM OPENQUERY(ORADB, ''SELECT COUNT(*) CNT FROM TBL_TERMDIC_ATTRIBUTE WHERE CA_CODE = ''''' + CAST(LEFT(@CATEGORY, 4) AS NVARCHAR(12)) + ''''' AND ATTRIBUTE_ID = ' + CAST(@ATTRIBUTE_ID AS NVARCHAR(20)) + ' AND ATTRIBUTE_ELEMENT_ID IS NULL'')'
						
					EXECUTE SP_EXECUTESQL @QRY, N'@CNT INT OUTPUT', @CNT = @I OUTPUT
				END
				
				SET @TEMP_SPECTITLE = CASE WHEN @MOBILEFLAG = 'Y' AND @I > 0 THEN '$TAG$_' + CAST(@ATTRIBUTE_ID AS VARCHAR(20)) + '_0_0_' ELSE '' END + 
									  CASE WHEN @ATTRIBUTE_BOLD = 1 THEN '<b>' ELSE '' END + REPLACE(REPLACE(REPLACE(LTRIM(RTRIM(@GALLERY_ATTRIBUTE_NM)), '</', '<¢Ì'), '/', '&#47;'), '<¢Ì', '</') + CASE WHEN @ATTRIBUTE_BOLD = 1 THEN '</b>' ELSE '' END + 
									  CASE WHEN @MOBILEFLAG = 'Y' AND @I > 0 THEN '$END$' ELSE '' END
				
				SET @REMOVE_SPECTITLE = CASE WHEN @ATTRIBUTE_BOLD = 1 THEN '<b>' ELSE '' END + REPLACE(REPLACE(REPLACE(LTRIM(RTRIM(@GALLERY_ATTRIBUTE_NM)), '</', '<¢Ì'), '/', '&#47;'), '<¢Ì', '</') + CASE WHEN @ATTRIBUTE_BOLD = 1 THEN '</b>' ELSE '' END
				
                IF @GROUP_ID > 0 AND
				   (CHARINDEX(@TEMP_SPECTITLE + ':', @GROUP_MAIN_SPEC) = 1 OR CHARINDEX(@TEMP_SPECTITLE + ':', @GROUP_SPEC) = 1 OR
				    CHARINDEX(@REMOVE_SPECTITLE + ':', @REMOVE_GROUP_MAIN_SPEC) = 1 OR CHARINDEX(@REMOVE_SPECTITLE + ':', @REMOVE_GROUP_SPEC) = 1)
				BEGIN
					SET @TEMP_SPECTITLE = ''
					SET @REMOVE_SPECTITLE = ''
				END
            END
        END
		
        IF @IS_DISPLAY = 1
		BEGIN
            IF (@USE_CLASS_CODE = '2' AND @ATTRIBUTE_VALUE <> '') OR (@USE_CLASS_CODE <> '2' AND @ATTRIBUTE_ELEMENT <> '')
			BEGIN
                IF @TEMP_SPEC <> ''
                    SET @TEMP_SPEC = @TEMP_SPEC + CASE WHEN @ELEMENT_CHAR = '' THEN ',' ELSE @ELEMENT_CHAR END
                
                IF @MOBILEFLAG = 'Y'
				BEGIN
					SET @I = 0
					SET @QRY = N'SELECT @CNT = CNT FROM OPENQUERY(ORADB, ''SELECT COUNT(*) CNT FROM TBL_TERMDIC_ATTRIBUTE WHERE CA_CODE = ''''' + CAST(LEFT(@CATEGORY, 4) AS NVARCHAR(12)) + ''''' AND ATTRIBUTE_ID = ' + CAST(@ATTRIBUTE_ID AS NVARCHAR(20)) + ' AND ATTRIBUTE_ELEMENT_ID  = ' + CAST(@ATTRIBUTE_ELEMENT_ID AS NVARCHAR(20)) + ''')'
					
					EXECUTE SP_EXECUTESQL @QRY, N'@CNT INT OUTPUT', @CNT = @I OUTPUT
					
                    IF @I = 0
                        SET @TEMP_SPEC = @TEMP_SPEC + '$TAG$_0_0_' + CAST(ISNULL(@SPECNO, 0) AS VARCHAR(20)) + '_'
                    ELSE
                        SET @TEMP_SPEC = @TEMP_SPEC + '$TAG$_' + CAST(@ATTRIBUTE_ID AS VARCHAR(20)) + '_' + CAST(@ATTRIBUTE_ELEMENT_ID AS VARCHAR(20)) + '_' + CAST(ISNULL(@SPECNO, 0) AS VARCHAR(20)) + '_'
                END
                SET @TEMP_SPEC = @TEMP_SPEC + CASE WHEN @ELEMENT_BOLD = 1 THEN '<b>' ELSE '' END
                IF @USE_CLASS_CODE = '2'
                    SET @TEMP_SPEC = @TEMP_SPEC + REPLACE(REPLACE(REPLACE(LTRIM(RTRIM(@ATTRIBUTE_VALUE)), '</', '<¢Ì'), '/', '&#47;'), '<¢Ì', '</')
                ELSE
                    SET @TEMP_SPEC = @TEMP_SPEC + REPLACE(REPLACE(REPLACE(LTRIM(RTRIM(@ATTRIBUTE_ELEMENT)), '</', '<¢Ì'), '/', '&#47;'), '<¢Ì', '</')
                SET @TEMP_SPEC = @TEMP_SPEC + CASE WHEN @ELEMENT_BOLD = 1 THEN '</b>' ELSE '' END
                IF @MOBILEFLAG = 'Y'
                    SET @TEMP_SPEC = @TEMP_SPEC + '$END$'
            END
        END
		
		FETCH NEXT FROM FETCH_CURSOR INTO @ATTRIBUTE_ID, @GALLERY_ATTRIBUTE_NM, @USE_CLASS_CODE, @GROUP_ATTRIBUTE_ID, @CHAR, @ELE_CHAR, @IS_GALLERY_DISPLAY, @ATTRIBUTE_ELEMENT_ID, @ATTRIBUTE_ELEMENT, @ATTRIBUTE_VALUE, @IS_DISPLAY, @ATTRIBUTE_BOLD, @ELEMENT_BOLD, @SPECNO
	END
	
	CLOSE FETCH_CURSOR
	DEALLOCATE FETCH_CURSOR
	
	IF (SELECT COUNT(*) FROM #TARGET_ATTRIBUTE) > 0
	BEGIN
		IF @GROUP_ID > 0
		BEGIN
            IF @TEMP_ATTRIBUTE_ID = @GROUP_ID
			BEGIN
                SET @GROUP_MAIN_SPEC = @TEMP_SPECTITLE + 
									   CASE WHEN @TEMP_SPECTITLE = '' OR @TEMP_SPEC = '' THEN '' ELSE ':' END + 
									   @TEMP_SPEC
                
				SET @REMOVE_GROUP_MAIN_SPEC = @REMOVE_SPECTITLE + 
										      CASE WHEN @REMOVE_SPECTITLE = '' OR @TEMP_SPEC = '' THEN '' ELSE ':' END + 
											  @TEMP_SPEC
				
                SET @TEMP_SPECTITLE = ''
                SET @TEMP_SPEC = ''
				SET @REMOVE_SPECTITLE = ''
			END
            ELSE
			BEGIN
				SET @GROUP_SPEC = @GROUP_SPEC + 
								  CASE WHEN @GROUP_SPEC = '' OR (@TEMP_SPECTITLE = '' AND @TEMP_SPEC = '') THEN '' ELSE CASE WHEN @GROUP_CHAR <> '' AND LEN(@GROUP_CHAR) % 2 <> 0 THEN @GROUP_CHAR ELSE ',' END END + 
								  @TEMP_SPECTITLE + 
								  CASE WHEN @TEMP_SPECTITLE = '' OR @TEMP_SPEC = '' THEN '' ELSE ':' END + 
								  @TEMP_SPEC
				
				SET @REMOVE_GROUP_SPEC = @REMOVE_GROUP_SPEC + 
								         CASE WHEN @REMOVE_GROUP_SPEC = '' OR (@REMOVE_SPECTITLE = '' AND @TEMP_SPEC = '') THEN '' ELSE CASE WHEN @GROUP_CHAR <> '' AND LEN(@GROUP_CHAR) % 2 <> 0 THEN @GROUP_CHAR ELSE ',' END END + 
										 @REMOVE_SPECTITLE + 
										 CASE WHEN @REMOVE_SPECTITLE = '' OR @TEMP_SPEC = '' THEN '' ELSE ':' END + 
										 @TEMP_SPEC
				
                SET @TEMP_SPECTITLE = ''
                SET @TEMP_SPEC = ''
				SET @REMOVE_SPECTITLE = ''
			END
            
			SET @SPEC = @SPEC + 
				        CASE WHEN @SPEC = '' OR (@GROUP_MAIN_SPEC = '' AND @GROUP_SPEC = '') THEN '' ELSE CASE WHEN @MOBILEFLAG = 'Y' AND (SELECT COUNT(*) FROM #BRACKET_GROUP WHERE BRACKET_ATTRIBUTE_ID = @TEMP_ATTRIBUTE_ID) > 0 THEN '/[´ë°ýÈ£]' ELSE '/' END END + 
						@GROUP_MAIN_SPEC + 
						CASE WHEN @GROUP_MAIN_SPEC = '' OR @GROUP_SPEC = '' THEN '' ELSE CASE WHEN @GROUP_CHAR <> '' AND LEN(@GROUP_CHAR) % 2 = 0 THEN LEFT(@GROUP_CHAR, LEN(@GROUP_CHAR) / 2) ELSE CASE WHEN @GROUP_CHAR <> '' THEN @GROUP_CHAR ELSE ',' END END END + 
						@GROUP_SPEC + 
						CASE WHEN @GROUP_MAIN_SPEC = '' OR @GROUP_SPEC = '' THEN '' ELSE CASE WHEN @GROUP_CHAR <> '' AND LEN(@GROUP_CHAR) % 2 = 0 THEN RIGHT(@GROUP_CHAR, LEN(@GROUP_CHAR) / 2) ELSE '' END END
				
            SET @GROUP_MAIN_SPEC = ''
            SET @GROUP_SPEC = ''
			SET @REMOVE_GROUP_MAIN_SPEC = ''
            SET @REMOVE_GROUP_SPEC = ''
		END
        ELSE
		BEGIN
			SET @SPEC = @SPEC + 
					    CASE WHEN @SPEC = '' OR (@TEMP_SPECTITLE = '' AND @TEMP_SPEC = '') THEN '' ELSE CASE WHEN @MOBILEFLAG = 'Y' AND (SELECT COUNT(*) FROM #BRACKET_GROUP WHERE BRACKET_ATTRIBUTE_ID = @TEMP_ATTRIBUTE_ID) > 0 THEN '/[´ë°ýÈ£]' ELSE '/' END END + 
						@TEMP_SPECTITLE + 
						CASE WHEN @TEMP_SPECTITLE = '' OR @TEMP_SPEC = '' THEN '' ELSE ':' END + 
						@TEMP_SPEC
			
            SET @TEMP_SPECTITLE = ''
            SET @TEMP_SPEC = ''
			SET @REMOVE_SPECTITLE = ''
        END
	END
	
	SET @I = 1
    SET @TEMP_SPEC = @SPEC
    WHILE LEN(@SPEC) > @I
	BEGIN
        SET @I = CHARINDEX('</b>', @SPEC, @I)
        IF @I > 0
		BEGIN
            IF SUBSTRING(@SPEC, @I, 8) <> '</b>/<b>' AND PATINDEX('</b>%<b>', SUBSTRING(@SPEC, @I, 8)) > 0
                SET @TEMP_SPEC = REPLACE(@TEMP_SPEC, SUBSTRING(@SPEC, @I, 8), SUBSTRING(SUBSTRING(@SPEC, @I, 8), 5, 1))
            SET @I = @I + 8
		END
        ELSE
            SET @I = LEN(@SPEC) + 8
	END
	SET @SPEC = @TEMP_SPEC
	IF NOT(@MOBILEFLAG = 'Y') AND @MODELNO > 0
		SET @SPEC = @SPEC + CASE WHEN @SPEC <> '' AND @SPEC_DESCRIPTION <> '' THEN '/' ELSE '' END + @SPEC_DESCRIPTION
	
	IF @MOBILEFLAG = 'Y'
	BEGIN
		SET @I = 1
		SET @QRY  = ''
		SET @TEMP_SPEC = ''
		SET @TEMP_SPECTITLE = ''
		SET @GROUP_MAIN_SPEC = ''
		SET @GROUP_SPEC = ''
		SET @SPEC_DESCRIPTION = ''
		WHILE LEN(@SPEC) >= @I
		BEGIN
			IF CHARINDEX('$END$', @SPEC, @I) > 0
			BEGIN
				SET @QRY = SUBSTRING(@SPEC, @I, CHARINDEX('$END$', @SPEC, @I) - @I)
				
				SET @TEMP_SPECTITLE = SUBSTRING(@QRY, 1, CHARINDEX('_', @QRY))
				SET @QRY = SUBSTRING(@QRY, CHARINDEX('_', @QRY) + 1, 1000)
				
				SET @GROUP_MAIN_SPEC = SUBSTRING(@QRY, 1, CHARINDEX('_', @QRY))
				SET @QRY = SUBSTRING(@QRY, CHARINDEX('_', @QRY) + 1, 1000)
				
				SET @GROUP_SPEC = SUBSTRING(@QRY, 1, CHARINDEX('_', @QRY))
				SET @QRY = SUBSTRING(@QRY, CHARINDEX('_', @QRY) + 1, 1000)
				
				SET @SPEC_DESCRIPTION = SUBSTRING(@QRY, 1, CHARINDEX('_', @QRY))
				SET @QRY = SUBSTRING(@QRY, CHARINDEX('_', @QRY) + 1, 1000)
				
				IF @TEMP_SPECTITLE = '' OR @GROUP_MAIN_SPEC = '' OR @GROUP_SPEC = '' OR @SPEC_DESCRIPTION = ''
				BEGIN
					SET @TEMP_SPECTITLE = ''
					SET @GROUP_MAIN_SPEC = ''
					SET @GROUP_SPEC = ''
					SET @SPEC_DESCRIPTION = ''
				END
				
				SET @TEMP_SPEC = @TEMP_SPECTITLE
				IF @GROUP_MAIN_SPEC <> '' AND @GROUP_MAIN_SPEC <> '0_'
					SET @TEMP_SPEC = @TEMP_SPEC + @GROUP_MAIN_SPEC + @GROUP_SPEC + @QRY + '$END$'
				ELSE
					SET @TEMP_SPEC = REPLACE(@TEMP_SPEC, '$TAG$_', '') + @QRY
				SET @SZVIPTAG = @SZVIPTAG + @TEMP_SPEC
				
				SET @TEMP_SPEC = @TEMP_SPECTITLE
				IF @SPEC_DESCRIPTION <> '' AND @SPEC_DESCRIPTION <> '0_'
					SET @TEMP_SPEC = @TEMP_SPEC + @SPEC_DESCRIPTION + @QRY + '$END$'
				ELSE
					SET @TEMP_SPEC = REPLACE(@TEMP_SPEC, '$TAG$_', '') + @QRY
				SET @SZLPTAG1 = @SZLPTAG1 + @TEMP_SPEC
				
				SET @I = CHARINDEX('$END$', @SPEC, @I) + 5
			END
			ELSE
			BEGIN
				SET @SZLPTAG1 = @SZLPTAG1 + SUBSTRING(@SPEC, @I, LEN(@SPEC))
				SET @SZVIPTAG = @SZVIPTAG + SUBSTRING(@SPEC, @I, LEN(@SPEC))
				SET @I = LEN(@SPEC) + 1
			END
		END
		
		IF CHARINDEX('/[´ë°ýÈ£]', @SZLPTAG1) > 0
		BEGIN
			SET @SZLPTAG2 = SUBSTRING(REPLACE(SUBSTRING(@SZLPTAG1, CHARINDEX('/[´ë°ýÈ£]', @SZLPTAG1), 8000), '/[´ë°ýÈ£]', '/'), 2, 8000)
			SET @SZLPTAG1 = SUBSTRING(@SZLPTAG1, 1, CHARINDEX('/[´ë°ýÈ£]', @SZLPTAG1) - 1)
			SET @SZVIPTAG = SUBSTRING(@SZVIPTAG, 1, CHARINDEX('/[´ë°ýÈ£]', @SZVIPTAG) - 1)
		END
		
		SET @I = 0
		SET @TEMP_SPEC = REPLACE(@SZLPTAG1, '</', '<¢Ì')
		SET @TEMP_SPECTITLE = REPLACE(@SZVIPTAG, '</', '<¢Ì')
		SET @SZLPTAG1 = ''
		SET @SZVIPTAG = ''
		WHILE @I < @TOP_CNT AND @TEMP_SPEC <> ''
		BEGIN
			SET @SZLPTAG1 = @SZLPTAG1 + 
							CASE WHEN @SZLPTAG1 <> '' THEN '/' ELSE '' END + 
							CASE WHEN CHARINDEX('/', @TEMP_SPEC) > 0 THEN SUBSTRING(@TEMP_SPEC, 1, CHARINDEX('/', @TEMP_SPEC) - 1) ELSE @TEMP_SPEC END
			SET @TEMP_SPEC = CASE WHEN CHARINDEX('/', @TEMP_SPEC) > 0 THEN  SUBSTRING(@TEMP_SPEC, CHARINDEX('/', @TEMP_SPEC) + 1, 8000) ELSE '' END
			
			SET @SZVIPTAG = @SZVIPTAG + 
							CASE WHEN @SZVIPTAG <> '' THEN '/' ELSE '' END + 
							CASE WHEN CHARINDEX('/', @TEMP_SPECTITLE) > 0 THEN SUBSTRING(@TEMP_SPECTITLE, 1, CHARINDEX('/', @TEMP_SPECTITLE) - 1) ELSE @TEMP_SPECTITLE END
			SET @TEMP_SPECTITLE = CASE WHEN CHARINDEX('/', @TEMP_SPECTITLE) > 0 THEN  SUBSTRING(@TEMP_SPECTITLE, CHARINDEX('/', @TEMP_SPECTITLE) + 1, 8000) ELSE '' END
			
			SET @I = @I + 1
		END
		SET @SZLPTAG1 = REPLACE(@SZLPTAG1, '<¢Ì', '</')
		SET @SZVIPTAG = REPLACE(@SZVIPTAG, '<¢Ì', '</')
	END
	ELSE
		SET @SZLPTAG1 = @SPEC
	
	IF @PRINTFLAG = 'Y'
		SELECT @SZLPTAG1, @SZLPTAG2, @SZVIPTAG
END
