/* *************************************************************************
 * NAME : dbo.UDP_MP_NONE_PROCESS
 * TYPE : PROCEDURE (SQL_STORED_PROCEDURE)
 * TIME : Create: 2018-01-22 13:30:48.913
 *        Modify: 2018-05-03 17:23:35.443
 *        Backup: 20180521_1737
 ************************************************************************* */


CREATE PROC [DBO].[UDP_MP_NONE_PROCESS]
	@MODELNO INT,
	@MM_ID VARCHAR(15)
AS
BEGIN
	-- ELOC만 처리
	
	SET NOCOUNT ON;
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
	
	-- 그룹툴 초기화
	UPDATE /* UDP_MP_NONE_PROCESS:01 */ GOODS
	SET G_FLAG = '1', G_MODELNO_GROUP = NULL, G_CONDITION_NUMBER = NULL, G_GROUP_ATTRIBUTE_ID = NULL, G_GROUP_FLAG = NULL
	WHERE G_MODELNO_GROUP = @MODELNO
	
	-- 속성 초기화
	UPDATE /* UDP_MP_NONE_PROCESS:02 */ GOODS_CATALOG_ATTRIBUTE
	SET DEL_YN = 'Y', UPD_DATE = GETDATE(), UPD_OPRT = @MM_ID
	WHERE DEL_YN = 'N' AND G_MODELNO = @MODELNO
	
	-- 삭제처리 로그
	INSERT /* UDP_MP_NONE_PROCESS:03 */ INTO GOODS_DELETE_MODELNO (G_MODELNO, G_MODELNM, G_FACTORY, G_CATEGORY, MM_ID)
	SELECT G_MODELNO, G_MODELNM, G_FACTORY, G_CATEGORY, @MM_ID
	FROM GOODS
	WHERE G_MODELNO = @MODELNO AND NOT EXISTS(SELECT TOP 1 1 FROM GOODS_DELETE_MODELNO WHERE G_MODELNO = @MODELNO)
	
	-- 카탈로그 초기화
	UPDATE /* UDP_MP_NONE_PROCESS:04 */ GOODS
	SET G_MODELNM = '모델삭제'
	  , G_CATEGORY = '00000000'
	  , G_FACTORY = ''
	  , G_IMGCHK = '4'
	  , G_CONSTRAIN = '1'
	  , G_FLAG = '0'
	  , G_REFID = 0
	  , G_JOBCODE = '0'
	  , G_PARTCODE = '0'
	  , G_WORK = '0'
	  , G_REFSHOP = '0'
	  , G_NOTICE = ''
	  , G_KEYWORD = ''
	  , G_MANUAL_LINK = ''
	  , G_LINKSERVICEFLAG = '1'
	  , G_SIZE = ''
	  , G_FUNC = NULL
	  , G_WEBCNT = 0
	  , G_ORWEBKEYWORD = NULL
	  , G_FACTORY_ETC = ''
	  , G_BRAND = ''
	  , G_FUNC_IMG = ''
	  , G_FUNC_IMG_FLAG = '0'
	  , G_KEYWORD2 = NULL
	  , G_WEIGHT = NULL
	  , G_IMGCHK_ROLLING = '0'
	  , G_ECATALOG_FLAG = NULL
	  , G_ECATALOG_URL = NULL
	  , G_MODELNO_GROUP = NULL
	  , G_CONDITION_NUMBER = NULL
	  , G_GROUP_FLAG = NULL
	  , G_STANDARD = NULL
	  , G_AMOUNT = NULL
	  , G_CHANGE = NULL
	  , G_U_NIT = NULL
	  , G_GROUP_ATTRIBUTE_ID = NULL
	  , BRAND_ID = NULL
	  , MAKER_ID = NULL
	  , G_SPEC2 = ''
	  , G_SPEC_DESCRIPTION = NULL
	  , G_ALL_COMPONENT = NULL
	WHERE G_MODELNO = @MODELNO
	
	-- 카탈로그 통계정보 삭제
	DELETE /* UDP_MP_NONE_PROCESS:05 */ FROM GOODS_SUM
	WHERE G_MODELNO = @MODELNO

	-- 작업로그
	INSERT /* UDP_MP_NONE_PROCESS:06 */ INTO LOGDB.DBO.JOB_GOODS (JG_MODELNO, JG_CATEGORY, JG_ID, JG_FLAG, JG_DATE)
	SELECT G_MODELNO, G_CATEGORY, @MM_ID, 'D', GETDATE()
	FROM GOODS
	WHERE G_MODELNO = @MODELNO AND EXISTS(SELECT TOP 1 1 FROM GOODS_DELETE_MODELNO WHERE G_MODELNO = @MODELNO AND REGDATE >= CONVERT(VARCHAR(10), GETDATE(), 120))
END
