/* *************************************************************************
 * NAME : dbo.UDP_MCSS_CATALOG_STEP1
 * TYPE : PROCEDURE (SQL_STORED_PROCEDURE)
 * TIME : Create: 2018-03-15 14:34:34.84
 *        Modify: 2018-05-03 17:23:35.463
 *        Backup: 20180521_1737
 ************************************************************************* */


CREATE PROC [DBO].[UDP_MCSS_CATALOG_STEP1]
AS
BEGIN
	SET NOCOUNT ON;
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
	
	DECLARE @QRY VARCHAR(8000)
	
	DELETE FROM TBL_MCSS_LOG WHERE YYYYMMDD = CONVERT(VARCHAR(10), GETDATE(), 112) AND PATH = 'TBL_MCSS_CATEGORY'
	DELETE FROM TBL_MCSS_LOG WHERE YYYYMMDD = CONVERT(VARCHAR(10), GETDATE(), 112) AND PATH = 'TBL_MCSS_ATTRIBUTE'
	DELETE FROM TBL_MCSS_LOG WHERE YYYYMMDD = CONVERT(VARCHAR(10), GETDATE(), 112) AND PATH = 'TBL_MCSS_ATTRIBUTE_ELEMENT'
	DELETE FROM TBL_MCSS_LOG WHERE YYYYMMDD = CONVERT(VARCHAR(10), GETDATE(), 112) AND PATH = 'TBL_MCSS_ATTRIBUTE_CATEGORY'
	DELETE FROM TBL_MCSS_LOG WHERE YYYYMMDD = CONVERT(VARCHAR(10), GETDATE(), 112) AND PATH = 'TBL_MCSS_CATALOG'
	
	--IF (OBJECT_ID('TBL_MCSS_ATTRIBUTE_OLD')			IS NOT NULL)	DROP TABLE TBL_MCSS_ATTRIBUTE_OLD
	--IF (OBJECT_ID('TBL_MCSS_ATTRIBUTE_CATALOG_OLD') IS NOT NULL)	DROP TABLE TBL_MCSS_ATTRIBUTE_CATALOG_OLD
	--IF (OBJECT_ID('TBL_MCSS_ATTRIBUTE_CATEGORY_OLD')IS NOT NULL)	DROP TABLE TBL_MCSS_ATTRIBUTE_CATEGORY_OLD
	--IF (OBJECT_ID('TBL_MCSS_ATTRIBUTE_ELEMENT_OLD')	IS NOT NULL)	DROP TABLE TBL_MCSS_ATTRIBUTE_ELEMENT_OLD
	--IF (OBJECT_ID('TBL_MCSS_CATALOG_OLD')			IS NOT NULL)	DROP TABLE TBL_MCSS_CATALOG_OLD
	--IF (OBJECT_ID('TBL_MCSS_CATEGORY_OLD')			IS NOT NULL)	DROP TABLE TBL_MCSS_CATEGORY_OLD
	--IF (OBJECT_ID('TBL_MCSS_EP_11ST_OLD')			IS NOT NULL)	DROP TABLE TBL_MCSS_EP_11ST_OLD
	
	--IF (OBJECT_ID('TBL_MCSS_ATTRIBUTE')			IS NOT NULL)	EXEC SP_RENAME TBL_MCSS_ATTRIBUTE,			TBL_MCSS_ATTRIBUTE_OLD
	--IF (OBJECT_ID('TBL_MCSS_ATTRIBUTE_CATALOG') IS NOT NULL)	EXEC SP_RENAME TBL_MCSS_ATTRIBUTE_CATALOG,	TBL_MCSS_ATTRIBUTE_CATALOG_OLD
	--IF (OBJECT_ID('TBL_MCSS_ATTRIBUTE_CATEGORY')IS NOT NULL)	EXEC SP_RENAME TBL_MCSS_ATTRIBUTE_CATEGORY,	TBL_MCSS_ATTRIBUTE_CATEGORY_OLD
	--IF (OBJECT_ID('TBL_MCSS_ATTRIBUTE_ELEMENT')	IS NOT NULL)	EXEC SP_RENAME TBL_MCSS_ATTRIBUTE_ELEMENT,	TBL_MCSS_ATTRIBUTE_ELEMENT_OLD
	--IF (OBJECT_ID('TBL_MCSS_CATALOG')			IS NOT NULL)	EXEC SP_RENAME TBL_MCSS_CATALOG,			TBL_MCSS_CATALOG_OLD
	--IF (OBJECT_ID('TBL_MCSS_CATEGORY')			IS NOT NULL)	EXEC SP_RENAME TBL_MCSS_CATEGORY,			TBL_MCSS_CATEGORY_OLD
	--IF (OBJECT_ID('TBL_MCSS_EP_11ST')			IS NOT NULL)	EXEC SP_RENAME TBL_MCSS_EP_11ST,			TBL_MCSS_EP_11ST_OLD
	
	------------------------------------------------------------------------------------------
	-- 카테고리 (ORACLE)
	INSERT INTO TBL_MCSS_LOG(YYYYMMDD, PATH)
	SELECT CONVERT(VARCHAR(10), GETDATE(), 112), 'TBL_MCSS_CATEGORY'
	
	DROP TABLE TBL_MCSS_CATEGORY
	CREATE TABLE TBL_MCSS_CATEGORY(
		CA_CODE VARCHAR(12) PRIMARY KEY
		, C_NAME VARCHAR(60)
		, C_LEVEL TINYINT
		, C_SEQNO TINYINT
		, C_CODE_FULL VARCHAR(20)
		, C_NAME_FULL VARCHAR(250)
		, PARENT_CODE VARCHAR(12)
		, IS_FINAL_DEPTH CHAR(1)
		, EXTRACT_DATE DATETIME DEFAULT GETDATE()
	)
	
	SET @QRY = 
	'
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
	
	INSERT INTO TBL_MCSS_CATEGORY(CA_CODE, C_NAME, C_LEVEL, C_SEQNO, C_CODE_FULL, C_NAME_FULL, PARENT_CODE, IS_FINAL_DEPTH)
	SELECT CA_CODE, C_NAME, C_LEVEL, C_SEQNO, C_CODE_FULL, C_NAME_FULL, PARENT_CODE, IS_FINAL_DEPTH
	FROM OPENQUERY(ORADB,''
		SELECT CA_CODE, C_NAME, C_LEVEL, C_SEQNO, C_CODE_FULL, C_NAME_FULL, PARENT_CODE, IS_FINAL_DEPTH
		FROM TMPT_MCSS_CATEGORY
	'')
	OPTION (MAXDOP 1)
	'
	
	EXEC (@QRY)
	
	UPDATE TBL_MCSS_LOG
	SET ENDDATE = GETDATE()
	WHERE YYYYMMDD = CONVERT(VARCHAR(10), GETDATE(), 112) AND PATH = 'TBL_MCSS_CATEGORY'
	------------------------------------------------------------------------------------------
	
	------------------------------------------------------------------------------------------
	-- 카탈로그 (ORACLE)
	DROP TABLE TBL_MCSS_CATALOG
	CREATE TABLE TBL_MCSS_CATALOG(
		MODELNO INT NOT NULL
		, CA_CODE VARCHAR(12)
		, MODELNO_GROUP INT
		, MODELNM VARCHAR(140)
		, CONDINAME VARCHAR(50)
		, FACTORY VARCHAR(100)
		, BRAND VARCHAR(100)
		, CONSTRAIN CHAR(1)
		, IMGCHK3 CHAR(1)
		, MALLCNT INT
		, MINPRICE INT
		, MAXPRICE INT
		, AVGPRICE INT
		, SPEC VARCHAR(4000)
		, KEYWORD2 VARCHAR(2600)
		, FUNC VARCHAR(8000)
		, POPULAR INT
		, INS_DATE DATETIME
		, UPD_DATE DATETIME
		, EXTRACT_DATE DATETIME DEFAULT GETDATE()
	)
	------------------------------------------------------------------------------------------
	
	------------------------------------------------------------------------------------------
	-- 속성 (ELOC)
	INSERT INTO TBL_MCSS_LOG(YYYYMMDD, PATH)
	SELECT CONVERT(VARCHAR(10), GETDATE(), 112), 'TBL_MCSS_ATTRIBUTE'
	
	DROP TABLE TBL_MCSS_ATTRIBUTE
	SELECT ATTRIBUTE_ID, CATEGORY, MANAGE_ATTRIBUTE_NM, GALLERY_ATTRIBUTE_NM, IS_GALLERY_DISPLAY, USE_CLASS_CODE, INS_DATE, UPD_DATE, DEL_YN, GETDATE() EXTRACT_DATE
	INTO TBL_MCSS_ATTRIBUTE
	FROM GOODS_ATTRIBUTE
	WHERE CATEGORY IN (SELECT CA_CODE FROM TBL_MCSS_CATEGORY WHERE C_LEVEL = 2)
	  AND MANAGE_ATTRIBUTE_NM NOT LIKE '%temp%'
	  AND GALLERY_ATTRIBUTE_NM NOT LIKE '%temp%'
	  AND USE_CLASS_CODE < '4'
	OPTION (MAXDOP 1)
	
	ALTER TABLE TBL_MCSS_ATTRIBUTE ADD CONSTRAINT [CL_TBL_MCSS_ATTRIBUTE] PRIMARY KEY CLUSTERED(ATTRIBUTE_ID ASC)
	
	UPDATE TBL_MCSS_LOG
	SET ENDDATE = GETDATE()
	WHERE YYYYMMDD = CONVERT(VARCHAR(10), GETDATE(), 112) AND PATH = 'TBL_MCSS_ATTRIBUTE'
	------------------------------------------------------------------------------------------
	
	------------------------------------------------------------------------------------------
	-- 속성원 (ELOC)
	INSERT INTO TBL_MCSS_LOG(YYYYMMDD, PATH)
	SELECT CONVERT(VARCHAR(10), GETDATE(), 112), 'TBL_MCSS_ATTRIBUTE_ELEMENT'
	
	DROP TABLE TBL_MCSS_ATTRIBUTE_ELEMENT
	SELECT ATTRIBUTE_ID, ATTRIBUTE_ELEMENT_ID, ATTRIBUTE_ELEMENT, DISPLAY_ORDER, INS_DATE, UPD_DATE, DEL_YN, GETDATE() EXTRACT_DATE
	INTO TBL_MCSS_ATTRIBUTE_ELEMENT
	FROM GOODS_ATTRIBUTE_ELEMENT
	WHERE ATTRIBUTE_ID IN (SELECT ATTRIBUTE_ID FROM TBL_MCSS_ATTRIBUTE)
	OPTION (MAXDOP 1)
	
	ALTER TABLE TBL_MCSS_ATTRIBUTE_ELEMENT ADD CONSTRAINT [CL_TBL_MCSS_ATTRIBUTE_ELEMENT] PRIMARY KEY CLUSTERED(ATTRIBUTE_ID ASC, ATTRIBUTE_ELEMENT_ID ASC)
	
	UPDATE TBL_MCSS_LOG
	SET ENDDATE = GETDATE()
	WHERE YYYYMMDD = CONVERT(VARCHAR(10), GETDATE(), 112) AND PATH = 'TBL_MCSS_ATTRIBUTE_ELEMENT'
	------------------------------------------------------------------------------------------
	
	------------------------------------------------------------------------------------------
	-- 카테고리 속성 (ELOC)
	INSERT INTO TBL_MCSS_LOG(YYYYMMDD, PATH)
	SELECT CONVERT(VARCHAR(10), GETDATE(), 112), 'TBL_MCSS_ATTRIBUTE_CATEGORY'
	
	DROP TABLE TBL_MCSS_ATTRIBUTE_CATEGORY
	SELECT CATEGORY, ATTRIBUTE_ID, GETDATE() EXTRACT_DATE
	INTO TBL_MCSS_ATTRIBUTE_CATEGORY
	FROM GOODS_CATEGORY_ATTRIBUTE
	WHERE CATEGORY IN (SELECT CATEGORY FROM TBL_MCSS_CATEGORY)
	  AND ATTRIBUTE_ID IN (SELECT ATTRIBUTE_ID FROM TBL_MCSS_ATTRIBUTE)
	OPTION (MAXDOP 1)
	
	ALTER TABLE TBL_MCSS_ATTRIBUTE_CATEGORY ADD CONSTRAINT [CL_TBL_MCSS_ATTRIBUTE_CATEGORY] PRIMARY KEY CLUSTERED(CATEGORY ASC, ATTRIBUTE_ID ASC)
	
	UPDATE TBL_MCSS_LOG
	SET ENDDATE = GETDATE()
	WHERE YYYYMMDD = CONVERT(VARCHAR(10), GETDATE(), 112) AND PATH = 'TBL_MCSS_ATTRIBUTE_CATEGORY'
	------------------------------------------------------------------------------------------
END
