/* *************************************************************************
 * NAME : dbo.UDP_MP_GOODS_ATTRIBUTE_ELEMENT_COPY
 * TYPE : PROCEDURE (SQL_STORED_PROCEDURE)
 * TIME : Create: 2016-06-15 17:58:58.447
 *        Modify: 2018-05-03 17:23:36.01
 *        Backup: 20180521_1737
 ************************************************************************* */


CREATE PROC [DBO].[UDP_MP_GOODS_ATTRIBUTE_ELEMENT_COPY]
	@ID INT,
	@ELEMENT_ID SMALLINT,
	@ATTRIBUTE_ID INT,
	@ATTRIBUTE_ELEMENT_ID SMALLINT,
	@SPECNO INT,
	@ICONNO INT,
	@MM_ID VARCHAR(20)
AS
BEGIN
	SET NOCOUNT ON;
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
	
	-- GOODS_ATTRIBUTE_ELEMENT
	UPDATE GOODS_ATTRIBUTE_ELEMENT
	SET DEL_YN = 'N', UPD_DATE = GETDATE(), UPD_OPRT = @MM_ID, INS_DATE = GETDATE(), SPECNO = @SPECNO, ICONNO = @ICONNO
	WHERE DEL_YN = 'Y' AND ATTRIBUTE_ID = @ATTRIBUTE_ID AND ATTRIBUTE_ELEMENT_ID = @ATTRIBUTE_ELEMENT_ID

    INSERT INTO GOODS_ATTRIBUTE_ELEMENT(ATTRIBUTE_ID, ATTRIBUTE_ELEMENT_ID, ATTRIBUTE_ELEMENT, DISPLAY_ORDER, DEL_YN, IS_DISPLAY, IS_BOLD, INS_DATE, INS_OPRT, SPECNO, ICONNO)
	SELECT @ATTRIBUTE_ID, @ATTRIBUTE_ELEMENT_ID, ATTRIBUTE_ELEMENT, DISPLAY_ORDER, 'N', IS_DISPLAY, IS_BOLD, GETDATE(), @MM_ID, @SPECNO, @ICONNO
	FROM GOODS_ATTRIBUTE_ELEMENT
	WHERE ATTRIBUTE_ID = @ID AND ATTRIBUTE_ELEMENT_ID = @ELEMENT_ID
	  AND NOT EXISTS (SELECT 1 FROM GOODS_ATTRIBUTE_ELEMENT WHERE ATTRIBUTE_ID = @ATTRIBUTE_ID AND ATTRIBUTE_ELEMENT_ID = @ATTRIBUTE_ELEMENT_ID)
END
