/* *************************************************************************
 * NAME : dbo.UDP_JOB_STATISTICS_ETC_MODELNO_LIST
 * TYPE : PROCEDURE (SQL_STORED_PROCEDURE)
 * TIME : Create: 2004-11-02 03:31:55.043
 *        Modify: 2018-05-03 17:23:35.253
 *        Backup: 20180521_1737
 ************************************************************************* */


/****** 개체: 저장 프로시저 dbo.UP_JOB_STATISTICS_ETC_MODELNO_LIST    스크립트 날짜: 2004-10-23 오전 11:11:53 ******/
/****** 개체: 저장 프로시저 dbo.UP_JOB_STATISTICS_ETC_MODELNO_LIST    스크립트 날짜: 2004-09-17 오후 1:02:33 ******/
/****** 개체: 저장 프로시저 dbo.UP_JOB_STATISTICS_ETC_MODELNO_LIST    스크립트 날짜: 2004-06-24 오전 8:44:19 ******/

CREATE     PROC UDP_JOB_STATISTICS_ETC_MODELNO_LIST
	@LCATE VARCHAR(8)
AS
BEGIN
	SET NOCOUNT ON
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
	
	IF @LCATE='' 
	BEGIN
		SELECT *
		FROM LOGDB..JOB_STATISTICS_ETC_MODELNO WITH (READUNCOMMITTED)
		WHERE JSEM_DATE > CONVERT(VARCHAR(8), DATEADD(D,-30,GETDATE()),112)  
		ORDER BY JSEM_DATE DESC, JSEM_CATE ASC
	END

	ELSE
	BEGIN
		SELECT *
		FROM LOGDB..JOB_STATISTICS_ETC_MODELNO WITH (READUNCOMMITTED)
		WHERE JSEM_DATE > CONVERT(VARCHAR(8), DATEADD(D,-30,GETDATE()),112)  
			AND JSEM_CATE=@LCATE
		ORDER BY JSEM_DATE DESC, JSEM_CATE ASC
	END

END


