/* *************************************************************************
 * NAME : dbo.USP_PRICELIST_SEL_9
 * TYPE : PROCEDURE (SQL_STORED_PROCEDURE)
 * TIME : Create: 2007-03-26 17:50:02.747
 *        Modify: 2018-05-03 17:23:35.833
 *        Backup: 20180521_1737
 ************************************************************************* */

CREATE PROC [dbo].[USP_PRICELIST_SEL_9]
	@PL_VCODE INT,
	@PL_URL VARCHAR(500)
AS
BEGIN
	SET NOCOUNT ON
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
	DECLARE @URL VARCHAR(500)
	SET @URL=@PL_URL
	SELECT PL_MODELNO, PL_PRICE, PL_ESSTOCKFLAG, PL_CATEGORY, PL_SRVFLAG, PL_AIRCONFEETYPE
	FROM PRICELIST --WITH (INDEX(NCL_PRICELIST_4)) 
	WHERE PL_VCODE = @PL_VCODE
		AND PL_URL_CS = CHECKSUM(@URL) 
		AND PL_URL = @URL
		AND PL_MODELNO > 0 
		AND PL_SRVFLAG = '0'
		AND PL_GOODSNM > '' 
		--AND PL_STATUS < '3'
		OPTION (MAXDOP 1)
END




