/* *************************************************************************
 * NAME : dbo.UDP_GOODS_INIT
 * TYPE : PROCEDURE (SQL_STORED_PROCEDURE)
 * TIME : Create: 2018-01-17 14:51:53.247
 *        Modify: 2018-05-16 11:01:02.06
 *        Backup: 20180521_1737
 ************************************************************************* */


CREATE PROC [DBO].[UDP_GOODS_INIT]
	@MODELNO INT,
	@MM_ID VARCHAR(15)
AS
BEGIN
	-- ELOC & ORACLE 모두 처리
	
	SET NOCOUNT ON;
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
	
	IF @MM_ID = '' SET @MM_ID = 'Lab_batch'
	
	DECLARE @QRY VARCHAR(4000)
	
	-- 분산큐(GOODS)
	INSERT INTO?TB_MODEL_CHG_HST(MODEL_NO, PGM_ID, DAT_CHG_DCD, FRW_YN, ORGN_DTM)
????VALUES (@MODELNO, 'db_proc', 'U', 'N', GETDATE())
	
	SET TRANSACTION ISOLATION LEVEL READ COMMITTED;
	-- 개봉상품 - 원분류는 미서비스로 업데이트, 추가분류는 삭제
	SET @QRY = '
		--IF EXISTS(SELECT /* UDP_GOODS_INIT:01 */ MODELNO FROM OPENQUERY(ORADB, ''SELECT /* UDP_GOODS_INIT:01 */ MODELNO FROM TBL_RESELL WHERE MODELNO = ' + CAST(@MODELNO AS VARCHAR(20)) + '''))
		--BEGIN
		--	DELETE /* UDP_GOODS_INIT:02 */ FROM OPENQUERY(ORADB, ''SELECT /* UDP_GOODS_INIT:02 */ MODELNO, CATEFLAG FROM TBL_CATE_GOODS WHERE CATEFLAG <> ''''0'''' AND MODELNO = ' + CAST(@MODELNO AS VARCHAR(20)) + ''');
		--	UPDATE /* UDP_GOODS_INIT:03 */ OPENQUERY(ORADB, ''SELECT /* UDP_GOODS_INIT:03 */ MODELNO, JOBCODE FROM TBL_GOODS WHERE MODELNO = ' + CAST(@MODELNO AS VARCHAR(20)) + ''') SET JOBCODE = ''0'';
		--END
		--ELSE
		--BEGIN
		--	DELETE /* UDP_GOODS_INIT:04 */ FROM OPENQUERY(ORADB, ''SELECT /* UDP_GOODS_INIT:04 */ MODELNO, CATEFLAG FROM TBL_CATE_GOODS WHERE MODELNO = ' + CAST(@MODELNO AS VARCHAR(20)) + ''');
		--	DELETE /* UDP_GOODS_INIT:05 */ FROM OPENQUERY(ORADB, ''SELECT /* UDP_GOODS_INIT:05 */ MODELNO FROM TBL_GOODS WHERE MODELNO = ' + CAST(@MODELNO AS VARCHAR(20)) + ''');
		--END
		--DELETE /* UDP_GOODS_INIT:06 */ FROM OPENQUERY(ORADB, ''SELECT /* UDP_GOODS_INIT:06 */ MODELNO FROM TBL_GOODS_SUM WHERE MODELNO = ' + CAST(@MODELNO AS VARCHAR(20)) + ''');
		DELETE /* UDP_GOODS_INIT:07 */ FROM OPENQUERY(ORADB, ''SELECT /* UDP_GOODS_INIT:07 */ MODELNO FROM TBL_GOODS_CHANGE WHERE MODELNO = ' + CAST(@MODELNO AS VARCHAR(20)) + ''');
	'
	EXEC (@QRY)
	
	-- EP 삭제
	--SET @QRY = 'DELETE /* UDP_GOODS_INIT:08 */ FROM OPENQUERY(ORADB, ''SELECT /* UDP_GOODS_INIT:08 */ MODELNO FROM TBL_PRICELIST WHERE MODELNO = ' + CAST(@MODELNO AS VARCHAR(20)) + ''')'
	--EXEC (@QRY)
	
	-- 관련사이트 삭제
	SET @QRY = 'DELETE /* UDP_GOODS_INIT:09 */ FROM OPENQUERY(ORADB, ''SELECT /* UDP_GOODS_INIT:09 */ MODELNO FROM TBL_GOODS_RELATE WHERE MODELNO = ' + CAST(@MODELNO AS VARCHAR(20)) + ''')'
	EXEC (@QRY)
	
	-- 소모품 삭제
	SET @QRY = 'DELETE /* UDP_GOODS_INIT:10 */ FROM OPENQUERY(ORADB, ''SELECT /* UDP_GOODS_INIT:10 */ MODELNO FROM TBL_GOODS_SUPPLY WHERE MODELNO = ' + CAST(@MODELNO AS VARCHAR(20)) + ' OR SU_MODELNO = ' + CAST(@MODELNO AS VARCHAR(20)) + ''')'
	EXEC (@QRY)
	
	-- 성분 삭제
	SET @QRY = 'DELETE /* UDP_GOODS_INIT:11 */ FROM OPENQUERY(ORADB, ''SELECT /* UDP_GOODS_INIT:11 */ MODELNO FROM TBL_GOODS_COMPONENT WHERE MODELNO = ' + CAST(@MODELNO AS VARCHAR(20)) + ''')'
	EXEC (@QRY)
	SET @QRY = 'DELETE /* UDP_GOODS_INIT:12 */ FROM OPENQUERY(ORADB, ''SELECT /* UDP_GOODS_INIT:12 */ MODELNO FROM TBL_COMPONENT_MODELNO_ORIGINAL WHERE MODELNO = ' + CAST(@MODELNO AS VARCHAR(20)) + ''')'
	EXEC (@QRY)
	SET @QRY = 'DELETE /* UDP_GOODS_INIT:13 */ FROM OPENQUERY(ORADB, ''SELECT /* UDP_GOODS_INIT:13 */ MODELNO FROM TBL_COMPONENT_MODELNO WHERE MODELNO = ' + CAST(@MODELNO AS VARCHAR(20)) + ''')'
	EXEC (@QRY)
	SET @QRY = 'DELETE /* UDP_GOODS_INIT:14 */ FROM OPENQUERY(ORADB, ''SELECT /* UDP_GOODS_INIT:14 */ MODELNO FROM TBL_COMPONENT_SUMMARY WHERE MODELNO = ' + CAST(@MODELNO AS VARCHAR(20)) + ''')'
	EXEC (@QRY)
	
	-- 모바일 Template 삭제
	SET @QRY = 'DELETE /* UDP_GOODS_INIT:15 */ FROM OPENQUERY(ORADB, ''SELECT /* UDP_GOODS_INIT:15 */ MODELNO FROM TBL_GOODS_SPEC_DETAIL WHERE MODELNO = ' + CAST(@MODELNO AS VARCHAR(20)) + ''')'
	EXEC (@QRY)
	
	-- 속성 사양선택 삭제
	SET @QRY = 'DELETE /* UDP_GOODS_INIT:16 */ FROM OPENQUERY(ORADB, ''SELECT /* UDP_GOODS_INIT:16 */ MODELNO FROM TBL_MODELNO_SPEC WHERE MODELNO = ' + CAST(@MODELNO AS VARCHAR(20)) + ''')'
	EXEC (@QRY)
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
	
	-- 그룹툴 초기화
	UPDATE /* UDP_GOODS_INIT:17 */ GOODS
	SET G_FLAG = '1', G_MODELNO_GROUP = NULL, G_CONDITION_NUMBER = NULL, G_GROUP_ATTRIBUTE_ID = NULL, G_GROUP_FLAG = NULL
	WHERE G_MODELNO_GROUP = @MODELNO
	
	-- 속성 초기화
	UPDATE /* UDP_GOODS_INIT:18 */ GOODS_CATALOG_ATTRIBUTE
	SET DEL_YN = 'Y', UPD_DATE = GETDATE(), UPD_OPRT = @MM_ID
	WHERE DEL_YN = 'N' AND G_MODELNO = @MODELNO
	
	-- 삭제처리 로그
	INSERT /* UDP_GOODS_INIT:19 */ INTO GOODS_DELETE_MODELNO (G_MODELNO, G_MODELNM, G_FACTORY, G_CATEGORY, MM_ID)
	SELECT G_MODELNO, G_MODELNM, G_FACTORY, G_CATEGORY, @MM_ID
	FROM GOODS
	WHERE G_MODELNO = @MODELNO AND NOT EXISTS(SELECT TOP 1 1 FROM GOODS_DELETE_MODELNO WHERE G_MODELNO = @MODELNO)
	
	-- 카탈로그 초기화
	UPDATE /* UDP_GOODS_INIT:20 */ GOODS
	SET G_MODELNM = '모델삭제'
	  , G_CATEGORY = '00000000'
	  , G_FACTORY = ''
	  , G_IMGCHK = '4'
	  , G_CONSTRAIN = '1'
	  , G_FLAG = '0'
	  , G_REFID = 0
	  , G_JOBCODE = '0'
	  , G_PARTCODE = '0'
	  , G_WORK = '0'
	  , G_REFSHOP = '0'
	  , G_NOTICE = ''
	  , G_KEYWORD = ''
	  , G_MANUAL_LINK = ''
	  , G_LINKSERVICEFLAG = '1'
	  , G_SIZE = ''
	  , G_FUNC = NULL
	  , G_WEBCNT = 0
	  , G_ORWEBKEYWORD = NULL
	  , G_FACTORY_ETC = ''
	  , G_BRAND = ''
	  , G_FUNC_IMG = ''
	  , G_FUNC_IMG_FLAG = '0'
	  , G_KEYWORD2 = NULL
	  , G_WEIGHT = NULL
	  , G_IMGCHK_ROLLING = '0'
	  , G_ECATALOG_FLAG = NULL
	  , G_ECATALOG_URL = NULL
	  , G_MODELNO_GROUP = NULL
	  , G_CONDITION_NUMBER = NULL
	  , G_GROUP_FLAG = NULL
	  , G_STANDARD = NULL
	  , G_AMOUNT = NULL
	  , G_CHANGE = NULL
	  , G_U_NIT = NULL
	  , G_GROUP_ATTRIBUTE_ID = NULL
	  , BRAND_ID = NULL
	  , MAKER_ID = NULL
	  , G_SPEC2 = ''
	  , G_SPEC_DESCRIPTION = NULL
	  , G_ALL_COMPONENT = NULL
	WHERE G_MODELNO = @MODELNO
	
	-- 카탈로그 통계정보 삭제
	DELETE /* UDP_GOODS_INIT:21 */ FROM GOODS_SUM
	WHERE G_MODELNO = @MODELNO
	
	-- 작업로그
	INSERT /* UDP_GOODS_INIT:22 */ INTO LOGDB.DBO.JOB_GOODS (JG_MODELNO, JG_CATEGORY, JG_ID, JG_FLAG, JG_DATE)
	SELECT G_MODELNO, G_CATEGORY, @MM_ID, 'D', GETDATE()
	FROM GOODS
	WHERE G_MODELNO = @MODELNO AND EXISTS(SELECT TOP 1 1 FROM GOODS_DELETE_MODELNO WHERE G_MODELNO = @MODELNO AND REGDATE >= CONVERT(VARCHAR(10), GETDATE(), 120))
	
	-- 모델삭제로 모델명이 바뀐경우 지식글 --> 전반적인 글로 수정함 : SP 모델번호
	EXEC UDP_RPC_KB_CHANGE_MODELNO2GENERAL @MODELNO
	
	-- 추가분류 초기화
	DELETE /* UDP_GOODS_INIT:23 */ FROM GOODS_ADDCATE
	WHERE GA_MODELNO = @MODELNO
	
	-- EP 초기화
	CREATE TABLE #UPDATE_TARGET(PL_NO BIGINT, PL_MODELNO INT)
	UPDATE /* UDP_GOODS_INIT:24 */ PRICELIST
	SET PL_MODELNO = 0
	OUTPUT DELETED.PL_NO, INSERTED.PL_MODELNO INTO #UPDATE_TARGET
	WHERE PL_MODELNO = @MODELNO
	OPTION (MAXDOP 1)
	-- 분산큐(PRICELIST)
	INSERT INTO TB_PL_CHG_HST(PL_NO, MODEL_NO, PGM_ID, DAT_CHG_DCD, FRW_YN, ORGN_DTM)
	SELECT PL_NO, PL_MODELNO, 'db_proc', 'U', 'N', GETDATE()
	FROM #UPDATE_TARGET
	
	-- 소모품 초기화
	DELETE /* UDP_GOODS_INIT:25 */ FROM GOODS_PRTSUPPLY
    WHERE GPRT_MODELNO = @MODELNO OR GPRT_POINTMODELNO = @MODELNO
	
	-- 속성 사양선택 초기화
	DELETE /* UDP_GOODS_INIT:26 */ FROM TBL_MODELNO_SPEC
    WHERE MODELNO = @MODELNO
END
