/* *************************************************************************
 * NAME : dbo.UDF_RTN_CATE_NAME_NEW
 * TYPE : FUNCTION (SQL_SCALAR_FUNCTION)
 * TIME : Create: 2016-06-13 15:54:29.673
 *        Modify: 2018-05-03 17:23:34.053
 *        Backup: 20180521_1737
 ************************************************************************* */


CREATE FUNCTION [DBO].[UDF_RTN_CATE_NAME_NEW] (@CA_CODE VARCHAR(12))
RETURNS VARCHAR(500)
AS
BEGIN
	DECLARE @RETURN VARCHAR(500)
	DECLARE @DIVIDE_CHAR NVARCHAR(10)
	DECLARE @LNAME VARCHAR(120)
	DECLARE @MNAME VARCHAR(120)
	DECLARE @SNAME VARCHAR(120)
	DECLARE @DNAME VARCHAR(120)
	
	SET @RETURN = ''
	SET @DIVIDE_CHAR = ' > '
	SET @LNAME = ''
	SET @MNAME = ''
	SET @SNAME = ''
	SET @DNAME = ''

	SELECT @LNAME = LTRIM(RTRIM(CL_NAME)) FROM C_LCATE WHERE CL_LCODE = SUBSTRING(@CA_CODE, 1, 2)
	SELECT @MNAME = LTRIM(RTRIM(CM_NAME)) FROM C_MCATE WHERE CM_LCODE = SUBSTRING(@CA_CODE, 1, 2) AND CM_MCODE = SUBSTRING(@CA_CODE, 3, 2)
	SELECT @SNAME = LTRIM(RTRIM(CS_NAME)) FROM C_SCATE WHERE CS_LCODE = SUBSTRING(@CA_CODE, 1, 2) AND CS_MCODE = SUBSTRING(@CA_CODE, 3, 2) AND CS_SCODE = SUBSTRING(@CA_CODE, 5, 2)
	SELECT @DNAME = LTRIM(RTRIM(CD_NAME)) FROM C_DCATE WHERE CD_LCODE = SUBSTRING(@CA_CODE, 1, 2) AND CD_MCODE = SUBSTRING(@CA_CODE, 3, 2) AND CD_SCODE = SUBSTRING(@CA_CODE, 5, 2) AND CD_DCODE = SUBSTRING(@CA_CODE, 7, 2)

	IF @LNAME <> ''
		SET @RETURN = @RETURN + CASE WHEN @RETURN <> '' THEN @DIVIDE_CHAR ELSE '' END + @LNAME
	
	IF @MNAME <> ''
		SET @RETURN = @RETURN + CASE WHEN @RETURN <> '' THEN @DIVIDE_CHAR ELSE '' END + @MNAME
	
	IF @SNAME <> ''
		SET @RETURN = @RETURN + CASE WHEN @RETURN <> '' THEN @DIVIDE_CHAR ELSE '' END + @SNAME

	IF @DNAME <> ''
		SET @RETURN = @RETURN + CASE WHEN @RETURN <> '' THEN @DIVIDE_CHAR ELSE '' END + @DNAME

	RETURN @RETURN
END
