/* *************************************************************************
 * NAME : dbo.UDP_MP_GOODS_SUPPLY_SYNC
 * TYPE : PROCEDURE (SQL_STORED_PROCEDURE)
 * TIME : Create: 2015-06-05 17:59:31.51
 *        Modify: 2018-05-03 17:23:34.447
 *        Backup: 20180521_1737
 ************************************************************************* */


CREATE PROCEDURE [DBO].[UDP_MP_GOODS_SUPPLY_SYNC]
AS
BEGIN
	-- GPRT_MODELNO = MODELNO,  GPRT_POINTMODELNO = SU_MODELNO

	SET NOCOUNT ON;
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

	SELECT SU_NO NO, MODELNO, SU_MODELNO POINTMODELNO
	INTO #ORA_SUPPLY
	FROM OPENQUERY(ORADB, 'SELECT DISTINCT SU_NO, MODELNO, SU_MODELNO FROM TBL_GOODS_SUPPLY')
	

	SET TRANSACTION ISOLATION LEVEL READ COMMITTED;
	--##################################################################
	-- 오라클 추가
	INSERT OPENQUERY(ORADB, 'SELECT SU_MODELNO, MODELNO, SU_NO, SU_FLAG FROM TBL_GOODS_SUPPLY')
	SELECT GPRT_POINTMODELNO, GPRT_MODELNO, (SELECT ISNULL(MAX(NO), 0) FROM #ORA_SUPPLY) + (ROW_NUMBER() OVER(ORDER BY GPRT_NO)), GPRT_FLAG
	FROM GOODS_PRTSUPPLY WITH (READUNCOMMITTED)
		LEFT JOIN #ORA_SUPPLY ON GPRT_MODELNO = MODELNO AND GPRT_POINTMODELNO = POINTMODELNO
	WHERE MODELNO IS NULL
	
	-- 오라클 삭제
	DELETE OPENQUERY(ORADB, 'SELECT SU_NO FROM TBL_GOODS_SUPPLY')
	WHERE SU_NO IN (
		SELECT NO
		FROM #ORA_SUPPLY
			LEFT JOIN GOODS_PRTSUPPLY WITH (READUNCOMMITTED) ON GPRT_MODELNO = MODELNO AND GPRT_POINTMODELNO = POINTMODELNO
		WHERE GPRT_MODELNO IS NULL
	)
	--##################################################################
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
END
