/* *************************************************************************
 * NAME : dbo.USP_PRICELIST_SEL_5
 * TYPE : PROCEDURE (SQL_STORED_PROCEDURE)
 * TIME : Create: 2007-03-26 17:40:19.283
 *        Modify: 2015-05-15 03:31:34.023
 *        Backup: 20180521_1737
 ************************************************************************* */


CREATE PROC USP_PRICELIST_SEL_5
	@PL_VCODE INT	
AS
BEGIN
	SET NOCOUNT ON
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

	SELECT PL_NO, ISNULL(PL_MODELNO, 0) AS PL_MODELNO, PL_VCODE, ISNULL(PL_CATEGORY, '00') AS PL_CATEGORY, ISNULL(PL_GOODSNM, '') AS PL_GOODSNM, 
		ISNULL(PL_PRICE, 0) AS PL_PRICE, ISNULL(PL_URL, '') AS PL_URL, ISNULL(PL_NOTE, '') AS PL_NOTE, PL_SRVFLAG, PL_STATUS,
		ISNULL(PL_ETC,'') AS PL_ETC, ISNULL(PL_AUTHFLAG, '0') AS PL_AUTHFLAG, PL_AUTHDATE, ISNULL(PL_RIGHTNLEFT, '0') AS PL_RIGHTNLEFT, ISNULL(PL_IMGURL, '') AS PL_IMGURL,
	    ISNULL(PL_COUPON, 0) AS PL_COUPON, IsNull(PL_DELFEETYPE,'') as PL_DELFEETYPE, IsNull(PL_DELPRICE,0) as PL_DELPRICE, IsNull(PL_DELIVERYFLAG ,'0') as PL_DELIVERYFLAG, PL_DELFEEDESC,
		PL_DELAREADESC, PL_ACCOUNT_YN, ISNULL(PL_INSTANCE_PRICE, 0) AS PL_INSTANCE_PRICE, ISNULL(PL_ESSTOCKFLAG, '0') AS PL_ESSTOCKFLAG,
		PL_GOODSFACTORY, PL_GOODSCODE 
	FROM PRICELIST 
	WHERE PL_VCODE= @PL_VCODE 
		AND PL_MODELNO > 0 
		AND PL_GOODSNM = '' 
		AND PL_GOODSNM_CS = CHECKSUM('') 
		AND PL_STATUS < '3' 
END