/* *************************************************************************
 * NAME : dbo.UDP_MP_GOODS_SPECNO_SYNC
 * TYPE : PROCEDURE (SQL_STORED_PROCEDURE)
 * TIME : Create: 2015-06-05 18:07:25.15
 *        Modify: 2018-05-03 17:23:35.39
 *        Backup: 20180521_1737
 ************************************************************************* */


CREATE PROCEDURE [DBO].[UDP_MP_GOODS_SPECNO_SYNC]
AS
BEGIN
	SET NOCOUNT ON;
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

	SELECT MODELNO, SPECNO
	INTO #ORA_SPEC
	FROM OPENQUERY(ORADB, 'SELECT DISTINCT MODELNO, SPECNO FROM TBL_MODELNO_SPEC')
	

	SET TRANSACTION ISOLATION LEVEL READ COMMITTED;
	--##################################################################
	-- 오라클 추가
	INSERT OPENQUERY(ORADB, 'SELECT MODELNO, SPECNO FROM TBL_MODELNO_SPEC')
	SELECT A.MODELNO, A.SPECNO
	FROM TBL_MODELNO_SPEC A WITH (READUNCOMMITTED)
		LEFT JOIN #ORA_SPEC B ON A.MODELNO = B.MODELNO AND A.SPECNO = B.SPECNO
	WHERE B.MODELNO IS NULL
	
	-- 오라클 삭제
	DELETE OPENQUERY(ORADB, 'SELECT MODELNO, SPECNO FROM TBL_MODELNO_SPEC')
	WHERE CAST(MODELNO AS VARCHAR(8)) + '-' + CAST(SPECNO AS VARCHAR(8)) IN (
		SELECT CAST(A.MODELNO AS VARCHAR(8)) + '-' + CAST(A.SPECNO AS VARCHAR(8))
		FROM #ORA_SPEC A
			LEFT JOIN TBL_MODELNO_SPEC B WITH (READUNCOMMITTED) ON A.MODELNO = B.MODELNO AND A.SPECNO = B.SPECNO
		WHERE B.MODELNO IS NULL
	)
	--##################################################################
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
END
