/* *************************************************************************
 * NAME : dbo.UDP_P_SHPDRY_CATE_INQR
 * TYPE : PROCEDURE (SQL_STORED_PROCEDURE)
 * TIME : Create: 2017-08-01 10:09:21.397
 *        Modify: 2017-08-01 10:09:21.397
 *        Backup: 20180521_1737
 ************************************************************************* */


CREATE PROCEDURE [dbo].[UDP_P_SHPDRY_CATE_INQR]	-- UDP_P_쇼핑다이어리카테고리문의
		 @SMTD_SHPML_CD INT						-- 스마트택배쇼핑몰코드
		 ,@SHPML_GOODS_CD VARCHAR(50)			-- 쇼핑몰상품코드	
		 ,@SHPML_GOODS_NM VARCHAR(200)			-- 쇼핑몰상품명
		 ,@LCATE_CD VARCHAR(2) OUTPUT			-- 대분류코드
		 ,@LCATE_NM VARCHAR(100) OUTPUT			-- 대분류명
		 ,@ENR_MODEL_NO INT OUTPUT				-- 에누리모델번호
		 ,@EXEC_RSLT_CD		INT	OUTPUT			-- 실행결과코드(0:정상)
		 ,@EXEC_RSLT_MSG_SBST	VARCHAR(500) OUTPUT	-- 실행결과메시지내용
		 ,@MCATE_CD VARCHAR(2) = NULL OUTPUT 			-- 중분류코드
		 ,@MCATE_NM VARCHAR(100)= NULL OUTPUT 			-- 중분류명
AS
BEGIN
	SET NOCOUNT ON
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
BEGIN TRY
	---------------------------------------------------------------------------------
	-- 0. 변수 및 초기값
    ---------------------------------------------------------------------------------
	DECLARE @ENR_SHPML_CD INT
	SET @ENR_SHPML_CD = NULL

	SET @LCATE_CD = NULL
	SET @LCATE_NM	= NULL	
	SET @MCATE_CD = NULL
	SET @MCATE_NM	= NULL
	SET @ENR_MODEL_NO	= -991
	SET @EXEC_RSLT_CD			= 0 -- 정상
	SET @EXEC_RSLT_MSG_SBST		= ''

	---------------------------------------------------------------------------------
	-- 1. 에누리 쇼핑몰 코드
    --------------------------------------------------------------------------------- 
	SELECT @ENR_SHPML_CD = ENR_SHPML_CD
	FROM ELOC2001.dbo.G_SMTD_ENR_SHPML_REL --20160705 ANALSDW -> ELOC2001
	WHERE SMTD_SHPML_CD = @SMTD_SHPML_CD
		AND USE_YN = 'Y' 
		AND REP_YN = 'Y'
	OPTION (MAXDOP 1)

	IF (@ENR_SHPML_CD IS NULL)
	BEGIN
		SET @EXEC_RSLT_CD			= 200
		SET @EXEC_RSLT_MSG_SBST		= 'can not find shopping mall code.'
	RETURN
	END

	---------------------------------------------------------------------------------
	-- 2. 에누리 모델번호 
    --------------------------------------------------------------------------------- 
	--IF(@SMTD_SHPML_CD <>12 OR (@SMTD_SHPML_CD = 12 AND LEN(@SHPML_GOODS_CD)>6)) -- 위메프가 아니거나 위메프 상품중 상품코드가 6자리 이상인것
	IF(@SMTD_SHPML_CD <>11 AND @SMTD_SHPML_CD <>12 ) -- 위메프와 티몬은 별도로 매칭(딜코드기준) 16.1.20
	BEGIN 
		SELECT @ENR_MODEL_NO = PL_MODELNO
			, @LCATE_CD = LCATE_CD
			, @MCATE_CD = MCATE_CD
		FROM
			(SELECT PL_MODELNO, LEFT(PL_CATEGORY,2) AS LCATE_CD , SUBSTRING(PL_CATEGORY,3,2) AS MCATE_CD
				, ROW_NUMBER()  OVER(PARTITION BY T101.PL_VCODE , T101.PL_GOODSCODE
										ORDER BY CASE WHEN T101.PL_MODELNO>0 THEN 1 ELSE 0 END DESC				-- 1)가격비교상품여부
											, CASE WHEN T101.PL_NO = T101.PL_COPYPLNO THEN 1  ELSE 0 END DESC	-- 2)대표상품여부 
											, T101.PL_MODELNO DESC, T101.PL_NO DESC) AS RANK					-- 3)모델번호, PL_NO 큰것
			FROM ELOC2001.DBO.PRICELIST T101 with(readuncommitted)
			WHERE T101.PL_VCODE = @ENR_SHPML_CD
				AND T101.PL_GOODSCODE = @SHPML_GOODS_CD
				AND T101.PL_GOODSCODE_CS =  CHECKSUM(@SHPML_GOODS_CD)
				AND T101.PL_GOODSNM<>''
			) T201
		WHERE T201.RANK = 1
		OPTION (MAXDOP 1)

		IF(@ENR_MODEL_NO = -991) -- CURRENT PRICELIST에 없는 경우 과거데이터에서 매칭 
		BEGIN
				SELECT @ENR_MODEL_NO = PL_MODELNO
					, @LCATE_CD = LCATE_CD
					, @MCATE_CD = MCATE_CD
				FROM
					(SELECT PL_MODELNO, LEFT(PL_CATEGORY,2) AS LCATE_CD, SUBSTRING(PL_CATEGORY,3,2) AS MCATE_CD
						, ROW_NUMBER()  OVER(PARTITION BY T101.PL_VCODE , T101.PL_GOODSCODE
												ORDER BY CASE WHEN T101.PL_MODELNO>0 THEN 1 ELSE 0 END DESC				-- 1)가격비교상품여부
													, CASE WHEN T101.PL_NO = T101.PL_COPYPLNO THEN 1  ELSE 0 END DESC	-- 2)대표상품여부 
													, T101.PL_MODELNO DESC, T101.PL_NO DESC) AS RANK					-- 3)모델번호, PL_NO 큰것
					FROM -- ELOC2001.DBO.PRICELIST_DEL_DATA -- 20151214
						eloc2001.dbo.vw_pricelist_del_data	T101 with(readuncommitted)
					WHERE T101.PL_VCODE = @ENR_SHPML_CD
						AND T101.PL_GOODSCODE = @SHPML_GOODS_CD
						AND T101.PL_GOODSCODE_CS =  CHECKSUM(@SHPML_GOODS_CD)
						AND T101.PL_GOODSNM<>''
					) T201
				WHERE T201.RANK = 1		
				OPTION (MAXDOP 1)	
		END
	END
	---------------------------------------------------------------------------------
	-- 2.1 위메프 티몬 매칭 16.1.20
    --------------------------------------------------------------------------------- 
	ELSE
	BEGIN
		/*
		2017.7.4 속도개선으로 위메프와 티몬은 과거 데이터 조회 안함
		SELECT @ENR_MODEL_NO = PL_MODELNO
			, @LCATE_CD = LCATE_CD
			, @MCATE_CD = MCATE_CD
		FROM
			(
			SELECT ISNULL(T103.PL_MODELNO, T104.PL_MODELNO)AS PL_MODELNO
					, LEFT(ISNULL(T103.PL_CATEGORY,T104.PL_CATEGORY),2) AS LCATE_CD
					, SUBSTRING(ISNULL(T103.PL_CATEGORY,T104.PL_CATEGORY),3,2) AS MCATE_CD
					, ROW_NUMBER()  OVER(PARTITION BY T102.PL_VCODE , T102.PL_URL_GOODSCODE
										ORDER BY 
											-- 1) 옵션명과 상품명 비교
												-- 옵션명칭은 없어서 제외				
											-- 2) 가격차이가 가장 적은것(티몬은 가격이 부정확하므로 제외)
												-- 가격도 없어서 제외
											 CASE WHEN ISNULL(T103.PL_MODELNO,T104.PL_MODELNO) >0 THEN 1 ELSE 0 END DESC				-- 3)가격비교상품여부
											, ISNULL(T105.G_POPULAR,0) DESC										-- 4)인기도
											, CASE WHEN ISNULL(T103.PL_MODELNO,T104.PL_MODELNO) = ISNULL(T103.PL_COPYPLNO, T104.PL_COPYPLNO) THEN 1  ELSE 0 END DESC	-- 5)대표상품여부 
											, ISNULL(T103.PL_MODELNO,T104.PL_MODELNO) DESC, ISNULL(T103.PL_NO,T104.PL_NO) DESC) AS RANK					-- 6)모델번호, PL_NO 큰것

			FROM ELOC2001.DBO.PRICELIST_MAKE_GOODSCODE T102 with(readuncommitted)
				LEFT OUTER JOIN ELOC2001.DBO.PRICELIST T103 with(readuncommitted) ON T102.PL_NO = T103.PL_NO
				LEFT OUTER JOIN analsdw.DBO.vw_pricelist_del_data T104 with(readuncommitted) ON T102.PL_NO = T104.PL_NO
				LEFT OUTER JOIN ELOC2001.DBO.GOODS T105 with(readuncommitted) ON ISNULL(T103.PL_MODELNO, T104.PL_MODELNO) = T105.G_MODELNO AND ISNULL(T103.PL_MODELNO, T104.PL_MODELNO)>0 --^^
			WHERE T102.PL_VCODE =@ENR_SHPML_CD
				AND T102.PL_URL_GOODSCODE = @SHPML_GOODS_CD
				AND T102.PL_URL_GOODSCODE_CS = CHECKSUM(@SHPML_GOODS_CD ) -- 2017.7.4 속도개선

		) T201
		WHERE T201.RANK = 1
		OPTION (MAXDOP 1)
		*/

		SELECT @ENR_MODEL_NO = PL_MODELNO
			, @LCATE_CD = LCATE_CD
			, @MCATE_CD = MCATE_CD
		FROM
			(
			SELECT T103.PL_MODELNO AS PL_MODELNO
					, LEFT(T103.PL_CATEGORY,2) AS LCATE_CD
					, SUBSTRING(T103.PL_CATEGORY,3,2) AS MCATE_CD
					, ROW_NUMBER()  OVER(PARTITION BY T102.PL_VCODE , T102.PL_URL_GOODSCODE
										ORDER BY 
											-- 1) 옵션명과 상품명 비교
												-- 옵션명칭은 없어서 제외				
											-- 2) 가격차이가 가장 적은것(티몬은 가격이 부정확하므로 제외)
												-- 가격도 없어서 제외
											 CASE WHEN T103.PL_MODELNO >0 THEN 1 ELSE 0 END DESC				-- 3)가격비교상품여부
											--, ISNULL(T105.G_POPULAR,0) DESC										-- 4)인기도
											--, CASE WHEN T103.PL_MODELNO = T103.PL_COPYPLNO THEN 1  ELSE 0 END DESC	-- 5)대표상품여부 
											, T103.PL_MODELNO DESC, T103.PL_NO DESC) AS RANK					-- 6)모델번호, PL_NO 큰것

			FROM ELOC2001.DBO.PRICELIST_MAKE_GOODSCODE T102 with(readuncommitted)
				LEFT OUTER JOIN ELOC2001.DBO.PRICELIST T103 with(readuncommitted) ON T102.PL_NO = T103.PL_NO
				
				--LEFT OUTER JOIN ELOC2001.DBO.GOODS T105 with(readuncommitted) ON T103.PL_MODELNO = T105.G_MODELNO AND T103.PL_MODELNO>0 --^^
			WHERE T102.PL_VCODE =@ENR_SHPML_CD
				AND T102.PL_URL_GOODSCODE = @SHPML_GOODS_CD
				AND T102.PL_URL_GOODSCODE_CS = CHECKSUM(@SHPML_GOODS_CD ) -- 2017.7.4 속도개선

		     ) T201
		WHERE T201.RANK = 1
		OPTION (MAXDOP 1)

	END 
	---------------------------------------------------------------------------------
	-- 3. 가격비교상품인 경우 카테고리
    --------------------------------------------------------------------------------- 
	IF(@ENR_MODEL_NO>0)
	BEGIN

		SELECT @LCATE_CD = LEFT(G_CATEGORY,2) , @MCATE_CD = SUBSTRING(G_CATEGORY,3,2)
		FROM ELOC2001.DBO.GOODS T101 with(readuncommitted)
		WHERE T101.G_MODELNO = @ENR_MODEL_NO
		OPTION (MAXDOP 1)
	END
	---------------------------------------------------------------------------------
	-- 4. 카테고리명
    --------------------------------------------------------------------------------- 
	SELECT @LCATE_NM= T102.CL_NAME
		, @MCATE_NM = T101.CM_NAME
	FROM ELOC2001.DBO.C_MCATE T101 with(readuncommitted)
		LEFT OUTER JOIN ELOC2001.DBO.C_LCATE T102 with(readuncommitted)
			 ON T101.CM_LCODE = T102.CL_LCODE
	WHERE T101.CM_LCODE = @LCATE_CD
		AND T101.CM_MCODE =  @MCATE_CD
	OPTION (MAXDOP 1)

END TRY
BEGIN CATCH

	SET @EXEC_RSLT_CD			= ERROR_NUMBER()
	SET @EXEC_RSLT_MSG_SBST		= ERROR_MESSAGE()

END CATCH

END

/*

[UDP_P_SHPDRY_CATE_INQR]

USE ANALSDW

-- INPUT
DECLARE @SMTD_SHPML_CD INT				-- 스마트택배쇼핑몰코드
DECLARE @SHPML_GOODS_CD VARCHAR(50)		-- 쇼핑몰상품코드	
DECLARE @SHPML_GOODS_NM VARCHAR(200)	-- 쇼핑몰상품명

-- OUTPUT
DECLARE @LCATE_CD VARCHAR(2)			-- 대분류코드
DECLARE @LCATE_NM VARCHAR(100)			-- 대분류명
DECLARE @MCATE_CD VARCHAR(2)			-- 대분류코드
DECLARE @MCATE_NM VARCHAR(100)			-- 대분류명

DECLARE @ENR_MODEL_NO INT				-- 에누리모델번호
DECLARE @EXEC_RSLT_CD		INT			-- 실행결과코드(0:정상)
DECLARE @EXEC_RSLT_MSG_SBST	VARCHAR(500) -- 실행결과메시지내용


SET @SMTD_SHPML_CD = 12
SET @SHPML_GOODS_CD = '671008'
SET @SHPML_GOODS_NM = NULL

SET @LCATE_CD = NULL
SET @LCATE_NM = NULL
SET @ENR_MODEL_NO = NULL
SET @EXEC_RSLT_CD = NULL
SET @EXEC_RSLT_MSG_SBST = NULL

EXEC UDP_P_SHPDRY_CATE_INQR @SMTD_SHPML_CD, @SHPML_GOODS_CD, @SHPML_GOODS_NM, @LCATE_CD OUTPUT, @LCATE_NM OUTPUT, @ENR_MODEL_NO OUTPUT, @EXEC_RSLT_CD OUTPUT, @EXEC_RSLT_MSG_SBST OUTPUT--, @MCATE_CD OUTPUT, @MCATE_NM OUTPUT
SELECT @LCATE_CD,@LCATE_NM, @ENR_MODEL_NO, @EXEC_RSLT_CD, @EXEC_RSLT_MSG_SBST--, @MCATE_CD, @MCATE_NM


EXEC UDP_P_SHPDRY_CATE_INQR @SMTD_SHPML_CD, @SHPML_GOODS_CD, @SHPML_GOODS_NM, @LCATE_CD OUTPUT, @LCATE_NM OUTPUT, @ENR_MODEL_NO OUTPUT, @EXEC_RSLT_CD OUTPUT, @EXEC_RSLT_MSG_SBST OUTPUT, @MCATE_CD OUTPUT, @MCATE_NM OUTPUT
SELECT @LCATE_CD,@LCATE_NM, @ENR_MODEL_NO, @EXEC_RSLT_CD, @EXEC_RSLT_MSG_SBST, @MCATE_CD, @MCATE_NM

SET @LCATE_CD = NULL
SET @LCATE_NM = NULL
SET @ENR_MODEL_NO = NULL

EXEC UDP_P_SHPDRY_CATE_INQR 2, '104778179', NULL, @LCATE_CD OUTPUT, @LCATE_NM OUTPUT, @ENR_MODEL_NO OUTPUT, @EXEC_RSLT_CD OUTPUT, @EXEC_RSLT_MSG_SBST OUTPUT, @MCATE_CD OUTPUT, @MCATE_NM OUTPUT
SELECT @LCATE_CD,@LCATE_NM, @ENR_MODEL_NO, @EXEC_RSLT_CD, @EXEC_RSLT_MSG_SBST, @MCATE_CD, @MCATE_NM

--------

EXEC UDP_P_SHPDRY_CATE_INQR 2, '104778179', NULL, @LCATE_CD OUTPUT, @LCATE_NM OUTPUT, @ENR_MODEL_NO OUTPUT, @EXEC_RSLT_CD OUTPUT, @EXEC_RSLT_MSG_SBST OUTPUT
SELECT @LCATE_CD,@LCATE_NM, @ENR_MODEL_NO, @EXEC_RSLT_CD, @EXEC_RSLT_MSG_SBST

SET @LCATE_CD = NULL
SET @LCATE_NM = NULL
SET @ENR_MODEL_NO = NULL
EXEC UDP_P_SHPDRY_CATE_INQR 2, '999', NULL, @LCATE_CD OUTPUT, @LCATE_NM OUTPUT, @ENR_MODEL_NO OUTPUT, @EXEC_RSLT_CD OUTPUT, @EXEC_RSLT_MSG_SBST OUTPUT
SELECT @LCATE_CD,@LCATE_NM, @ENR_MODEL_NO, @EXEC_RSLT_CD, @EXEC_RSLT_MSG_SBST

SET @LCATE_CD = NULL
SET @LCATE_NM = NULL
SET @ENR_MODEL_NO = NULL
EXEC UDP_P_SHPDRY_CATE_INQR 12, '427480', NULL, @LCATE_CD OUTPUT, @LCATE_NM OUTPUT, @ENR_MODEL_NO OUTPUT, @EXEC_RSLT_CD OUTPUT, @EXEC_RSLT_MSG_SBST OUTPUT
SELECT @LCATE_CD,@LCATE_NM, @ENR_MODEL_NO, @EXEC_RSLT_CD, @EXEC_RSLT_MSG_SBST

SET @LCATE_CD = NULL
SET @LCATE_NM = NULL
SET @ENR_MODEL_NO = NULL
EXEC UDP_P_SHPDRY_CATE_INQR 12, '999', NULL, @LCATE_CD OUTPUT, @LCATE_NM OUTPUT, @ENR_MODEL_NO OUTPUT, @EXEC_RSLT_CD OUTPUT, @EXEC_RSLT_MSG_SBST OUTPUT
SELECT @LCATE_CD,@LCATE_NM, @ENR_MODEL_NO, @EXEC_RSLT_CD, @EXEC_RSLT_MSG_SBST

SET @LCATE_CD = NULL
SET @LCATE_NM = NULL
SET @ENR_MODEL_NO = NULL
EXEC UDP_P_SHPDRY_CATE_INQR 999, '999', NULL, @LCATE_CD OUTPUT, @LCATE_NM OUTPUT, @ENR_MODEL_NO OUTPUT, @EXEC_RSLT_CD OUTPUT, @EXEC_RSLT_MSG_SBST OUTPUT
SELECT @LCATE_CD,@LCATE_NM, @ENR_MODEL_NO, @EXEC_RSLT_CD, @EXEC_RSLT_MSG_SBST

*/







