/* *************************************************************************
 * NAME : dbo.UDP_JOB_STATISTICS_ETC_MODELNO_INSERT_bak_bslee
 * TYPE : PROCEDURE (SQL_STORED_PROCEDURE)
 * TIME : Create: 2005-02-14 17:25:57.077
 *        Modify: 2015-05-15 03:31:33.88
 *        Backup: 20180521_1737
 ************************************************************************* */




/****** 개체: 저장 프로시저 dbo.UP_JOB_STATISTICS_ETC_MODELNO_INSERT    스크립트 날짜: 2004-10-23 오전 11:11:46 ******/
/****** 개체: 저장 프로시저 dbo.UP_JOB_STATISTICS_ETC_MODELNO_INSERT    스크립트 날짜: 2004-09-17 오후 2:10:11 ******/
/****** 개체: 저장 프로시저 dbo.UP_JOB_STATISTICS_ETC_MODELNO_INSERT    스크립트 날짜: 2004-09-17 오후 1:12:09 ******/
/****** 개체: 저장 프로시저 dbo.UP_JOB_STATISTICS_ETC_MODELNO_INSERT    스크립트 날짜: 2004-09-17 오후 1:04:58 ******/
-- EXEC UP_JOB_STATISTICS_ETC_MODELNO_INSERT '2004-09-17'
/****** 개체: 저장 프로시저 dbo.UP_JOB_STATISTICS_ETC_MODELNO_INSERT    스크립트 날짜: 2004-06-24 오전 8:51:57 ******/
/****** BSLEE 2005.2.14 *****/
CREATE       PROC UDP_JOB_STATISTICS_ETC_MODELNO_INSERT_bak_bslee
	@NDATE VARCHAR(8)
AS
BEGIN
	SET NOCOUNT ON
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
	DECLARE @T_C INT --카테고리미등록
	DECLARE @T_X INT
	DECLARE @T_0 INT
	DECLARE @T_1 INT
	DECLARE @T_2 INT
	DECLARE @T_3 INT
	DECLARE @T_4 INT
	DECLARE @T_5 INT
	DECLARE @T_6 INT
	DECLARE @T_7 INT
	DECLARE @T_10 INT
	DECLARE @T_11 INT
	DECLARE @T_12 INT
	DECLARE @T_100 INT

	--카테고리정보
	DECLARE @TEMPCATECNT INT
	DECLARE @TEMPLCODE VARCHAR(4)
	DECLARE @TEMPCATETABLE TABLE
	(
		IDX INT IDENTITY(1,1),
		CL_LCODE VARCHAR(8)
	)
	INSERT INTO @TEMPCATETABLE (CL_LCODE)
	SELECT CL_LCODE 
	FROM DBO.C_LCATE (NOLOCK) 
	WHERE CL_SEQNO > 0
		AND CL_LCODE<>'11'
		AND CL_LCODE<>'99'
	INSERT INTO @TEMPCATETABLE (CL_LCODE) VALUES ('13')
	INSERT INTO @TEMPCATETABLE (CL_LCODE) VALUES ('20')
	INSERT INTO @TEMPCATETABLE (CL_LCODE) VALUES ('22')
	INSERT INTO @TEMPCATETABLE (CL_LCODE) VALUES ('23')
	INSERT INTO @TEMPCATETABLE (CL_LCODE) VALUES ('24')
	INSERT INTO @TEMPCATETABLE (CL_LCODE) VALUES ('25')


	

	SELECT @TEMPCATECNT = COUNT(IDX) FROM @TEMPCATETABLE
	DECLARE @TEMPCODE2 VARCHAR(8)
	--카테고리루틴
	WHILE @TEMPCATECNT<>0	
	BEGIN
		SELECT @TEMPLCODE = CL_LCODE
		FROM @TEMPCATETABLE
		WHERE IDX = @TEMPCATECNT
		
		SET @T_C=0
		SET @T_X=0
		SET @T_0=0
		SET @T_1=0
		SET @T_2=0
		SET @T_3=0
		SET @T_4=0
		SET @T_5=0
		SET @T_6=0
		SET @T_7=0
		SET @T_10=0
		SET @T_11=0
		SET @T_12=0
		SET @T_100=0
		

		IF @TEMPLCODE='13'
		BEGIN
			SELECT @T_C = COUNT(G_NO)
			FROM GOODS (NOLOCK)
			WHERE G_MODELNO>0
				AND G_CATEGORY LIKE '1103%'
				AND G_JOBCODE='0'
				AND G_MALLCNT>0
		END
		ELSE IF @TEMPLCODE='20'
		BEGIN
			SELECT @T_C = COUNT(G_NO)
			FROM GOODS (NOLOCK)
			WHERE G_MODELNO>0
				AND G_CATEGORY LIKE '1110%'
				AND G_JOBCODE='0'
				AND G_MALLCNT>0	
		END
		ELSE IF @TEMPLCODE='22'
		BEGIN
			SELECT @T_C = COUNT(G_NO)
			FROM GOODS (NOLOCK)
			WHERE G_MODELNO>0
				AND G_CATEGORY LIKE '1111%'
				AND G_JOBCODE='0'
				AND G_MALLCNT>0
		END
		ELSE IF @TEMPLCODE='23'
		BEGIN
			SELECT @T_C = COUNT(G_NO)
			FROM GOODS (NOLOCK)
			WHERE G_MODELNO>0
				AND G_CATEGORY LIKE '1101%'
				AND G_JOBCODE='0'
				AND G_MALLCNT>0
		END
		ELSE IF @TEMPLCODE='24'
		BEGIN
			SELECT @T_C = COUNT(G_NO)
			FROM GOODS (NOLOCK)
			WHERE G_MODELNO>0
				AND G_CATEGORY LIKE '1113%'
				AND G_JOBCODE='0'
				AND G_MALLCNT>0
		END
		ELSE IF @TEMPLCODE='25'
		BEGIN
			SELECT @T_C = COUNT(G_NO)
			FROM GOODS (NOLOCK)
			WHERE G_MODELNO>0
				AND G_CATEGORY LIKE '1114%'
				AND G_JOBCODE='0'
				AND G_MALLCNT>0
		END

		ELSE
		BEGIN
			SELECT @T_C = COUNT(G_NO)
			FROM GOODS (NOLOCK)
			WHERE G_MODELNO>0
				AND G_CATEGORY LIKE @TEMPLCODE + '%'
				AND G_JOBCODE='0'
				AND G_MALLCNT>0
		END



		SET @TEMPCODE2 = @TEMPLCODE
		IF @TEMPLCODE='13'
			SET @TEMPCODE2 = '1103'
		ELSE IF @TEMPLCODE='20'
			SET @TEMPCODE2 = '1110'
		ELSE IF @TEMPLCODE='22'
			SET @TEMPCODE2 = '1111'
		ELSE IF @TEMPLCODE='23'
			SET @TEMPCODE2 = '1101'
		ELSE IF @TEMPLCODE='24'
			SET @TEMPCODE2 = '1113'
		ELSE IF @TEMPLCODE='25'
			SET @TEMPCODE2 = '1114'

		CREATE TABLE #TEMPA 
		(
			IDX INT IDENTITY(1,1),
			PL_MODELNO INT,
			NCNT INT
		)	
		
		INSERT INTO #TEMPA (PL_MODELNO, NCNT)
		SELECT ISNULL(PL_MODELNO,-1000), COUNT(ISNULL(PL_MODELNO,-1000)) 
		FROM PRICELIST (NOLOCK)
		WHERE ISNULL(PL_MODELNO,-1000) <= 0  
			AND PL_CATEGORY = @TEMPCODE2 
			AND PL_STATUS < '3' 
		GROUP BY PL_MODELNO 
		ORDER BY PL_MODELNO DESC
	
	
		DECLARE @TOTCNT INT
		DECLARE @TEMPMODELNO INT
		DECLARE @TEMPCOUNT INT
		SELECT @TOTCNT = COUNT(IDX) FROM #TEMPA
	
		--미정상품수 작업타입루틴
		WHILE @TOTCNT<>0
		BEGIN
			SELECT @TEMPMODELNO = PL_MODELNO,
				@TEMPCOUNT = NCNT
			FROM #TEMPA
			WHERE IDX = @TOTCNT
			
			IF @TEMPMODELNO=-1000 --모델넘버 없는경우(NULL)
			BEGIN
				SET @T_X=@TEMPCOUNT
			END
			ELSE IF @TEMPMODELNO=0
			BEGIN
				SET @T_0=@TEMPCOUNT
			END
			ELSE IF @TEMPMODELNO=-1
			BEGIN
				SET @T_1=@TEMPCOUNT
			END
			ELSE IF @TEMPMODELNO=-2
			BEGIN
				SET @T_2=@TEMPCOUNT
			END
			ELSE IF @TEMPMODELNO=-3
			BEGIN
				SET @T_3=@TEMPCOUNT
			END
			ELSE IF @TEMPMODELNO=-4
			BEGIN
				SET @T_4=@TEMPCOUNT
			END
			ELSE IF @TEMPMODELNO=-5
			BEGIN
				SET @T_5=@TEMPCOUNT
			END
			ELSE IF @TEMPMODELNO=-6
			BEGIN
				SET @T_6=@TEMPCOUNT
			END
			ELSE IF @TEMPMODELNO=-7
			BEGIN
				SET @T_7=@TEMPCOUNT
			END
			ELSE IF @TEMPMODELNO=-10
			BEGIN
				SET @T_10=@TEMPCOUNT
			END
			ELSE IF @TEMPMODELNO=-11
			BEGIN
				SET @T_11=@TEMPCOUNT
			END
			ELSE IF @TEMPMODELNO=-12
			BEGIN
				SET @T_12=@TEMPCOUNT
			END
			ELSE IF @TEMPMODELNO=-100
			BEGIN
				SET @T_100=@TEMPCOUNT
			END
	
			SET @TOTCNT = @TOTCNT -1
		END
		DROP TABLE #TEMPA

		INSERT INTO LOGDB.DBO.JOB_STATISTICS_ETC_MODELNO
		(jsem_date, jsem_cate, jsem_flagc, jsem_flagx,jsem_flag0,jsem_flag1,jsem_flag2,jsem_flag3,jsem_flag4,jsem_flag5,jsem_flag6,jsem_flag7,jsem_flag10,jsem_flag11,jsem_flag12,jsem_flag100 )
		VALUES
		(@NDATE , @TEMPCODE2, @T_C, @T_X, @T_0, @T_1, @T_2, @T_3, @T_4, @T_5, @T_6, @T_7, @T_10, @T_11, @T_12, @T_100)

		SET @TEMPCATECNT = @TEMPCATECNT-1
	END
	
END







