/* *************************************************************************
 * NAME : dbo.USP_PRICELIST_SEL_12
 * TYPE : PROCEDURE (SQL_STORED_PROCEDURE)
 * TIME : Create: 2007-03-26 17:57:31.98
 *        Modify: 2018-05-03 17:23:35.89
 *        Backup: 20180521_1737
 ************************************************************************* */

CREATE PROC [dbo].[USP_PRICELIST_SEL_12]

	@PL_VCODE INT,
	@PL_GOODSCODE VARCHAR(50)
AS
BEGIN
	SET NOCOUNT ON
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
	SELECT TOP 1
		PL_NO ,ISNULL(PL_MODELNO, 0) ,ISNULL(PL_CATEGORY, '00') , PL_GOODSNM, PL_PRICE ,PL_URL,
		PL_STATUS, PL_RIGHTNLEFT, PL_DELIVERYINFO, PL_IMGURL, PL_COUPON, PL_ACCOUNT_YN, PL_FREEINTEREST, PL_GOODSFACTORY, PL_NOCHANGE
	FROM PRICELIST --WITH (INDEX(NCL_PRICELIST_6)) 
	WHERE PL_VCODE = @PL_VCODE
		AND PL_GOODSCODE = @PL_GOODSCODE
		AND PL_GOODSCODE_CS = CHECKSUM(@PL_GOODSCODE)
		AND pl_goodsnm <> ''
END

