/* *************************************************************************
 * NAME : dbo.UDP_WEB_GOODS_SEARCH_INSERT
 * TYPE : PROCEDURE (SQL_STORED_PROCEDURE)
 * TIME : Create: 2004-11-02 03:31:57.03
 *        Modify: 2018-05-03 17:23:35.767
 *        Backup: 20180521_1737
 ************************************************************************* */

CREATE  PROC UDP_WEB_GOODS_SEARCH_INSERT
	@PL_NO		bigINT,
	@G_MODELNO	INT
AS
BEGIN
	SET NOCOUNT ON
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

 	IF NOT EXISTS( SELECT WGS_G_MODELNO 
 		FROM TBL_WEB_GOODS_SEARCH 
 		WHERE WGS_G_MODELNO = @G_MODELNO
 			AND WGS_PL_NO=@PL_NO)
 	BEGIN
		INSERT INTO TBL_WEB_GOODS_SEARCH
		(WGS_G_MODELNO, WGS_PL_NO)
		VALUES
		(@G_MODELNO,@PL_NO)
 	END

END
