/* *************************************************************************
 * NAME : dbo.UDP_PACKAGE_GOODS_PLIST_SNAPSHOT
 * TYPE : PROCEDURE (SQL_STORED_PROCEDURE)
 * TIME : Create: 2008-12-08 14:34:31.687
 *        Modify: 2015-05-15 03:31:33.85
 *        Backup: 20180521_1737
 ************************************************************************* */

CREATE PROC UDP_PACKAGE_GOODS_PLIST_SNAPSHOT
AS
	-- ----------------------------------------------------------------------------------
	-- 작성자 : wookki25 / 2008.12.08
	-- 설  명 : 패키지상품 가격/모델명 변경 체크하기 위해 PLIST 스냅샷처리
	--          196에서 호출 실행
	-- 실  행 : EXE CUDP_PACKAGE_GOODS_PLIST_SNAPSHOT
	-- 수  정 :
	/*
	수정일:		수정자:		수정내용:
	----------	-----------	-----------------------------------------------------

	*/
	-- ----------------------------------------------------------------------------------
	SET NOCOUNT ON
	SET TRANSACTION ISOLATION LEVEL  READ UNCOMMITTED


	-- 패키지 인기상품
	SELECT	*
	INTO	#TBL_PACKAGE_GOODS_POPULAR
	FROM	OLTPLOG_196.OLTPLOG.DBO.TBL_PACKAGE_GOODS_POPULAR



	-- 당일치 가격, 모델명 스냅샷!
	/*
	-- 테이블 생성
	CREATE TABLE PRICELIST_PACKAGE_GOODS_SNAPSHOT
	(
		SNAPSHOT_DATE SMALLDATETIME
	,	PL_MODELNO INT
	,	PL_NO INT
	,	PL_PRICE MONEY
	,	PL_GOODSNM NVARCHAR(200)
	)
	*/

	-- 이전 스냅샷 삭제
	DELETE FROM PRICELIST_PACKAGE_GOODS_SNAPSHOT WHERE SNAPSHOT_DATE < CONVERT(VARCHAR(10), GETDATE()-1, 120)

	-- 당일 스냅샷 저장
	INSERT INTO PRICELIST_PACKAGE_GOODS_SNAPSHOT
	(SNAPSHOT_DATE, PL_MODELNO, PL_NO, PL_PRICE, PL_GOODSNM)
	SELECT	CONVERT(VARCHAR(10),GETDATE(), 120)
	,		B.PL_MODELNO
	,		A.PL_NO
	,		PL_PRICE
	,		PL_GOODSNM
	FROM	#TBL_PACKAGE_GOODS_POPULAR A
				INNER JOIN
			PRICELIST B
				ON A.PL_NO = B.PL_NO
	ORDER BY A.PL_NO


	-- 마이너스 랭킹 입력
	INSERT INTO OLTPLOG_196.OLTPLOG.DBO.TBL_PACKAGE_GOODS_POPULAR_PENALTY
	SELECT C.PL_NO, CONVERT(VARCHAR(10), (D.NUM+GETDATE()), 120) AS APP_DATE, C.MINUS_RANK
	FROM
		(
		SELECT
			A.PL_NO
		,	CASE WHEN A.PL_PRICE <> B.PL_PRICE THEN 1 ELSE 0 END
			+ CASE WHEN A.PL_GOODSNM <> B.PL_GOODSNM THEN 1 ELSE 0 END AS MINUS_RANK
		FROM
			PRICELIST_PACKAGE_GOODS_SNAPSHOT A
				INNER JOIN
			PRICELIST_PACKAGE_GOODS_SNAPSHOT B
				ON A.PL_NO =  B.PL_NO
		WHERE (A.PL_PRICE < B.PL_PRICE OR A.PL_GOODSNM <> B.PL_GOODSNM)
		AND		A.SNAPSHOT_DATE = CONVERT(VARCHAR(10), GETDATE()-1, 120)
		AND		B.SNAPSHOT_DATE = CONVERT(VARCHAR(10), GETDATE(), 120)
		) C
		CROSS JOIN
		( SELECT 0 AS NUM UNION ALL SELECT 1 UNION ALL SELECT 2 ) D


