/* *************************************************************************
 * NAME : dbo.UDP_ELOC_PRICELIST_MODIFY
 * TYPE : PROCEDURE (SQL_STORED_PROCEDURE)
 * TIME : Create: 2004-11-03 17:38:33.25
 *        Modify: 2015-09-17 16:49:12.467
 *        Backup: 20180521_1737
 ************************************************************************* */

CREATE        PROC [dbo].[UDP_ELOC_PRICELIST_MODIFY]
	@PL_NO		bigINT,
	@SHOP_VCODE	INT,
	@PL_PRICE	MONEY,
	@PL_ETC	NVARCHAR(100),
	@PL_URL	VARCHAR(250),
	@PL_RIGHTNLEFT CHAR(1),
	@PL_SRVFLAG	CHAR(1),
	--@PL_FLAG	CHAR(1),
	@PL_STATUS	CHAR(1),
	@PL_GOODSNM		NVARCHAR(400) = NULL,
	@PL_GOODSCODE	VARCHAR(50) = NULL,

	@iRETURN	INT	OUTPUT
AS
BEGIN
	SET NOCOUNT ON
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
	DECLARE @TMPVCODE	INT
	SET @TMPVCODE=0
	SELECT @TMPVCODE = PL_VCODE
	FROM PRICELIST
	WHERE PL_NO=@PL_NO

	IF @TMPVCODE=0 -- 상품없음.
	BEGIN
		SET @iRETURN=1
	END
	ELSE
	BEGIN
		IF @TMPVCODE <> @SHOP_VCODE --해당업체가 아님.
		BEGIN
			SET @iRETURN=2
		END
		ELSE
		BEGIN
			BEGIN TRAN

				UPDATE PRICELIST
				SET PL_PRICE = @PL_PRICE,
					PL_ETC = @PL_ETC,
					PL_URL	= @PL_URL,
					--PL_RIGHTNLEFT = @PL_RIGHTNLEFT, -- DELETED BY WOOKKI25 2007.06.05
					PL_SRVFLAG = @PL_SRVFLAG,
					--PL_FLAG	 = @PL_FLAG,
					PL_STATUS = @PL_STATUS,
					PL_DATE = GETDATE()
				,	PL_GOODSNM = ISNULL(@PL_GOODSNM, PL_GOODSNM),
					PL_GOODSCODE = @PL_GOODSCODE
				WHERE	PL_NO= @PL_NO 

			IF @@ERROR<>0 or @@rowcount=0
			BEGIN
				SET @iRETURN=99
				ROLLBACK TRAN
			END
			ELSE
			BEGIN
				SET @iRETURN =0
				COMMIT TRAN
			END

		END


	END

END

