/* *************************************************************************
 * NAME : dbo.UDP_ELOC_EDU_PRICELIST_SAVE_2
 * TYPE : PROCEDURE (SQL_STORED_PROCEDURE)
 * TIME : Create: 2005-12-08 10:31:24.39
 *        Modify: 2018-05-03 17:23:35.78
 *        Backup: 20180521_1737
 ************************************************************************* */

CREATE PROC UDP_ELOC_EDU_PRICELIST_SAVE_2
	@PL_NO		bigINT,	
	@PL_VCODE		INT,	
	@PL_STATUS   CHAR(1),
	@PL_GOODSNM	NVARCHAR(200),
	@PL_PRICE		MONEY,
	@PL_INSTANCE_PRICE		MONEY,
		
	@iRETURN		INT 	OUTPUT
AS
BEGIN
	SET NOCOUNT ON
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
	BEGIN
		UPDATE PRICELIST SET PL_STATUS = @PL_STATUS, PL_GOODSNM = @PL_GOODSNM, PL_PRICE = @PL_PRICE, PL_INSTANCE_PRICE = @PL_INSTANCE_PRICE, PL_DATE = GetDate()
		WHERE PL_VCODE = @PL_VCODE AND PL_NO = @PL_NO
	END

	IF @@ERROR<>0
		BEGIN

			SET @iRETURN = 99
		END
	ELSE
		BEGIN

			SET @iRETURN = 0
				
		END

END
