/* *************************************************************************
 * NAME : dbo.UDP_MP_GOODS_ATTRIBUTE_CONDITION
 * TYPE : PROCEDURE (SQL_STORED_PROCEDURE)
 * TIME : Create: 2017-01-12 15:28:51.197
 *        Modify: 2018-05-03 17:23:34.33
 *        Backup: 20180521_1737
 ************************************************************************* */


CREATE PROC [DBO].[UDP_MP_GOODS_ATTRIBUTE_CONDITION]
	@MODELNO INT
AS
BEGIN
	SET NOCOUNT ON;
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
	
	DECLARE @ATTRIBUTE_ID INT
	DECLARE @ATTRIBUTE_ELEMENT_ID SMALLINT
	
	--DROP TABLE #CONDITION
	SELECT DISTINCT ATTRIBUTE_ID, ATTRIBUTE_ELEMENT_ID
	INTO #CONDITION
	FROM GOODS
		INNER JOIN GOODS_GROUP_CONDITION ON GGC_CATEGORY = LEFT(G_CATEGORY, 6) AND LTRIM(RTRIM(RIGHT(LTRIM(RTRIM(G_MODELNM)), LEN(LTRIM(RTRIM(G_MODELNM))) - CHARINDEX('@', LTRIM(RTRIM(G_MODELNM)))))) = GGC_NAME
		INNER JOIN GOODS_ATTRIBUTE_ELEMENT ON ATTRIBUTE_ID = (SELECT ATTRIBUTE_ID FROM GOODS_ATTRIBUTE WHERE DEL_YN = 'N' AND CATEGORY = '' AND MANAGE_ATTRIBUTE_NM = '조건명_' + LEFT(G_CATEGORY, 4)) AND GGC_NAME = ATTRIBUTE_ELEMENT
	WHERE CHARINDEX('@', G_MODELNM) > 0 AND G_MODELNO = @MODELNO
	
	IF (SELECT COUNT(*) FROM #CONDITION) = 1
	BEGIN
		SELECT @ATTRIBUTE_ID = ATTRIBUTE_ID, @ATTRIBUTE_ELEMENT_ID = ATTRIBUTE_ELEMENT_ID
		FROM #CONDITION
		
		-- 조건명 카탈 속성 추가
		UPDATE GOODS_CATALOG_ATTRIBUTE
		SET DEL_YN = 'N', UPD_DATE = GETDATE(), UPD_OPRT = 'Lab_batch', INS_DATE = GETDATE()
		FROM GOODS_CATALOG_ATTRIBUTE
		WHERE DEL_YN = 'Y' AND G_MODELNO = @MODELNO AND ATTRIBUTE_ID = @ATTRIBUTE_ID AND ATTRIBUTE_ELEMENT_ID = @ATTRIBUTE_ELEMENT_ID
		
		IF (SELECT COUNT(*) FROM GOODS_CATALOG_ATTRIBUTE WHERE DEL_YN = 'N' AND G_MODELNO = @MODELNO AND ATTRIBUTE_ID = @ATTRIBUTE_ID AND ATTRIBUTE_ELEMENT_ID = @ATTRIBUTE_ELEMENT_ID) = 0
		BEGIN
			INSERT INTO GOODS_CATALOG_ATTRIBUTE(G_MODELNO, ATTRIBUTE_ID, ATTRIBUTE_ELEMENT_ID, INS_DATE, INS_OPRT, DEL_YN, UPD_DATE, UPD_OPRT)
			SELECT @MODELNO, @ATTRIBUTE_ID, @ATTRIBUTE_ELEMENT_ID, GETDATE(), 'Lab_batch', 'N', GETDATE(), 'Lab_batch'
		END
		
		UPDATE GOODS_CATALOG_ATTRIBUTE
		SET DEL_YN = 'Y', UPD_DATE = GETDATE(), UPD_OPRT = 'Lab_batch'
		WHERE DEL_YN = 'N' AND G_MODELNO = @MODELNO AND ATTRIBUTE_ID = @ATTRIBUTE_ID AND ATTRIBUTE_ELEMENT_ID <> @ATTRIBUTE_ELEMENT_ID
	END
	ELSE
	BEGIN
		UPDATE GOODS_CATALOG_ATTRIBUTE
		SET DEL_YN = 'Y', UPD_DATE = GETDATE(), UPD_OPRT = 'Lab_batch'
		WHERE DEL_YN = 'N' AND G_MODELNO = @MODELNO AND ATTRIBUTE_ID IN (SELECT ATTRIBUTE_ID FROM GOODS_ATTRIBUTE WHERE DEL_YN = 'N' AND CATEGORY = '' AND GALLERY_ATTRIBUTE_NM = '조건명')
	END
END
