/* *************************************************************************
 * NAME : dbo.UDP_MP_GOODS_ADDCATE_CHANGE2
 * TYPE : PROCEDURE (SQL_STORED_PROCEDURE)
 * TIME : Create: 2016-04-05 20:20:32.047
 *        Modify: 2018-05-03 17:23:34.773
 *        Backup: 20180521_1737
 ************************************************************************* */


CREATE PROCEDURE [DBO].[UDP_MP_GOODS_ADDCATE_CHANGE2]
	@ORIGINAL_CATE VARCHAR(12),
	@NEW_CATE VARCHAR(12),
	@MM_ID VARCHAR(12),
	@MM_NM VARCHAR(12)
AS
BEGIN
	SET NOCOUNT ON;
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
	
	DECLARE @AFF_ROWS INT
	SET @AFF_ROWS = 0
	
	IF NOT (@ORIGINAL_CATE = '' AND @NEW_CATE = '')
		-- 추가분류 일괄변경
		BEGIN
			SELECT G_MODELNO
			INTO #TEMP_GOODS
			FROM GOODS
			WHERE G_CATEGORY LIKE @ORIGINAL_CATE + '%'
			
			-- 추가분류 ''3'' 변경모델
			SELECT GA_NO, GA_MODELNO
			INTO #TEMP_GOODS_ADDCATE_1
			FROM GOODS_ADDCATE
			WHERE GA_CATEGORY = @NEW_CATE
			  AND GA_MODELNO IN (SELECT G_MODELNO FROM #TEMP_GOODS)
			  AND GA_FLAG = '3'
			
			-- 추가분류 ''3'' 변경모델 업데이트
			UPDATE GOODS
			SET G_FLAG = '1'
			WHERE G_MODELNO IN (SELECT DISTINCT GA_MODELNO FROM #TEMP_GOODS_ADDCATE_1)
			
			-- 추가분류 ''3'' 업데이트
			UPDATE GOODS_ADDCATE
			SET GA_FLAG = '2'
			WHERE GA_NO IN (SELECT DISTINCT GA_NO FROM #TEMP_GOODS_ADDCATE_1)
			
			SET @AFF_ROWS = @AFF_ROWS + @@ROWCOUNT
			
			-- 추가분류 추가모델
			SELECT GA_NO, GA_MODELNO
			INTO #TEMP_GOODS_ADDCATE_2
			FROM GOODS_ADDCATE
			WHERE GA_CATEGORY = @NEW_CATE
			  AND GA_MODELNO IN (SELECT G_MODELNO FROM #TEMP_GOODS)
			
			-- 추가분류 추가모델 업데이트
			UPDATE GOODS
			SET G_FLAG = '1'
			WHERE G_MODELNO IN (SELECT DISTINCT G_MODELNO FROM #TEMP_GOODS)
				  AND G_MODELNO NOT IN (SELECT DISTINCT GA_MODELNO FROM #TEMP_GOODS_ADDCATE_2)
			
			--  추가분류 추가
			INSERT INTO GOODS_ADDCATE (GA_MODELNO, GA_CATEGORY, GA_FLAG)
			SELECT G_MODELNO, @NEW_CATE, '2'
			FROM #TEMP_GOODS
			WHERE G_MODELNO NOT IN (SELECT DISTINCT GA_MODELNO FROM #TEMP_GOODS_ADDCATE_2)
			
			SET @AFF_ROWS = @AFF_ROWS + @@ROWCOUNT
		END
	
	IF (@AFF_ROWS > 0)
		BEGIN
			-- 분류변경 로그
			INSERT INTO LOGDB.DBO.TBL_CATE_CHG_LOG (DEL_CATE, NEW_CATE, MM_ID, MM_NM, CHG_FLAG, REGDATE)
			SELECT @ORIGINAL_CATE, @NEW_CATE, @MM_ID, @MM_NM, '4', GETDATE()
		END
END
