/* *************************************************************************
 * NAME : dbo.UDP_ORDERDATA_MODEL_DETAIL_ORD_UNIFY
 * TYPE : PROCEDURE (SQL_STORED_PROCEDURE)
 * TIME : Create: 2018-05-15 13:52:03.0
 *        Modify: 2018-05-15 13:52:03.0
 *        Backup: 20180521_1737
 ************************************************************************* */

CREATE PROC UDP_ORDERDATA_MODEL_DETAIL_ORD_UNIFY
	@CATE	VARCHAR(8)
,	@SDATE	datetime
,	@EDATE	datetime
,	@SHOP_CODE INT = 0
,	@JUMIN_SEX	CHAR(1) = ' '
,	@JUMIN_S_YYYY SMALLINT = 0
,	@JUMIN_E_YYYY SMALLINT = 0
,	@is_now_cate bit = 0
AS
	-- ----------------------------------------------------------------------------------
	-- 작성자 : wookki25 / 2009.02.25
	-- 설  명 : 해당 모델번호의 상세 주문내역-체결기준 데이터
	--          tbl_orderdata + tbl_orderdata_gmarket_auction
	-- ----------------------------------------------------------------------------------
	
	-- ----------------------------------------------------------------------------------
	-- 수정내역
	-- ----------------------------------------------------------------------------------
	/*
	수정일:			수정자:			수정내용:
	----------		-----------		-----------------------------------------------------		
	2008.01.28		wookki25		페이징처리  취소
	2009.11.18		wookki25		인터파크(shop_code=55) 주문자 성별,연령 정보 쿼리
	*/
	SET NOCOUNT ON
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
	
	--SELECT * FROM #TBL_ORDERDATA_MODELNO_IS_0 WHERE SEQ BETWEEN @ROWCNT-100+1 AND @ROWCNT

	IF @SHOP_CODE = 55 BEGIN
		if @is_now_cate = 0 begin
			SELECT G_MODELNO, ISNULL(G_MODELNM,''), G_FACTORY,  ROW_SUM, OD_CNT, PRICE_SUM, CL_NAME, CM_NAME, CS_NAME, CD_NAME, isnull(MALE_CNT,0), isnull(FEMALE_CNT,0)
			,		isnull(Y_10,0)
			,		isnull(Y_20,0), isnull(Y_24,0), isnull(Y_27,0)
			,		isnull(Y_30,0), isnull(Y_34,0), isnull(Y_37,0)
			,		isnull(Y_40,0), isnull(Y_44,0), isnull(Y_47,0)
			,		isnull(Y_50,0), isnull(Y_60,0)
			FROM 
				(
				SELECT	SHOP_VCODE, PL_MODELNO, MAX(OD_CATEGORY) AS OD_CATEGORY, COUNT(*) AS ROW_SUM, SUM(OD_CNT) AS OD_CNT, SUM(OD_PRICE*OD_CNT) AS PRICE_SUM
					,		MALE_CNT = SUM(CASE WHEN OD_JUMIN_SEX = '1' THEN 1 END)
					,		FEMALE_CNT = SUM(CASE WHEN OD_JUMIN_SEX = '2' THEN 1 END)
					,		Y_10 = SUM(CASE WHEN YEAR(GETDATE())-OD_JUMIN_YYYY+1 BETWEEN  1 AND 19 THEN 1 END)
					,		Y_20 = SUM(CASE WHEN YEAR(GETDATE())-OD_JUMIN_YYYY+1 BETWEEN 20 AND 23 THEN 1 END)
					,		Y_24 = SUM(CASE WHEN YEAR(GETDATE())-OD_JUMIN_YYYY+1 BETWEEN 24 AND 26 THEN 1 END)
					,		Y_27 = SUM(CASE WHEN YEAR(GETDATE())-OD_JUMIN_YYYY+1 BETWEEN 27 AND 29 THEN 1 END)
					,		Y_30 = SUM(CASE WHEN YEAR(GETDATE())-OD_JUMIN_YYYY+1 BETWEEN 30 AND 33 THEN 1 END)
					,		Y_34 = SUM(CASE WHEN YEAR(GETDATE())-OD_JUMIN_YYYY+1 BETWEEN 34 AND 36 THEN 1 END)
					,		Y_37 = SUM(CASE WHEN YEAR(GETDATE())-OD_JUMIN_YYYY+1 BETWEEN 37 AND 39 THEN 1 END)
					,		Y_40 = SUM(CASE WHEN YEAR(GETDATE())-OD_JUMIN_YYYY+1 BETWEEN 40 AND 43 THEN 1 END)
					,		Y_44 = SUM(CASE WHEN YEAR(GETDATE())-OD_JUMIN_YYYY+1 BETWEEN 44 AND 46 THEN 1 END)
					,		Y_47 = SUM(CASE WHEN YEAR(GETDATE())-OD_JUMIN_YYYY+1 BETWEEN 47 AND 49 THEN 1 END)
					,		Y_50 = SUM(CASE WHEN YEAR(GETDATE())-OD_JUMIN_YYYY+1 BETWEEN 50 AND 59 THEN 1 END)
					,		Y_60 = SUM(CASE WHEN YEAR(GETDATE())-OD_JUMIN_YYYY+1 BETWEEN 60 AND 200 THEN 1 END)
				FROM	VW_ORDERDATA_ORD
				WHERE	OD_DATE >= @SDATE AND OD_DATE < @EDATE+1
				AND		OD_CATEGORY LIKE @CATE+'%'
				AND		SHOP_VCODE BETWEEN @SHOP_CODE AND CASE WHEN @SHOP_CODE = 0 THEN 100000 ELSE  @SHOP_CODE END
				AND		ISNULL(OD_JUMIN_SEX,0) = CASE WHEN @JUMIN_SEX IN (1,2) THEN @JUMIN_SEX ELSE ISNULL(OD_JUMIN_SEX,0) END
				AND		ISNULL(OD_JUMIN_YYYY, YEAR(GETDATE()))	BETWEEN @JUMIN_S_YYYY AND @JUMIN_E_YYYY					
				GROUP BY SHOP_VCODE, PL_MODELNO
				) A
					LEFT OUTER JOIN 
				analstoreDB.DBO.GOODS B
					ON A.PL_MODELNO = B.G_MODELNO
					LEFT OUTER JOIN
				analstoreDB.DBO.CATE
					ON LEFT(A.OD_CATEGORY+'00000000',8) = CATEGORY
			ORDER BY PRICE_SUM DESC
		end else begin
			SELECT G_MODELNO, ISNULL(G_MODELNM,''), G_FACTORY,  ROW_SUM, OD_CNT, PRICE_SUM, CL_NAME, CM_NAME, CS_NAME, CD_NAME, isnull(MALE_CNT,0), isnull(FEMALE_CNT,0)
			,		isnull(Y_10,0)
			,		isnull(Y_20,0), isnull(Y_24,0), isnull(Y_27,0)
			,		isnull(Y_30,0), isnull(Y_34,0), isnull(Y_37,0)
			,		isnull(Y_40,0), isnull(Y_44,0), isnull(Y_47,0)
			,		isnull(Y_50,0), isnull(Y_60,0)
			FROM 
				(
				SELECT	SHOP_VCODE, PL_MODELNO, MAX(OD_CATEGORY) AS OD_CATEGORY, COUNT(*) AS ROW_SUM, SUM(OD_CNT) AS OD_CNT, SUM(OD_PRICE*OD_CNT) AS PRICE_SUM
					,		MALE_CNT = SUM(CASE WHEN OD_JUMIN_SEX = '1' THEN 1 END)
					,		FEMALE_CNT = SUM(CASE WHEN OD_JUMIN_SEX = '2' THEN 1 END)
					,		Y_10 = SUM(CASE WHEN YEAR(GETDATE())-OD_JUMIN_YYYY+1 BETWEEN  1 AND 19 THEN 1 END)
					,		Y_20 = SUM(CASE WHEN YEAR(GETDATE())-OD_JUMIN_YYYY+1 BETWEEN 20 AND 23 THEN 1 END)
					,		Y_24 = SUM(CASE WHEN YEAR(GETDATE())-OD_JUMIN_YYYY+1 BETWEEN 24 AND 26 THEN 1 END)
					,		Y_27 = SUM(CASE WHEN YEAR(GETDATE())-OD_JUMIN_YYYY+1 BETWEEN 27 AND 29 THEN 1 END)
					,		Y_30 = SUM(CASE WHEN YEAR(GETDATE())-OD_JUMIN_YYYY+1 BETWEEN 30 AND 33 THEN 1 END)
					,		Y_34 = SUM(CASE WHEN YEAR(GETDATE())-OD_JUMIN_YYYY+1 BETWEEN 34 AND 36 THEN 1 END)
					,		Y_37 = SUM(CASE WHEN YEAR(GETDATE())-OD_JUMIN_YYYY+1 BETWEEN 37 AND 39 THEN 1 END)
					,		Y_40 = SUM(CASE WHEN YEAR(GETDATE())-OD_JUMIN_YYYY+1 BETWEEN 40 AND 43 THEN 1 END)
					,		Y_44 = SUM(CASE WHEN YEAR(GETDATE())-OD_JUMIN_YYYY+1 BETWEEN 44 AND 46 THEN 1 END)
					,		Y_47 = SUM(CASE WHEN YEAR(GETDATE())-OD_JUMIN_YYYY+1 BETWEEN 47 AND 49 THEN 1 END)
					,		Y_50 = SUM(CASE WHEN YEAR(GETDATE())-OD_JUMIN_YYYY+1 BETWEEN 50 AND 59 THEN 1 END)
					,		Y_60 = SUM(CASE WHEN YEAR(GETDATE())-OD_JUMIN_YYYY+1 BETWEEN 60 AND 200 THEN 1 END)
				FROM	VW_ORDERDATA_ORD
				WHERE	OD_DATE >= @SDATE AND OD_DATE < @EDATE+1
				AND		SHOP_VCODE BETWEEN @SHOP_CODE AND CASE WHEN @SHOP_CODE = 0 THEN 100000 ELSE  @SHOP_CODE END
				AND		ISNULL(OD_JUMIN_SEX,0) = CASE WHEN @JUMIN_SEX IN (1,2) THEN @JUMIN_SEX ELSE ISNULL(OD_JUMIN_SEX,0) END
				AND		ISNULL(OD_JUMIN_YYYY, YEAR(GETDATE()))	BETWEEN @JUMIN_S_YYYY AND @JUMIN_E_YYYY					
				GROUP BY SHOP_VCODE, PL_MODELNO
				) A
					LEFT OUTER JOIN 
				analstoreDB.DBO.GOODS B
					ON A.PL_MODELNO = B.G_MODELNO
					LEFT OUTER JOIN
				analstoreDB.DBO.CATE
					ON LEFT(A.OD_CATEGORY+'00000000',8) = CATEGORY
			WHERE isnull(G_CATEGORY, od_category) LIKE @CATE+'%'
			ORDER BY PRICE_SUM DESC
		end
	END ELSE BEGIN
		if @is_now_cate = 0 begin
			SELECT G_MODELNO, ISNULL(G_MODELNM,''), G_FACTORY,  ROW_SUM, OD_CNT, PRICE_SUM
			FROM 
				(
				SELECT	SHOP_VCODE, PL_MODELNO, MAX(OD_CATEGORY) AS OD_CATEGORY, COUNT(*) AS ROW_SUM, SUM(OD_CNT) AS OD_CNT, SUM(OD_PRICE*OD_CNT) AS PRICE_SUM
				FROM	VW_ORDERDATA_ORD
				WHERE	OD_DATE >= @SDATE AND OD_DATE < @EDATE+1
				AND		OD_CATEGORY LIKE @CATE+'%'
				AND		SHOP_VCODE BETWEEN @SHOP_CODE AND CASE WHEN @SHOP_CODE = 0 THEN 100000 ELSE  @SHOP_CODE END
				GROUP BY SHOP_VCODE, PL_MODELNO
				) A
					LEFT OUTER JOIN 
				analstoreDB.DBO.GOODS B
					ON A.PL_MODELNO = B.G_MODELNO
			ORDER BY PRICE_SUM DESC
		end else begin 
			SELECT G_MODELNO, ISNULL(G_MODELNM,''), G_FACTORY,  ROW_SUM, OD_CNT, PRICE_SUM
			FROM 
				(
				SELECT	SHOP_VCODE, PL_MODELNO, OD_CATEGORY, COUNT(*) AS ROW_SUM, SUM(OD_CNT) AS OD_CNT, SUM(OD_PRICE*OD_CNT) AS PRICE_SUM
				FROM	VW_ORDERDATA_ORD
				WHERE	OD_DATE >= @SDATE AND OD_DATE < @EDATE+1
				AND		SHOP_VCODE BETWEEN @SHOP_CODE AND CASE WHEN @SHOP_CODE = 0 THEN 100000 ELSE  @SHOP_CODE END
				GROUP BY SHOP_VCODE, PL_MODELNO, od_category
				) A
					LEFT OUTER JOIN 
				analstoreDB.DBO.GOODS B
					ON A.PL_MODELNO = B.G_MODELNO
			WHERE isnull(G_CATEGORY, od_category) LIKE @CATE+'%'
			ORDER BY PRICE_SUM DESC
		end
	END







