
CREATE TABLE DBADM.TB_MIG_JOBS (
     JOB_ID             VARCHAR(10)     NOT NULL     
   , JOB_NM             VARCHAR(100)    NOT NULL 
   , JOB_GROUP          VARCHAR(20)     
   , JOB_TYPE           VARCHAR(20)     NOT NULL
   , PRIORITY           NUMBER(5)       DEFAULT(0) NOT NULL 
   , JOB_DESC           VARCHAR(1000)
   , TARGET_TBL         VARCHAR(100)    NOT NULL
   , SOURCE_TBL         VARCHAR(100)
   , CMD_SQL            CLOB
   , BAS_SOURCE_CNT     NUMBER
   , BAS_TARGET_CNT     NUMBER
   , BAS_RESULT_CNT     NUMBER
   , BAS_ELAPSED_SEC    NUMBER
   , BAS_ELAPSED_HMS    VARCHAR(10)
   , BAS_LOG_ID         VARCHAR(30)
   , BAS_START_DT       DATE
   , BAS_END_DT         DATE
   , RUN_STAT           VARCHAR2(10)
   , LOG_ID             NUMBER(10)      --- VARCHAR(30)
   , CREATE_DT          DATE            DEFAULT (SYSDATE) NOT NULL 
   , CREATE_NM          VARCHAR(20)     NOT NULL
   , MODIFY_DT          DATE            DEFAULT (SYSDATE) NOT NULL 
   , MODIFY_NM          VARCHAR(20)     NOT NULL 
   , CONSTRAINT PK_DBM_JOBS PRIMARY KEY (JOB_ID)
   , CONSTRAINT UK_DBM_JOBS UNIQUE (JOB_NM)
);



CREATE TABLE DBADM.TB_MIG_JOB_DEPENDENCIES (
     JOB_ID             VARCHAR2(10)
   , DEPEND_JOB_ID      VARCHAR2(10)
   , DEPEND_TYP_CD      VARCHAR2(1)   -- M:Madatory, O:Optional, 
   , DEPEND_DESC        VARCHAR2(1000)
   , CREATE_DT          DATE             DEFAULT (SYSDATE) NOT NULL 
   , CREATE_NM          VARCHAR2(20)     NOT NULL
   , MODIFY_DT          DATE             DEFAULT (SYSDATE) NOT NULL 
   , MODIFY_NM          VARCHAR2(20)     NOT NULL 
   , CONSTRAINT PK_DBM_JOB_DEPENDENCIES     PRIMARY KEY (JOB_ID, DEPEND_JOB_ID)
   , CONSTRAINT FK_DBM_JOB_DEPENDENCIES_01  FOREIGN KEY (JOB_ID) REFERENCES TB_DBM_JOBS(JOB_ID)
   , CONSTRAINT FK_DBM_JOB_DEPENDENCIES_02  FOREIGN KEY (DEPEND_JOB_ID) REFERENCES TB_DBM_JOBS(JOB_ID)
);


ALTER TABLE DBADM.TB_DBM_JOB_DEPENDENCIES DISABLE CONSTRAINTS FK_DBM_JOB_DEPENDENCIES_01;
ALTER TABLE DBADM.TB_DBM_JOB_DEPENDENCIES DISABLE CONSTRAINTS FK_DBM_JOB_DEPENDENCIES_02;



CREATE TABLE DBADM.TB_MIG_JOB_LOG
(
     LOG_ID      VARCHAR2(30)  NOT NULL
   , LOG_GROUP   VARCHAR2(20)
   , JOB_ID      VARCHAR2(10)  NOT NULL
   , JOB_NM      VARCHAR2(100) NOT NULL
   , JOB_GROUP   VARCHAR2(20)
   , JOB_TYPE    VARCHAR2(20)
   , TARGET_TBL  VARCHAR2(100)
   , SOURCE_TBL  VARCHAR2(100)
   , STATUS      VARCHAR2(10)
   , START_TIME  DATE
   , END_TIME    DATE
   , RESULT      VARCHAR2(10)
   , SOURCE_CNT  NUMBER
   , TARGET_CNT  NUMBER
   , RESULT_CNT  NUMBER
   , ERR_CODE    VARCHAR2(10)
   , ERR_MSG     VARCHAR2(500)
   , LOG_TIME    DATE
   , REMARK      VARCHAR2(200)
   , CONSTRAINT PK_DBM_MIG_LOG PRIMARY KEY (LOG_ID)
);