
CREATE TABLE TB_MIG_JOBS (
     JOB_ID             VARCHAR(10)     NOT NULL     
   , JOB_NM             VARCHAR(100)    NOT NULL 
   , JOB_GROUP          VARCHAR(20)     
   , JOB_TYPE           VARCHAR(20)     NOT NULL
   , PRIORITY           SMALLINT        DEFAULT(0) NOT NULL 
   , JOB_DESC           VARCHAR(1000)
   , TARGET_DB          VARCHAR(100)    NOT NULL
   , TARGET_TBL         VARCHAR(100)    NOT NULL
   , SOURCE_TBL         VARCHAR(100)
   , CMD_SQL            VARCHAR(MAX)
   , BAS_SOURCE_CNT     INTEGER
   , BAS_TARGET_CNT     INTEGER
   , BAS_RESULT_CNT     INTEGER
   , BAS_ELAPSED_SEC    INTEGER
   , BAS_ELAPSED_HMS    VARCHAR(10)
   , BAS_LOG_ID         VARCHAR(30)
   , BAS_START_DT       DATETIME
   , BAS_END_DT         DATETIME
   , RUN_STAT           VARCHAR(10)
   , LOG_ID             INTEGER
   , CREATE_DT          DATETIME        DEFAULT (GETDATE()) NOT NULL 
   , CREATE_NM          VARCHAR(20)     NOT NULL
   , MODIFY_DT          DATETIME        DEFAULT (GETDATE()) NOT NULL 
   , MODIFY_NM          VARCHAR(20)     NOT NULL 
   , CONSTRAINT PK_DBM_JOBS PRIMARY KEY (JOB_ID)
   , CONSTRAINT UK_DBM_JOBS UNIQUE (JOB_NM)
);
