/* *************************************************************************
 * NAME : dbo.USP_PRICELIST_UP_16
 * TYPE : PROCEDURE (SQL_STORED_PROCEDURE)
 * TIME : Create: 2007-03-27 15:06:47.033
 *        Modify: 2018-05-03 17:23:34.05
 *        Backup: 20180521_1739
 ************************************************************************* */

CREATE PROC USP_PRICELIST_UP_16
	@PL_NO bigINT,
	@PL_CATEGORY VARCHAR(8),
	@PL_PRICE MONEY,
	@PL_URL VARCHAR(500),
	@PL_STATUS CHAR(1),
	@PL_RIGHTNLEFT CHAR(1),
	@PL_DELIVERYINFO NVARCHAR(100),
	@PL_IMGURL VARCHAR(250),
	@PL_COUPON TINYINT,
	@PL_ACCOUNT_YN CHAR(1),
	@PL_FREEINTEREST NVARCHAR(50)	
AS
BEGIN
	SET NOCOUNT ON
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

	UPDATE PRICELIST
	SET PL_CATEGORY = @PL_CATEGORY,
		PL_PRICE = @PL_PRICE,
		PL_URL = @PL_URL,
		PL_STATUS = @PL_STATUS,
		PL_DATE = GETDATE(),
		PL_RIGHTNLEFT = @PL_RIGHTNLEFT,
		PL_DELIVERYINFO = @PL_DELIVERYINFO,
		PL_IMGURL = @PL_IMGURL,
		PL_COUPON = @PL_COUPON,
		PL_ACCOUNT_YN = @PL_ACCOUNT_YN,
		PL_FREEINTEREST = @PL_FREEINTEREST,
		PL_IMGURLFLAG = (CASE WHEN PL_IMGURL<>@PL_IMGURL THEN '0' ELSE PL_IMGURLFLAG END)
	WHERE PL_NO = @PL_NO
END

