/* *************************************************************************
 * NAME : dbo.UDP_EP_MINPRICE_STATS
 * TYPE : PROCEDURE (SQL_STORED_PROCEDURE)
 * TIME : Create: 2018-01-31 09:17:03.943
 *        Modify: 2018-05-03 17:23:35.767
 *        Backup: 20180521_1739
 ************************************************************************* */


CREATE PROC [DBO].[UDP_EP_MINPRICE_STATS]
AS
BEGIN
	SET NOCOUNT ON;
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
	
	IF INDEXPROPERTY(OBJECT_ID('TMP_SHOT_20161227_PRICELIST'), 'IX_TMP_SHOT_20161227_PRICELIST_2', 'IndexID') IS NULL CREATE NONCLUSTERED INDEX IX_TMP_SHOT_20161227_PRICELIST_2 ON TMP_SHOT_20161227_PRICELIST(PL_VCODE ASC)
	
	IF INDEXPROPERTY(OBJECT_ID('TMP_SHOT_20161227_GOODS'), 'IX_TMP_SHOT_20161227_GOODS_1', 'IndexID') IS NULL CREATE NONCLUSTERED INDEX IX_TMP_SHOT_20161227_GOODS_1 ON TMP_SHOT_20161227_GOODS(G_MODELNO ASC, IS_G_SERVICE)
	
	DROP TABLE TBL_CPG_P_CNT_BY_SHOP_TEMP
	SELECT A.PL_VCODE, ISNULL(A.CATEGORY, '0000') CATEGORY, CAST(GETDATE() AS DATE) REGDATE,
		   A.IS_P_MATCH,		-- 일반상품/가격비교 상품 구분
		   COUNT(*) P_CNT_T,	-- 쇼핑몰 상품 총개수
		   SUM(CASE WHEN IS_MINPRICE = 1 THEN 1 ELSE 0 END) P_CNT_MIN
	INTO TBL_CPG_P_CNT_BY_SHOP_TEMP
	FROM TMP_SHOT_20161227_PRICELIST A
		LEFT JOIN TMP_SHOT_20161227_GOODS B ON A.PL_MODELNO = B.G_MODELNO AND IS_G_SERVICE = 1	-- GOODS 서비스하는 모델만
	WHERE PL_VCODE IN (55,536,4027,5910) AND IS_P_SERVICE = 1 AND IS_P_9X_CATE = 0
	GROUP BY PL_VCODE, ISNULL(A.CATEGORY, '0000'), IS_P_MATCH
	OPTION (MAXDOP 1)
	
	IF INDEXPROPERTY(OBJECT_ID('TMP_SHOT_20161227_PRICELIST'), 'IX_TMP_SHOT_20161227_PRICELIST_2', 'IndexID') IS NOT NULL DROP INDEX TMP_SHOT_20161227_PRICELIST.IX_TMP_SHOT_20161227_PRICELIST_2
	
	IF INDEXPROPERTY(OBJECT_ID('TMP_SHOT_20161227_GOODS'), 'IX_TMP_SHOT_20161227_GOODS_1', 'IndexID') IS NOT NULL DROP INDEX TMP_SHOT_20161227_GOODS.IX_TMP_SHOT_20161227_GOODS_1
	------------------------------------------------------------------------------
	
	DELETE FROM EP_MINPRICE_STATS WHERE YYYYMMDD = CAST(GETDATE() AS DATE)
	
	INSERT INTO EP_MINPRICE_STATS(YYYYMMDD, SHOP_CODE, CATEGORY, TOTAL_CNT, MATCH_CNT, MIN_CNT, NON_MATCH_CNT)
	SELECT YYYYMMDD, PL_VCODE, CATEGORY,
		   P_CNT_T, P_CNT_M1_T, P_CNT_M1_MIN, P_CNT_M0_T
	FROM (
 		SELECT YYYYMMDD, PL_VCODE, CATEGORY,
 			   -- 전체상품 : 가격비교+일반
			   SUM(P_CNT_T_0  + P_CNT_T_1)	P_CNT_T,			-- 상품.개수.전체
			   -- 가격비교
			   SUM(P_CNT_T_1)	P_CNT_M1_T,			-- 상품.개수.가격비교.전체
			   SUM(P_CNT_MIN_1)	P_CNT_M1_MIN,		-- 상품.개수.가격비교.최저가
			   -- 일반상품
			   SUM(P_CNT_T_0)	P_CNT_M0_T			-- 상품.개수.일반상품.전체
 		FROM
 		(
 	 		-- 가격비교
 	 		SELECT CAST(REGDATE AS DATE) YYYYMMDD, PL_VCODE, CATEGORY,
				   SUM(P_CNT_T) P_CNT_T_1, --SUM(PC_GT_MB) PC_GT_MB_1, SUM(PC_EQ_MB) PC_EQ_MB_1, SUM(PC_LT_MB) PC_LT_MB_1, SUM(G_CNT_T) G_CNT_T_1, SUM(G_CNT_S0) G_CNT_S0_1,
				   SUM(P_CNT_MIN) P_CNT_MIN_1,
				   0 P_CNT_T_0
 	 		FROM TBL_CPG_P_CNT_BY_SHOP_TEMP
      		WHERE IS_P_MATCH = 1
 	 		GROUP BY CAST(REGDATE AS DATE), PL_VCODE, CATEGORY
 	 		UNION ALL
 	 		-- 일반상품
 	 		SELECT CAST(REGDATE AS DATE), PL_VCODE, CATEGORY,
 	 			   0, 0, --0, 0, 0, 0, 0,
				   SUM(P_CNT_T)
 	 		FROM TBL_CPG_P_CNT_BY_SHOP_TEMP
 	 		WHERE IS_P_MATCH = 0
 	 		GROUP BY CAST(REGDATE AS DATE), PL_VCODE, CATEGORY
 		) A
 		GROUP BY YYYYMMDD, PL_VCODE, CATEGORY
	) A
	WHERE LEFT(CATEGORY, 2) IN ('02', '03', '04', '05', '06', '07', '08', '09', '10', '12', '14', '15', '16', '18', '21', '22', '24')
	OPTION (MAXDOP 1)
END
