/* *************************************************************************
 * NAME : dbo.UDP_ORDERDATA_COPY_TO_EVENT
 * TYPE : PROCEDURE (SQL_STORED_PROCEDURE)
 * TIME : Create: 2009-12-14 14:27:00.21
 *        Modify: 2018-05-03 17:23:36.147
 *        Backup: 20180521_1739
 ************************************************************************* */

CREATE PROC [DBO].[UDP_ORDERDATA_COPY_TO_EVENT]
	@FLAG	VARCHAR(5)
AS
	-- ----------------------------------------------------------------------------------
	-- 작성자 : WOOKKI25 / 2009.12.14
	-- 설  명 : 이벤트 데이터 입력
	-- 참  고 : UDP_MAKE_SHOP_ORDERDATA
	-- ----------------------------------------------------------------------------------
	SET NOCOUNT ON
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

	--return -- 2010.04.07 이벤트 종료로 실행 안한다.

	-- 업체구분
	DECLARE @SHOP_VCODE INT
	SELECT TOP 1 @SHOP_VCODE = SHOP_VCODE FROM TBL_ORDERDATA_WORKER

	IF @FLAG = 'ORD' AND @SHOP_VCODE IN (55, 4027, 5910, 536)--인팍, 옥션, 11번가, 지마켓
	BEGIN
		-- 배송기준 주문 데이터 있는 업체는 체결데이터 사용하지 않는다.
		RETURN
	END

	-- 이전 데이터와 중복 데이터 삭제
	DELETE	KNOWBOXDB2.DBO.TBL_EVENT_USERORDER_DATA
	FROM	KNOWBOXDB2.DBO.TBL_EVENT_USERORDER_DATA A INNER JOIN TBL_ORDERDATA_WORKER B
			ON A.OD_ID = B.OD_ID AND A.OD_GOODSCODE = B.OD_GOODSCODE
	WHERE	A.SHOP_VCODE = @SHOP_VCODE

	-- 데이터 이전
	INSERT INTO KNOWBOXDB2.DBO.TBL_EVENT_USERORDER_DATA
	(SHOP_VCODE,OD_DATE,OD_ID,OD_ID_NO,OD_GOODSCODE,OD_GOODSNM,OD_PRICE,OD_CNT,PL_NO,G_MODELNO,G_CATEGORY,OD_JUMIN,KEYWORD_AD_INFO,OD_REGDATE,OD_COMMENT,OD_UNIT_PRICE)
	SELECT SHOP_VCODE,OD_DATE,OD_ID,OD_ID_NO,OD_GOODSCODE,OD_GOODSNM,OD_PRICE,OD_CNT,PL_NO,G_MODELNO,G_CATEGORY,OD_JUMIN,KEYWORD_AD_INFO,OD_REGDATE,OD_COMMENT,OD_UNIT_PRICE
	FROM TBL_ORDERDATA_WORKER

