/* *************************************************************************
 * NAME : dbo.USP_PRICELIST_SEL_7
 * TYPE : PROCEDURE (SQL_STORED_PROCEDURE)
 * TIME : Create: 2007-03-26 17:43:49.44
 *        Modify: 2015-09-17 16:49:12.587
 *        Backup: 20180521_1739
 ************************************************************************* */

CREATE PROC [dbo].[USP_PRICELIST_SEL_7]
	@PL_NO bigINT	
AS
BEGIN
	SET NOCOUNT ON
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
	SELECT PL_NO, ISNULL(PL_MODELNO, 0) AS PL_MODELNO, PL_VCODE, ISNULL(PL_CATEGORY, '00') AS PL_CATEGORY, ISNULL(PL_GOODSNM, '') AS PL_GOODSNM,
		ISNULL(PL_PRICE, 0) AS PL_PRICE, ISNULL(PL_URL, '') AS PL_URL, ISNULL(PL_NOTE, '') AS PL_NOTE, PL_SRVFLAG, PL_STATUS,	
		ISNULL(PL_ETC,'') AS PL_ETC, ISNULL(PL_AUTHFLAG, '0') AS PL_AUTHFLAG, PL_AUTHDATE, ISNULL(PL_RIGHTNLEFT, '0') AS PL_RIGHTNLEFT, ISNULL(PL_DELIVERYINFO,'') AS PL_DELIVERYINFO, ISNULL(PL_IMGURL, '') AS PL_IMGURL,
		ISNULL(PL_COUPON, 0) AS PL_COUPON, PL_ACCOUNT_YN, ISNULL(PL_INSTANCE_PRICE, 0) AS PL_INSTANCE_PRICE, ISNULL(PL_ESSTOCKFLAG, '0') AS PL_ESSTOCKFLAG,
		PL_GOODSFACTORY, PL_GOODSCODE, ISNULL(PL_SUBSIDE,0), PL_IMGURLFLAG, ISNULL(PL_FREEINTEREST,'') AS PL_FREEINTEREST, ISNULL(PL_AIRCONFEETYPE,'0') AS PL_AIRCONFEETYPE, ISNULL(PL_AGREE_MONTH,0) AS PL_AGREE_MONTH, PL_HOMEFLAG
	FROM PRICELIST 
	WHERE PL_NO = @PL_NO
		AND PL_STATUS <> '0'
END


