/* *************************************************************************
 * NAME : dbo.UDP_MCSS_CATALOG_STEP3
 * TYPE : PROCEDURE (SQL_STORED_PROCEDURE)
 * TIME : Create: 2018-03-15 15:45:53.5
 *        Modify: 2018-05-03 17:23:35.38
 *        Backup: 20180521_1739
 ************************************************************************* */


CREATE PROC [DBO].[UDP_MCSS_CATALOG_STEP3]
AS
BEGIN
	SET NOCOUNT ON;
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
	
	DELETE FROM TBL_MCSS_LOG WHERE YYYYMMDD = CONVERT(VARCHAR(10), GETDATE(), 112) AND PATH = 'TBL_MCSS_ATTRIBUTE_CATALOG'
	DELETE FROM TBL_MCSS_LOG WHERE YYYYMMDD = CONVERT(VARCHAR(10), GETDATE(), 112) AND PATH = 'TBL_MCSS_EP_11ST'
	
	ALTER TABLE TBL_MCSS_CATALOG ADD CONSTRAINT [CL_TBL_MCSS_CATALOG] PRIMARY KEY CLUSTERED(MODELNO ASC)
	------------------------------------------------------------------------------------------
	-- Ä«Å»¼Ó¼º (ELOC)
	INSERT INTO TBL_MCSS_LOG(YYYYMMDD, PATH)
	SELECT CONVERT(VARCHAR(10), GETDATE(), 112), 'TBL_MCSS_ATTRIBUTE_CATALOG'
	
	DROP TABLE TBL_MCSS_ATTRIBUTE_CATALOG
	CREATE TABLE TBL_MCSS_ATTRIBUTE_CATALOG(
		MODELNO		INT NOT NULL
		, ATTRIBUTE_ID	INT NOT NULL
		, ATTRIBUTE_ELEMENT_ID	INT NOT NULL
		, ATTRIBUTE_VALUE	VARCHAR(500)
		, INS_DATE		DATETIME
		, UPD_DATE		DATETIME
		, EXTRACT_DATE DATETIME DEFAULT GETDATE()
	)
	ALTER TABLE TBL_MCSS_ATTRIBUTE_CATALOG ADD CONSTRAINT [CL_TBL_MCSS_ATTRIBUTE_CATALOG] PRIMARY KEY CLUSTERED(MODELNO ASC, ATTRIBUTE_ID ASC, ATTRIBUTE_ELEMENT_ID ASC)
	CREATE NONCLUSTERED INDEX [NCL_TBL_MCSS_ATTRIBUTE_CATALOG] ON TBL_MCSS_ATTRIBUTE_CATALOG(ATTRIBUTE_ID ASC, ATTRIBUTE_ELEMENT_ID ASC)
	
	INSERT INTO TBL_MCSS_ATTRIBUTE_CATALOG(MODELNO, ATTRIBUTE_ID, ATTRIBUTE_ELEMENT_ID, ATTRIBUTE_VALUE, INS_DATE, UPD_DATE)
	SELECT A.G_MODELNO, A.ATTRIBUTE_ID, A.ATTRIBUTE_ELEMENT_ID, ISNULL((CASE WHEN USE_CLASS_CODE = '2' THEN ATTRIBUTE_VALUE ELSE '' END), ''), A.INS_DATE, A.UPD_DATE
	FROM GOODS_CATALOG_ATTRIBUTE A
		INNER JOIN TBL_MCSS_CATALOG B ON MODELNO = G_MODELNO
		INNER JOIN TBL_MCSS_ATTRIBUTE C ON C.ATTRIBUTE_ID = A.ATTRIBUTE_ID
		INNER JOIN TBL_MCSS_ATTRIBUTE_ELEMENT D ON D.ATTRIBUTE_ID = A.ATTRIBUTE_ID AND D.ATTRIBUTE_ELEMENT_ID = A.ATTRIBUTE_ELEMENT_ID
	WHERE A.DEL_YN = 'N' AND C.DEL_YN = 'N' AND D.DEL_YN = 'N'
	OPTION (MAXDOP 1)
	
	UPDATE TBL_MCSS_LOG
	SET ENDDATE = GETDATE()
	WHERE YYYYMMDD = CONVERT(VARCHAR(10), GETDATE(), 112) AND PATH = 'TBL_MCSS_ATTRIBUTE_CATALOG'
	------------------------------------------------------------------------------------------
	
	------------------------------------------------------------------------------------------
	-- ¸ÅÄª EP (ELOC)
	INSERT INTO TBL_MCSS_LOG(YYYYMMDD, PATH)
	SELECT CONVERT(VARCHAR(10), GETDATE(), 112), 'TBL_MCSS_EP_11ST'
	
	DROP TABLE TBL_MCSS_EP_11ST
	SELECT PL_MODELNO, PL_GOODSCODE, GETDATE() EXTRACT_DATE
	INTO TBL_MCSS_EP_11ST
	FROM PRICELIST
	WHERE PL_MODELNO IN (SELECT MODELNO FROM TBL_MCSS_CATALOG)
	  AND PL_VCODE = 5910 AND ISNULL(PL_GOODSNM, '') <> '' AND PL_STATUS NOT IN ('3','4','5') AND PL_SRVFLAG IN ('0','R','L','B')
	OPTION (MAXDOP 1)
	
	CREATE NONCLUSTERED INDEX [NCL_TBL_MCSS_EP_11ST] ON TBL_MCSS_EP_11ST(PL_MODELNO ASC)
	
	UPDATE TBL_MCSS_LOG
	SET ENDDATE = GETDATE()
	WHERE YYYYMMDD = CONVERT(VARCHAR(10), GETDATE(), 112) AND PATH = 'TBL_MCSS_EP_11ST'
	------------------------------------------------------------------------------------------
END
