/* *************************************************************************
 * NAME : dbo.UDP_GOODS_ADDCATE_CHANGE
 * TYPE : PROCEDURE (SQL_STORED_PROCEDURE)
 * TIME : Create: 2006-12-28 18:06:05.84
 *        Modify: 2018-05-03 17:23:35.8
 *        Backup: 20180521_1739
 ************************************************************************* */


CREATE PROC [DBO].[UDP_GOODS_ADDCATE_CHANGE]
	@O_CATE VARCHAR(8),
	@A_CATE VARCHAR(8),
	@N_CATE VARCHAR(8)
AS
BEGIN
	SET NOCOUNT ON;
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

	DECLARE @T TABLE
	(
		IDX INT IDENTITY(1,1),
		MODELNO INT 
	)

	INSERT INTO @T(MODELNO)
	SELECT GA_MODELNO
	FROM GOODS_ADDCATE
	WHERE GA_MODELNO IN (
		SELECT G_MODELNO
		FROM GOODS
		WHERE G_CATEGORY=@O_CATE
		)
		AND GA_CATEGORY=@A_CATE

	DECLARE @MODELNO INT
	DECLARE @MAX INT
	SELECT @MAX = @@ROWCOUNT
	PRINT @MAX
	WHILE @MAX<>0
	BEGIN
		SELECT @MODELNO=MODELNO
		FROM @T 
		WHERE IDX=@MAX

		UPDATE GOODS
		SET G_CATEGORY=@N_CATE, G_FLAG='1'
		WHERE G_MODELNO=@MODELNO
		
		SET @MAX = @MAX-1
	END
	PRINT '카테고리변경완료 : ' + @O_CATE + '-->' + @N_CATE
END
