/* *************************************************************************
 * NAME : dbo.UDP_MP_GOODS_ICON_ATTRIBUTE
 * TYPE : PROCEDURE (SQL_STORED_PROCEDURE)
 * TIME : Create: 2016-04-05 20:24:13.127
 *        Modify: 2018-05-03 17:23:35.103
 *        Backup: 20180521_1739
 ************************************************************************* */


CREATE PROC [DBO].[UDP_MP_GOODS_ICON_ATTRIBUTE]
	@MODELNO INT
AS
BEGIN
	SET NOCOUNT ON;
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
	
	DECLARE @CATEGORY VARCHAR(12)
	SELECT @CATEGORY = G_CATEGORY
	FROM GOODS
	WHERE G_MODELNO = @MODELNO;

	SELECT ICONNO
	FROM (
		SELECT DISTINCT CAST(ICONNO AS VARCHAR(20)) ICONNO, SORT
		--SELECT DISTINCT A.G_MODELNO, SPECNO
		FROM GOODS_CATALOG_ATTRIBUTE A
			INNER JOIN GOODS_ATTRIBUTE B ON A.ATTRIBUTE_ID = B.ATTRIBUTE_ID
			INNER JOIN GOODS_ATTRIBUTE_ELEMENT C ON A.ATTRIBUTE_ID = C.ATTRIBUTE_ID AND A.ATTRIBUTE_ELEMENT_ID = C.ATTRIBUTE_ELEMENT_ID
			INNER JOIN GOODS_CATEGORY_ATTRIBUTE D ON A.ATTRIBUTE_ID = D.ATTRIBUTE_ID AND D.CATEGORY IN (SELECT TOP 1 CATEGORY FROM GOODS_CATEGORY_ATTRIBUTE WHERE CATEGORY = LEFT(@CATEGORY, 4) OR CATEGORY = LEFT(@CATEGORY, 6) OR CATEGORY = LEFT(@CATEGORY, 8) ORDER BY LEN(CATEGORY) DESC)
			INNER JOIN TBL_FUNC_IMG E ON ICONNO = SEQ AND B.CATEGORY = G_CATEGORY
		WHERE A.DEL_YN = 'N'
		  AND B.DEL_YN = 'N'
		  AND C.DEL_YN = 'N'
		  AND G_MODELNO = @MODELNO
		  AND SORT > 0
	) A
	ORDER BY SORT
END
