/* *************************************************************************
 * NAME : dbo.UDF_GOODS_EXTERNAL_NON_ATTRIBUTE_WITH
 * TYPE : FUNCTION (SQL_INLINE_TABLE_VALUED_FUNCTION)
 * TIME : Create: 2017-04-12 14:32:00.017
 *        Modify: 2018-05-03 17:23:35.837
 *        Backup: 20180521_1739
 ************************************************************************* */


CREATE FUNCTION UDF_GOODS_EXTERNAL_NON_ATTRIBUTE_WITH
(	
	@SHOP_CODE INT,
	@CATEGORY VARCHAR(12)
)
RETURNS TABLE
AS
RETURN
(
	WITH
		TARGET(G_MODELNO, G_CATEGORY) AS (
			SELECT DISTINCT G_MODELNO, G_CATEGORY
			FROM GOODS WITH (READUNCOMMITTED)
				INNER JOIN TBL_EXTERNAL_NON_TARGET WITH (READUNCOMMITTED) ON SHOP_CODE = @SHOP_CODE AND MODELNO = G_MODELNO
			WHERE G_CATEGORY LIKE @CATEGORY + '%'
			  /* AND EXISTS (SELECT TOP 1 1 FROM PRICELIST WITH (READUNCOMMITTED) WHERE PL_VCODE = @SHOP_CODE AND PL_MODELNO = G_MODELNO AND PL_SRVFLAG = '4' AND PL_STATUS = '4') */),
			--SELECT DISTINCT B.G_MODELNO, B.G_CATEGORY
			--FROM TBL_EXTERNAL_SEND_TARGET_PLNO A WITH (READUNCOMMITTED)
			--	INNER JOIN GOODS B WITH (READUNCOMMITTED) ON B.G_MODELNO = A.PL_MODELNO
			--	LEFT JOIN TBL_EXTERNAL_SEND_TARGET_MODEL C WITH (READUNCOMMITTED) ON C.SHOP_CODE = @SHOP_CODE AND MODELNO = A.PL_MODELNO
			--WHERE A.SHOP_CODE = @SHOP_CODE AND A.PL_MODELNO > 0 AND MODELNO IS NULL
			--  AND G_CATEGORY LIKE @CATEGORY + '%'
			--  /* AND EXISTS (SELECT TOP 1 1 FROM PRICELIST WITH (READUNCOMMITTED) WHERE PL_VCODE = @SHOP_CODE AND PL_MODELNO = G_MODELNO AND PL_SRVFLAG = '4' AND PL_STATUS = '4') */),
		ATTRIBUTE_TARGET(G_MODELNO) AS (
			SELECT DISTINCT A.G_MODELNO
			FROM TARGET A WITH (READUNCOMMITTED)
				INNER JOIN TBL_EXTERNAL_ATTRIBUTE B WITH (READUNCOMMITTED) ON B.SHOP_CODE = @SHOP_CODE AND B.CATEGORY = LEFT(G_CATEGORY, LEN(B.CATEGORY))
				--INNER JOIN GOODS_CATEGORY_ATTRIBUTE C WITH (READUNCOMMITTED) ON C.ATTRIBUTE_ID = B.ATTRIBUTE_ID AND B.CATEGORY IN (SELECT TOP 1 CATEGORY FROM GOODS_CATEGORY_ATTRIBUTE WITH (READUNCOMMITTED) WHERE CATEGORY = LEFT(G_CATEGORY, 4) OR CATEGORY = LEFT(G_CATEGORY, 6) OR CATEGORY = LEFT(G_CATEGORY, 8) ORDER BY LEN(CATEGORY) DESC)
				INNER JOIN GOODS_CATALOG_ATTRIBUTE D WITH (READUNCOMMITTED) ON D.G_MODELNO = A.G_MODELNO AND D.ATTRIBUTE_ID = B.ATTRIBUTE_ID AND DEL_YN = 'N')
	SELECT G_MODELNO
	FROM TARGET WITH (READUNCOMMITTED)
	WHERE G_MODELNO NOT IN (SELECT G_MODELNO FROM ATTRIBUTE_TARGET WITH (READUNCOMMITTED))
)
