/* *************************************************************************
 * NAME : dbo.UDP_ENURI_MAKERBRAND_MATCHING
 * TYPE : PROCEDURE (SQL_STORED_PROCEDURE)
 * TIME : Create: 2015-03-12 15:32:40.4
 *        Modify: 2018-05-03 17:23:35.753
 *        Backup: 20180521_1739
 ************************************************************************* */


CREATE PROC [DBO].[UDP_ENURI_MAKERBRAND_MATCHING]
AS
BEGIN
	SET NOCOUNT ON;
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
	
	-- *************************************************************
	-- 에누리 제조사 기준
	SELECT MAKER_ID ENURI_ID, MAKER_NM ENURI_NM,
		(SELECT TOP 1 EBAY_MAKER_ID
		 FROM TBL_EBAY_MATCHING_MAKER A
			INNER JOIN TBL_EBAY_MAKER B ON EBAY_MAKER_ID = B.MAKER_ID WHERE ENURI_MAKER_ID = C.MAKER_ID AND A.DEL_YN = 'N' AND B.DEL_YN = 'N') EBAY_ID
	INTO #TEMP_MAKER_MATCHING
	FROM TBL_ENURI_MAKER C
	WHERE DEL_YN = 'N' AND
		((UPD_DATE >= CAST(CAST(DATEADD(DAY, -1, GETDATE()) AS VARCHAR(10)) AS SMALLDATETIME) AND UPD_DATE < CAST(CAST(GETDATE() AS VARCHAR(10)) AS SMALLDATETIME)) OR
		 (INS_DATE >= CAST(CAST(DATEADD(DAY, -1, GETDATE()) AS VARCHAR(10)) AS SMALLDATETIME) AND INS_DATE < CAST(CAST(GETDATE() AS VARCHAR(10)) AS SMALLDATETIME)))
	OPTION (MAXDOP 1)
	
	DELETE FROM #TEMP_MAKER_MATCHING WHERE EBAY_ID IS NOT NULL
	
	UPDATE #TEMP_MAKER_MATCHING
	SET EBAY_ID = (
		SELECT TOP 1 MAKER_ID
		FROM TBL_EBAY_MAKER
		WHERE DEL_YN = 'N' AND MAKER_NM IS NOT NULL AND (
			MAKER_NM = REPLACE(CASE WHEN CHARINDEX('[', ENURI_NM) > 0 AND CHARINDEX(']', ENURI_NM) > 0 AND CHARINDEX(']', ENURI_NM) > CHARINDEX('[', ENURI_NM) THEN SUBSTRING(ENURI_NM, CHARINDEX('[', ENURI_NM) + 1, CHARINDEX(']', ENURI_NM) - CHARINDEX('[', ENURI_NM) - 1) ELSE NULL END, '''', '''''') OR
			MAKER_NM = REPLACE(CASE WHEN CHARINDEX('(주)', ENURI_NM) > 0 THEN REPLACE(ENURI_NM, '(주)', '') ELSE NULL END, '''', '''''') OR
			MAKER_NM = REPLACE(ENURI_NM, '''', ''''''))
		ORDER BY MAKER_NM)
	OPTION (MAXDOP 1)
	
	UPDATE TBL_EBAY_MATCHING_MAKER
	SET DEL_YN = 'N', UPD_DATE = GETDATE(), UPD_OPRT = 'Lab_batch'
	FROM TBL_EBAY_MATCHING_MAKER
		INNER JOIN #TEMP_MAKER_MATCHING ON ENURI_ID = ENURI_MAKER_ID AND EBAY_ID = EBAY_MAKER_ID
	WHERE DEL_YN = 'Y' AND EBAY_ID IS NOT NULL
	
	INSERT INTO TBL_EBAY_MATCHING_MAKER (ENURI_MAKER_ID, EBAY_MAKER_ID, DEL_YN, INS_DATE, INS_OPRT)
	SELECT ENURI_ID, EBAY_ID, 'N', GETDATE(), 'Lab_batch'
	FROM #TEMP_MAKER_MATCHING
		LEFT JOIN TBL_EBAY_MATCHING_MAKER ON ENURI_ID = ENURI_MAKER_ID AND EBAY_ID = EBAY_MAKER_ID
	WHERE ENURI_MAKER_ID IS NULL AND EBAY_ID IS NOT NULL
	-- *************************************************************
	
	
	-- *************************************************************
	-- 에누리 브랜드 기준
	SELECT BRAND_ID ENURI_ID, BRAND_NM ENURI_NM,
		(SELECT TOP 1 EBAY_BRAND_ID
		 FROM TBL_EBAY_MATCHING_BRAND A
			INNER JOIN TBL_EBAY_BRAND B ON EBAY_BRAND_ID = B.BRAND_ID WHERE ENURI_BRAND_ID = C.BRAND_ID AND A.DEL_YN = 'N' AND B.DEL_YN = 'N') EBAY_ID
	INTO #TEMP_BRAND_MATCHING
	FROM TBL_ENURI_BRAND C
	WHERE DEL_YN = 'N' AND
		((UPD_DATE >= CAST(CAST(DATEADD(DAY, -1, GETDATE()) AS VARCHAR(10)) AS SMALLDATETIME) AND UPD_DATE < CAST(CAST(GETDATE() AS VARCHAR(10)) AS SMALLDATETIME)) OR
		 (INS_DATE >= CAST(CAST(DATEADD(DAY, -1, GETDATE()) AS VARCHAR(10)) AS SMALLDATETIME) AND INS_DATE < CAST(CAST(GETDATE() AS VARCHAR(10)) AS SMALLDATETIME)))
	OPTION (MAXDOP 1)
	
	DELETE FROM #TEMP_BRAND_MATCHING WHERE EBAY_ID IS NOT NULL
	
	UPDATE #TEMP_BRAND_MATCHING
	SET EBAY_ID = (
		SELECT TOP 1 BRAND_ID
		FROM TBL_EBAY_BRAND
		WHERE DEL_YN = 'N' AND BRAND_NM IS NOT NULL AND (
			BRAND_NM = REPLACE(CASE WHEN CHARINDEX('[', ENURI_NM) > 0 AND CHARINDEX(']', ENURI_NM) > 0 AND CHARINDEX(']', ENURI_NM) > CHARINDEX('[', ENURI_NM) THEN SUBSTRING(ENURI_NM, CHARINDEX('[', ENURI_NM) + 1, CHARINDEX(']', ENURI_NM) - CHARINDEX('[', ENURI_NM) - 1) ELSE NULL END, '''', '''''') OR
			BRAND_NM = REPLACE(CASE WHEN CHARINDEX('(주)', ENURI_NM) > 0 THEN REPLACE(ENURI_NM, '(주)', '') ELSE NULL END, '''', '''''') OR
			BRAND_NM = REPLACE(ENURI_NM, '''', ''''''))
		ORDER BY BRAND_NM)
	OPTION (MAXDOP 1)
	
	UPDATE TBL_EBAY_MATCHING_BRAND
	SET DEL_YN = 'N', UPD_DATE = GETDATE(), UPD_OPRT = 'Lab_batch'
	FROM TBL_EBAY_MATCHING_BRAND
		INNER JOIN #TEMP_BRAND_MATCHING ON ENURI_ID = ENURI_BRAND_ID AND EBAY_ID = EBAY_BRAND_ID
	WHERE DEL_YN = 'Y' AND EBAY_ID IS NOT NULL
	
	INSERT INTO TBL_EBAY_MATCHING_BRAND (ENURI_BRAND_ID, EBAY_BRAND_ID, DEL_YN, INS_DATE, INS_OPRT)
	SELECT ENURI_ID, EBAY_ID, 'N', GETDATE(), 'Lab_batch'
	FROM #TEMP_BRAND_MATCHING
		LEFT JOIN TBL_EBAY_MATCHING_BRAND ON ENURI_ID = ENURI_BRAND_ID AND EBAY_ID = EBAY_BRAND_ID
	WHERE ENURI_BRAND_ID IS NULL AND EBAY_ID IS NOT NULL
	-- *************************************************************
END
