/* *************************************************************************
 * NAME : dbo.UDF_GOODS_EXTERNAL_ATTRIBUTE
 * TYPE : FUNCTION (SQL_INLINE_TABLE_VALUED_FUNCTION)
 * TIME : Create: 2017-03-09 16:51:44.227
 *        Modify: 2018-05-03 17:23:34.76
 *        Backup: 20180521_1739
 ************************************************************************* */


CREATE FUNCTION UDF_GOODS_EXTERNAL_ATTRIBUTE
(	
	@SHOP_CODE INT,
	@CATEGORY VARCHAR(12),
	@CNT SMALLINT
)
RETURNS TABLE
AS
RETURN
(
	SELECT A.G_MODELNO
	FROM (
		SELECT A.G_MODELNO, COUNT(DISTINCT B.ATTRIBUTE_ID) EXTERNAL_ATTRIBUTE_CNT
		FROM GOODS A WITH (READUNCOMMITTED)
			INNER JOIN TBL_EXTERNAL_ATTRIBUTE B WITH (READUNCOMMITTED) ON B.SHOP_CODE = @SHOP_CODE AND B.CATEGORY = LEFT(G_CATEGORY, LEN(B.CATEGORY))
			INNER JOIN GOODS_CATEGORY_ATTRIBUTE C WITH (READUNCOMMITTED) ON C.ATTRIBUTE_ID = B.ATTRIBUTE_ID AND C.CATEGORY IN (SELECT TOP 1 CATEGORY FROM GOODS_CATEGORY_ATTRIBUTE WITH (READUNCOMMITTED) WHERE CATEGORY = LEFT(G_CATEGORY, 4) OR CATEGORY = LEFT(G_CATEGORY, 6) OR CATEGORY = LEFT(G_CATEGORY, 8) ORDER BY LEN(CATEGORY) DESC)
			INNER JOIN GOODS_CATALOG_ATTRIBUTE D WITH (READUNCOMMITTED) ON D.G_MODELNO = A.G_MODELNO AND D.ATTRIBUTE_ID = B.ATTRIBUTE_ID AND DEL_YN = 'N'
		WHERE G_CATEGORY LIKE @CATEGORY + '%'
		  AND EXISTS (SELECT TOP 1 1 FROM PRICELIST WITH (READUNCOMMITTED) WHERE PL_VCODE = @SHOP_CODE AND PL_MODELNO = A.G_MODELNO AND PL_SRVFLAG = '4' AND PL_STATUS = '4')
		GROUP BY A.G_MODELNO
	) A
	WHERE EXTERNAL_ATTRIBUTE_CNT = @CNT
)
