/* *************************************************************************
 * NAME : dbo.UDP_WEBB_INS
 * TYPE : PROCEDURE (SQL_STORED_PROCEDURE)
 * TIME : Create: 2008-07-16 14:51:07.91
 *        Modify: 2018-05-03 17:23:34.467
 *        Backup: 20180521_1739
 ************************************************************************* */

CREATE PROC [dbo].[UDP_WEBB_INS]

	@MODELNO		INT,
	@VCODE			INT,
	@PL_GOODSNM		NVARCHAR(200),
	@PRICE			MONEY,
	@URL			VARCHAR(500),
	@IMGURL		VARCHAR(250),
	@ACCOUNT_YN		CHAR(1),
	@FREEINTEREST		VARCHAR(50),
	@GOODSFACTORY	VARCHAR(50),
	@CATEGORY	VARCHAR(100),
	@GOODSCODE		VARCHAR(50),
	@DELIVERY		VARCHAR(100),
	@PRICE_CARD			MONEY,
	
	@PLNO		bigINT	OUTPUT,
	@iRETURN	INT 	OUTPUT
AS
BEGIN
	SET NOCOUNT ON
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
    If @MODELNO = 0  	
		begin
			set @CATEGORY = NURIBOTDB.dbo.UDF_TEST_RTN_CATE(@VCODE, @CATEGORY)	
		end
	
	If @DELIVERY = '무료배송' 
		begin 
			Insert Into pricelist (PL_MODELNO, PL_VCODE, PL_CATEGORY, PL_GOODSNM, PL_PRICE, PL_URL, PL_SRVFLAG, PL_STATUS, PL_IMGURL, PL_ACCOUNT_YN, PL_GOODSFACTORY, PL_GOODSCODE, PL_FREEINTEREST, PL_DELIVERYINFO, PL_RIGHTNLEFT, pl_authdate, pl_price_card)
			VALUES(@MODELNO, @VCODE, @CATEGORY, @PL_GOODSNM, @PRICE, @URL, dbo.UDF_TEST_RTN_SRVFLAG(@PL_GOODSNM), '2', @IMGURL, @ACCOUNT_YN, @GOODSFACTORY, @GOODSCODE, @FREEINTEREST, '무료배송', '1', getdate(), @PRICE_CARD)
		end
	else if @DELIVERY = ''	
		begin
			Insert Into pricelist (PL_MODELNO, PL_VCODE, PL_CATEGORY, PL_GOODSNM, PL_PRICE, PL_URL, PL_SRVFLAG, PL_STATUS, PL_IMGURL, PL_ACCOUNT_YN, PL_GOODSFACTORY, PL_GOODSCODE, PL_FREEINTEREST, PL_DELIVERYINFO, PL_RIGHTNLEFT, pl_authdate, pl_price_card)
			VALUES(@MODELNO, @VCODE, @CATEGORY, @PL_GOODSNM, @PRICE, @URL, dbo.UDF_TEST_RTN_SRVFLAG(@PL_GOODSNM), '2', @IMGURL, @ACCOUNT_YN, @GOODSFACTORY, @GOODSCODE, @FREEINTEREST,	'유무료', '2', getdate(), @PRICE_CARD)
		end 
	else
		begin
			Insert Into pricelist (PL_MODELNO, PL_VCODE, PL_CATEGORY, PL_GOODSNM, PL_PRICE, PL_URL, PL_SRVFLAG, PL_STATUS, PL_IMGURL, PL_ACCOUNT_YN, PL_GOODSFACTORY, PL_GOODSCODE, PL_FREEINTEREST, PL_DELIVERYINFO, PL_RIGHTNLEFT, pl_authdate, pl_price_card)
			VALUES(@MODELNO, @VCODE, @CATEGORY, @PL_GOODSNM, @PRICE, @URL, dbo.UDF_TEST_RTN_SRVFLAG(@PL_GOODSNM), '2', @IMGURL, @ACCOUNT_YN, @GOODSFACTORY, @GOODSCODE, @FREEINTEREST,	@DELIVERY, '2', getdate(), @PRICE_CARD)
		end 

	SET @PLNO=SCOPE_IDENTITY()

	IF @@ERROR<>0
	BEGIN
		SET @iRETURN = 99
	END
	ELSE
	BEGIN
		SET @iRETURN = 0
	END

END


