/* *************************************************************************
 * NAME : dbo.UDP_MP_TERMDIC_ATTRIBUTE
 * TYPE : PROCEDURE (SQL_STORED_PROCEDURE)
 * TIME : Create: 2016-06-22 11:32:37.207
 *        Modify: 2018-05-03 17:23:36.137
 *        Backup: 20180521_1739
 ************************************************************************* */


CREATE PROCEDURE [DBO].[UDP_MP_TERMDIC_ATTRIBUTE]
	@CATEGORY CHAR(4)
AS
BEGIN
	SET NOCOUNT ON;
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;


	SET TRANSACTION ISOLATION LEVEL READ COMMITTED;
	--##################################################################
	DECLARE @QRY VARCHAR(8000)
	SET @QRY = 'DELETE OPENQUERY(ORADB, ''SELECT CA_CODE, ATTRIBUTE_ID, ATTRIBUTE_ELEMENT_ID, REF_KB_NO FROM TBL_TERMDIC_ATTRIBUTE WHERE CA_CODE = ''''' + @CATEGORY + ''''''')'
	EXEC (@QRY)

	INSERT OPENQUERY(ORADB, 'SELECT CA_CODE, ATTRIBUTE_ID, ATTRIBUTE_ELEMENT_ID, REF_KB_NO FROM TBL_TERMDIC_ATTRIBUTE')
	SELECT CATEGORY, ATTRIBUTE_ID, ATTRIBUTE_ELEMENT_ID, REF_KB_NO
	FROM TBL_TERMDIC_ATTRIBUTE
	WHERE CATEGORY = @CATEGORY
	--##################################################################
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
END
