/* *************************************************************************
 * NAME : dbo.UDP_LIST_VCODE
 * TYPE : PROCEDURE (SQL_STORED_PROCEDURE)
 * TIME : Create: 2006-09-20 09:55:49.137
 *        Modify: 2018-05-03 17:23:34.907
 *        Backup: 20180521_1739
 ************************************************************************* */









CREATE         PROC UDP_LIST_VCODE
	@PL_VCODE INT
AS
BEGIN

	SET NOCOUNT ON
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
	DECLARE @ATYPE VARCHAR(2)
	SET @ATYPE=''
	EXEC NURIBOT_195.NURIBOTDB.DBO.UDP_NB_ATYPE @PL_VCODE, @ATYPE OUTPUT
	IF( @ATYPE='WB' or  @PL_VCODE = '4027') --GROUP BY GOODSCODE
	BEGIN

	
		SELECT @PL_VCODE AS NBD_VCODE, 
			MAX(PL_CATEGORY) AS NBD_CATEGORY, 
			NULL AS NBD_CATENO, 
			MAX(PL_GOODSNM) AS NBD_GOODSNM, 
			MAX(PL_PRICE) AS  NBD_PRICE,
			 
			MAX(PL_URL) AS NBD_URL, 
			'0' AS PL_FLAG, 
			GETDATE() AS NBD_DATE, 
			MAX(PL_RIGHTNLEFT) AS NBD_RIGHTNLEFT, 
			MAX(PL_IMGURL) AS NBD_IMGURL,
	
			MAX(PL_COUPON) AS NBD_COUPON, 
			0 AS NBD_DIRECTPRICE, 
			MAX(PL_ACCOUNT_YN) AS NBD_ACCOUNT_YN,
			MAX(PL_DELIVERYINFO) AS NBD_DELIVERYINFO,
			MAX(PL_GOODSFACTORY) AS NBD_FACTORY, 
	
			MAX(PL_GOODSCODE) AS NBD_GOODSCODE,
			NULL AS NBD_MODELNO, 
			NULL AS NBD_MAINCATE, 
			NULL AS NBD_MODEL_DATE,
			'0' AS PL_STATUS 
			--MAX(PL_STATUS) AS NBD_STATUS
		FROM PRICELIST (nolock) 
		WHERE PL_VCODE = @PL_VCODE
			AND PL_STATUS NOT IN ('3','4','5')
			AND PL_GOODSNM_CS<> CHECKSUM('')
		GROUP BY PL_GOODSCODE 
	END
	ELSE
	BEGIN		

		SELECT @PL_VCODE AS NBD_VCODE, 
			MAX(PL_CATEGORY) AS NBD_CATEGORY, 
			NULL AS NBD_CATENO, 
			MAX(PL_GOODSNM) AS NBD_GOODSNM, 
			MAX(PL_PRICE) AS  NBD_PRICE,
			 
			MAX(PL_URL) AS NBD_URL, 
			'0' AS PL_FLAG, 
			GETDATE() AS NBD_DATE, 
			MAX(PL_RIGHTNLEFT) AS NBD_RIGHTNLEFT, 
			MAX(PL_IMGURL) AS NBD_IMGURL,
	
			MAX(PL_COUPON) AS NBD_COUPON, 
			0 AS NBD_DIRECTPRICE, 
			MAX(PL_ACCOUNT_YN) AS NBD_ACCOUNT_YN,
			MAX(PL_DELIVERYINFO) AS NBD_DELIVERYINFO,
			MAX(PL_GOODSFACTORY) AS NBD_FACTORY, 
	
			MAX(PL_GOODSCODE) AS NBD_GOODSCODE,
			NULL AS NBD_MODELNO, 
			NULL AS NBD_MAINCATE, 
			NULL AS NBD_MODEL_DATE,
			'0' AS PL_STATUS
			--MAX(PL_STATUS) AS NBD_STATUS
		FROM PRICELIST (nolock)
		WHERE PL_VCODE = @PL_VCODE
			AND PL_STATUS NOT IN ('3','4','5')
			AND PL_GOODSNM_CS<> CHECKSUM('')
		GROUP BY PL_GOODSNM 

	END

END








