/* *************************************************************************
 * NAME : dbo.UDP_MP_MCATE_ATTRIBUTE_VALUE
 * TYPE : PROCEDURE (SQL_STORED_PROCEDURE)
 * TIME : Create: 2016-04-05 20:34:00.817
 *        Modify: 2018-05-03 17:23:35.68
 *        Backup: 20180521_1739
 ************************************************************************* */


CREATE PROC [DBO].[UDP_MP_MCATE_ATTRIBUTE_VALUE]
	@CATEGORY VARCHAR(12)
AS
BEGIN
	SET NOCOUNT ON;
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
	
	SELECT [분류코드]		=	ISNULL(G_CATEGORY, '')
		 , [모델번호]		=	ISNULL(C.G_MODELNO, '')
		 , [속성ID]		=	ISNULL(C.ATTRIBUTE_ID, '')
		 , [관리속성명]	=	ISNULL(MANAGE_ATTRIBUTE_NM, '')
		 , [전시속성명]	=	ISNULL(GALLERY_ATTRIBUTE_NM, '')
		 , [속성노출]		=	ISNULL(IS_GALLERY_DISPLAY, '')
		 , [구분]		=	ISNULL(USE_CLASS_CODE, '')
		 , [대표ID]		=	ISNULL(GROUP_ATTRIBUTE_ID, '')
		 , [대표기호]		=	ISNULL(GROUP_CHAR, '')
		 , [속성원기호]	=	ISNULL(ELEMENT_CHAR, '')
		 , [속성원ID]		=	ISNULL(C.ATTRIBUTE_ELEMENT_ID, '')
		 , [속성원순서]	=	ISNULL(DISPLAY_ORDER, '')
		 , [속성원명]		=	ISNULL(ATTRIBUTE_ELEMENT, '')
		 , [속성원노출]	=	ISNULL(IS_DISPLAY, '')
		 , [속성값]		=	ISNULL(ATTRIBUTE_VALUE, '')
	FROM GOODS_ATTRIBUTE A
		INNER JOIN GOODS_ATTRIBUTE_ELEMENT B ON A.ATTRIBUTE_ID = B.ATTRIBUTE_ID
		INNER JOIN GOODS_CATALOG_ATTRIBUTE C ON B.ATTRIBUTE_ID = C.ATTRIBUTE_ID AND B.ATTRIBUTE_ELEMENT_ID = C.ATTRIBUTE_ELEMENT_ID
		INNER JOIN GOODS D ON C.G_MODELNO = D.G_MODELNO
	WHERE A.DEL_YN = 'N' AND B.DEL_YN = 'N' AND C.DEL_YN = 'N' AND CATEGORY = LEFT(@CATEGORY, 4) AND G_CATEGORY LIKE @CATEGORY + '%'
	--AND USE_CLASS_CODE = '2'
	--AND G_CATEGORY LIKE '035951%'
	--AND MANAGE_ATTRIBUTE_NM LIKE '%브랜드%'
	--AND G_MALLCNT>0-- : 서비스 상품만
	ORDER BY [속성ID], [속성원ID], [속성원순서], [분류코드], [모델번호]
	OPTION (MAXDOP 1)
END
