/* *************************************************************************
 * NAME : dbo.USP_PRICELIST_GLOBAL
 * TYPE : PROCEDURE (SQL_STORED_PROCEDURE)
 * TIME : Create: 2014-05-22 18:18:30.67
 *        Modify: 2018-05-03 17:23:34.347
 *        Backup: 20180521_1739
 ************************************************************************* */


CREATE PROC [dbo].[USP_PRICELIST_GLOBAL]
	@PL_CATEGORY VARCHAR(8)
AS
BEGIN
	SET NOCOUNT ON
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
	
	SELECT PL_NO
	INTO #TEMP
	FROM PRICELIST
	WHERE PL_AIRCONFEETYPE <> '6'  
	  AND (PL_GOODSNM LIKE '%해외%'       OR
		   PL_GOODSNM LIKE '%글로벌셀러%' OR
		   PL_GOODSNM LIKE '%글로벌쇼핑%' OR
		   PL_GOODSNM LIKE '%미국직배송%' OR
		   PL_GOODSNM LIKE '%구매대행%'   OR
		   PL_GOODSNM LIKE '%아마존베이%')
	  AND PL_CATEGORY LIKE @PL_CATEGORY + '%'
	  AND PL_MODELNO > 0
      AND PL_SRVFLAG IN ('0','R','L') 
      AND (PL_STATUS < '3' OR PL_STATUS > '5')
	OPTION (MAXDOP 3)

	UPDATE PRICELIST
	SET PL_STATUS = (CASE WHEN PL_STATUS < '3' THEN '1' ELSE PL_STATUS END), PL_DATE = (CASE WHEN PL_STATUS >= '8' THEN GETDATE() ELSE PL_DATE END),
		PL_AIRCONFEETYPE = '6'
	WHERE PL_NO IN (SELECT PL_NO FROM #TEMP)
	OPTION (MAXDOP 3)
END 
