/* *************************************************************************
 * NAME : dbo.UDP_MP_GOODS_REFER_SYNC
 * TYPE : PROCEDURE (SQL_STORED_PROCEDURE)
 * TIME : Create: 2016-11-09 11:23:21.397
 *        Modify: 2018-05-03 17:23:35.16
 *        Backup: 20180521_1739
 ************************************************************************* */


CREATE PROCEDURE [DBO].[UDP_MP_GOODS_REFER_SYNC]
AS
BEGIN
	SET NOCOUNT ON;
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

	SELECT MODELNO, REFERMODELNO
	INTO #ORA_REFER
	FROM OPENQUERY(ORADB, 'SELECT DISTINCT MODELNO, REFERMODELNO FROM TBL_REFER_GOODS')
	

	SET TRANSACTION ISOLATION LEVEL READ COMMITTED;
	--##################################################################
	-- 오라클 추가
	INSERT OPENQUERY(ORADB, 'SELECT MODELNO, REFERMODELNO FROM TBL_REFER_GOODS')
	SELECT A.MODELNO, A.REFERMODELNO
	FROM TBL_REFER_GOODS A WITH (READUNCOMMITTED)
		LEFT JOIN #ORA_REFER B ON A.MODELNO = B.MODELNO AND A.REFERMODELNO = B.REFERMODELNO
	WHERE B.MODELNO IS NULL
	
	-- 오라클 삭제
	DELETE OPENQUERY(ORADB, 'SELECT MODELNO, REFERMODELNO FROM TBL_REFER_GOODS')
	WHERE CAST(MODELNO AS VARCHAR(8)) + '-' + CAST(REFERMODELNO AS VARCHAR(8)) IN (
		SELECT CAST(A.MODELNO AS VARCHAR(8)) + '-' + CAST(A.REFERMODELNO AS VARCHAR(8))
		FROM #ORA_REFER A
			LEFT JOIN TBL_REFER_GOODS B WITH (READUNCOMMITTED) ON A.MODELNO = B.MODELNO AND A.REFERMODELNO = B.REFERMODELNO
		WHERE B.MODELNO IS NULL
	)
	--##################################################################
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
END
