/* *************************************************************************
 * NAME : dbo.USP_PRICELIST_SEL_19
 * TYPE : PROCEDURE (SQL_STORED_PROCEDURE)
 * TIME : Create: 2007-03-26 18:14:48.06
 *        Modify: 2018-05-03 17:23:36.053
 *        Backup: 20180521_1739
 ************************************************************************* */

CREATE PROC [dbo].[USP_PRICELIST_SEL_19]
	@PL_NO bigINT,
	@PL_VCODE INT,
	@PL_MODELNO	 INT,
	@PL_GOODSCODE VARCHAR(50)
AS
BEGIN
	SET NOCOUNT ON
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
	SELECT TOP 1
		PL_NO
	FROM PRICELIST
	WHERE PL_NO <> @PL_NO
		AND PL_VCODE = @PL_VCODE
		AND PL_MODELNO = @PL_MODELNO
		AND PL_GOODSCODE = @PL_GOODSCODE
		AND PL_GOODSCODE_CS = CHECKSUM(@PL_GOODSCODE)
		AND PL_STATUS <= '2'
	ORDER BY PL_PRICE ASC
END

