/* *************************************************************************
 * NAME : dbo.UDP_ELOC_EDU_PRICELIST_STATUS_MODIFY
 * TYPE : PROCEDURE (SQL_STORED_PROCEDURE)
 * TIME : Create: 2005-01-25 19:15:40.403
 *        Modify: 2018-05-03 17:23:35.313
 *        Backup: 20180521_1739
 ************************************************************************* */

CREATE   PROC UDP_ELOC_EDU_PRICELIST_STATUS_MODIFY
	@PL_NO			bigINT,
	@PL_VCODE		INT,
	@PL_STATUS		CHAR(1),

	@iRETURN	INT	OUTPUT		
AS 
BEGIN
	SET NOCOUNT ON
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
	DECLARE @TMPVCODE	INT
	SET @TMPVCODE=0
	SELECT @TMPVCODE = PL_VCODE
	FROM PRICELIST
	WHERE PL_NO=@PL_NO

	IF @TMPVCODE=0 -- 상품없음.
	BEGIN
		SET @iRETURN=1
	END
	ELSE
	BEGIN
		IF @TMPVCODE <> @PL_VCODE --해당업체가 아님.
		BEGIN
			SET @iRETURN=2 
		END
		ELSE
		BEGIN
			BEGIN TRAN

				UPDATE PRICELIST SET 
					PL_STATUS = @PL_STATUS, 
					PL_DATE = GETDATE()
				WHERE	PL_NO= @PL_NO

			IF @@ERROR<>0
			BEGIN
				SET @iRETURN=99
				ROLLBACK TRAN
			END
			ELSE
			BEGIN
				SET @iRETURN =0
				COMMIT TRAN
			END				

		END
	

	END
	
END
