/* *************************************************************************
 * NAME : dbo.UDP_VCODE_MIGRATION
 * TYPE : PROCEDURE (SQL_STORED_PROCEDURE)
 * TIME : Create: 2004-11-06 11:24:17.373
 *        Modify: 2018-05-03 17:23:35.197
 *        Backup: 20180521_1739
 ************************************************************************* */



CREATE PROC UDP_VCODE_MIGRATION

AS
BEGIN
	SET NOCOUNT ON
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

	DECLARE @MAX INT
	SELECT @MAX = MAX(IDX) FROM TBL_VCODE WITH (READUNCOMMITTED) 

	WHILE @MAX<>0
	BEGIN
		DECLARE @VCODE INT
		SELECT @VCODE = VCODE
		FROM TBL_VCODE WITH (READUNCOMMITTED) 
		WHERE IDX = @MAX


		SELECT MAX(PL_NO) AS PL_NO, PL_VCODE, PL_GOODSNM
		INTO #TBL_X
		FROM PRICELIST WITH (READUNCOMMITTED) 
		WHERE PL_VCODE = @VCODE
		GROUP BY PL_VCODE, PL_GOODSNM

		DELETE FROM PRICELIST
		WHERE PL_NO NOT IN ( SELECT PL_NO FROM #TBL_X )
			AND PL_VCODE =@VCODE

		DROP TABLE #TBL_X
		
		SET @MAX = @MAX-1
	END
	
END
