/* *************************************************************************
 * NAME : dbo.x_UDP_MP_MATCHING_TARGET_INS
 * TYPE : PROCEDURE (SQL_STORED_PROCEDURE)
 * TIME : Create: 2016-04-05 20:23:05.943
 *        Modify: 2018-05-04 12:42:39.51
 *        Backup: 20180521_1739
 ************************************************************************* */


CREATE PROC [DBO].[UDP_MP_MATCHING_TARGET_INS]
	@CATEGORY AS CHAR(4)
AS
BEGIN
	SET NOCOUNT ON;
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
	
	DELETE FROM TBL_MATCHING_TARGET
	WHERE CATEGORY = @CATEGORY;
	
	INSERT INTO TBL_MATCHING_TARGET (MODELNO, CATEGORY, DATA_KIND, PRICE_MIN, PRICE_MAX, ASSIGN_MM_ID, IS_BRACKET_IN, IS_BRACKET, IS_CONDITION, IS_BRAND, IS_FACTORY)
	SELECT G_MODELNO
	     , A.CATEGORY
		 , A.DATA_KIND
		 , PRICE_S_RANGE
		 , PRICE_E_RANGE
		 , MM_ID
		 , IS_BRACKET_IN
		 , IS_BRACKET
		 , IS_CONDITION
		 , IS_BRAND
		 , IS_FACTORY
	FROM (
		SELECT G_MODELNO
		     , MAX(A.CATEGORY) CATEGORY
			 , MAX(DATA_KIND) DATA_KIND
		FROM (
			-- 인기상품
			SELECT G_MODELNO
			     , A.CATEGORY
				 , DATA_KIND
			FROM (
				SELECT G_MODELNO
				     , LEFT(G_CATEGORY, 4) CATEGORY
					 , DENSE_RANK() OVER(PARTITION BY LEFT(G_CATEGORY, 4) ORDER BY G_POPULAR DESC, G_MODELNO DESC) RANK
				FROM GOODS
				WHERE LEFT(G_CATEGORY, 4) = @CATEGORY
			) A
				INNER JOIN SEARCHKEY_193.ENURIDB.DBO.TBL_CM_ALBA_SET_CONFIG B ON A.CATEGORY = B.CATEGORY AND DATA_KIND = 'P'
			WHERE B.CATEGORY IS NOT NULL
			  AND RANK >= POPULAR_S_RANGE
			  AND RANK <= POPULAR_E_RANGE
			-- 신상품
			UNION ALL
			SELECT G_MODELNO
			     , LEFT(G_CATEGORY, 4) CATEGORY
				 , DATA_KIND
			FROM GOODS
				INNER JOIN SEARCHKEY_193.ENURIDB.DBO.TBL_CM_ALBA_SET_CONFIG B ON LEFT(G_CATEGORY, 4) = B.CATEGORY AND DATA_KIND = 'N'
			WHERE B.CATEGORY IS NOT NULL
			  AND LEFT(G_CATEGORY, 4) = @CATEGORY
			  AND G_DATE >= CAST(CAST(DATEADD(D, -1 * POPULAR_E_RANGE, GETDATE()) AS VARCHAR(10)) AS SMALLDATETIME)
			  AND G_DATE < CAST(CAST(DATEADD(D, -1 * (POPULAR_S_RANGE - 1), GETDATE()) AS VARCHAR(10)) AS SMALLDATETIME)
		) A
		GROUP BY G_MODELNO
	) A
		INNER JOIN SEARCHKEY_193.ENURIDB.DBO.TBL_CM_ALBA_SET_CATE B ON A.CATEGORY = B.CATEGORY
		INNER JOIN SEARCHKEY_193.ENURIDB.DBO.TBL_CM_ALBA_SET_CONFIG C ON A.CATEGORY = C.CATEGORY AND A.DATA_KIND = C.DATA_KIND
		LEFT JOIN TBL_WEB_SEARCH_CONFIG D ON A.CATEGORY = D.CATEGORY AND D.DATA_KIND = 'I'
END
