/* *************************************************************************
 * NAME : dbo.UDP_MP_GOODS_UNIT_CHECK
 * TYPE : PROCEDURE (SQL_STORED_PROCEDURE)
 * TIME : Create: 2016-04-05 19:37:38.45
 *        Modify: 2018-05-03 17:23:35.783
 *        Backup: 20180521_1739
 ************************************************************************* */


CREATE PROC [DBO].[UDP_MP_GOODS_UNIT_CHECK]
	@MODELNO INT
AS
BEGIN
	SET NOCOUNT ON;
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
	
	SELECT G_STANDARD, G_AMOUNT, G_CHANGE, G_U_NIT
	FROM (
		SELECT DISTINCT ISNULL(G_STANDARD, 1) G_STANDARD, ISNULL(G_AMOUNT, 1) G_AMOUNT, ISNULL(G_CHANGE, '') G_CHANGE, LTRIM(RTRIM(ISNULL(G_U_NIT, ''))) G_U_NIT
		FROM GOODS WITH (READUNCOMMITTED)
		WHERE G_MODELNO_GROUP = (SELECT G_MODELNO_GROUP FROM GOODS WITH (READUNCOMMITTED) WHERE G_MODELNO = @MODELNO) AND G_MODELNO <> @MODELNO AND LTRIM(RTRIM(ISNULL(G_U_NIT, ''))) <> ''
		UNION ALL
		SELECT DISTINCT ISNULL(G_STANDARD, 1) G_STANDARD, ISNULL(G_AMOUNT, 1) G_AMOUNT, ISNULL(G_CHANGE, '') G_CHANGE, LTRIM(RTRIM(ISNULL(G_U_NIT, ''))) G_U_NIT
		FROM GOODS WITH (READUNCOMMITTED)
		WHERE G_MODELNO = @MODELNO AND LTRIM(RTRIM(ISNULL(G_U_NIT, ''))) <> ''
	) A
	GROUP BY G_STANDARD, G_AMOUNT, G_CHANGE, G_U_NIT
	HAVING COUNT(*) > 1
END
