/* *************************************************************************
 * NAME : dbo.UDP_MCSS_CATALOG_STEP2
 * TYPE : PROCEDURE (SQL_STORED_PROCEDURE)
 * TIME : Create: 2018-03-15 14:53:03.417
 *        Modify: 2018-05-03 17:23:35.843
 *        Backup: 20180521_1739
 ************************************************************************* */


CREATE PROC [DBO].[UDP_MCSS_CATALOG_STEP2]
	@SEQNO INT
AS
BEGIN
	SET NOCOUNT ON;
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
	
	DECLARE @QRY VARCHAR(8000)
	
	INSERT INTO TBL_MCSS_LOG(YYYYMMDD, PATH, MODE)
	SELECT CONVERT(VARCHAR(10), GETDATE(), 112), 'TBL_MCSS_CATALOG', @SEQNO
	
	------------------------------------------------------------------------------------------
	-- Ä«Å»·Î±× (ORACLE)
	SET @QRY =
	'
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
	
	INSERT INTO TBL_MCSS_CATALOG(MODELNO, CA_CODE, MODELNO_GROUP, MODELNM, CONDINAME, FACTORY, BRAND, CONSTRAIN, IMGCHK3, MALLCNT, MINPRICE, MAXPRICE, AVGPRICE, SPEC, KEYWORD2, FUNC, POPULAR, INS_DATE, UPD_DATE)
	SELECT MODELNO, CA_CODE, MODELNO_GROUP, MODELNM, CONDINAME, FACTORY, BRAND, CONSTRAIN, IMGCHK3, MALLCNT, MINPRICE, MAXPRICE, AVGPRICE, SPEC, KEYWORD2, CAST(FUNC AS VARCHAR(8000)) FUNC, POPULAR, C_DATE, MODDATE
	FROM OPENQUERY(ORADB, ''
		SELECT MODELNO, CA_CODE, MODELNO_GROUP, MODELNM, CONDINAME, FACTORY, BRAND, CONSTRAIN, IMGCHK3, MALLCNT, MINPRICE, MAXPRICE, AVGPRICE, SPEC, KEYWORD2, FUNC, POPULAR, C_DATE, MODDATE
		FROM TMPT_MCSS_GOODS
		WHERE MOD_20 = ' + CAST(@SEQNO AS VARCHAR(20)) + '
	'')
	OPTION (MAXDOP 1)
	'
	
	EXEC (@QRY)
	------------------------------------------------------------------------------------------
	
	UPDATE TBL_MCSS_LOG
	SET ENDDATE = GETDATE()
	WHERE YYYYMMDD = CONVERT(VARCHAR(10), GETDATE(), 112) AND PATH = 'TBL_MCSS_CATALOG' AND MODE = @SEQNO
END
