/* *************************************************************************
 * NAME : dbo.UDP_MP_PRICE_CASE_SEL_1
 * TYPE : PROCEDURE (SQL_STORED_PROCEDURE)
 * TIME : Create: 2015-06-12 10:51:06.65
 *        Modify: 2018-05-03 17:23:34.453
 *        Backup: 20180521_1739
 ************************************************************************* */


CREATE PROC [DBO].[UDP_MP_PRICE_CASE_SEL_1]
	@MODELNO	INT,
	@PLNO		BIGINT
AS
BEGIN
	SET NOCOUNT ON;
	SET TRANSACTION ISOLATION LEVEL  READ UNCOMMITTED;
	
	DECLARE @PC_MIN MONEY
	DECLARE @MOBILE_MIN MONEY

	DECLARE @PC_MAX MONEY
	DECLARE @MOBILE_MAX MONEY

	DECLARE @ROUTE VARCHAR(10)

	SET @ROUTE = ''

	-- 최저가 대상 모집단
	SELECT PL_PRICE, PL_INSTANCE_PRICE, PL_MOBILE_FLAG, PL_DELIVERYINFO
	INTO #TEMP_PRICELIST
	FROM PRICELIST WITH (READUNCOMMITTED)
	WHERE PL_MODELNO = @MODELNO AND PL_SRVFLAG IN ('0','R','L','B') AND ISNULL(PL_ESSTOCKFLAG, '0') = '0' AND PL_STATUS NOT IN ('3','4','5') AND OPTION_FLAG2 = '0'

	-- PC, MOBILE별 유료,무료 최저가 산출
	SELECT TYPE, MIN, AVG, MAX, PL_DELIVERYTYPE
	INTO #PRICELIST_PRICE
	FROM (
		SELECT 'PC' TYPE, ISNULL(MIN(PL_PRICE), 0) MIN, ISNULL(AVG(PL_PRICE), 0) AVG, ISNULL(MAX(PL_PRICE), 0) MAX, (CASE WHEN PL_DELIVERYINFO IN ('0','-1','[기본설치비무료 / 무료배송]','0원 이상 무료','0원이상무료','무료','무료배송') THEN '무료' ELSE '유료' END) PL_DELIVERYTYPE
		FROM #TEMP_PRICELIST
		WHERE PL_PRICE > 0 AND ISNULL(PL_MOBILE_FLAG, '0') <> '1'
		GROUP BY (CASE WHEN PL_DELIVERYINFO IN ('0','-1','[기본설치비무료 / 무료배송]','0원 이상 무료','0원이상무료','무료','무료배송') THEN '무료' ELSE '유료' END)
		UNION ALL
		SELECT 'MOBILE' TYPE, ISNULL(MIN(PL_INSTANCE_PRICE), 0) MIN, ISNULL(AVG(PL_INSTANCE_PRICE), 0) AVG, ISNULL(MAX(PL_INSTANCE_PRICE), 0) MAX, (CASE WHEN PL_DELIVERYINFO IN ('0','-1','[기본설치비무료 / 무료배송]','0원 이상 무료','0원이상무료','무료','무료배송') THEN '무료' ELSE '유료' END) PL_DELIVERYTYPE
		FROM #TEMP_PRICELIST
		WHERE PL_INSTANCE_PRICE > 0
		GROUP BY (CASE WHEN PL_DELIVERYINFO IN ('0','-1','[기본설치비무료 / 무료배송]','0원 이상 무료','0원이상무료','무료','무료배송') THEN '무료' ELSE '유료' END)
	) A

	-- PC 최저가
	SELECT @PC_MIN = MIN, @PC_MAX = MAX
	FROM #PRICELIST_PRICE
	WHERE TYPE = 'PC'
	  AND PL_DELIVERYTYPE IN (SELECT (CASE WHEN PL_DELIVERYINFO IN ('0','-1','[기본설치비무료 / 무료배송]','0원 이상 무료','0원이상무료','무료','무료배송') THEN '무료' ELSE '유료' END) FROM PRICELIST WHERE PL_NO = @PLNO)

	IF @PC_MIN IS NULL
		BEGIN
			SELECT @PC_MIN = MIN, @PC_MAX = MAX
			FROM #PRICELIST_PRICE
			WHERE TYPE = 'PC'	
		END

	-- MOBILE 최저가
	SELECT @MOBILE_MIN = MIN, @MOBILE_MAX = MAX
	FROM #PRICELIST_PRICE
	WHERE TYPE = 'MOBILE'
	  AND PL_DELIVERYTYPE IN (SELECT (CASE WHEN PL_DELIVERYINFO IN ('0','-1','[기본설치비무료 / 무료배송]','0원 이상 무료','0원이상무료','무료','무료배송') THEN '무료' ELSE '유료' END) FROM PRICELIST WHERE PL_NO = @PLNO)

	IF @MOBILE_MIN IS NULL
		BEGIN
			SELECT @MOBILE_MIN = MIN, @MOBILE_MAX = MAX
			FROM #PRICELIST_PRICE
			WHERE TYPE = 'MOBILE'	
		END

	-- PC, MOBILE 최저가가 없을 경우 우선순위에 따라 대체
	IF @PC_MIN IS NULL AND @MOBILE_MIN IS NULL
		BEGIN
			SET @ROUTE = '_BackUp'

			SELECT TOP 1 @PC_MIN = WG_MINPRICE, @PC_MAX = WG_MAXPRICE, @MOBILE_MIN = WG_MINPRICE, @MOBILE_MAX = WG_MAXPRICE
			FROM WEEKDATA.DBO.TBL_WEEK_GOODS
			WHERE WG_MODELNO = @MODELNO
			ORDER BY WG_SHOP_CNT DESC, WG_DATE_ID DESC
		END
	ELSE IF @PC_MIN IS NULL
		BEGIN
			SELECT @PC_MIN = @MOBILE_MIN, @PC_MAX = @MOBILE_MAX
		END
	ELSE IF @MOBILE_MIN IS NULL
		BEGIN
			SELECT @MOBILE_MIN = @PC_MIN, @MOBILE_MAX = @PC_MAX
		END

	SELECT TYPE, MIN, MAX
	FROM (
		SELECT 'PC' + @ROUTE TYPE, ISNULL(@PC_MIN, 0) MIN, ISNULL(@PC_MAX, 0) MAX
		UNION ALL
		SELECT 'MOBILE' + @ROUTE TYPE, ISNULL(@MOBILE_MIN, 0) MIN, ISNULL(@MOBILE_MAX, 0) MAX
	) A
END
