/* *************************************************************************
 * NAME : dbo.UDP_JOB_GOODS_STATIC
 * TYPE : PROCEDURE (SQL_STORED_PROCEDURE)
 * TIME : Create: 2005-06-29 13:48:06.53
 *        Modify: 2015-05-15 03:31:33.793
 *        Backup: 20180521_1739
 ************************************************************************* */





CREATE     PROC UDP_JOB_GOODS_STATIC
	@CATEGORY	VARCHAR(10),
	@SDATE		DATETIME,
	@EDATE		DATETIME,
	@FLAG		VARCHAR(1),
	
	@IRETURN	INT	OUTPUT
AS
BEGIN
	SET NOCOUNT ON
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
	
	SELECT @IRETURN = COUNT(*)
	FROM (
		SELECT JG_MODELNO
		FROM LOGDB_193.LOGDB.DBO.JOB_GOODS A 
		INNER JOIN ELOC2001..GOODS B WITH (READUNCOMMITTED)
		ON JG_MODELNO=G_MODELNO
			AND B.G_CATEGORY LIKE @CATEGORY + '%'
		WHERE JG_FLAG=@FLAG
			AND JG_DATE>@SDATE 
			AND JG_DATE< @EDATE
			AND JG_FLAG=@FLAG
		GROUP BY JG_MODELNO
	) C

END




