/* *************************************************************************
 * NAME : dbo.UDP_BC_BOARD_INSERT
 * TYPE : PROCEDURE (SQL_STORED_PROCEDURE)
 * TIME : Create: 2004-11-02 03:31:53.607
 *        Modify: 2018-05-03 17:23:34.957
 *        Backup: 20180521_1739
 ************************************************************************* */



/****** 개체: 저장 프로시저 dbo.UP_BC_BOARD_INSERT    스크립트 날짜: 2004-10-23 오전 10:55:40 ******/

/****** 개체: 저장 프로시저 dbo.UP_BC_BOARD_INSERT    스크립트 날짜: 2004-07-07 오후 1:00:38 ******/

/****** 개체: 저장 프로시저 dbo.UP_BC_BOARD_INSERT    스크립트 날짜: 2004-07-07 오전 11:42:15 ******/
CREATE    PROC UDP_BC_BOARD_INSERT
	@GROUP 	INT,
	@USERID	VARCHAR(12),
	@USERNM	VARCHAR(12),
	@RECEIVER	VARCHAR(12),
	@REFERER	VARCHAR(512),
	@TITLE		VARCHAR(255),
	@CONTENT	VARCHAR(8000),
	@PWD		VARCHAR(12),
	@FILE1		VARCHAR(255),
	@FILE2		VARCHAR(255),


	@iRETURN	INT 	OUTPUT
AS
BEGIN
	SET NOCOUNT ON
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

	DECLARE @BB_NO INT
	DECLARE @BB_REF INT

	BEGIN TRAN
		SELECT @BB_NO = ISNULL(MAX(BB_NO), 0) + 1
	  	FROM TBL_BC_BOARD (NOLOCK)
		WHERE BB_GROUP = @GROUP
	
		SELECT @BB_REF = ISNULL(MAX(BB_REF),0)+1
		FROM TBL_BC_BOARD (NOLOCK)
		WHERE BB_GROUP = @GROUP

		INSERT INTO TBL_BC_BOARD
		(BB_GROUP, BB_NO, BB_REF, BB_STEP, BB_DEPTH, 
			BB_USERID, BB_USERNAME, BB_RECEIVER, BB_REFERER, BB_TITLE, BB_CONTENT, BB_PWD)
		VALUES
		(@GROUP, @BB_NO, @BB_REF, 0, 0,
			@USERID, @USERNM, @RECEIVER, @REFERER, @TITLE, @CONTENT, @PWD)
		IF @@ERROR<>0 GOTO ERROR_HANDLER

		IF (@FILE1<>'')
		BEGIN
			INSERT INTO TBL_BOARD_ATTACHFILE 
			(BA_GROUP, BA_NO, BA_FILE)
			VALUES
			(@GROUP, @BB_NO,@FILE1)
			IF @@ERROR<>0 GOTO ERROR_HANDLER
		END
		
		IF (@FILE2<>'')
		BEGIN
			INSERT INTO TBL_BOARD_ATTACHFILE 
			(BA_GROUP, BA_NO, BA_FILE)
			VALUES
			(@GROUP, @BB_NO,@FILE2)
			IF @@ERROR<>0 GOTO ERROR_HANDLER
		END
		
	IF @@ERROR<>0
	BEGIN
		ERROR_HANDLER:
		BEGIN
			SET @iRETURN =1
			ROLLBACK TRAN
		END
	END
	ELSE
	BEGIN
		SET @iRETURN = 0
		COMMIT TRAN
	END	




END




