/* *************************************************************************
 * NAME : dbo.UDP_NB_PRICELIST_MP_CHECK_PROC_2
 * TYPE : PROCEDURE (SQL_STORED_PROCEDURE)
 * TIME : Create: 2005-01-26 11:36:14.53
 *        Modify: 2015-05-15 03:31:33.87
 *        Backup: 20180521_1739
 ************************************************************************* */


/****** 개체: 저장 프로시저 dbo.UP_NB_PRICELIST_MP_CHECK_PROC    스크립트 날짜: 2004-10-23 오전 11:04:05 ******/
-- UP_NB_PRICELIST_MP_CHECK_PROC  :   edit bslee2004.11.26 --
CREATE           PROC UDP_NB_PRICELIST_MP_CHECK_PROC_2
	@p_no int
AS
BEGIN
	SET NOCOUNT ON
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
	
	SELECT
		PL_NO
		, ISNULL(PL_MODELNO, -100) AS PL_MODELNO
		, PL_VCODE
		, ISNULL(PL_CATEGORY, '00') AS PL_CATEGORY
		, ISNULL(PL_GOODSNM, '') AS PL_GOODSNM
		, ISNULL(PL_PRICE, 0) AS PL_PRICE
		, ISNULL(PL_URL, '') AS PL_URL
		, ISNULL(PL_NOTE, '') AS PL_NOTE
		, PL_SRVFLAG
		, PL_STATUS
		, ISNULL(PL_ETC,'') AS PL_ETC
		, ISNULL(PL_AUTHFLAG, '0') AS PL_AUTHFLAG
		, PL_AUTHDATE
		, ISNULL(PL_DELFEETYPE, '') AS PL_DELFEETYPE
		, ISNULL(PL_IMGURL, '') AS PL_IMGURL
		, ISNULL(PL_COUPON, 0) AS PL_COUPON
		, PL_DELPRICE 
		, ISNULL(PL_DELIVERYFLAG ,'') as PL_DELIVERYFLAG
	FROM PRICELIST WITH(READUNCOMMITTED)
	WHERE PL_NO = @p_no
	
	SET NOCOUNT OFF

END

