/* *************************************************************************
 * NAME : dbo.USP_PRICELIST_SEL_20
 * TYPE : PROCEDURE (SQL_STORED_PROCEDURE)
 * TIME : Create: 2007-03-26 18:16:25.497
 *        Modify: 2018-05-03 17:23:36.11
 *        Backup: 20180521_1739
 ************************************************************************* */

CREATE PROC [dbo].[USP_PRICELIST_SEL_20]
	@PL_VCODE INT,
	@PL_GOODSCODE VARCHAR(50)
AS
BEGIN
	SET NOCOUNT ON
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
	SELECT TOP 1
		PL_MODELNO, PL_PRICE, PL_CATEGORY, PL_SRVFLAG, PL_AIRCONFEETYPE
	FROM PRICELIST --WITH (INDEX(NCL_PRICELIST_6)) 
	WHERE PL_VCODE = @PL_VCODE
		AND PL_GOODSCODE = @PL_GOODSCODE
		AND PL_GOODSCODE_CS = CHECKSUM(@PL_GOODSCODE) AND pl_modelno > 0
	ORDER BY PL_PRICE
END



