/* *************************************************************************
 * NAME : dbo.USP_PRICELIST_SEL_8
 * TYPE : PROCEDURE (SQL_STORED_PROCEDURE)
 * TIME : Create: 2007-03-26 17:47:33.573
 *        Modify: 2018-05-03 17:23:35.823
 *        Backup: 20180521_1739
 ************************************************************************* */

CREATE PROC [dbo].[USP_PRICELIST_SEL_8]
	@PL_VCODE INT,
	@PL_GOODSNM NVARCHAR(200)
AS
BEGIN
	SET NOCOUNT ON
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
	DECLARE @GOODSNM NVARCHAR(200)
	SET @GOODSNM = @PL_GOODSNM
	SELECT TOP 1
		PL_NO ,ISNULL(PL_MODELNO, 0) ,ISNULL(PL_CATEGORY, '00') ,PL_PRICE ,PL_URL,
		PL_STATUS, PL_RIGHTNLEFT, PL_DELIVERYINFO, PL_IMGURL, PL_COUPON, PL_ACCOUNT_YN, PL_FREEINTEREST
	FROM PRICELIST --WITH (INDEX(NCL_PRICELIST_3))
	WHERE PL_VCODE = @PL_VCODE
		AND PL_GOODSNM_CS = CHECKSUM(@GOODSNM) 
		AND PL_GOODSNM = @GOODSNM 
END




