/* *************************************************************************
 * NAME : dbo.UDP_BC_MEMBERS_READ
 * TYPE : PROCEDURE (SQL_STORED_PROCEDURE)
 * TIME : Create: 2004-11-02 03:31:54.153
 *        Modify: 2018-05-03 17:23:35.1
 *        Backup: 20180521_1739
 ************************************************************************* */



/****** 개체: 저장 프로시저 dbo.UP_BC_MEMBERS_READ    스크립트 날짜: 2004-10-23 오전 10:56:34 ******/
CREATE  PROC UDP_BC_MEMBERS_READ
	@FROM_USER_NAME	VARCHAR(10),
	@TO_USER_NAME	VARCHAR(10),

	@FROM_USER_EMAIL	VARCHAR(255) OUTPUT,
	@TO_USER_EMAIL	VARCHAR(255) OUTPUT
AS
BEGIN
	SET NOCOUNT ON
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

	SET @FROM_USER_EMAIL=''
	SET @TO_USER_EMAIL=''

	SELECT TOP 1 @FROM_USER_EMAIL= BM_EMAIL
	FROM TBL_BC_MEMBERS (NOLOCK)
	WHERE BM_NAME = @FROM_USER_NAME

	SELECT TOP 1 @TO_USER_EMAIL= BM_EMAIL
	FROM TBL_BC_MEMBERS (NOLOCK)
	WHERE BM_NAME = @TO_USER_NAME

END


