/* *************************************************************************
 * NAME : dbo.UDP_ELOC_EDU_PRICELIST_INSERT_SUMMARY
 * TYPE : PROCEDURE (SQL_STORED_PROCEDURE)
 * TIME : Create: 2005-12-08 10:31:08.56
 *        Modify: 2015-09-17 16:49:12.3
 *        Backup: 20180521_1739
 ************************************************************************* */

CREATE PROC UDP_ELOC_EDU_PRICELIST_INSERT_SUMMARY
	@PL_MODELNO	INT,
	@PL_VCODE		INT,
	@PL_CATEGORY	VARCHAR(8),
	@PL_GOODSNM	NVARCHAR(200),
	@PL_PRICE		MONEY,
	@PL_STATUS		CHAR(1),
	@PL_JOBTYPE		CHAR(1),
	@PL_AUTHFLAG	CHAR(1),
	@PL_MULTIFLAG	CHAR(1),	
	@PL_INSTANCE_PRICE  MONEY,
	
	@PLNO		bigINT	OUTPUT,
	@iRETURN		INT 	OUTPUT
AS
BEGIN
	SET NOCOUNT ON
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
	BEGIN TRAN	
			INSERT INTO PRICELIST( PL_MODELNO, PL_VCODE, PL_CATEGORY, PL_GOODSNM, PL_PRICE, PL_STATUS
			, PL_JOBTYPE, PL_AUTHFLAG, PL_MULTIFLAG, PL_INSTANCE_PRICE ) 
			VALUES(@PL_MODELNO,@PL_VCODE,@PL_CATEGORY,@PL_GOODSNM,@PL_PRICE,@PL_STATUS
			, @PL_JOBTYPE,@PL_AUTHFLAG,@PL_MULTIFLAG, @PL_INSTANCE_PRICE ) 
	
			SET @PLNO=SCOPE_IDENTITY()
	
	IF @@ERROR<>0
		BEGIN
			ROLLBACK TRAN
			SET @iRETURN = 99
		END
	ELSE
		BEGIN
			COMMIT TRAN
			SET @iRETURN = 00
				
		END

END
