/* *************************************************************************
 * NAME : dbo.UDF_RTN_CATEGORY_SPEC
 * TYPE : FUNCTION (SQL_SCALAR_FUNCTION)
 * TIME : Create: 2016-02-29 18:11:35.733
 *        Modify: 2018-05-03 17:23:35.083
 *        Backup: 20180521_1739
 ************************************************************************* */


CREATE FUNCTION [dbo].[UDF_RTN_CATEGORY_SPEC] (@CATEGORY VARCHAR(12), @BRAND VARCHAR(100))
RETURNS VARCHAR(8000)
AS
BEGIN
	DECLARE @RETURN VARCHAR(8000)
	DECLARE @MCATENM VARCHAR(8000)
	DECLARE @SCATENM VARCHAR(8000)
	DECLARE @DCATENM VARCHAR(8000)
	DECLARE @SZSTR VARCHAR(8000)
	DECLARE @DIVIDECHR VARCHAR(10)
	
	SET @CATEGORY = LTRIM(RTRIM(ISNULL(@CATEGORY, '')))
	SET @BRAND = LTRIM(RTRIM(ISNULL(@BRAND, '')))

	SELECT @RETURN = ''
		 , @MCATENM = LTRIM(RTRIM(ISNULL(REPLACE((SELECT CM_NAME FROM C_MCATE WITH (READUNCOMMITTED) WHERE CHARINDEX('★관리용', CM_NAME) = 0 AND CHARINDEX('temp', CM_NAME) = 0 AND CHARINDEX('blank', CM_NAME) = 0 AND CM_LCODE = SUBSTRING(@CATEGORY, 1, 2) AND CM_MCODE = SUBSTRING(@CATEGORY, 3, 2)), '/', '&#47;'), '')))
	     , @SCATENM = LTRIM(RTRIM(ISNULL(REPLACE((SELECT CS_NAME FROM C_SCATE WITH (READUNCOMMITTED) WHERE CHARINDEX('★관리용', CS_NAME) = 0 AND CHARINDEX('temp', CS_NAME) = 0 AND CHARINDEX('blank', CS_NAME) = 0 AND CS_LCODE = SUBSTRING(@CATEGORY, 1, 2) AND CS_MCODE = SUBSTRING(@CATEGORY, 3, 2) AND CS_SCODE = SUBSTRING(@CATEGORY, 5, 2)), '/', '&#47;'), '')))
		 , @DCATENM = LTRIM(RTRIM(ISNULL(REPLACE((SELECT CD_NAME FROM C_DCATE WITH (READUNCOMMITTED) WHERE CHARINDEX('★관리용', CD_NAME) = 0 AND CHARINDEX('temp', CD_NAME) = 0 AND CHARINDEX('blank', CD_NAME) = 0 AND CD_LCODE = SUBSTRING(@CATEGORY, 1, 2) AND CD_MCODE = SUBSTRING(@CATEGORY, 3, 2) AND CD_SCODE = SUBSTRING(@CATEGORY, 5, 2) AND CD_DCODE = SUBSTRING(@CATEGORY, 7, 2)), '/', '&#47;'), '')))
		 , @DIVIDECHR = '  /  '
		 , @BRAND = (CASE WHEN LTRIM(RTRIM(@BRAND)) = '[불명]' THEN '' ELSE LTRIM(RTRIM(REPLACE(@BRAND, '/', '&#47;'))) END)
	
	IF CHARINDEX(',' + SUBSTRING(@CATEGORY, 1, 2) + ',', ',93,') > 0
		-- 소분류 '_' 앞
		BEGIN
			SET @DIVIDECHR = ' > '

			SET @SZSTR = LTRIM(RTRIM(CASE WHEN CHARINDEX('_', @SCATENM) = 0 THEN @SCATENM ELSE SUBSTRING(@SCATENM, 1, CHARINDEX('_', @SCATENM) - 1) END))
			SET @RETURN = @SZSTR
		END
	ELSE IF CHARINDEX(',' + SUBSTRING(@CATEGORY, 1, 2) + ',', ',09,') > 0
		BEGIN
			SET @SZSTR = LTRIM(RTRIM(CASE WHEN CHARINDEX('_', @MCATENM) = 0 THEN @MCATENM ELSE SUBSTRING(@MCATENM, 1, CHARINDEX('_', @MCATENM) - 1) END))
			SET @RETURN = @SZSTR

			IF CHARINDEX('_', @DCATENM) > 0
				-- 소분류 '_' 앞 + 미분류 '_' 뒤 + 미분류 '_' 앞
				BEGIN
					SET @SZSTR = LTRIM(RTRIM(CASE WHEN CHARINDEX('_', @SCATENM) = 0 THEN @SCATENM ELSE SUBSTRING(@SCATENM, 1, CHARINDEX('_', @SCATENM) - 1) END))
					SET @RETURN = @RETURN + (CASE WHEN @RETURN = '' OR @SZSTR = '' THEN '' ELSE @DIVIDECHR END) + @SZSTR

					SET @SZSTR = LTRIM(RTRIM(CASE WHEN CHARINDEX('_', @DCATENM) = 0 THEN @DCATENM ELSE SUBSTRING(@DCATENM, CHARINDEX('_', @DCATENM) + 1, 1000) END))
					SET @RETURN = @RETURN + (CASE WHEN @RETURN = '' OR @SZSTR = '' THEN '' ELSE @DIVIDECHR END) + @SZSTR

					SET @SZSTR = LTRIM(RTRIM(CASE WHEN CHARINDEX('_', @DCATENM) = 0 THEN @DCATENM ELSE SUBSTRING(@DCATENM, 1, CHARINDEX('_', @DCATENM) - 1) END))
					SET @RETURN = @RETURN + (CASE WHEN @RETURN = '' OR @SZSTR = '' THEN '' ELSE @DIVIDECHR END) + @SZSTR
				END
			ELSE 
				-- 소분류 '_' 뒤 + 소분류 '_' 앞 + 미분류 '_' 앞
				BEGIN
					IF CHARINDEX('_', @SCATENM) > 0
					BEGIN
						SET @SZSTR = LTRIM(RTRIM(CASE WHEN CHARINDEX('_', @SCATENM) = 0 THEN @SCATENM ELSE SUBSTRING(@SCATENM, CHARINDEX('_', @SCATENM) + 1, 1000) END))
						SET @RETURN = @RETURN + (CASE WHEN @RETURN = '' OR @SZSTR = '' THEN '' ELSE @DIVIDECHR END) + @SZSTR
					END

					SET @SZSTR = LTRIM(RTRIM(CASE WHEN CHARINDEX('_', @SCATENM) = 0 THEN @SCATENM ELSE SUBSTRING(@SCATENM, 1, CHARINDEX('_', @SCATENM) - 1) END))
					SET @RETURN = @RETURN + (CASE WHEN @RETURN = '' OR @SZSTR = '' THEN '' ELSE @DIVIDECHR END) + @SZSTR

					SET @SZSTR = LTRIM(RTRIM(CASE WHEN CHARINDEX('_', @DCATENM) = 0 THEN @DCATENM ELSE SUBSTRING(@DCATENM, 1, CHARINDEX('_', @DCATENM) - 1) END))
					SET @RETURN = @RETURN + (CASE WHEN @RETURN = '' OR @SZSTR = '' THEN '' ELSE @DIVIDECHR END) + @SZSTR
				END

			IF @DCATENM = ''
				SET @RETURN = @RETURN + (CASE WHEN @RETURN = '' OR @BRAND = '' THEN '' ELSE @DIVIDECHR END) + @BRAND
		END
	ELSE
		-- '_' 앞
		BEGIN
			SET @SZSTR = LTRIM(RTRIM(CASE WHEN CHARINDEX('_', @MCATENM) = 0 THEN @MCATENM ELSE SUBSTRING(@MCATENM, 1, CHARINDEX('_', @MCATENM) - 1) END))
			SET @RETURN = @SZSTR

			SET @SZSTR = LTRIM(RTRIM(CASE WHEN CHARINDEX('_', @SCATENM) = 0 THEN @SCATENM ELSE SUBSTRING(@SCATENM, 1, CHARINDEX('_', @SCATENM) - 1) END))
			SET @RETURN = @RETURN + (CASE WHEN @RETURN = '' OR @SZSTR = '' THEN '' ELSE @DIVIDECHR END) + @SZSTR

			SET @SZSTR = LTRIM(RTRIM(CASE WHEN CHARINDEX('_', @DCATENM) = 0 THEN @DCATENM ELSE SUBSTRING(@DCATENM, 1, CHARINDEX('_', @DCATENM) - 1) END))
			SET @RETURN = @RETURN + (CASE WHEN @RETURN = '' OR @SZSTR = '' THEN '' ELSE @DIVIDECHR END) + @SZSTR

			IF @DCATENM = '' OR CHARINDEX(',' + SUBSTRING(@CATEGORY, 1, 2) + ',', ',15,') > 0
				SET @RETURN = @RETURN + (CASE WHEN @RETURN = '' OR @BRAND = '' THEN '' ELSE @DIVIDECHR END) + @BRAND
		END

	RETURN REPLACE(@RETURN, '&nbsp;', '')
END

