/* *************************************************************************
 * NAME : dbo.UDP_PRICELIST_MATCHING_ALARM_SRCH
 * TYPE : PROCEDURE (SQL_STORED_PROCEDURE)
 * TIME : Create: 2017-02-23 17:20:20.277
 *        Modify: 2018-05-03 17:23:35.35
 *        Backup: 20180521_1739
 ************************************************************************* */


CREATE PROC [DBO].[UDP_PRICELIST_MATCHING_ALARM_SRCH]
	@FLAG	CHAR(1),
	@ID		VARCHAR(20)
AS
BEGIN
	SET NOCOUNT ON;
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
	
	-- 최저가, 최고가 경고창 확인 처리만...
	
	DECLARE @QRY VARCHAR(8000)
	--DECLARE @FLAG CHAR(1)
	--SET @FLAG = '2'
	
	CREATE TABLE #TEMP(
		PL_NO BIGINT,
		PL_COPYPLNO BIGINT
	)
	
	CREATE TABLE #TARGET_PRICELIST(
		PL_NO BIGINT
	)
	
	-- 할당된 PL_NO 전체
	SET @QRY = ' INSERT INTO #TEMP' + 
			   ' SELECT A.PL_NO, ISNULL(A.PL_COPYPLNO, 0)' + 
			   ' FROM PRICELIST A' + 
					' INNER JOIN PRICELIST_MATCHING_ALARM_SRCH B ON A.PL_NO = B.PL_NO' + 
			   ' WHERE ALARM_FLAG = ''' + @FLAG + ''' AND P_STATUS = ''I'' AND ASSIGN_MM_ID IS NOT NULL' + 
			   ' OPTION (MAXDOP 1)'
	EXEC (@QRY)
	
	-- 최저가확인 로그 (PL_NO & PL_COPYPLNO)
	SET @QRY = ' INSERT INTO LOGDB.DBO.JOB_PRICELIST (JP_PLISTNO, JP_MODELNO, JP_VCODE, JP_ID, JP_FLAG, JP_DATE, JP_GOODSNM, JP_PRICE, JP_CATEGORY, JP_PRICE_MOBILE, JP_NOTE)' + 
			   ' OUTPUT INSERTED.JP_PLISTNO INTO #TARGET_PRICELIST' + 
			   ' SELECT A.PL_NO, PL_MODELNO, PL_VCODE, ''' + @ID + ''', ''D'', GETDATE(), PL_GOODSNM, PL_PRICE, PL_CATEGORY, PL_INSTANCE_PRICE, PL_NOTE' + 
			   ' FROM PRICELIST A' + 
					' INNER JOIN PRICELIST_MATCHING_ALARM_SRCH B ON A.PL_NO = B.PL_NO' + 
			   ' WHERE ALARM_FLAG = ''' + @FLAG + ''' AND P_STATUS = ''I''' + 
				' AND A.PL_NO IN (' + 
					' SELECT DISTINCT PL_NO FROM PRICELIST WHERE PL_NO IN (SELECT DISTINCT PL_NO FROM #TEMP) UNION' + 
					' SELECT DISTINCT PL_NO FROM PRICELIST WHERE PL_COPYPLNO IN (SELECT DISTINCT PL_COPYPLNO FROM #TEMP WHERE PL_COPYPLNO > 0))' + 
			   ' OPTION (MAXDOP 1)'
	EXEC (@QRY)
	
	-- 확인 처리 (PL_NO & PL_COPYPLNO)
	SET @QRY = ' UPDATE PRICELIST_MATCHING_ALARM_SRCH' + 
			   ' SET P_STATUS = ''D'', MM_ID = ''' + @ID + ''', P_DATE = GETDATE()' + 
			   ' WHERE PL_NO IN (SELECT DISTINCT PL_NO FROM #TARGET_PRICELIST) AND ALARM_FLAG = ''' + @FLAG + ''' AND P_STATUS = ''I''' + 
			   ' OPTION (MAXDOP 1)'
	EXEC (@QRY)
END
