/* *************************************************************************
 * NAME : dbo.UDF_RTN_PRTSUPPLY
 * TYPE : FUNCTION (SQL_SCALAR_FUNCTION)
 * TIME : Create: 2016-04-18 13:53:47.913
 *        Modify: 2018-05-03 17:23:35.22
 *        Backup: 20180521_1739
 ************************************************************************* */


CREATE FUNCTION [DBO].[UDF_RTN_PRTSUPPLY] (@MODELNO INT)
RETURNS VARCHAR(8000)
AS
BEGIN
	DECLARE @RETURN VARCHAR(8000)
	DECLARE @VALUE VARCHAR(500)
	
	DECLARE FETCH_CURSOR CURSOR FOR
	SELECT CAST(G_MODELNO AS VARCHAR(20)) + ' ¡Ü ' + LTRIM(RTRIM(G_MODELNM))
	FROM (
		SELECT DISTINCT G_MODELNO, G_MODELNM
		FROM GOODS_PRTSUPPLY
			INNER JOIN GOODS ON G_MODELNO = GPRT_MODELNO AND (LEFT(G_CATEGORY, 6) IN ('040207') OR LEFT(G_CATEGORY, 8) IN ('04020208')) AND G_MODELNM <> '¸ðµ¨»èÁ¦'
		WHERE GPRT_CATEGORY = '04020000' AND GPRT_POINTMODELNO = @MODELNO
	) A
	ORDER BY LTRIM(RTRIM(G_MODELNM))

	OPEN FETCH_CURSOR
	
	SELECT @RETURN = ''
	FETCH NEXT FROM FETCH_CURSOR INTO @VALUE
	WHILE (@@FETCH_STATUS = 0)
	BEGIN
		SELECT @RETURN = @RETURN + CASE WHEN @RETURN = '' THEN '' ELSE ', ' END + @VALUE

		FETCH NEXT FROM FETCH_CURSOR INTO @VALUE
	END
	
	CLOSE FETCH_CURSOR
	
	DEALLOCATE FETCH_CURSOR
	
	RETURN @RETURN
END
