/* *************************************************************************
 * NAME : dbo.UDP_MP_GOODS_CATALOG_ATTRIBUTE_SPEC_CATE_BATCH
 * TYPE : PROCEDURE (SQL_STORED_PROCEDURE)
 * TIME : Create: 2016-10-20 15:44:07.877
 *        Modify: 2018-05-03 17:23:35.17
 *        Backup: 20180521_1739
 ************************************************************************* */


CREATE PROC [DBO].[UDP_MP_GOODS_CATALOG_ATTRIBUTE_SPEC_CATE_BATCH]
	@CATEGORY VARCHAR(12),
	@EXCEPT_FLAG CHAR(1),
	@LAST_MOD VARCHAR(20)
AS
BEGIN
	SET NOCOUNT ON;
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
	
	DECLARE @CATE AS VARCHAR(12)

	CREATE TABLE #TARGET_CATE(
		CA_CODE VARCHAR(12)
	)

	IF @EXCEPT_FLAG = '0'
	BEGIN
		INSERT INTO #TARGET_CATE(CA_CODE)
		SELECT DISTINCT G_CATEGORY
		FROM GOODS
		WHERE G_CATEGORY LIKE @CATEGORY + '%'
		OPTION (MAXDOP 1)
	END
	ELSE
	BEGIN
		INSERT INTO #TARGET_CATE(CA_CODE)
		SELECT DISTINCT G_CATEGORY
		FROM GOODS
		WHERE G_CATEGORY LIKE @CATEGORY + '%'
		  AND LEFT(G_CATEGORY, 6) NOT IN (SELECT DISTINCT CATEGORY FROM GOODS_CATEGORY_ATTRIBUTE WHERE CATEGORY LIKE @CATEGORY + '[0-9]%' AND LEN(CATEGORY) = 6)
		  AND LEFT(G_CATEGORY, 8) NOT IN (SELECT DISTINCT CATEGORY FROM GOODS_CATEGORY_ATTRIBUTE WHERE CATEGORY LIKE @CATEGORY + '[0-9]%' AND LEN(CATEGORY) = 8)
		OPTION (MAXDOP 1)
	END

	DECLARE CATE_FETCH CURSOR FOR
	SELECT CA_CODE
	FROM #TARGET_CATE
	ORDER BY CA_CODE

	OPEN CATE_FETCH

	FETCH NEXT FROM CATE_FETCH INTO @CATE
	WHILE @@FETCH_STATUS = 0
	BEGIN
		EXEC UDP_MP_GOODS_CATALOG_ATTRIBUTE_SPEC_BATCH @CATE
		
		FETCH NEXT FROM CATE_FETCH INTO @CATE
	END

	CLOSE CATE_FETCH
	DEALLOCATE CATE_FETCH

	IF @EXCEPT_FLAG = '0'
	BEGIN
		DELETE FROM LOGDB.DBO.TBL_CATE_DISPLAY_LOG
		WHERE CA_CODE = @CATEGORY AND MOD_DATE <= DATEADD(SECOND, 1, CAST(@LAST_MOD AS DATETIME))
	END
END
