/* *************************************************************************
 * NAME : dbo.UDP_ELOC_PRICELIST_INSERT_WEBB_1
 * TYPE : PROCEDURE (SQL_STORED_PROCEDURE)
 * TIME : Create: 2008-02-13 15:46:37.493
 *        Modify: 2018-05-03 17:23:34.307
 *        Backup: 20180521_1739
 ************************************************************************* */

CREATE  PROC [dbo].[UDP_ELOC_PRICELIST_INSERT_WEBB_1]

	@MODELNO		INT,
	@VCODE			INT,
	@CATEGORY		VARCHAR(8),
	@PL_GOODSNM		NVARCHAR(400),
	@PRICE			MONEY,
	@URL			VARCHAR(255),
	@IMGURL		VARCHAR(255),
	@ACCOUNT_YN		CHAR(1),
	@GOODSFACTORY	VARCHAR(50),
	@GOODSCODE		VARCHAR(50),
	@FREEINTEREST		VARCHAR(50),
	@DELIVERY		VARCHAR(100),
	@RIGHTNLEFT		CHAR(1),
	
	@PLNO		bigINT	OUTPUT
	
AS
BEGIN
	SET NOCOUNT ON
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

	INSERT INTO PRICELIST (PL_MODELNO, PL_VCODE, PL_CATEGORY, PL_GOODSNM, PL_PRICE, PL_URL, PL_STATUS, PL_IMGURL, PL_ACCOUNT_YN, PL_GOODSFACTORY, PL_GOODSCODE, PL_FREEINTEREST, PL_DELIVERYINFO, PL_RIGHTNLEFT)
	VALUES(@MODELNO, @VCODE, NURIBOTDB.dbo.UDF_TEST_RTN_CATE(@VCODE, @CATEGORY), @PL_GOODSNM, @PRICE, @URL, '2', @IMGURL, @ACCOUNT_YN, @GOODSFACTORY, @GOODSCODE, @FREEINTEREST, @DELIVERY, @RIGHTNLEFT)

	SET @PLNO=SCOPE_IDENTITY()

END
