/* *************************************************************************
 * NAME : dbo.UDP_JCA_AP_REPORT_ORD_LIST_MONTHLY_HANAFOS
 * TYPE : PROCEDURE (SQL_STORED_PROCEDURE)
 * TIME : Create: 2008-03-19 10:30:35.08
 *        Modify: 2018-05-03 17:23:35.883
 *        Backup: 20180521_1739
 ************************************************************************* */

CREATE PROC [dbo].[UDP_JCA_AP_REPORT_ORD_LIST_MONTHLY_HANAFOS]
	@YEAR	SMALLINT
AS
	SET NOCOUNT ON
	SET TRANSACTION ISOLATION LEVEL  READ UNCOMMITTED
	-- ----------------------------------------------------------------------------------
	-- 작성자 : wookki25 / 2008.03.18
	-- 설  명 : AP 월별 주문액 리스트
	-- 실  행 : UDP_JCA_AP_REPORT_ORD_LIST_MONTHLY_HANAFOS 2008
	-- ----------------------------------------------------------------------------------
	
	-- ----------------------------------------------------------------------------------
	-- 수정내역
	-- ----------------------------------------------------------------------------------
	/*
	수정일:			수정자:			수정내용:
	----------		-----------		-----------------------------------------------------		
	*/
	SELECT	SHOP_NAME,
			AS_DAY_SUM1,AS_DAY_SUM2,AS_DAY_SUM3,AS_DAY_SUM4,AS_DAY_SUM5,
			AS_DAY_SUM6,AS_DAY_SUM7,AS_DAY_SUM8,AS_DAY_SUM9,AS_DAY_SUM10,
			AS_DAY_SUM11,AS_DAY_SUM12,
			AS_DAY_SUM,
			CASE WHEN SHOP_NAME = '합계' AND ISNULL(AS_DAY_SUM,0) > 0 THEN
			AS_DAY_SUM/(
			ISNULL(SIGN(AS_DAY_SUM1+1),0)+
			ISNULL(SIGN(AS_DAY_SUM2+1),0)+
			ISNULL(SIGN(AS_DAY_SUM3+1),0)+
			ISNULL(SIGN(AS_DAY_SUM4+1),0)+
			ISNULL(SIGN(AS_DAY_SUM5+1),0)+
			ISNULL(SIGN(AS_DAY_SUM6+1),0)+
			ISNULL(SIGN(AS_DAY_SUM7+1),0)+
			ISNULL(SIGN(AS_DAY_SUM8+1),0)+
			ISNULL(SIGN(AS_DAY_SUM9+1),0)+
			ISNULL(SIGN(AS_DAY_SUM10+1),0)+
			ISNULL(SIGN(AS_DAY_SUM11+1),0)+
			ISNULL(SIGN(AS_DAY_SUM12+1),0)
			) ELSE AS_DAY_SUM_AVG END AS AS_DAY_SUM_AVG
	FROM
	(
		SELECT MAX(CASE WHEN NUM = 1 THEN  SHOP_NAME ELSE '합계' END) AS SHOP_NAME,
		SUM([1월]) AS AS_DAY_SUM1,SUM([2월]) AS AS_DAY_SUM2,SUM([3월]) AS AS_DAY_SUM3,SUM([4월]) AS AS_DAY_SUM4,SUM([5월]) AS AS_DAY_SUM5,SUM([6월]) AS AS_DAY_SUM6,
		SUM([7월]) AS AS_DAY_SUM7,SUM([8월]) AS AS_DAY_SUM8,SUM([9월]) AS AS_DAY_SUM9,SUM([10월]) AS AS_DAY_SUM10,SUM([11월]) AS AS_DAY_SUM11,SUM([12월]) AS AS_DAY_SUM12,
		SUM(AS_DAY_SUM) AS AS_DAY_SUM, SUM(AS_DAY_SUM_AVG) AS AS_DAY_SUM_AVG
		FROM
			(
				SELECT	SHOP_NAME,
						SUM(CASE AS_DATE_MONTH WHEN 1 THEN AS_DAY_SUM END) AS '1월',
						SUM(CASE AS_DATE_MONTH WHEN 2 THEN AS_DAY_SUM END) AS '2월',
						SUM(CASE AS_DATE_MONTH WHEN 3 THEN AS_DAY_SUM END) AS '3월',
						SUM(CASE AS_DATE_MONTH WHEN 4 THEN AS_DAY_SUM END) AS '4월',
						SUM(CASE AS_DATE_MONTH WHEN 5 THEN AS_DAY_SUM END) AS '5월',
						SUM(CASE AS_DATE_MONTH WHEN 6 THEN AS_DAY_SUM END) AS '6월',
						SUM(CASE AS_DATE_MONTH WHEN 7 THEN AS_DAY_SUM END) AS '7월',
						SUM(CASE AS_DATE_MONTH WHEN 8 THEN AS_DAY_SUM END) AS '8월',
						SUM(CASE AS_DATE_MONTH WHEN 9 THEN AS_DAY_SUM END) AS '9월',
						SUM(CASE AS_DATE_MONTH WHEN 10 THEN AS_DAY_SUM END) AS '10월',
						SUM(CASE AS_DATE_MONTH WHEN 11 THEN AS_DAY_SUM END) AS '11월',
						SUM(CASE AS_DATE_MONTH WHEN 12 THEN AS_DAY_SUM END) AS '12월',
						SUM(AS_DAY_SUM) AS AS_DAY_SUM, SUM(AS_DAY_SUM) / SUM(1) AS AS_DAY_SUM_AVG
				FROM	TBL_AP_SHOP_HANAFOS
							INNER JOIN
						SHOPLIST
							ON AS_SHOP = SHOP_VCODE
							AND shop_vcode in (select shop_vcode from tbl_ap_sales_shop)--SHOP_APFLAG = '1'
				WHERE	AS_DATE_YEAR = @YEAR AND
						AS_DAY_SUM IS NOT NULL
				GROUP BY SHOP_NAME

			) TBL_TMP
				CROSS JOIN
			(SELECT 1 NUM UNION ALL SELECT 2) COPY_T
		GROUP BY (CASE WHEN NUM = 1 THEN SHOP_NAME ELSE '합계' END)
	) TBL_TMP2
	ORDER BY (CASE WHEN SHOP_NAME = '합계' THEN -1 ELSE ISNULL(AS_DAY_SUM,0) END) DESC, TBL_TMP2.SHOP_NAME ASC
