/* *************************************************************************
 * NAME : dbo.UDF_RTN_GB2NOS
 * TYPE : FUNCTION (SQL_SCALAR_FUNCTION)
 * TIME : Create: 2015-11-25 14:06:51.667
 *        Modify: 2018-05-03 17:23:34.763
 *        Backup: 20180521_1739
 ************************************************************************* */


CREATE FUNCTION [dbo].[UDF_RTN_GB2NOS] (@MODELNO INT)
RETURNS VARCHAR(500)
AS
BEGIN
	DECLARE @RETURN VARCHAR(500)
	DECLARE @GB2NO INT
	
	DECLARE FETCH_CURSOR CURSOR FOR
	SELECT DISTINCT GB2_NO
	FROM TBL_GOODS_BRAND_DETAIL
	WHERE MODELNO = @MODELNO
	ORDER BY GB2_NO
	
	OPEN FETCH_CURSOR
	
	SELECT @RETURN = ''
	FETCH NEXT FROM FETCH_CURSOR INTO @GB2NO
	WHILE (@@FETCH_STATUS = 0)
	BEGIN
		SELECT @RETURN = @RETURN + CASE WHEN @RETURN <> '' THEN ' ' ELSE '' END + CAST(@GB2NO AS VARCHAR(10))
		FETCH NEXT FROM FETCH_CURSOR INTO @GB2NO
	END
	
	CLOSE FETCH_CURSOR
	
	DEALLOCATE FETCH_CURSOR
	
	RETURN @RETURN
END