/* *************************************************************************
 * NAME : dbo.VIEW_CATE2
 * TYPE : VIEW (VIEW)
 * TIME : Create: 2007-03-28 11:21:40.803
 *        Modify: 2018-05-02 15:22:19.583
 *        Backup: 20180521_1739
 ************************************************************************* */

CREATE VIEW [DBO].[VIEW_CATE2]
AS 
	SELECT	DBO.C_LCATE.CL_LCODE + LEFT(LTRIM(ISNULL(DBO.C_MCATE.CM_MCODE, '00'))+'00',2) + LEFT(LTRIM(ISNULL(DBO.C_SCATE.CS_SCODE, '00'))+'00',2) + LEFT(LTRIM(ISNULL(DBO.C_DCATE.CD_DCODE, '00'))+'00',2) AS CATEGORY
	,		DBO.C_LCATE.CL_NAME
	,		DBO.C_MCATE.CM_NAME
	,		DBO.C_SCATE.CS_NAME
	,		DBO.C_DCATE.CD_NAME
	,		DBO.C_LCATE.CL_SEQNO
	,		DBO.C_MCATE.CM_SEQNO
	,		DBO.C_SCATE.CS_SEQNO
	,		DBO.C_DCATE.CD_SEQNO	
	FROM	DBO.C_LCATE WITH (READUNCOMMITTED) 
	LEFT OUTER JOIN DBO.C_MCATE WITH (READUNCOMMITTED) 
		ON DBO.C_LCATE.CL_LCODE = DBO.C_MCATE.CM_LCODE 
	LEFT OUTER JOIN DBO.C_SCATE WITH (READUNCOMMITTED) 
		ON DBO.C_LCATE.CL_LCODE = DBO.C_SCATE.CS_LCODE AND DBO.C_MCATE.CM_MCODE = DBO.C_SCATE.CS_MCODE 
	LEFT OUTER JOIN DBO.C_DCATE WITH (READUNCOMMITTED) 
		ON DBO.C_LCATE.CL_LCODE = DBO.C_DCATE.CD_LCODE AND DBO.C_MCATE.CM_MCODE = DBO.C_DCATE.CD_MCODE AND DBO.C_SCATE.CS_SCODE = DBO.C_DCATE.CD_SCODE
	WHERE     (DBO.C_LCATE.CL_LCODE < '98') --AND (DBO.C_LCATE.CL_SEQNO > 0)
