/* *************************************************************************
 * NAME : dbo.UDP_MP_PRICE_CASE_SEL_2
 * TYPE : PROCEDURE (SQL_STORED_PROCEDURE)
 * TIME : Create: 2015-06-12 10:58:38.1
 *        Modify: 2018-05-03 17:23:34.25
 *        Backup: 20180521_1739
 ************************************************************************* */


CREATE PROC [DBO].[UDP_MP_PRICE_CASE_SEL_2]
	@MODELNO	INT
AS
BEGIN
	SET NOCOUNT ON
	SET TRANSACTION ISOLATION LEVEL  READ UNCOMMITTED
	
	-- 최저가 대상 모집단
	SELECT PL_PRICE, PL_INSTANCE_PRICE, PL_MOBILE_FLAG, OPTION_FLAG2
	INTO #TEMP_PRICELIST
	FROM PRICELIST WITH (READUNCOMMITTED)
	WHERE PL_MODELNO = @MODELNO AND PL_SRVFLAG IN ('0','R','L','B') AND ISNULL(PL_ESSTOCKFLAG, '0') = '0' AND PL_STATUS NOT IN ('3','4','5')

	-- PC, MOBILE별 유료,무료 최저가 산출
	SELECT TYPE, MIN, AVG, MAX, OPTION_FLAG2
	FROM (
		SELECT 'PC' TYPE, ISNULL(MIN(PL_PRICE), 0) MIN, ISNULL(AVG(PL_PRICE), 0) AVG, ISNULL(MAX(PL_PRICE), 0) MAX, (CASE WHEN OPTION_FLAG2 = '1' THEN '1' ELSE '0' END) OPTION_FLAG2
		FROM #TEMP_PRICELIST
		WHERE PL_PRICE > 0 AND ISNULL(PL_MOBILE_FLAG, '0') <> '1'
		GROUP BY (CASE WHEN OPTION_FLAG2 = '1' THEN '1' ELSE '0' END)
		UNION ALL
		SELECT 'MOBILE' TYPE, ISNULL(MIN(PL_INSTANCE_PRICE), 0) MIN, ISNULL(AVG(PL_INSTANCE_PRICE), 0) AVG, ISNULL(MAX(PL_INSTANCE_PRICE), 0) MAX, MIN(OPTION_FLAG2) OPTION_FLAG2
		FROM #TEMP_PRICELIST
		WHERE PL_INSTANCE_PRICE > 0 AND OPTION_FLAG2 = '0'
		GROUP BY (CASE WHEN OPTION_FLAG2 = '1' THEN '1' ELSE '0' END)
	) A
	ORDER BY TYPE DESC, OPTION_FLAG2
END
