/* *************************************************************************
 * NAME : dbo.UDP_BC_BOARD_MODIFY
 * TYPE : PROCEDURE (SQL_STORED_PROCEDURE)
 * TIME : Create: 2004-11-02 03:31:53.763
 *        Modify: 2018-05-03 17:23:34.987
 *        Backup: 20180521_1739
 ************************************************************************* */



/****** 개체: 저장 프로시저 dbo.UP_BC_BOARD_MODIFY    스크립트 날짜: 2004-10-23 오전 10:56:00 ******/

/****** 개체: 저장 프로시저 dbo.UP_BC_BOARD_INSERT    스크립트 날짜: 2004-07-07 오후 3:02:12 ******/

/****** 개체: 저장 프로시저 dbo.UP_BC_BOARD_INSERT    스크립트 날짜: 2004-07-07 오후 1:00:38 ******/

/****** 개체: 저장 프로시저 dbo.UP_BC_BOARD_INSERT    스크립트 날짜: 2004-07-07 오전 11:42:15 ******/
CREATE     PROC UDP_BC_BOARD_MODIFY
	@GROUP 	INT,
	@BB_NO		INT,
	@USERID	VARCHAR(12),
	@USERNM	VARCHAR(12),
	@RECEIVER	VARCHAR(12),
	@REFERER	VARCHAR(512),
	@TITLE		VARCHAR(255),
	@CONTENT	VARCHAR(8000),
	@PWD		VARCHAR(12),
	@FILE1		VARCHAR(255),
	@FILE2		VARCHAR(255),
	@OLDFILE1	VARCHAR(255),
	@OLDFILE2	VARCHAR(255),


	@iRETURN	INT 	OUTPUT
AS
BEGIN
	SET NOCOUNT ON
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

	DECLARE @OLDPWD VARCHAR(12)
	SET @OLDPWD=''
	SELECT @OLDPWD = BB_PWD
	FROM TBL_BC_BOARD (NOLOCK)
	WHERE BB_GROUP  = @GROUP
		AND BB_NO = @BB_NO
			
	IF LOWER(@OLDPWD)=LOWER(@PWD)
	BEGIN

		BEGIN TRAN
			
			UPDATE TBL_BC_BOARD
			SET BB_RECEIVER = @RECEIVER,
				BB_REFERER = @REFERER,
				BB_TITLE = @TITLE,
				BB_CONTENT = @CONTENT
			WHERE BB_GROUP  = @GROUP
				AND BB_NO = @BB_NO
			IF @@ERROR<>0 GOTO ERROR_HANDLER
	
			IF(@OLDFILE1<>'')
			BEGIN
				IF(@FILE1<>'')
				BEGIN
					UPDATE TBL_BOARD_ATTACHFILE
					SET BA_FILE = @FILE1
					WHERE BA_GROUP = @GROUP
						AND BA_NO = @BB_NO
						AND BA_FILE=@OLDFILE1
					IF @@ERROR<>0 GOTO ERROR_HANDLER
				END
			END
			ELSE
			BEGIN
				IF (@FILE1<>'')
				BEGIN
					INSERT INTO TBL_BOARD_ATTACHFILE 
					(BA_GROUP, BA_NO, BA_FILE)
					VALUES
					(@GROUP, @BB_NO,@FILE1)	
					IF @@ERROR<>0 GOTO ERROR_HANDLER
				END
			END
	
			IF(@OLDFILE2<>'')
			BEGIN
				IF(@FILE2<>'')
				BEGIN
					UPDATE TBL_BOARD_ATTACHFILE
					SET BA_FILE = @FILE2
					WHERE BA_GROUP = @GROUP
						AND BA_NO = @BB_NO
						AND BA_FILE=@OLDFILE2
					IF @@ERROR<>0 GOTO ERROR_HANDLER
				END
			END
			ELSE
			BEGIN
				IF (@FILE2<>'')
				BEGIN
					INSERT INTO TBL_BOARD_ATTACHFILE 
					(BA_GROUP, BA_NO, BA_FILE)
					VALUES
					(@GROUP, @BB_NO,@FILE2)	
					IF @@ERROR<>0 GOTO ERROR_HANDLER
				END
			END
			
	
	
			
		IF @@ERROR<>0
		BEGIN
			ERROR_HANDLER:
			BEGIN
				SET @iRETURN =99
				ROLLBACK TRAN
			END
		END
		ELSE
		BEGIN
			SET @iRETURN = 0
			COMMIT TRAN
		END	
	END
	ELSE
	BEGIN
		SET @iRETURN = 1
	END
END





