/* *************************************************************************
 * NAME : dbo.UDP_MP_MCATE_TERMDIC_ATTRIBUTE
 * TYPE : PROCEDURE (SQL_STORED_PROCEDURE)
 * TIME : Create: 2017-02-24 14:24:53.403
 *        Modify: 2018-05-03 17:23:34.653
 *        Backup: 20180521_1739
 ************************************************************************* */


CREATE PROC [DBO].[UDP_MP_MCATE_TERMDIC_ATTRIBUTE]
	@CATEGORY VARCHAR(12)
AS
BEGIN
	SET NOCOUNT ON;
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
	
	SELECT [加己ID]		=	ATTRIBUTE_ID
	     , [包府加己疙]	=	MANAGE_ATTRIBUTE_NM
		 , [傈矫加己疙]	=	GALLERY_ATTRIBUTE_NM
		 , [加己盔ID]		=	ATTRIBUTE_ELEMENT_ID
		 , [加己盔疙]		=	ATTRIBUTE_ELEMENT
		 , [侩绢荤傈ID]	=	REF_KB_NO
		 , [侩绢荤傈 力格]	=	KTT_TITLE

	FROM (
		SELECT A.ATTRIBUTE_ID, ISNULL(MANAGE_ATTRIBUTE_NM, '') MANAGE_ATTRIBUTE_NM, ISNULL(GALLERY_ATTRIBUTE_NM, '') GALLERY_ATTRIBUTE_NM, ISNULL(CAST(C.ATTRIBUTE_ELEMENT_ID AS VARCHAR(20)), '') ATTRIBUTE_ELEMENT_ID, '' ATTRIBUTE_ELEMENT, REF_KB_NO, ISNULL(KTT_TITLE, '') KTT_TITLE
		FROM GOODS_ATTRIBUTE A
			INNER JOIN TBL_TERMDIC_ATTRIBUTE C ON A.CATEGORY = C.CATEGORY AND A.ATTRIBUTE_ID = C.ATTRIBUTE_ID AND C.ATTRIBUTE_ELEMENT_ID IS NULL
			INNER JOIN MPDB02.KNOWBOXDB2.DBO.KNOW_TERMDIC_TITLE D ON REF_KB_NO = REF_KBNO
		WHERE A.DEL_YN = 'N' AND A.CATEGORY = @CATEGORY
		UNION ALL
		SELECT A.ATTRIBUTE_ID, ISNULL(MANAGE_ATTRIBUTE_NM, '') MANAGE_ATTRIBUTE_NM, ISNULL(GALLERY_ATTRIBUTE_NM, '') GALLERY_ATTRIBUTE_NM, CAST(C.ATTRIBUTE_ELEMENT_ID AS VARCHAR(20)) ATTRIBUTE_ELEMENT_ID, ISNULL(ATTRIBUTE_ELEMENT, '') ATTRIBUTE_ELEMENT, REF_KB_NO, ISNULL(KTT_TITLE, '') KTT_TITLE
		FROM GOODS_ATTRIBUTE A
			INNER JOIN GOODS_ATTRIBUTE_ELEMENT B ON A.ATTRIBUTE_ID = B.ATTRIBUTE_ID
			INNER JOIN TBL_TERMDIC_ATTRIBUTE C ON A.CATEGORY = C.CATEGORY AND A.ATTRIBUTE_ID = C.ATTRIBUTE_ID AND B.ATTRIBUTE_ELEMENT_ID = C.ATTRIBUTE_ELEMENT_ID
			INNER JOIN MPDB02.KNOWBOXDB2.DBO.KNOW_TERMDIC_TITLE D ON REF_KB_NO = REF_KBNO
		WHERE A.DEL_YN = 'N' AND B.DEL_YN = 'N' AND A.CATEGORY = @CATEGORY
	) A
	ORDER BY ATTRIBUTE_ID
END
