/* *************************************************************************
 * NAME : dbo.USP_PRICELIST_SEL_23
 * TYPE : PROCEDURE (SQL_STORED_PROCEDURE)
 * TIME : Create: 2007-03-27 17:34:37.59
 *        Modify: 2018-05-03 17:23:34.127
 *        Backup: 20180521_1739
 ************************************************************************* */


CREATE PROC [dbo].[USP_PRICELIST_SEL_23]
	@PL_VCODES VARCHAR(255),
	@PL_GOODSCODE VARCHAR(50)
AS
BEGIN
	SET NOCOUNT ON
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
	DECLARE @SQL NVARCHAR(1024) --컬럼의 전체데이터 길이를 생각해서 넉넉하게...
	DECLARE @ParmDefinition NVARCHAR(255)
	SET @ParmDefinition = N'@GOODSCODE VARCHAR(50)'
	SET @SQL = N'SELECT PL_MODELNO, PL_PRICE, PL_CATEGORY'
	SET @SQL = @SQL + N' FROM PRICELIST WITH (READUNCOMMITTED)'
	SET @SQL = @SQL + N' WHERE PL_VCODE IN (' + @PL_VCODES + N')'
	SET @SQL = @SQL + N' AND PL_GOODSCODE = @GOODSCODE'
	SET @SQL = @SQL + N' AND PL_GOODSCODE_CS = CHECKSUM(@GOODSCODE)'
	SET @SQL = @SQL + N' AND PL_MODELNO>0 AND PL_SRVFLAG=''0'' AND PL_GOODSNM<>'''' AND PL_STATUS<''3'''
	SET @SQL = @SQL + N' ORDER BY PL_PRICE ASC'
	EXEC SP_EXECUTESQL @SQL, @ParmDefinition, @GOODSCODE=@PL_GOODSCODE		
END