/* *************************************************************************
 * NAME : dbo.UDP_GOODS_EXTERNAL_CATALOG_ATTRIBUTE
 * TYPE : PROCEDURE (SQL_STORED_PROCEDURE)
 * TIME : Create: 2017-02-28 17:00:03.447
 *        Modify: 2018-05-03 17:23:35.013
 *        Backup: 20180521_1739
 ************************************************************************* */


CREATE PROC [DBO].[UDP_GOODS_EXTERNAL_CATALOG_ATTRIBUTE]
	@SHOP_CODE INT
AS
BEGIN
	SET NOCOUNT ON;
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
	
	SELECT G_MODELNO
		 , (CASE WHEN E.ATTRIBUTE_ID IS NOT NULL THEN 1 ELSE 0 END) GS_ATTRIBUTE
		 , A.ATTRIBUTE_ID
		 , A.ATTRIBUTE_ELEMENT_ID
		 , ATTRIBUTE_VALUE
		 , A.INS_OPRT
		 , A.UPD_OPRT
		 , ISNULL(A.DEL_YN, 'N') DEL_YN
		 , ISNULL(CONVERT(CHAR(21), A.INS_DATE, 120), CONVERT(CHAR(21), GETDATE(), 120)) INS_DATE
		 , ISNULL(CONVERT(CHAR(21), A.UPD_DATE, 120), CONVERT(CHAR(21), GETDATE(), 120)) UPD_DATE
	FROM GOODS_CATALOG_ATTRIBUTE A
		INNER JOIN TBL_EXTERNAL_SEND_TARGET_MODEL B ON B.SHOP_CODE = @SHOP_CODE AND G_MODELNO = MODELNO
		INNER JOIN GOODS_CATEGORY_ATTRIBUTE C ON A.ATTRIBUTE_ID = C.ATTRIBUTE_ID AND C.CATEGORY IN (SELECT TOP 1 CATEGORY FROM GOODS_CATEGORY_ATTRIBUTE WHERE CATEGORY = LEFT(B.CATEGORY, 4) OR CATEGORY = LEFT(B.CATEGORY, 6) OR CATEGORY = LEFT(B.CATEGORY, 8) ORDER BY LEN(CATEGORY) DESC)
		INNER JOIN GOODS_ATTRIBUTE_ELEMENT D ON A.ATTRIBUTE_ID = D.ATTRIBUTE_ID AND A.ATTRIBUTE_ELEMENT_ID = D.ATTRIBUTE_ELEMENT_ID
		LEFT JOIN TBL_EXTERNAL_ATTRIBUTE E ON E.SHOP_CODE = @SHOP_CODE AND E.CATEGORY = LEFT(B.CATEGORY, LEN(E.CATEGORY)) AND E.ATTRIBUTE_ID = A.ATTRIBUTE_ID AND E.ATTRIBUTE_ID > 0
	WHERE A.ATTRIBUTE_ID IN (
		SELECT DISTINCT ATTRIBUTE_ID
		FROM GOODS_ATTRIBUTE
		WHERE MANAGE_ATTRIBUTE_NM NOT LIKE '%temp%'
		  AND GALLERY_ATTRIBUTE_NM NOT LIKE '%temp%'
		  AND CATEGORY <> ''
		  AND USE_CLASS_CODE < '4')
	  AND A.DEL_YN = 'N' AND D.DEL_YN = 'N'
	ORDER BY G_MODELNO, C.DISPLAY_ORDER, A.ATTRIBUTE_ID, D.DISPLAY_ORDER, ATTRIBUTE_ELEMENT_ID, ATTRIBUTE_VALUE
	OPTION (MAXDOP 1)
END
