/* *************************************************************************
 * NAME : dbo.UDP_PPS_CATEGORY
 * TYPE : PROCEDURE (SQL_STORED_PROCEDURE)
 * TIME : Create: 2017-10-25 16:33:46.953
 *        Modify: 2018-05-03 17:23:34.753
 *        Backup: 20180521_1739
 ************************************************************************* */


CREATE PROC [DBO].[UDP_PPS_CATEGORY]
-- 炼崔没 墨抛绊府, 加己, 加己盔, 墨抛绊府 加己
AS
BEGIN
	SET NOCOUNT ON;
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
	
	-------------------------------------------------------------------
	-- 墨抛绊府
	DROP TABLE TBL_PPS_CATEGORY
	
	SELECT CAST(CA_CODE1 AS VARCHAR(12)) CATEGORY, C_NAME CATEGORY_NM, C_LEVEL LEVEL
	INTO TBL_PPS_CATEGORY
	FROM OPENQUERY(ORADB, '
		SELECT CA_CODE1, C_NAME, C_LEVEL
		FROM TBL_CATEGORY
		WHERE C_LEVEL = 1 AND C_SEQNO > 0 AND C_NAME IS NOT NULL AND INSTR(CA_CODE, '' '') = 0 AND INSTR(CA_CODE, ''xx'') = 0 AND INSTR(C_NAME, ''temp'') = 0 AND INSTR(C_NAME, ''blank'') = 0')
	WHERE CA_CODE1 IN ('02', '03', '04', '05', '06', '07', '10', '12', '16', '18', '24')
	
	INSERT INTO TBL_PPS_CATEGORY(CATEGORY, CATEGORY_NM, LEVEL)
	SELECT CA_CODE2, C_NAME, C_LEVEL
	FROM OPENQUERY(ORADB, '
		SELECT CA_CODE1, CA_CODE2, C_NAME, C_LEVEL
		FROM TBL_CATEGORY
		WHERE C_LEVEL = 2 AND C_SEQNO > 0 AND C_NAME IS NOT NULL AND INSTR(CA_CODE, '' '') = 0 AND INSTR(CA_CODE, ''xx'') = 0 AND INSTR(C_NAME, ''temp'') = 0 AND INSTR(C_NAME, ''blank'') = 0')
	WHERE CA_CODE1 IN (SELECT CATEGORY FROM TBL_PPS_CATEGORY WHERE LEVEL = 1)
	
	INSERT INTO TBL_PPS_CATEGORY(CATEGORY, CATEGORY_NM, LEVEL)
	SELECT CA_CODE3, C_NAME, C_LEVEL
	FROM OPENQUERY(ORADB, '
		SELECT CA_CODE2, CA_CODE3, C_NAME, C_LEVEL
		FROM TBL_CATEGORY
		WHERE C_LEVEL = 3 AND C_SEQNO > 0 AND C_NAME IS NOT NULL AND INSTR(CA_CODE, '' '') = 0 AND INSTR(CA_CODE, ''xx'') = 0 AND INSTR(C_NAME, ''temp'') = 0 AND INSTR(C_NAME, ''blank'') = 0')
	WHERE CA_CODE2 IN (SELECT CATEGORY FROM TBL_PPS_CATEGORY WHERE LEVEL = 2)
	
	INSERT INTO TBL_PPS_CATEGORY(CATEGORY, CATEGORY_NM, LEVEL)
	SELECT CA_CODE4, C_NAME, C_LEVEL
	FROM OPENQUERY(ORADB, '
		SELECT CA_CODE3, CA_CODE4, C_NAME, C_LEVEL
		FROM TBL_CATEGORY
		WHERE C_LEVEL = 4 AND C_SEQNO > 0 AND C_NAME IS NOT NULL AND INSTR(CA_CODE, '' '') = 0 AND INSTR(CA_CODE, ''xx'') = 0 AND INSTR(C_NAME, ''temp'') = 0 AND INSTR(C_NAME, ''blank'') = 0')
	WHERE CA_CODE3 IN (SELECT CATEGORY FROM TBL_PPS_CATEGORY WHERE LEVEL = 3)
	-------------------------------------------------------------------
	
	-------------------------------------------------------------------
	-- 加己
	DROP TABLE TBL_PPS_ATTRIBUTE
	SELECT ATTRIBUTE_ID, IS_GALLERY_DISPLAY, MANAGE_ATTRIBUTE_NM, GALLERY_ATTRIBUTE_NM, USE_CLASS_CODE, IS_UNIT, UNIT_NM, INS_DATE, UPD_DATE, DEL_YN, CATEGORY
	INTO TBL_PPS_ATTRIBUTE
	FROM GOODS_ATTRIBUTE
	WHERE MANAGE_ATTRIBUTE_NM NOT LIKE '%temp%'
	  AND GALLERY_ATTRIBUTE_NM NOT LIKE '%temp%'
	  AND CATEGORY IN (SELECT CATEGORY FROM TBL_PPS_CATEGORY WHERE LEVEL = 2)
	  AND USE_CLASS_CODE < '4'
	OPTION (MAXDOP 1)
	
	ALTER TABLE TBL_PPS_ATTRIBUTE ADD CONSTRAINT [CL_TBL_PPS_ATTRIBUTE] PRIMARY KEY CLUSTERED(ATTRIBUTE_ID ASC)
	-------------------------------------------------------------------
	
	-------------------------------------------------------------------
	-- 加己盔
	DROP TABLE TBL_PPS_ATTRIBUTE_ELEMENT
	SELECT ATTRIBUTE_ID, ATTRIBUTE_ELEMENT_ID, IS_DISPLAY, ISNULL(DISPLAY_ORDER, 0) DISPLAY_ORDER, ATTRIBUTE_ELEMENT, INS_DATE, UPD_DATE, DEL_YN
	INTO TBL_PPS_ATTRIBUTE_ELEMENT
	FROM GOODS_ATTRIBUTE_ELEMENT
	WHERE ATTRIBUTE_ID IN (SELECT ATTRIBUTE_ID FROM TBL_PPS_ATTRIBUTE)
	OPTION (MAXDOP 1)
	
	ALTER TABLE TBL_PPS_ATTRIBUTE_ELEMENT ADD CONSTRAINT [CL_TBL_PPS_ATTRIBUTE_ELEMENT] PRIMARY KEY CLUSTERED(ATTRIBUTE_ID ASC, ATTRIBUTE_ELEMENT_ID ASC)
	-------------------------------------------------------------------
	
	-------------------------------------------------------------------
	-- 墨抛绊府 加己
	DROP TABLE TBL_PPS_CATEGORY_ATTRIBUTE
	SELECT CATEGORY, ATTRIBUTE_ID
	INTO TBL_PPS_CATEGORY_ATTRIBUTE
	FROM GOODS_CATEGORY_ATTRIBUTE
	WHERE CATEGORY IN (SELECT CATEGORY FROM TBL_PPS_CATEGORY)
	  AND ATTRIBUTE_ID IN (SELECT ATTRIBUTE_ID FROM TBL_PPS_ATTRIBUTE)
	OPTION (MAXDOP 1)
	
	ALTER TABLE TBL_PPS_CATEGORY_ATTRIBUTE ADD CONSTRAINT [CL_TBL_PPS_CATEGORY_ATTRIBUTE] PRIMARY KEY CLUSTERED(CATEGORY ASC, ATTRIBUTE_ID ASC)
	-------------------------------------------------------------------
	
	SELECT CATEGORY, CATEGORY_NM FROM TBL_PPS_CATEGORY ORDER BY CATEGORY
	/*
	SELECT ATTRIBUTE_ID, IS_GALLERY_DISPLAY, MANAGE_ATTRIBUTE_NM, GALLERY_ATTRIBUTE_NM, USE_CLASS_CODE, IS_UNIT, UNIT_NM, INS_DATE, UPD_DATE, DEL_YN
	FROM TBL_PPS_ATTRIBUTE
	ORDER BY CASE WHEN CATEGORY = '' THEN '9999' ELSE CATEGORY END, ATTRIBUTE_ID
	
	SELECT ATTRIBUTE_ID, ATTRIBUTE_ELEMENT_ID, IS_DISPLAY, DISPLAY_ORDER, ATTRIBUTE_ELEMENT, INS_DATE, UPD_DATE, DEL_YN
	FROM TBL_PPS_ATTRIBUTE_ELEMENT
	ORDER BY ATTRIBUTE_ID, DISPLAY_ORDER, ATTRIBUTE_ELEMENT_ID
	
	SELECT CATEGORY, ATTRIBUTE_ID
	FROM TBL_PPS_CATEGORY_ATTRIBUTE
	ORDER BY CATEGORY, ATTRIBUTE_ID
	*/
END
