/* *************************************************************************
 * NAME : dbo.USP_TBL_AUTO_MATCHING_PRICE
 * TYPE : PROCEDURE (SQL_STORED_PROCEDURE)
 * TIME : Create: 2014-07-31 10:43:21.713
 *        Modify: 2018-05-03 17:23:34.76
 *        Backup: 20180521_1739
 ************************************************************************* */


CREATE PROC [DBO].[USP_TBL_AUTO_MATCHING_PRICE]
AS
BEGIN
	SET NOCOUNT ON;
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
	
	DECLARE @I INT
	DECLARE @CATEGORY VARCHAR(12)
	
	SELECT DISTINCT CATEGORY, DENSE_RANK() OVER (ORDER BY CATEGORY DESC) NRANK
	INTO #CATEGORY
	FROM NURIBOTDB.DBO.TBL_SAME_GOODSNAME_MANAGER_CATE_SET
	WHERE SRV_FLAG = '0'
	
	SET @I = @@ROWCOUNT
	
	WHILE @I > 0 BEGIN
		SET @CATEGORY = ''
		SELECT @CATEGORY = CATEGORY FROM #CATEGORY WHERE NRANK = @I
		
		IF @CATEGORY <> '' EXEC USP_TBL_AUTO_MATCHING_PRICE_BATCH @CATEGORY
		
		SET @I = @I - 1
	END
	
	-- 6개월 지난 SGM 로그 삭제
	SELECT PL_NO
	INTO #SGM_DELETE
	FROM TBL_AUTO_MATCHING_PRICE_LOG
	WHERE REGDATE < DATEADD(DAY, 1, DATEADD(MONTH, -6, CAST(GETDATE() AS VARCHAR(10))))
	
	DELETE FROM TBL_AUTO_MATCHING_PRICE_LOG
	WHERE PL_NO IN (SELECT PL_NO FROM #SGM_DELETE)
	
	UPDATE PRICELIST
	SET PL_FINALUSEDFLAG = 0
	WHERE PL_NO IN (SELECT PL_NO FROM #SGM_DELETE)
END
