/* *************************************************************************
 * NAME : dbo.UDP_ELOC_PRICELIST_MODIFY_NO_PLNO
 * TYPE : PROCEDURE (SQL_STORED_PROCEDURE)
 * TIME : Create: 2004-11-03 17:38:48.39
 *        Modify: 2015-05-15 03:31:33.237
 *        Backup: 20180521_1739
 ************************************************************************* */

CREATE          PROC [dbo].[UDP_ELOC_PRICELIST_MODIFY_NO_PLNO]
	@PL_MODELNO	INT,
	@SHOP_VCODE	INT,
	@PL_PRICE	MONEY,
	@PL_ETC	NVARCHAR(100),
	@PL_URL	VARCHAR(250),
	@PL_RIGHTNLEFT CHAR(1),
	@PL_SRVFLAG	CHAR(1),
	--@PL_FLAG	CHAR(1),
	@PL_STATUS	CHAR(1),
	@PL_GOODSNM		NVARCHAR(400) = NULL,
	@PL_GOODSCODE	VARCHAR(50) = NULL,

	@iRETURN	INT	OUTPUT
AS
BEGIN
	SET NOCOUNT ON
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
	UPDATE PRICELIST
	SET PL_PRICE = @PL_PRICE,
		PL_ETC = @PL_ETC,
		PL_URL	= @PL_URL,
		PL_RIGHTNLEFT = @PL_RIGHTNLEFT,
		PL_SRVFLAG = @PL_SRVFLAG,
		--PL_FLAG	 = @PL_FLAG,
		PL_STATUS = @PL_STATUS,
		PL_DATE = GETDATE()
	,	PL_GOODSNM = ISNULL(@PL_GOODSNM, PL_GOODSNM),
		PL_GOODSCODE = @PL_GOODSCODE
	WHERE	PL_MODELNO=@PL_MODELNO
		AND PL_VCODE=@SHOP_VCODE
		AND (PL_STATUS <= '3' OR PL_GOODSNM IS NULL OR PL_GOODSNM='')

	IF @@ERROR<>0
	BEGIN
		SET @iRETURN=99
	END
	ELSE
	BEGIN
		SET @iRETURN =0
	END

END
