/* *************************************************************************
 * NAME : dbo.USP_PRICELIST_SEL_10
 * TYPE : PROCEDURE (SQL_STORED_PROCEDURE)
 * TIME : Create: 2007-03-26 17:53:26.497
 *        Modify: 2018-05-03 17:23:35.863
 *        Backup: 20180521_1739
 ************************************************************************* */


CREATE PROC USP_PRICELIST_SEL_10
	@PL_GOODSNM NVARCHAR(200)
AS
BEGIN
	SET NOCOUNT ON
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
	SELECT TOP 1 
		PL_MODELNO, PL_PRICE, PL_CATEGORY
	FROM PRICELIST
	WHERE PL_GOODSNM_CS = CHECKSUM(@PL_GOODSNM) 
		AND PL_GOODSNM = @PL_GOODSNM
		AND PL_MODELNO > 0 
		AND PL_SRVFLAG = '0' 
		AND PL_STATUS < '3' 
		AND PL_COPYPLNO IS NULL
	ORDER BY PL_PRICE ASC
END
