/* *************************************************************************
 * NAME : dbo.UDP_SPEC_GOODS_BATCH
 * TYPE : PROCEDURE (SQL_STORED_PROCEDURE)
 * TIME : Create: 2016-12-26 18:24:34.24
 *        Modify: 2018-05-03 17:23:36.113
 *        Backup: 20180521_1739
 ************************************************************************* */


CREATE PROC [DBO].[UDP_SPEC_GOODS_BATCH]
	@MODE INT
AS
BEGIN
	/*
		TRUNCATE TABLE TEMP_GOODS

		INSERT INTO TEMP_GOODS(G_MODELNO)
		SELECT G_MODELNO
		FROM GOODS
		WHERE G_CATEGORY <> '00000000' AND G_MODELNM <> '¸ðµ¨»èÁ¦'
		OPTION (MAXDOP 1)
	*/
	SET NOCOUNT ON;
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
	
	DECLARE @MODELNO INT
	DECLARE @SZLPTAG1 VARCHAR(8000)
	DECLARE @SZLPTAG2 VARCHAR(8000)
	DECLARE @SZVIPTAG VARCHAR(8000)

	SELECT G_MODELNO
	INTO #TEMP
	FROM TEMP_GOODS
	WHERE MODE = @MODE

	DECLARE CURSOR_FETCH CURSOR FOR
	SELECT G_MODELNO
	FROM #TEMP
	ORDER BY G_MODELNO

	OPEN CURSOR_FETCH

	FETCH NEXT FROM CURSOR_FETCH INTO @MODELNO
	WHILE @@FETCH_STATUS = 0
	BEGIN
		EXEC UDP_MP_GOODS_CATALOG_ATTRIBUTE_SPEC_MAKE @MODELNO, '', 'N', 'N', @SZLPTAG1 OUTPUT, @SZLPTAG2 OUTPUT, @SZVIPTAG OUTPUT

		UPDATE GOODS
		SET G_SPEC2 = @SZLPTAG1
		WHERE G_MODELNO = @MODELNO

		FETCH NEXT FROM CURSOR_FETCH INTO @MODELNO
	END

	CLOSE CURSOR_FETCH
	DEALLOCATE CURSOR_FETCH
END
