/* *************************************************************************
 * NAME : dbo.UDP_GOODS_FACTORY_FIRSTINPUT_LIST_BAK_20071228
 * TYPE : PROCEDURE (SQL_STORED_PROCEDURE)
 * TIME : Create: 2007-12-28 11:13:16.2
 *        Modify: 2015-05-15 03:31:33.17
 *        Backup: 20180521_1739
 ************************************************************************* */


-- --------------------------------
-- 백업처리 : WOOKKI25 2007.12.28
-- 설    명 : 단일 쿼리로 새로 생성
-- --------------------------------
CREATE   PROC UDP_GOODS_FACTORY_FIRSTINPUT_LIST_BAK_20071228
	@CATEGORY VARCHAR(8) ,
	@SDATE	VARCHAR(10),
	@EDATE VARCHAR(10)

AS
BEGIN
	SET NOCOUNT ON
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
	DECLARE @TCOUNT INT
	DECLARE @TMPFACTORY VARCHAR(100)	
	DECLARE @TMPREGDATE DATETIME
	DECLARE @TEMP TABLE
	(
		IDX INT IDENTITY(1,1),
		FACTORY VARCHAR(100),
		FIRST_REGDATE DATETIME
	)
	INSERT INTO @TEMP (FACTORY)
	SELECT G_FACTORY FROM GOODS WITH (READUNCOMMITTED)
	WHERE G_CATEGORY LIKE @CATEGORY + '%'
		AND G_FACTORY<>''
		AND G_MALLCNT>0
		AND G_CONSTRAIN='1'
		AND G_JOBCODE>'0'
		
	GROUP BY G_FACTORY

	SELECT @TCOUNT = COUNT(IDX) FROM @TEMP

	WHILE @TCOUNT<>0
	BEGIN
		SELECT @TMPFACTORY= FACTORY
		FROM @TEMP
		WHERE IDX = @TCOUNT

		SELECT TOP 1 @TMPREGDATE = G_DATE
		FROM GOODS
		WHERE G_FACTORY = @TMPFACTORY
		ORDER BY G_DATE ASC
		
		UPDATE @TEMP
		SET FIRST_REGDATE = @TMPREGDATE
		WHERE IDX = @TCOUNT

		SET @TCOUNT = @TCOUNT -1
	END

	
	SELECT FACTORY
	FROM @TEMP
	WHERE FIRST_REGDATE >= @SDATE
		AND FIRST_REGDATE < @EDATE
	ORDER BY FACTORY ASC
		


	--AND G_DATE >= @SDATE AND G_DATE < @EDATE

END




