/* *************************************************************************
 * NAME : dbo.UDP_ATTRIBUTE_AUTO_COMPLETE
 * TYPE : PROCEDURE (SQL_STORED_PROCEDURE)
 * TIME : Create: 2015-03-20 17:22:29.727
 *        Modify: 2018-05-03 17:23:35.347
 *        Backup: 20180521_1739
 ************************************************************************* */


CREATE PROC [DBO].[UDP_ATTRIBUTE_AUTO_COMPLETE]
AS
BEGIN
	SET NOCOUNT ON;
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

	TRUNCATE /* UDP_ATTRIBUTE_AUTO_COMPLETE:01 */ TABLE GOODS_CATALOG_ATTRIBUTE_AUTO_COMPLETE
	
	INSERT /* UDP_ATTRIBUTE_AUTO_COMPLETE:02 */ INTO GOODS_CATALOG_ATTRIBUTE_AUTO_COMPLETE(ATTRIBUTE_ID, ATTRIBUTE_ELEMENT_ID, ATTRIBUTE_VALUE)
	SELECT DISTINCT
	       ATTRIBUTE_ID
		 , ATTRIBUTE_ELEMENT_ID
		 , LTRIM(RTRIM(ISNULL(ATTRIBUTE_VALUE, ''))) ATTRIBUTE_VALUE
	FROM GOODS_CATALOG_ATTRIBUTE A
		INNER JOIN GOODS_SUM B ON A.G_MODELNO = B.G_MODELNO
	WHERE DEL_YN = 'N'
	  AND G_MALLCNT > 0
	  AND LTRIM(RTRIM(ISNULL(ATTRIBUTE_VALUE, ''))) <> ''
	OPTION (MAXDOP 1)
END
