/* *************************************************************************
 * NAME : dbo.USP_PRICELIST_SEL_2
 * TYPE : PROCEDURE (SQL_STORED_PROCEDURE)
 * TIME : Create: 2007-03-26 15:54:24.647
 *        Modify: 2015-05-15 03:31:33.993
 *        Backup: 20180521_1739
 ************************************************************************* */


CREATE PROC USP_PRICELIST_SEL_2
	@PL_VCODE INT	
AS
BEGIN
	SET NOCOUNT ON
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
	SELECT PL_NO, PL_MODELNO, PL_VCODE, PL_CATEGORY, PL_GOODSNM, 
		ISNULL(PL_PRICE, 0) as PL_PRICE, ISNULL(PL_URL, '') as PL_URL, PL_NOTE, PL_SRVFLAG, PL_STATUS,
		PL_ETC, PL_AUTHFLAG, PL_AUTHDATE, PL_DATE, ISNULL(PL_RIGHTNLEFT, '0') AS PL_RIGHTNLEFT,
		PL_IMGURL, PL_COUPON, PL_DELFEETYPE, ISNULL(PL_DELPRICE,0) as PL_DELPRICE, PL_DELIVERYFLAG,
		PL_DELFEEDESC, PL_DELAREADESC, PL_ACCOUNT_YN, PL_INSTANCE_PRICE
	FROM PRICELIST 
	WHERE PL_VCODE= @PL_VCODE 
		AND PL_MODELNO > 0
		AND PL_GOODSNM = '' 
		AND PL_GOODSNM_CS = CHECKSUM('') 
		AND PL_STATUS < '3'
END