/* *************************************************************************
 * NAME : dbo.UDP_MP_GOODS_SPECNO_ATTRIBUTE
 * TYPE : PROCEDURE (SQL_STORED_PROCEDURE)
 * TIME : Create: 2016-04-05 20:24:03.857
 *        Modify: 2018-05-03 17:23:35.067
 *        Backup: 20180521_1739
 ************************************************************************* */


CREATE PROC [DBO].[UDP_MP_GOODS_SPECNO_ATTRIBUTE]
	@MODELNO INT
AS
BEGIN
	SET NOCOUNT ON;
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

	DECLARE @CATEGORY VARCHAR(12)
	SELECT @CATEGORY = G_CATEGORY
	FROM GOODS
	WHERE G_MODELNO = @MODELNO;

	SELECT DISTINCT A.G_MODELNO, SPECNO
	INTO #MODELNO_SPEC
	FROM GOODS_CATALOG_ATTRIBUTE A
		INNER JOIN GOODS_ATTRIBUTE B ON A.ATTRIBUTE_ID = B.ATTRIBUTE_ID
		INNER JOIN GOODS_ATTRIBUTE_ELEMENT C ON A.ATTRIBUTE_ID = C.ATTRIBUTE_ID AND A.ATTRIBUTE_ELEMENT_ID = C.ATTRIBUTE_ELEMENT_ID
		INNER JOIN GOODS_CATEGORY_ATTRIBUTE D ON A.ATTRIBUTE_ID = D.ATTRIBUTE_ID AND D.CATEGORY IN (SELECT TOP 1 CATEGORY FROM GOODS_CATEGORY_ATTRIBUTE WHERE CATEGORY = LEFT(@CATEGORY, 4) OR CATEGORY = LEFT(@CATEGORY, 6) OR CATEGORY = LEFT(@CATEGORY, 8) ORDER BY LEN(CATEGORY) DESC)
	WHERE A.DEL_YN = 'N'
	  AND B.DEL_YN = 'N'
	  AND C.DEL_YN = 'N'
	  AND SPECNO > 0
	  AND G_MODELNO = @MODELNO

	DELETE FROM TBL_MODELNO_SPEC WHERE MODELNO = @MODELNO

	INSERT INTO TBL_MODELNO_SPEC(MODELNO, SPECNO)
	SELECT G_MODELNO, SPECNO
	FROM #MODELNO_SPEC


	SET TRANSACTION ISOLATION LEVEL READ COMMITTED;
	--##################################################################
	DECLARE @QRY VARCHAR(8000)
	SET @QRY = 'DELETE OPENQUERY(ORADB, ''SELECT MODELNO, SPECNO FROM TBL_MODELNO_SPEC WHERE MODELNO = ' + CAST(@MODELNO AS VARCHAR(20)) + ''')'
	EXEC (@QRY)

	INSERT OPENQUERY(ORADB, 'SELECT MODELNO, SPECNO FROM TBL_MODELNO_SPEC')
	SELECT G_MODELNO, SPECNO
	FROM #MODELNO_SPEC
	--##################################################################
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
END
