/* *************************************************************************
 * NAME : dbo.USP_IR4_SEARCH_PRCS_SRT
 * TYPE : PROCEDURE (SQL_STORED_PROCEDURE)
 * TIME : Create: 2015-11-25 17:29:32.64
 *        Modify: 2016-01-11 11:34:55.123
 *        Backup: 20180521_1739
 ************************************************************************* */

CREATE PROCEDURE USP_IR4_SEARCH_PRCS_SRT
	@OPT CHAR(1)
AS
BEGIN
	SET NOCOUNT ON;
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

	UPDATE SYS_SEARCH_PRCS_LOG
	SET PRCS_SRT_DT = GETDATE(), COLLECTION_TYPE_CD = @OPT, PRCS_STTS_VLU = 'P'
	WHERE COLLECTION_NM = 'MP_GOODS'

	TRUNCATE TABLE TBL_GOODS_BRAND_DETAIL
	IF @OPT = 'T'
		BEGIN
			INSERT INTO TBL_GOODS_BRAND_DETAIL(MODELNO, GB1_NO, GB2_NO)
			SELECT MODELNO, GB1_NO, GB2_NO
			FROM SEARCHKEY_193.SEARCHKEY.DBO.TBL_GOODS_BRAND_DETAIL
		END
	ELSE
		BEGIN
			INSERT INTO TBL_GOODS_BRAND_DETAIL(MODELNO, GB1_NO, GB2_NO)
			SELECT MODELNO, GB1_NO, GB2_NO
			FROM SEARCHKEY_193.SEARCHKEY.DBO.TBL_GOODS_BRAND_DETAIL
			WHERE MODELNO IN (
				SELECT JG_MODELNO
				FROM LOGDB.DBO.JOB_GOODS 
				WHERE JG_DATE > (SELECT PRCS_FNS_DT FROM SYS_SEARCH_PRCS_LOG WHERE COLLECTION_NM = 'MP_GOODS')
				  AND JG_DATE <=(SELECT PRCS_SRT_DT FROM SYS_SEARCH_PRCS_LOG WHERE COLLECTION_NM = 'MP_GOODS')
				UNION ALL
				SELECT JG_MODELNO
				FROM LOGDB.DBO.JOB_GOODS_OLD 
				WHERE JG_DATE > (SELECT PRCS_FNS_DT FROM SYS_SEARCH_PRCS_LOG WHERE COLLECTION_NM = 'MP_GOODS')
				  AND JG_DATE <=(SELECT PRCS_SRT_DT FROM SYS_SEARCH_PRCS_LOG WHERE COLLECTION_NM = 'MP_GOODS'))
		END
END