/* *************************************************************************
 * NAME : dbo.USP_PRICELIST_SEL_11
 * TYPE : PROCEDURE (SQL_STORED_PROCEDURE)
 * TIME : Create: 2007-03-26 17:55:01.043
 *        Modify: 2018-05-03 17:23:35.877
 *        Backup: 20180521_1739
 ************************************************************************* */

CREATE PROC USP_PRICELIST_SEL_11
	@PL_VCODE INT,
	@PL_GOODSNM NVARCHAR(200)
AS
BEGIN
	SET NOCOUNT ON
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
	SELECT TOP 1 
		PL_NO ,ISNULL(PL_MODELNO, 0) ,ISNULL(PL_CATEGORY, '00') , PL_GOODSNM, PL_PRICE ,PL_URL,
		PL_STATUS, PL_RIGHTNLEFT, PL_DELIVERYINFO, PL_IMGURL, PL_COUPON, PL_ACCOUNT_YN, PL_FREEINTEREST, PL_GOODSFACTORY, PL_GOODSCODE
	FROM PRICELIST
	WHERE PL_VCODE = @PL_VCODE 
		AND PL_GOODSNM_CS = CHECKSUM(@PL_GOODSNM) 
		AND PL_GOODSNM = @PL_GOODSNM
END