/* *************************************************************************
 * NAME : dbo.del_20120816_UDP_JOB_STATISTICS_ETC_MODELNO_LIST
 * TYPE : PROCEDURE (SQL_STORED_PROCEDURE)
 * TIME : Create: 2012-08-16 15:42:49.403
 *        Modify: 2015-05-15 00:53:14.497
 *        Backup: 20180521_1739
 ************************************************************************* */

CREATE PROC del_20120816_UDP_JOB_STATISTICS_ETC_MODELNO_LIST
	@LCATE VARCHAR(8) = '%'
AS
BEGIN
	SET NOCOUNT ON
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

	SELECT *
	FROM JOB_STATISTICS_ETC_MODELNO WITH (READUNCOMMITTED)
	WHERE JSEM_DATE > CONVERT(VARCHAR(8), DATEADD(D,-30,GETDATE()),112)  
	AND JSEM_CATE LIKE @LCATE
	ORDER BY JSEM_DATE DESC, JSEM_CATE ASC
END

