/* *************************************************************************
 * NAME : dbo.UP_EX_SELECT_ALL_PROC
 * TYPE : PROCEDURE (SQL_STORED_PROCEDURE)
 * TIME : Create: 2004-08-17 14:36:12.013
 *        Modify: 2015-05-15 00:52:26.01
 *        Backup: 20180521_1739
 ************************************************************************* */





-- UP_EX_SELECT_ALL_PROC   :   2004.8.17 --
CREATE        PROC UP_EX_SELECT_ALL_PROC 
	@szInsCcateNO varchar(100)
AS
	SET NOCOUNT ON
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

		SELECT NBSE_START_SOURCE1, NBSE_START_SOURCE2, NBSE_FINISH_SOURCE, NBSE_ATYPE, NBSE_ATYPECHECK, NBSE_DOMAIN, NBSE_FILENAME, NBSE_FORM_PAGING1, NBSE_FORM_PAGING2, NBSE_SNUM_PAGING, NBSE_FORM_ANOTHER, NBSE_SPLIT_STRING, NBSE_URLEND_SEPARATOR, NBSE_URL_REPLACE, NBSE_URL_REPLACE_STRING, NBSE_PASS_GOODS_SEPARATOR1, NBSE_PASS_GOODS_SEPARATOR2, NBSE_PASS_GOODS_SEPARATOR3, NBSE_END_GOODS_SEPARATOR, NBSE_PASS_PRICE_SEPARATOR1, NBSE_PASS_PRICE_SEPARATOR2, NBSE_PASS_PRICE_SEPARATOR3, NBSE_END_PRICE_SEPARATOR, NBSE_SOLDOUT_STRING, NBSE_BTYPE, NBSE_OBJ_START_SOURCE1, NBSE_OBJ_START_SOURCE2, NBSE_OBJ_SEPARATOR, NBSE_OBJ_STRING, NBSE_FLAG, NBSE_RIGHTNLEFT, NBSE_IMGURL, NBSE_COUPON, NBSE_COUPON_STRING, NBSE_ACCOUNT_YN
		FROM TBL_NB_SHOP_EX WITH (READUNCOMMITTED) 
		WHERE NBSE_NO = @szInsCcateNO
	SET NOCOUNT OFF




