/* *************************************************************************
 * NAME : dbo.UDP_SYNC_SHOPLIST
 * TYPE : PROCEDURE (SQL_STORED_PROCEDURE)
 * TIME : Create: 2007-03-22 10:35:25.32
 *        Modify: 2015-05-15 00:52:26.02
 *        Backup: 20180521_1739
 ************************************************************************* */



CREATE        PROC [dbo].[UDP_SYNC_SHOPLIST] 
	@INSGROUP char(3)
AS
BEGIN
	SET NOCOUNT ON
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
		
		IF (@INSGROUP = 'ALL')
			BEGIN
				SELECT VCODE, SRVFLAG, GROUP_INFO, NOTE, STATUS, SDATE, EDATE, SDATE_STEP1, EDATE_STEP1, SDATE_STEP2, EDATE_STEP2, SDATE_STEP3, EDATE_STEP3
				FROM dbo.TBL_NB_SHOPLIST WITH(NOLOCK)
			END	
		ELSE
			BEGIN
				SELECT VCODE, SRVFLAG, GROUP_INFO, NOTE, STATUS, SDATE, EDATE, SDATE_STEP1, EDATE_STEP1, SDATE_STEP2, EDATE_STEP2, SDATE_STEP3, EDATE_STEP3
				FROM dbo.TBL_NB_SHOPLIST WITH(NOLOCK)
				WHERE GROUP_INFO = @INSGROUP
			END

END




