/* *************************************************************************
 * NAME : ASISTEST.UDP_MAIN_SOCIAL_STAGE_UP
 * TYPE : PROCEDURE
 * TIME : Create: 2018-05-04 18:33:27
 *        Modify: 2018-05-04 18:53:44
 *        Backup: 20180521_1739
 ************************************************************************* */


  CREATE OR REPLACE PROCEDURE "ASISTEST"."UDP_MAIN_SOCIAL_STAGE_UP" 
IS

BEGIN

  DELETE TBL_MAIN_SOCIAL@ORADB_253;

  INSERT INTO TBL_MAIN_SOCIAL@ORADB_253   
  (SELECT SOCIAL_IDX,A.DEAL_SHOP_CODE DEAL_SHOP_CODE, A.META_ID META_ID, A.STATUS STATUS , A.TITLE TITLE, B.ORIGINAL ORIGINAL, A.DISCOUNT DISCOUNT, B.PRICE PRICE, B.START_AT START_AT,B.END_AT END_AT,
  A.IMAGE IMAGE, A.URL URL, DISPLAY_START_AT, DISPLAY_END_AT, DIS_CATE, DIS_ORDER, A.REG_DATE REG_DATE, B.COUPON_START_AT COUPON_START_AT, B.COUPON_END_AT COUPON_END_AT FROM
  TBL_MAIN_SOCIAL_MAN A, DEAL_GOODS B
  WHERE A.DEAL_SHOP_CODE = B.DEAL_SHOP_CODE AND A.META_ID = B.META_ID);
  commit;

 EXCEPTION
     WHEN OTHERS THEN
        rollback;
        DBMS_OUTPUT.PUT_LINE('UDP_MAIN_SOCIAL_STAGE_UP error : errorcode => ' || SQLCODE || ', ERRMSG => ' || SQLERRM);

END;