/* *************************************************************************
 * NAME : ASISTEST.UDP_MP_COMPONENT_MODELNO
 * TYPE : PROCEDURE
 * TIME : Create: 2018-05-04 18:33:28
 *        Modify: 2018-05-04 18:53:45
 *        Backup: 20180521_1739
 ************************************************************************* */


  CREATE OR REPLACE PROCEDURE "ASISTEST"."UDP_MP_COMPONENT_MODELNO" 
(CP_MODELNO TBL_GOODS.MODELNO%TYPE, CP_MM_ID TBL_COMPONENT.INS_OPRT%TYPE)
IS
	CP_COMPONENT TBL_GOODS_COMPONENT.ALL_COMPONENT%TYPE := '';
	SZSTR TBL_GOODS_COMPONENT.ALL_COMPONENT%TYPE := '';
BEGIN
	-- 전성분
	BEGIN
		SELECT TRIM(NVL(ALL_COMPONENT, ''))
		INTO CP_COMPONENT
		FROM TBL_GOODS_COMPONENT
		WHERE MODELNO = CP_MODELNO;

		EXCEPTION
			WHEN NO_DATA_FOUND THEN NULL;
	END;

    WHILE LENGTH(CP_COMPONENT) > 0 LOOP
    	SZSTR := TRIM(CASE WHEN INSTR(CP_COMPONENT, ',') > 0 THEN SUBSTR(CP_COMPONENT, 1, INSTR(CP_COMPONENT, ',') - 1) ELSE CP_COMPONENT END);
    	CP_COMPONENT := TRIM(CASE WHEN INSTR(CP_COMPONENT, ',') > 0 THEN SUBSTR(CP_COMPONENT, INSTR(CP_COMPONENT, ',') + 1, LENGTH(CP_COMPONENT)) ELSE '' END);

    	--DBMS_OUTPUT.PUT_LINE(SZSTR);
        --DBMS_OUTPUT.PUT_LINE(CP_COMPONENT);

		-- 성분 MAPPING
		INSERT INTO TBL_COMPONENT_MODELNO_ORIGINAL (MODELNO, CP_ID, DEL_YN, INS_DATE, INS_OPRT, UPD_DATE, UPD_OPRT)
		SELECT DISTINCT CP_MODELNO, CP_ID, 'N', SYSDATE, CP_MM_ID, SYSDATE, 'temp_batch'
		FROM (
			SELECT CP_ID
			FROM TBL_COMPONENT
			WHERE CP_NAME_KR = SZSTR AND DEL_YN = 'N'
			UNION ALL
			SELECT CP_ID
			FROM TBL_COMPONENT_SYNONYM
			WHERE CPS_NAME = SZSTR AND DEL_YN = 'N'
		) A
		WHERE NOT EXISTS(SELECT DISTINCT '1' FROM TBL_COMPONENT_MODELNO_ORIGINAL WHERE MODELNO = CP_MODELNO AND CP_ID = A.CP_ID);

		-- 성분 MAPPING
        UPDATE TBL_COMPONENT_MODELNO_ORIGINAL
        SET DEL_YN = 'N'
          , INS_DATE = (CASE WHEN DEL_YN = 'Y' THEN SYSDATE ELSE INS_DATE END)
          , UPD_DATE = (CASE WHEN DEL_YN = 'Y' THEN SYSDATE ELSE UPD_DATE END)
          , UPD_OPRT = 'temp_batch'
        WHERE MODELNO = CP_MODELNO AND CP_ID IN (
        	SELECT CP_ID
			FROM TBL_COMPONENT
			WHERE CP_NAME_KR = SZSTR AND DEL_YN = 'N'
			UNION ALL
			SELECT CP_ID
			FROM TBL_COMPONENT_SYNONYM
			WHERE CPS_NAME = SZSTR AND DEL_YN = 'N'
		);
    END LOOP;

    UPDATE TBL_COMPONENT_MODELNO_ORIGINAL
	SET DEL_YN = (CASE WHEN UPD_OPRT = 'temp_batch' THEN DEL_YN ELSE 'Y' END)
	  , UPD_OPRT = (CASE WHEN UPD_OPRT = 'temp_batch' THEN CP_MM_ID ELSE 'LAB_BATCH' END)
	  , UPD_DATE = (CASE WHEN UPD_OPRT = 'temp_batch' THEN UPD_DATE ELSE SYSDATE END)
	WHERE MODELNO = CP_MODELNO AND DEL_YN = 'N';
END;