/* *************************************************************************
 * NAME : ASISTEST.UDP_MAIN_PLANS_ENURI_UP
 * TYPE : PROCEDURE
 * TIME : Create: 2018-05-04 18:33:27
 *        Modify: 2018-05-07 13:11:15
 *        Backup: 20180521_1739
 ************************************************************************* */


  CREATE OR REPLACE PROCEDURE "ASISTEST"."UDP_MAIN_PLANS_ENURI_UP" AS 
BEGIN

  DELETE TBL_MAIN_PLANS;
  INSERT INTO TBL_MAIN_PLANS
  SELECT GOODS_IDX, SUBJECT_IDX, GOODS_TYPE, SHOP_NAME, GOODS_TITLE, GOODS_URL, USE_YN, START_DATE, END_DATE, REG_DATE, PLANS_IMAGE FROM TBL_MAIN_PLANS_MAN;
  commit;
  
  DELETE TBL_MAIN_PLAN_SUBJECT;
  INSERT INTO TBL_MAIN_PLAN_SUBJECT
  SELECT SUBJECT_IDX, TITLE, SUBJECT_ORDER, USE_YN FROM TBL_MAIN_PLAN_SUBJECT_MAN;
  commit;

 EXCEPTION
     WHEN OTHERS THEN
       DBMS_OUTPUT.PUT_LINE('UDP_MAIN_PLANS_ENURI_UP error : errorcode => ' || SQLCODE || ', ERRMSG => ' || SQLERRM);

END;