/* *************************************************************************
 * NAME : ASISTEST.UDP_TOUR_MASTER_CREATE
 * TYPE : PROCEDURE
 * TIME : Create: 2018-05-04 18:33:32
 *        Modify: 2018-05-07 13:11:15
 *        Backup: 20180521_1739
 ************************************************************************* */


  CREATE OR REPLACE PROCEDURE "ASISTEST"."UDP_TOUR_MASTER_CREATE" 
IS

BEGIN

  DBMS_OUTPUT.ENABLE;
  DBMS_OUTPUT.PUT_LINE('UDP_ANALYZE start ......');

  DELETE TBL_TOUR_GOODS_MASTER;

  INSERT INTO TBL_TOUR_GOODS_MASTER
    SELECT MODELNO, TR_GOODSUBNAME,TR_SUBPERIOD_DAY,TR_FACTORY,SHOP_CODE,MIN(TR_PRICE) MINPRICE,MAX(TR_PRICE) MAXPRICE
    FROM TBL_TOUR_GOODSUB
    WHERE TR_DEL_FLAG='0'
    GROUP BY MODELNO, TR_GOODSUBNAME,TR_SUBPERIOD_DAY,TR_FACTORY,SHOP_CODE
    ORDER BY TR_GOODSUBNAME;

    commit;

  DBMS_OUTPUT.PUT_LINE('UDP_ANALYZE end ......');

 EXCEPTION
     WHEN OTHERS THEN
       DBMS_OUTPUT.PUT_LINE('UDP_ANALYZE error : errorcode => ' || SQLCODE || ', ERRMSG => ' || SQLERRM);

END;