/* *************************************************************************
 * NAME : ASISTEST.UDP_MAIN_TOUR_STAGE_UP
 * TYPE : PROCEDURE
 * TIME : Create: 2018-05-04 18:33:27
 *        Modify: 2018-05-04 18:53:44
 *        Backup: 20180521_1739
 ************************************************************************* */


  CREATE OR REPLACE PROCEDURE "ASISTEST"."UDP_MAIN_TOUR_STAGE_UP" 
IS

BEGIN

  DELETE TBL_MAIN_TOUR_GOODS@ORADB_253;

  INSERT INTO TBL_MAIN_TOUR_GOODS@ORADB_253 
  SELECT GOODS_IDX,MODEL_SUBNO,SHOP_CODE,GOODS_TITLE,SUM_PRICE,START_DATE,END_DATE,IMG_URL,URL,VIEW_YN,REG_DATE,SPECIAL_PRICE_YN
  FROM TBL_MAIN_TOUR_GOODS_MAN
  commit;

 EXCEPTION
     WHEN OTHERS THEN
        ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('UDP_MAIN_TOUR_ENURI_UP error : errorcode => ' || SQLCODE || ', ERRMSG => ' || SQLERRM);

END;