/* *************************************************************************
 * NAME : ASISTEST.UDP_ENURI_PC_PRODUCT
 * TYPE : PROCEDURE
 * TIME : Create: 2018-05-04 18:33:22
 *        Modify: 2018-05-04 18:53:42
 *        Backup: 20180521_1739
 ************************************************************************* */


  CREATE OR REPLACE PROCEDURE "ASISTEST"."UDP_ENURI_PC_PRODUCT" ( logDate VARCHAR2  ) AS 
v_run_date           char(14) :=0; 
v_sqlcode           varchar2(4000) :='';
v_sqlmsg            varchar2(4000) :='';
BEGIN
  SELECT to_char(sysdate,'YYYYMMDDHH24MISS') INTO v_run_date FROM dual;
  INSERT INTO TBL_ENURIPC_PRODUCT_BAK (PD_NO,PD_NAME,PD_IMAGE,PD_MADE,PD_CATE1,PD_CATE2,PD_MENT,PD_DELIVERY_BOX,MODELNO,PD_REGDATE,PD_VIEWCNT,PD_DPRICE,PD_BILL_YN,PD_NO_INTEREST,PD_COUPON,PD_CARD_DISCOUNT,PD_DIFF_DPRICE,PD_INSTALL_FEE,P_CATE_CODE,PILSU_INFO_TYPE,PD_MINPRICE,PRICE_COMPARE_CLOSE_YN,AD_ORD,BEST_ORD,BAK_DATE)   
  (
    SELECT PD_NO,PD_NAME,PD_IMAGE,PD_MADE,PD_CATE1,PD_CATE2,PD_MENT,PD_DELIVERY_BOX,MODELNO,PD_REGDATE,PD_VIEWCNT,PD_DPRICE,PD_BILL_YN,PD_NO_INTEREST,PD_COUPON,PD_CARD_DISCOUNT,PD_DIFF_DPRICE,PD_INSTALL_FEE,P_CATE_CODE,PILSU_INFO_TYPE,PD_MINPRICE,PRICE_COMPARE_CLOSE_YN,AD_ORD,BEST_ORD,v_run_date FROM TBL_ENURIPC_PRODUCT
   );
   DELETE TBL_ENURIPC_PRODUCT;
   INSERT INTO TBL_ENURIPC_PRODUCT (SELECT * FROM TBL_ENURIPC_PRODUCT_TMP);       
 
  MERGE INTO TBL_ENURIPC_GOODS_PV  P
  USING ( SELECT MODELNO,PD_NO,PD_NAME 
          FROM TBL_ENURIPC_PRODUCT 
         ) V
  ON ( P.PD_NO = V.PD_NO)
  WHEN MATCHED THEN
    UPDATE SET P.PD_NAME = V.PD_NAME, P.UPD_DATE = SYSDATE
  WHEN NOT MATCHED THEN
    INSERT (P.MODELNO,P.PD_NO,P.PD_NAME,P.INS_DATE)
    VALUES (NVL(V.MODELNO,0),V.PD_NO,V.PD_NAME,SYSDATE);
    
  INSERT INTO TBL_ENURIPC_PRODUCT_PILSU_B(PD_NO,PILSU_NO,ITEM,CONST,BAK_DATE) 
  (
    SELECT PD_NO,PILSU_NO,ITEM,CONST,v_run_date FROM TBL_ENURIPC_PRODUCT_PILSU
   );
   DELETE TBL_ENURIPC_PRODUCT_PILSU;
   INSERT INTO TBL_ENURIPC_PRODUCT_PILSU (SELECT * FROM TBL_ENURIPC_PRODUCT_PILSU_T);
   
  commit; 
  UDP_ENURIPC_SPEC(logDate); 
 
 EXCEPTION
     WHEN OTHERS THEN
       v_sqlcode := SQLCODE;
       v_sqlmsg  := SQLERRM;       
       ROLLBACK;
       insert into TBL_ENURIPC_API_LOG values (logDate,'UDP_ENURI_PC_PRODUCT',sysdate,sysdate,'FAIL','UDP_ENURI_PC_PRODUCT error : errorcode => ' || v_sqlcode || ', ERRMSG => ' || v_sqlmsg,0,'PRODUCT');
       commit;  
         
END UDP_ENURI_PC_PRODUCT;