/* *************************************************************************
 * NAME : ASISTEST.UDP_METAGOODS_CHECK_SALE_COUNT
 * TYPE : PROCEDURE
 * TIME : Create: 2018-05-04 18:33:28
 *        Modify: 2018-05-07 13:11:15
 *        Backup: 20180521_1739
 ************************************************************************* */


  CREATE OR REPLACE PROCEDURE "ASISTEST"."UDP_METAGOODS_CHECK_SALE_COUNT" 
IS

BEGIN
    UPDATE TBL_META_GOODS_NEW SET DEAL_STATUS = '3' WHERE SALE_COUNT >= MAX_COUNT AND DEAL_STATUS = '1';
    UPDATE TBL_META_GOODS_NEW SET DEAL_STATUS = '3' WHERE MOD_DATE IS NOT NULL AND MOD_DATE < TO_CHAR(SYSDATE,'YYYYMMDD') AND TO_CHAR(MOD_DATE,'YYYYMMDD') = TO_CHAR(SYSDATE-2,'YYYYMMDD');      
    commit;
END;