/* *************************************************************************
 * NAME : DBENURI.UDP_ENURI_PC
 * TYPE : PROCEDURE
 * TIME : Create: 2018-03-28 18:50:00
 *        Modify: 2018-03-28 18:50:04
 *        Backup: 20180521_1739
 ************************************************************************* */


  CREATE OR REPLACE PROCEDURE "DBENURI"."UDP_ENURI_PC" ( logDate VARCHAR2  ) AS 
v_run_date           char(14) :=0; 
v_sqlcode           varchar2(4000) :='';
v_sqlmsg            varchar2(4000) :='';
BEGIN
  SELECT to_char(sysdate,'YYYYMMDDHH24MISS') INTO v_run_date FROM dual;
  
  INSERT INTO TBL_ENURIPC_GOODS_BAK (MODELNO,SY_NO,SY_NAME,SY_SPEC,SY_CATE,SY_EVENT,SY_ADVICE,SY_MD,SY_HASHTAG,SY_IMAGE,SY_CONTENTS,SY_PILSU_INFO,SY_MENT,SY_LEVEL,SY_PRICE_CARD,SY_PRICE_CASH,SY_MINPRICE,SY_REGDATE,SY_VIEWCNT,SY_MADE,SY_DPRICE,SY_BILL_YN,SY_NO_INTEREST,SY_COUPON,SY_CARD_DISCOUNT,SY_DIFF_DPRICE,SY_INSTALL_FEE, SY_PC_TYPE, SY_SS_ORD, BAK_DATE) 
  (
    SELECT MODELNO,SY_NO,SY_NAME,SY_SPEC,SY_CATE,SY_EVENT,SY_ADVICE,SY_MD,SY_HASHTAG,SY_IMAGE,SY_CONTENTS,SY_PILSU_INFO,SY_MENT,SY_LEVEL,SY_PRICE_CARD,SY_PRICE_CASH,SY_MINPRICE,SY_REGDATE,SY_VIEWCNT,SY_MADE,SY_DPRICE,SY_BILL_YN,SY_NO_INTEREST,SY_COUPON,SY_CARD_DISCOUNT,SY_DIFF_DPRICE,SY_INSTALL_FEE, SY_PC_TYPE, SY_SS_ORD, v_run_date FROM TBL_ENURIPC_GOODS
  );
  DELETE TBL_ENURIPC_GOODS;
  INSERT INTO TBL_ENURIPC_GOODS (SELECT * FROM TBL_ENURIPC_GOODS_TMP);
  
  MERGE INTO TBL_ENURIPC_GOODS_PV  P
    USING ( SELECT MODELNO,SY_NO,SY_NAME 
          FROM TBL_ENURIPC_GOODS 
         ) V
  ON ( P.SY_NO = V.SY_NO)
  WHEN MATCHED THEN
    UPDATE SET P.PD_NAME = V.SY_NAME, P.UPD_DATE = SYSDATE
  WHEN NOT MATCHED THEN
    INSERT (P.MODELNO,P.SY_NO,P.PD_NAME,P.INS_DATE)
    VALUES (V.MODELNO,V.SY_NO,V.SY_NAME,SYSDATE);  
  /*
  UPDATE TBL_ENURIPC_GOODS A SET (MODELNO,SY_REGDATE,SY_VIEWCNT) = 
  (SELECT MODELNO,SY_REGDATE,SY_VIEWCNT FROM TBL_ENURIPC_GOODS_BAK B WHERE BAK_DATE = v_run_date  AND A.SY_NO = B.SY_NO);  
  */
  
  INSERT INTO TBL_ENURIPC_GOODS_PILSU_INFO_B(SY_NO,PILSU_NO,ITEM,CONST,BAK_DATE) 
  (
    SELECT SY_NO,PILSU_NO,ITEM,CONST,v_run_date FROM TBL_ENURIPC_GOODS_PILSU_INFO
   );
   DELETE TBL_ENURIPC_GOODS_PILSU_INFO;
   INSERT INTO TBL_ENURIPC_GOODS_PILSU_INFO (SELECT * FROM TBL_ENURIPC_GOODS_PILSU_INFO_T);
   
  INSERT INTO TBL_ENURIPC_COMPANY_BAK(SY_NO,NO,PRICE,BAK_DATE) 
  (
    SELECT SY_NO,NO,PRICE,v_run_date FROM TBL_ENURIPC_COMPANY
   );
   DELETE TBL_ENURIPC_COMPANY;
   INSERT INTO TBL_ENURIPC_COMPANY (SELECT * FROM TBL_ENURIPC_COMPANY_TMP);
   
  UPDATE TBL_ENURIPC_GOODS A SET SY_MINPRICE = 
  (SELECT MINPRICE FROM (SELECT SY_NO,  MIN(PRICE) AS MINPRICE FROM TBL_ENURIPC_COMPANY WHERE PRICE > 0 GROUP BY SY_NO ) B
  WHERE A.SY_NO = B.SY_NO);   
   
  INSERT INTO TBL_ENURIPC_SUBGOODS_BAK (SY_NO,PD_NO,PD_CNT,CATE,CATE_NAME,TYPE,SEARCH,MODELNO,ORDERNO,CATE_CODE,BAK_DATE) 
  (
    SELECT SY_NO,PD_NO,PD_CNT,CATE,CATE_NAME,TYPE,SEARCH,MODELNO,ORDERNO,CATE_CODE,v_run_date FROM TBL_ENURIPC_SUBGOODS
   );
   DELETE TBL_ENURIPC_SUBGOODS; 
   INSERT INTO TBL_ENURIPC_SUBGOODS (SELECT * FROM TBL_ENURIPC_SUBGOODS_TMP);  
   
  INSERT INTO TBL_ENURIPC_SUBGOODS_CHANGE_B (PD_NO,C_NAME,C_PD_NO,C_PD_CNT,C_MODELNO,SY_NO,CATE_CODE,BAK_DATE,ORDERNO) 
  (
    SELECT PD_NO,C_NAME,C_PD_NO,C_PD_CNT,C_MODELNO,SY_NO,CATE_CODE,v_run_date,ORDERNO FROM TBL_ENURIPC_SUBGOODS_CHANGE
   );
   DELETE TBL_ENURIPC_SUBGOODS_CHANGE;
   INSERT INTO TBL_ENURIPC_SUBGOODS_CHANGE (SELECT * FROM TBL_ENURIPC_SUBGOODS_CHANGE_T);    
  
  INSERT INTO TBL_ENURIPC_SUBGOODS_TYPE_BAK (CATE,CATE_NAME,TYPE,CATE_ORDER,BAK_DATE) 
  (
    SELECT CATE,CATE_NAME,TYPE,CATE_ORDER,v_run_date FROM TBL_ENURIPC_SUBGOODS_TYPE
   );
   DELETE TBL_ENURIPC_SUBGOODS_TYPE;
   INSERT INTO TBL_ENURIPC_SUBGOODS_TYPE (SELECT * FROM TBL_ENURIPC_SUBGOODS_TYPE_TMP);    
  commit; 

 EXCEPTION
     WHEN OTHERS THEN
       DBMS_OUTPUT.PUT_LINE('UDP_ENURI_PC error : errorcode => ' || SQLCODE || ', ERRMSG => ' || SQLERRM);
       v_sqlcode := SQLCODE;
       v_sqlmsg  := SQLERRM;       
       ROLLBACK;
       insert into TBL_ENURIPC_API_LOG values (logDate,'UDP_ENURI_PC',sysdate,sysdate,'FAIL','UDP_ENURI_PC error : errorcode => ' || v_sqlcode || ', ERRMSG => ' || v_sqlmsg,0,'PC');
       commit;

END UDP_ENURI_PC;