/* *************************************************************************
 * NAME : DBENURI.SP_RESET_SEQ
 * TYPE : PROCEDURE
 * TIME : Create: 2018-03-28 18:50:00
 *        Modify: 2018-03-28 18:50:02
 *        Backup: 20180521_1739
 ************************************************************************* */


  CREATE OR REPLACE PROCEDURE "DBENURI"."SP_RESET_SEQ" (SEQ_NAME IN VARCHAR2)
IS
  CURR_VAL INTEGER;
BEGIN
    EXECUTE IMMEDIATE 'ALTER SEQUENCE '||SEQ_NAME||' MINVALUE 0';

    EXECUTE IMMEDIATE 'SELECT '||SEQ_NAME||'.NEXTVAL FROM DUAL' INTO CURR_VAL;

    EXECUTE IMMEDIATE 'ALTER SEQUENCE '||SEQ_NAME||' INCREMENT BY -'||CURR_VAL;

    EXECUTE IMMEDIATE 'SELECT '||SEQ_NAME||'.NEXTVAL FROM DUAL' INTO CURR_VAL;

    EXECUTE IMMEDIATE 'ALTER SEQUENCE '||SEQ_NAME||' INCREMENT BY 1';
END SP_RESET_SEQ;