/* *************************************************************************
 * NAME : DBENURI.MOBILE_MAIN_TRG
 * TYPE : TRIGGER
 * TIME : Create: 2018-03-28 18:50:09
 *        Modify: 2018-03-28 18:50:09
 *        Backup: 20180521_1739
 ************************************************************************* */


  CREATE OR REPLACE TRIGGER "DBENURI"."MOBILE_MAIN_TRG" 
BEFORE INSERT ON DBENURI.MOBILE_MAIN 
FOR EACH ROW
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ITEM_ID IS NULL THEN
      SELECT MOBILE_MAIN_SEQ1.NEXTVAL INTO :NEW.ITEM_ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;

ALTER TRIGGER "DBENURI"."MOBILE_MAIN_TRG" ENABLE