/* *************************************************************************
 * NAME : DBENURI.UDP_METAGOODS_CHECK_SALE_COUNT
 * TYPE : PROCEDURE
 * TIME : Create: 2018-03-28 18:50:01
 *        Modify: 2018-03-28 18:50:03
 *        Backup: 20180521_1739
 ************************************************************************* */


  CREATE OR REPLACE PROCEDURE "DBENURI"."UDP_METAGOODS_CHECK_SALE_COUNT" 
IS

BEGIN
    UPDATE TBL_META_GOODS_NEW SET DEAL_STATUS = '3' WHERE SALE_COUNT >= MAX_COUNT AND DEAL_STATUS = '1';
    UPDATE TBL_META_GOODS_NEW SET DEAL_STATUS = '3' WHERE MOD_DATE IS NOT NULL AND MOD_DATE < TO_CHAR(SYSDATE,'YYYYMMDD') AND TO_CHAR(MOD_DATE,'YYYYMMDD') = TO_CHAR(SYSDATE-2,'YYYYMMDD');      
    commit;
END;