/* *************************************************************************
 * NAME : DBENURI.UDP_MAIN_DEPART_GOODS_ENURI_UP
 * TYPE : PROCEDURE
 * TIME : Create: 2018-03-28 18:50:00
 *        Modify: 2018-03-28 18:50:03
 *        Backup: 20180521_1739
 ************************************************************************* */


  CREATE OR REPLACE PROCEDURE "DBENURI"."UDP_MAIN_DEPART_GOODS_ENURI_UP" AS 
BEGIN

  DELETE FROM TBL_MAIN_DEPT_GOODS WHERE MENU_NO='1';
  
  INSERT INTO TBL_MAIN_DEPT_GOODS
  SELECT MENU_NO, MODELNO, INS_DATE, MODELNM, BRAND, MODEL_IMG, CA_CODE, MOBILE_YN, PLAN_TITLE, PLAN_CONTENT, PLAN_URL FROM TBL_MAIN_DEPT_GOODS_MAN WHERE MENU_NO='1';
  commit; 

 EXCEPTION
     WHEN OTHERS THEN
       DBMS_OUTPUT.PUT_LINE('UDP_MAIN_DEPART_GOODS_ENURI_UP error : errorcode => ' || SQLCODE || ', ERRMSG => ' || SQLERRM);
       
END UDP_MAIN_DEPART_GOODS_ENURI_UP;