/* *************************************************************************
 * NAME : DBENURI.UDP_MAIN_KEYWORD_ENURI_UP
 * TYPE : PROCEDURE
 * TIME : Create: 2018-03-28 18:50:00
 *        Modify: 2018-03-28 18:50:03
 *        Backup: 20180521_1739
 ************************************************************************* */


  CREATE OR REPLACE PROCEDURE "DBENURI"."UDP_MAIN_KEYWORD_ENURI_UP" AS 
BEGIN

  DELETE TBL_MAIN_KEYWORD;
  INSERT INTO TBL_MAIN_KEYWORD
  SELECT KEYWORD_IDX, KEYWORD, URL, VIEW_YN, REG_DATE, KEYWORD_DESC, KEYWORD_ORDER FROM TBL_MAIN_KEYWORD_MAN;
  commit;
  
  DELETE TBL_MAIN_KEYWORD_GOODS;
  INSERT INTO TBL_MAIN_KEYWORD_GOODS
  SELECT GOODS_IDX, KEYWORD_IDX, IS_ENURI, MODELNO, GOODSCODE, SHOP_CODE, MODELNM, FACTORY, CA_CODE, COPY, MODEL_IMAGE, URL, VIEW_YN, REG_DATE ,SPECIAL_PRICE, SPECIAL_CATEGORY FROM TBL_MAIN_KEYWORD_GOODS_MAN;
  commit;

 EXCEPTION
     WHEN OTHERS THEN
       DBMS_OUTPUT.PUT_LINE('UDP_MAIN_KEYWORD_ENURI_UP error : errorcode => ' || SQLCODE || ', ERRMSG => ' || SQLERRM);

END;