/* *************************************************************************
 * NAME : DBENURI.MOBILE_NEWS_BOX_TRG
 * TYPE : TRIGGER
 * TIME : Create: 2018-03-28 18:50:09
 *        Modify: 2018-03-28 18:50:09
 *        Backup: 20180521_1739
 ************************************************************************* */


  CREATE OR REPLACE TRIGGER "DBENURI"."MOBILE_NEWS_BOX_TRG" 
BEFORE INSERT ON MOBILE_NEWS_BOX 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.NEWS_ID IS NULL THEN
      SELECT MOBILE_NEWS_BOX_SEQ.NEXTVAL INTO :NEW.NEWS_ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;

ALTER TRIGGER "DBENURI"."MOBILE_NEWS_BOX_TRG" ENABLE